# frozen_string_literal: true

module Engine
  module Game
    module G1824
      module Entities
        COMPANIES = [
          {
            name: 'Eisenbahn Pilsen - Priesen (EPP)',
            sym: 'EPP',
            value: 0,
            interval: [120, 140, 160, 180, 200],
            revenue: 0,
            desc: "Buyer take control of minor Coal Railway EPP. EPP can be exchanged for the Director's "\
                  'certificate of Regional Railway BK during SRs in phase 3 or 4, or automatically when phase 5 starts. '\
                  'BK floats after exchange as soon as 50% or more are owned by players. This private cannot be sold. EPP '\
                  'starts at C6 with a 1g-train and what is left from the purchase when cost of g-train (120G) has been paid.',
            color: :black,
            text_color: :white,
            meta: { start_packet: true, type: :coal },
            abilities: [
              { type: 'shares', shares: 'EPP_0' },
            ],
          },
          {
            name: 'Eisenbahn Oderberg - Dombran (EOD)',
            sym: 'EOD',
            value: 0,
            interval: [120, 140, 160, 180, 200],
            revenue: 0,
            desc: "Buyer take control of minor Coal Railway EOD. EOD can be exchanged for the Director's "\
                  'certificate of Regional Railway MS during SRs in phase 3 or 4, or automatically when phase 5 starts. '\
                  'MS floats after exchange as soon as 50% or more are owned by players. This private cannot be sold. EOD '\
                  'starts at A12 with a 1g-train and what is left from the purchase when cost of g-train (120G) has been paid.',
            color: :black,
            text_color: :white,
            meta: { start_packet: true, type: :coal },
            abilities: [
              { type: 'shares', shares: 'EOD_0' },
            ],
          },
          {
            name: 'Mosty - Lemberg Bahn (MLB)',
            sym: 'MLB',
            value: 0,
            interval: [120, 140, 160, 180, 200],
            revenue: 0,
            desc: "Buyer take control of minor Coal Railway MLB. MLB can be exchanged for the Director's "\
                  'certificate of Regional Railway CL during SRs in phase 3 or 4, or automatically when phase 5 starts. '\
                  'CL floats after exchange as soon as 50% or more are owned by players. This private cannot be sold. MLB '\
                  'starts at A22 with a 1g-train and what is left from the purchase when cost of g-train (120G) has been paid.',
            color: :black,
            text_color: :white,
            meta: { start_packet: true, type: :coal },
            abilities: [
              { type: 'shares', shares: 'MLB_0' },
            ],
          },
          {
            name: 'Simeria-Petrosani Bahn (SPB)',
            sym: 'SPB',
            value: 0,
            interval: [120, 140, 160, 180, 200],
            revenue: 0,
            desc: "Buyer take control of minor Coal Railway SPB. SPB can be exchanged for the Director's "\
                  'certificate of Regional Railway SB during SRs in phase 3 or 4, or automatically when phase 5 starts. '\
                  'SB floats after exchange as soon as 50% or more are owned by players. This private cannot be sold. SPB '\
                  'starts at H25 with a 1g-train and what is left from the purchase when cost of g-train (120G) has been paid.',
            color: :black,
            text_color: :white,
            meta: { start_packet: true, type: :coal },
            abilities: [
              { type: 'shares', shares: 'SPB_0' },
            ],
          },
          {
            name: 'Kaiserin Elisabeth-Bahn (KK1)',
            sym: 'KK1',
            value: 240,
            revenue: 0,
            desc: 'Located in Wien (E12) with 240K starting capital. '\
                  "Buyer take control of pre-staatsbahn KK1. KK1 will be exchanged for the Director's certificate "\
                  'of Staatsbahn KK at the end of the OR the first 6 train was sold in. KK1 cannot be sold.',
            color: :brown,
            text_color: :white,
            meta: { start_packet: true, type: :pre_staatsbahn_primary },
            abilities: [{ type: 'shares', shares: 'KK1_0' }],
          },
          {
            name: 'KK2 Kaiser Franz Joseph-Bahn (KK2)',
            sym: 'KK2',
            value: 120,
            revenue: 0,
            desc: 'Located in Wien (E12) with 120K starting capital. '\
                  'Buyer take control of Pre-Staatsbahn KK2. KK2 will be exchanged for a 10% share of Staatsbahn '\
                  'KK at the end of the OR the first 6 train is sold. KK2 cannot be sold.',
            color: :brown,
            text_color: :white,
            meta: { start_packet: true, type: :pre_staatsbahn_secondary },
            abilities: [{ type: 'shares', shares: 'KK2_0' }],
          },
          {
            name: 'Wien-Gloggnitzer Eisenbahngesellschaft (SD1)',
            sym: 'SD1',
            value: 240,
            revenue: 0,
            desc: 'Located in Wien (E12) with 240K starting capital. '\
                  "Buyer take control of Pre-Staatsbahn SD1. SD1 will be exchanged for the Director's certificate "\
                  'of Staatsbahn SD at the end of the OR the first 4 train is sold. SD1 cannot be sold.',
            color: :orange,
            meta: { start_packet: true, type: :pre_staatsbahn_primary },
            abilities: [
              { type: 'shares', shares: 'SD1_0' },
            ],
          },
          {
            name: 'Kärntner Bahn (SD2)',
            sym: 'SD2',
            value: 120,
            revenue: 0,
            desc: 'Located in Graz (G10) with 120K starting capital. '\
                  'Buyer take control of Pre-Staatsbahn SD2. SD2 will be exchanged for a 10% share of Staatsbahn '\
                  'SD at the end of the OR the first 4 train is sold. SD2 cannot be sold.',
            color: :orange,
            meta: { start_packet: true, type: :pre_staatsbahn_secondary },
            abilities: [
              { type: 'shares', shares: 'SD2_0' },
            ],
          },
          {
            sym: 'SD3',
            name: 'Nordtiroler Staatsbahn (SD3)',
            value: 120,
            revenue: 0,
            desc: 'Located in Innsbruck (G4) with 120K starting capital. '\
                  'Buyer take control of Pre-Staatsbahn SD3. SD3 will be exchanged for a 10% share of Staatsbahn '\
                  'SD at the end of the OR the first 4 train is sold. SD3 cannot be sold.',
            color: :orange,
            meta: { start_packet: true, type: :pre_staatsbahn_secondary },
            abilities: [
              { type: 'shares', shares: 'SD3_0' },
            ],
          },
          {
            name: 'Eisenbahn Pest - Waitzen (UG1)',
            sym: 'UG1',
            value: 240,
            revenue: 0,
            desc: 'Located in Pest (F17) with 240K starting capital. '\
                  "Buyer take control of pre-staatsbahn UG1. UG1 will be exchanged for the Director's certificate "\
                  'in Staatsbahn UG at the end of the OR the first 5 train is sold. UG1 cannot be sold.',
            color: :pink,
            text_color: :black,
            meta: { start_packet: true, type: :pre_staatsbahn_primary },
            abilities: [{ type: 'shares', shares: 'UG1_0' }],
          },
          {
            name: 'Mohacs-Fünfkirchener Bahn (UG2)',
            sym: 'UG2',
            value: 120,
            desc: 'Located in Fünfkirchener (H15) with 120K starting capital. '\
                  'Buyer take control of Pre-Staatsbahn UG2. UG2 will be exchanged for a 10% share of Staatsbahn '\
                  'UG at the end of the OR the 5 train is sold. UG2 cannot be sold.',
            color: :pink,
            text_color: :black,
            meta: { start_packet: true, type: :pre_staatsbahn_secondary },
            abilities: [{ type: 'shares', shares: 'UG2_0' }],
          },
        ].freeze

        # Do not change order of minors below, as that gives the operation order
        CORPORATIONS = [
          {
            name: 'Eisenbahn Pilsen - Priesen (EPP)',
            sym: 'EPP',
            logo: '1824/C1',
            tokens: [0],
            reserved_shares: [100],
            float_percent: 100,
            max_ownership_percent: 100,
            type: 'minor',
            coordinates: 'C6',
            color: :black,
            abilities: [
              {
                type: 'exchange',
                description: 'Exchange for BK share',
                corporations: ['BK'],
                when: 'exchange',
                from: 'reserved',
              },
            ],
          },
          {
            name: 'Eisenbahn Oderberg - Dombran (EOD)',
            sym: 'EOD',
            logo: '1824/C2',
            tokens: [0],
            reserved_shares: [100],
            float_percent: 100,
            max_ownership_percent: 100,
            type: 'minor',
            coordinates: 'A12',
            color: :black,
            abilities: [
              {
                type: 'exchange',
                description: 'Exchange for MS share',
                corporations: ['MS'],
                when: 'exchange',
                from: 'reserved',
              },
            ],
          },
          {
            name: 'Mosty - Lemberg Bahn (MLB)',
            sym: 'MLB',
            logo: '1824/C3',
            tokens: [0],
            reserved_shares: [100],
            float_percent: 100,
            max_ownership_percent: 100,
            type: 'minor',
            coordinates: 'A22',
            color: :black,
            abilities: [
              {
                type: 'exchange',
                description: 'Exchange for CL share',
                corporations: ['CL'],
                when: 'exchange',
                from: 'reserved',
              },
            ],
          },
          {
            name: 'Simeria-Petrosani Bahn (SPB)',
            sym: 'SPB',
            logo: '1824/C4',
            tokens: [0],
            reserved_shares: [100],
            float_percent: 100,
            max_ownership_percent: 100,
            type: 'minor',
            coordinates: 'H25',
            color: :black,
            abilities: [
              {
                type: 'exchange',
                description: 'Exchange for SB share',
                corporations: ['SB'],
                when: 'exchange',
                from: 'reserved',
              },
            ],
          },
          {
            name: 'Wien-Gloggnitzer Eisenbahngesellschaft (SD1)',
            sym: 'SD1',
            logo: '1824/S1',
            tokens: [0],
            reserved_shares: [100],
            float_percent: 100,
            max_ownership_percent: 100,
            type: 'minor',
            coordinates: 'E12',
            city: 0,
            color: :orange,
          },
          {
            name: 'Kärntner Bahn (SD2)',
            sym: 'SD2',
            logo: '1824/S2',
            tokens: [0],
            reserved_shares: [100],
            float_percent: 100,
            max_ownership_percent: 100,
            type: 'minor',
            coordinates: 'G10',
            color: :orange,
          },
          {
            name: 'Nordtiroler Staatsbahn (SD3)',
            sym: 'SD3',
            logo: '1824/S3',
            tokens: [0],
            reserved_shares: [100],
            float_percent: 100,
            max_ownership_percent: 100,
            type: 'minor',
            coordinates: 'G4',
            color: :orange,
          },
          {
            name: 'Eisenbahn Pest - Waitzen (UG1)',
            sym: 'UG1',
            logo: '1824/U1',
            tokens: [0],
            reserved_shares: [100],
            treasury_as_holding: true,
            float_percent: 50,
            max_ownership_percent: 100,
            type: 'minor',
            coordinates: 'F17',
            city: 1,
            color: :pink,
            text_color: :black,
          },
          {
            name: 'Mohacs-Fünfkirchner Bahn (UG2)',
            sym: 'UG2',
            logo: '1824/U2',
            tokens: [0],
            reserved_shares: [100],
            float_percent: 100,
            max_ownership_percent: 100,
            type: 'minor',
            coordinates: 'H15',
            color: :pink,
            text_color: :black,
          },
          {
            name: 'Kaiserin Elisabeth-Bahn (KK1)',
            sym: 'KK1',
            logo: '1824/K1',
            tokens: [0],
            reserved_shares: [100],
            float_percent: 100,
            max_ownership_percent: 100,
            type: 'minor',
            coordinates: 'E12',
            city: 1,
            color: :brown,
          },
          {
            name: 'Kaiser Franz Joseph-Bahn (KK2)',
            sym: 'KK2',
            logo: '1824/K2',
            tokens: [0],
            reserved_shares: [100],
            float_percent: 100,
            max_ownership_percent: 100,
            type: 'minor',
            coordinates: 'E12',
            city: 2,
            color: :brown,
          },
          {
            name: 'Bosnisch-Herzegowinische Landesbahn',
            sym: 'BH',
            logo: '1824/BH',
            simple_logo: '1824/BH.alt',
            tokens: [0, 40, 100],
            ipo_shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            float_percent: 50,
            always_market_price: true,
            type: 'major',
            coordinates: 'J13',
            color: :red,
          },
          {
            name: 'Böhmische Kommerzbahn',
            sym: 'BK',
            logo: '1824/BK',
            simple_logo: '1824/BK.alt',
            tokens: [0, 40, 100],
            ipo_shares: [10, 10, 10, 10, 10, 10, 10, 10],
            reserved_shares: [20],
            float_percent: 50,
            always_market_price: true,
            type: 'major',
            coordinates: 'B9',
            color: :blue,
          },
          {
            sym: 'CL',
            name: 'Carl Ludwigs-Bahn',
            logo: '1824/CL',
            simple_logo: '1824/CL.alt',
            tokens: [0, 40, 100],
            ipo_shares: [10, 10, 10, 10, 10, 10, 10, 10],
            reserved_shares: [20],
            float_percent: 50,
            always_market_price: true,
            type: 'major',
            coordinates: 'B23',
            color: :black,
          },
          {
            name: 'Mährisch-Schlesische Eisenbahn',
            sym: 'MS',
            logo: '1824/MS',
            simple_logo: '1824/MS.alt',
            tokens: [0, 40, 100],
            ipo_shares: [10, 10, 10, 10, 10, 10, 10, 10],
            reserved_shares: [20],
            float_percent: 50,
            always_market_price: true,
            type: 'major',
            coordinates: 'C12',
            color: :yellow,
            text_color: :black,
          },
          {
            name: 'Siebenbürgische Bahn',
            sym: 'SB',
            logo: '1824/SB',
            simple_logo: '1824/SB.alt',
            tokens: [0, 40, 100],
            ipo_shares: [10, 10, 10, 10, 10, 10, 10, 10],
            reserved_shares: [20],
            float_percent: 50,
            always_market_price: true,
            type: 'major',
            coordinates: 'G26',
            color: :green,
          },
          {
            name: 'Südbahn',
            sym: 'SD',
            logo: '1824/SD',
            simple_logo: '1824/SD.alt',
            tokens: [100, 100],
            ipo_shares: [10, 10, 10, 10, 10, 10],
            reserved_shares: [20, 10, 10],
            always_market_price: true,
            type: 'national',
            floatable: false,
            color: :orange,
          },
          {
            name: 'k&k Staatsbahn',
            sym: 'KK',
            logo: '1824/KK',
            simple_logo: '1824/KK.alt',
            tokens: [100, 100, 100],
            ipo_shares: [10, 10, 10, 10, 10, 10, 10],
            reserved_shares: [20, 10],
            always_market_price: true,
            type: 'national',
            floatable: false,
            color: :brown,
          },
          {
            name: 'Ungarische Staatsbahn',
            sym: 'UG',
            logo: '1824/UG',
            simple_logo: '1824/UG.alt',
            tokens: [100, 100, 100],
            ipo_shares: [10, 10, 10, 10, 10, 10, 10],
            reserved_shares: [20, 10],
            always_market_price: true,
            type: 'national',
            floatable: false,
            color: :pink,
            text_color: :black,
          },
        ].freeze
      end
    end
  end
end
