# frozen_string_literal: true

module Engine
  module Game
    module G1824
      module Trains
        TRAINS_STANDARD = [
          {
            name: '2',
            distance: 2,
            num: 9,
            price: 80,
            rusts_on: '4',
          },
          {
            name: '1g',
            distance: [{ 'nodes' => %w[city offboard], 'pay' => 2, 'visit' => 2 },
                       { 'nodes' => ['town'], 'pay' => 99, 'visit' => 99 }],
            num: 6,
            price: 120,
            available_on: '2',
            rusts_on: '3g',
          },
          {
            name: '3',
            distance: 3,
            num: 7,
            price: 180,
            rusts_on: '6',
            discount: { '2' => 40 },
          },
          {
            name: '2g',
            distance: [{ 'nodes' => %w[city offboard], 'pay' => 3, 'visit' => 3 },
                       { 'nodes' => ['town'], 'pay' => 99, 'visit' => 99 }],
            num: 5,
            price: 240,
            available_on: '3',
            rusts_on: '4g',
            discount: { '1g' => 60 },
          },
          {
            name: '4',
            distance: 4,
            num: 4,
            price: 280,
            rusts_on: '8',
            events: [{ 'type' => 'close_mountain_railways' }, { 'type' => 'sd_formation' }],
            discount: { '3' => 90 },
          },
          {
            name: '3g',
            distance: [{ 'nodes' => %w[city offboard], 'pay' => 4, 'visit' => 4 },
                       { 'nodes' => ['town'], 'pay' => 99, 'visit' => 99 }],
            num: 4,
            price: 360,
            available_on: '4',
            rusts_on: '5g',
            discount: { '2g' => 120 },
          },
          {
            name: '5',
            distance: 5,
            num: 3,
            price: 400,
            rusts_on: '10',
            events: [{ 'type' => 'close_coal_railways' }, { 'type' => 'ug_formation' }],
            discount: { '4' => 140 },
          },
          {
            name: '6',
            distance: 6,
            num: 3,
            price: 630,
            events: [{ 'type' => 'kk_formation' }],
            discount: { '5' => 200 },
          },
          {
            name: '4g',
            distance: [{ 'nodes' => %w[city offboard], 'pay' => 5, 'visit' => 5 },
                       { 'nodes' => ['town'], 'pay' => 99, 'visit' => 99 }],
            num: 3,
            price: 600,
            available_on: '6',
            discount: { '3g' => 180 },
          },
          {
            name: '8',
            distance: 8,
            num: 3,
            price: 800,
            discount: { '6' => 300 },
          },
          {
            name: '5g',
            distance: [{ 'nodes' => %w[city offboard], 'pay' => 6, 'visit' => 6 },
                       { 'nodes' => ['town'], 'pay' => 99, 'visit' => 99 }],
            num: 2,
            price: 800,
            available_on: '8',
            discount: { '4g' => 300 },
          },
          {
            name: '10',
            distance: 10,
            num: 20,
            price: 1000,
            discount: { '8' => 400 },
          },
        ].freeze

        TRAINS_2_PLAYER = [
          {
            name: '2',
            distance: 2,
            num: 6,
            price: 80,
            rusts_on: '4',
          },
          {
            name: '1g',
            distance: [{ 'nodes' => %w[city offboard], 'pay' => 2, 'visit' => 2 },
                       { 'nodes' => ['town'], 'pay' => 99, 'visit' => 99 }],
            num: 3,
            price: 120,
            available_on: '2',
            rusts_on: '3g',
          },
          {
            name: '3',
            distance: 3,
            num: 5,
            price: 180,
            rusts_on: '6',
            discount: { '2' => 40 },
          },
          {
            name: '2g',
            distance: [{ 'nodes' => %w[city offboard], 'pay' => 3, 'visit' => 3 },
                       { 'nodes' => ['town'], 'pay' => 99, 'visit' => 99 }],
            num: 2,
            price: 240,
            available_on: '3',
            rusts_on: '4g',
            discount: { '1g' => 60 },
          },
          {
            name: '4',
            distance: 4,
            num: 4,
            price: 280,
            rusts_on: '8',
            events: [{ 'type' => 'close_mountain_railways' }, { 'type' => 'sd_formation' }],
            discount: { '3' => 90 },
          },
          {
            name: '3g',
            distance: [{ 'nodes' => %w[city offboard], 'pay' => 4, 'visit' => 4 },
                       { 'nodes' => ['town'], 'pay' => 99, 'visit' => 99 }],
            num: 2,
            price: 360,
            available_on: '4',
            rusts_on: '5g',
            discount: { '2g' => 120 },
          },
          {
            name: '5',
            distance: 5,
            num: 2,
            price: 400,
            rusts_on: '10',
            events: [{ 'type' => 'close_coal_railways' }, { 'type' => 'kk_formation' }],
            discount: { '4' => 140 },
          },
          {
            name: '6',
            distance: 6,
            num: 2,
            price: 600,
            events: [],
            discount: { '5' => 200 },
          },
          {
            name: '4g',
            distance: [{ 'nodes' => %w[city offboard], 'pay' => 5, 'visit' => 5 },
                       { 'nodes' => ['town'], 'pay' => 99, 'visit' => 99 }],
            num: 1,
            price: 600,
            available_on: '6',
            discount: { '3g' => 180 },
          },
          {
            name: '8',
            distance: 8,
            num: 1,
            price: 800,
            discount: { '6' => 300 },
          },
          {
            name: '5g',
            distance: [{ 'nodes' => %w[city offboard], 'pay' => 6, 'visit' => 6 },
                       { 'nodes' => ['town'], 'pay' => 99, 'visit' => 99 }],
            num: 2,
            price: 800,
            available_on: '8',
            discount: { '4g' => 300 },
          },
          {
            name: '10',
            distance: 10,
            num: 20,
            price: 1000,
            discount: { '8' => 400 },
          },
        ].freeze

        TRAINS_3_PLAYER_CISLETHANIA = [
          {
            name: '2',
            distance: 2,
            num: 8,
            price: 80,
            rusts_on: '4',
          },
          {
            name: '1g',
            distance: [{ 'nodes' => %w[city offboard], 'pay' => 2, 'visit' => 2 },
                       { 'nodes' => ['town'], 'pay' => 99, 'visit' => 99 }],
            num: 5,
            price: 120,
            available_on: '2',
            rusts_on: '3g',
          },
          {
            name: '3',
            distance: 3,
            num: 6,
            price: 180,
            rusts_on: '6',
            discount: { '2' => 40 },
          },
          {
            name: '2g',
            distance: [{ 'nodes' => %w[city offboard], 'pay' => 3, 'visit' => 3 },
                       { 'nodes' => ['town'], 'pay' => 99, 'visit' => 99 }],
            num: 4,
            price: 240,
            available_on: '3',
            rusts_on: '4g',
            discount: { '1g' => 60 },
          },
          {
            name: '4',
            distance: 4,
            num: 4,
            price: 280,
            rusts_on: '8',
            events: [{ 'type' => 'close_mountain_railways' }, { 'type' => 'sd_formation' }],
            discount: { '3' => 90 },
          },
          {
            name: '3g',
            distance: [{ 'nodes' => %w[city offboard], 'pay' => 4, 'visit' => 4 },
                       { 'nodes' => ['town'], 'pay' => 99, 'visit' => 99 }],
            num: 3,
            price: 360,
            available_on: '4',
            rusts_on: '5g',
            discount: { '2g' => 120 },
          },
          {
            name: '5',
            distance: 5,
            num: 3,
            price: 400,
            rusts_on: '10',
            events: [{ 'type' => 'close_coal_railways' }, { 'type' => 'ug_formation' }],
            discount: { '4' => 140 },
          },
          {
            name: '6',
            distance: 6,
            num: 3,
            price: 600,
            events: [{ 'type' => 'kk_formation' }],
            discount: { '5' => 200 },
          },
          {
            name: '4g',
            distance: [{ 'nodes' => %w[city offboard], 'pay' => 5, 'visit' => 5 },
                       { 'nodes' => ['town'], 'pay' => 99, 'visit' => 99 }],
            num: 3,
            price: 600,
            available_on: '6',
            discount: { '3g' => 180 },
          },
          {
            name: '8',
            distance: 8,
            num: 2,
            price: 800,
            discount: { '6' => 300 },
          },
          {
            name: '5g',
            distance: [{ 'nodes' => %w[city offboard], 'pay' => 6, 'visit' => 6 },
                       { 'nodes' => ['town'], 'pay' => 99, 'visit' => 99 }],
            num: 2,
            price: 800,
            available_on: '8',
            discount: { '4g' => 300 },
          },
          {
            name: '10',
            distance: 10,
            num: 20,
            price: 1000,
            discount: { '8' => 400 },
          },
        ].freeze
      end
    end
  end
end
