# frozen_string_literal: true

require_relative 'map'

module Engine
  module Game
    module G18EUS
      module Entities
        COMPANIES = [
          {
            name: 'A0 - Late Bloomer',
            value: 0,
            revenue: 10,
            desc: 'Cannot be brought into railroad company until OR4a or later. Close' \
                  ' company by swapping this private for any unused private or for' \
                  ' $400 into the company treasury.',
            sym: 'A0',
          },
          {
            name: 'A1 - Permanent 1-Train',
            value: 0,
            revenue: 0,
            desc: 'Permanent 1-train. Runs city with station token. Does not count' \
                  ' towards train limit or count towards train ownership. Income from' \
                  ' this cannot be split from other trains. Cannot be bought by other' \
                  ' companies. A railroad company may own multiple permanent 1-trains;' \
                  ' if a railroad company has 2 1-trains, they can both run the same city.',
            sym: 'A1',
          },
          {
            name: 'A2 - Mail Contract',
            value: 0,
            revenue: 10,
            desc: 'After run trains step, owning company receives additional money' \
                  ' equal to 20% of the total revenue generated by its trains.',
            sym: 'A2',
          },
          {
            name: 'A3 - Haggler',
            value: 0,
            revenue: 10,
            desc: 'Gives 15% off train purchases of owning company. Round up for' \
                  ' price paid for train (3 train costs $213, for example).',
            sym: 'A3',
          },
          {
            name: 'A4 - Rural Junction',
            value: 0,
            revenue: 10,
            desc: 'Gives company 2 rural junction tiles (one “K” tile and one “X” tile)' \
                  ' that can be placed on any plain hex or plain city hex (not Chicago,' \
                  ' New York, metropolis, or red city) that has not been built and that' \
                  ' is not a home station for a new company. Does not count towards' \
                  ' track lay. Trains can count the 10 income but do not count this as a' \
                  ' stop. Routes cannot start or end at a rural junction tile. This income' \
                  ' is doubled by a 3D or 4D.',
            sym: 'A4',
          },
          {
            name: 'A5 - Scenic Route',
            value: 0,
            revenue: 10,
            desc: 'Close company to lay one extra yellow tile with a +20 token' \
                  ' (company may lay another tile as part of its lay track action). Trains' \
                  ' (of any company) using this track segment add $20 to the run. This' \
                  ' hex cannot be upgraded. This income is doubled by a 3D or 4D.',
            sym: 'A5',
          },
          {
            name: 'A6 - Bank Bond',
            value: 0,
            revenue: 0,
            desc: 'Owning player or company receives the bank dividend each time' \
                  ' the bank operates. Does not close.',
            sym: 'A6',
          },
          {
            name: 'A7 - Little Engine that Could',
            value: 0,
            revenue: 0,
            desc: 'Acts as a permanent train that runs for $10 each OR and always' \
                  ' pays out, even if company withholds its other trains. Does not' \
                  ' count towards train limit or count towards train ownership. May not' \
                  ' be added to from N+1 or N+2.',
            sym: 'A7',
          },
          {
            name: 'A8 - Goldrush Railway',
            value: 0,
            revenue: 10,
            desc: 'Close company by swapping out red-value square (that is in' \
                  ' owning company\'s network) with the 40-60-80-100 square.',
            sym: 'A8',
          },
          {
            name: 'A9 - Responsible President',
            value: 0,
            revenue: 10,
            desc: 'Does not close. During each operating turn of owning company,' \
                  ' the company\'s president may pay off one loan, using the' \
                  ' president\'s personal cash.',
            sym: 'A9',
          },
          {
            name: 'B0 - Permanent 1-Train',
            value: 0,
            revenue: 0,
            desc: 'Permanent 1-train. Runs city with station token. Does not count' \
                  ' towards train limit or count towards train ownership. Income from' \
                  ' this cannot be split from other trains. Cannot be bought by other' \
                  ' companies. A railroad company may own multiple permanent 1-trains;' \
                  ' if a railroad company has 2 1-trains, they can both run the same city.',
            sym: 'B0',
          },
          {
            name: 'B1 - Presidential Financing',
            value: 0,
            revenue: 10,
            desc: 'Comes with $50 plus the winning bid (total capped at $150); this' \
                  ' money is set aside. Absorbing railroad company gets this cash.',
            sym: 'B1',
          },
          {
            name: 'B2 - Boomtown',
            value: 0,
            revenue: 10,
            desc: 'Close company by placing +20 token to plain city (not a red city,' \
                  ' Chicago, New York, or Metropolis) which owning company can' \
                  ' trace a legal route. All trains running to this city (of any company)' \
                  ' add +20 to the run. Note: this may be added to a city that already' \
                  ' has +10 from a subsidy bonus.',
            sym: 'B2',
          },
          {
            name: 'B3 - N+1',
            value: 0,
            revenue: 0,
            desc: 'Owning company may add this to train to extend the train’s run by' \
                  ' 1 stop. For example, when added to a 3 train, it can run 4 stops.' \
                  ' This stays in the company and cannot be bought across. Each OR ' \
                  ' this may enhance a different train. A 3D or 4D train does double' \
                  ' the extra stop (becomes a “4D” or “5D”). This may add to a' \
                  ' permanent 1-train. It may add in combination to Private C2 (N+2)' \
                  ' to add a total of 3 stops.',
            sym: 'B3',
          },
          {
            name: 'B4 - Bank Share',
            value: 0,
            revenue: 10,
            desc: 'Owning company receives share of Bank of New York. This will' \
                  ' pay bank dividends to company when bank operates. Any player' \
                  ' who does not have loans may purchase bank share from owning' \
                  ' company paying company current bank stock price. The owning' \
                  ' company may not sell this bank share.',
            sym: 'B4',
          },
          {
            name: 'B5 - Triple Hopper',
            value: 0,
            revenue: 10,
            desc: 'Owning company will move forward three spaces horizontally if its' \
                  ' payout is &gt;= 3 times the stock price. Company does not close.',
            sym: 'B5',
          },
          {
            name: 'B6 - Soft Rust',
            value: 0,
            revenue: 20,
            desc: 'Close company to allow newly-rusted train to run one more time.' \
                  ' May not be used on (+) train.',
            sym: 'B6',
          },
          {
            name: 'B7 - Industrious Railway',
            value: 0,
            revenue: 10,
            desc: 'Owning company gets extra build each operating round (can be' \
                  ' yellow or upgrade). Does not close. During final build, owning' \
                  ' company gets 4 builds instead of 2.',
            sym: 'B7',
          },
          {
            name: 'B8 - Rust Insurance',
            value: 0,
            revenue: 10,
            desc: 'If owning company is emergency fundraising and presidential out-' \
                  'of-pocket funding is required: First calculate presidential out-of-' \
                  'pocket expense. Close this company to provide 50% (rounded' \
                  ' down to the nearest $1) of this expense.',
            sym: 'B8',
          },
          {
            name: 'B9 - Quick Starter',
            value: 0,
            revenue: 20,
            desc: 'Close company to buy one train at the start of the operating turn.' \
                  ' Owning company may then run that train the same OR. Owning' \
                  ' company must have the funds to buy the train; it may not' \
                  ' emergency fund raise to buy the train.',
            sym: 'B9',
          },
          {
            name: 'C0 - Urban Expansion',
            value: 0,
            revenue: 10,
            desc: 'Comes with free extra token that may be placed in “tokened-out”' \
                  ' city. If this token is in a city that upgrades to acquire an extra token' \
                  ' spot, this token will then go into the extra token spot.',
            sym: 'C0',
          },
          {
            name: 'C1 - Pullman',
            value: 0,
            revenue: 0,
            desc: 'Owning company may add this private to enhance train; train adds' \
                  ' +$20 per city visited to run. For example, when added to a 5 train' \
                  ' that visits 5 cities, add +$100 to run. Pullman does not close,' \
                  ' cannot be bought across, and may be added to a different train' \
                  ' each OR. 3D or 4D does double the extra income.',
            sym: 'C1',
          },
          {
            name: 'C2 - N+2',
            value: 0,
            revenue: 0,
            desc: 'Owning company may add this to train to extend the train’s run by' \
                  ' 2 stops. For example, when added to a 3 train, it can run 5 stops.' \
                  ' This stays in the company and cannot be bought across. Each OR ' \
                  ' this may enhance a different train. A 3D or 4D train does double' \
                  ' the extra stop (becomes a “5D” or “6D”). This may add to a' \
                  ' permanent 1-train. It may add in combination to Private B3 (N+1)' \
                  ' to add a total of 3 stops.',
            sym: 'C2',
          },
          {
            name: 'C3 - Simpleton Railway',
            value: 0,
            revenue: 0,
            desc: 'When held by a railroad company, railroad company receives 3' \
                  ' times the current bank interest rate at the start of each OR (during' \
                  ' the pay private companies step).',
            sym: 'C3',
          },
          {
            name: 'C4 - Bank Lobbyist',
            value: 0,
            revenue: 10,
            desc: 'Owning company may close private company to add or subtract up' \
                  ' to 4 loans from bank charter. (One-time use)',
            sym: 'C4',
          },
          {
            name: 'C5 - Re-appraisal',
            value: 0,
            revenue: 10,
            desc: 'Owning railroad company may close private company to take a free' \
                  ' horizontal stock increase.',
            sym: 'C5',
          },
          {
            name: 'C6 - EW Destination',
            value: 0,
            revenue: 10,
            desc: 'Does not close. For each train that company runs from either New' \
                  ' York or Montreal to the West or St. Louis, total run is increased by' \
                  ' $150. 3D and 4D do not double this bonus.',
            sym: 'C6',
          },
          {
            name: 'C7 - NS Destination',
            value: 0,
            revenue: 10,
            desc: 'Does not close. For each train that company runs from either' \
                  ' Montreal or Toronto to Memphis or Florida, total run is increased by' \
                  ' $150. 3D and 4D do not double this bonus.',
            sym: 'C7',
          },
          {
            name: 'C8 - Station Upgrade',
            value: 0,
            revenue: 10,
            desc: 'Does not close. Each station token of owning company adds $20 to' \
                  ' the value of that city, for the owning company only.',
            sym: 'C8',
          },
          {
            name: 'C9 - Bank Reappraisal',
            value: 0,
            revenue: 0, # TODO: What does current bank interest rate mean?
            desc: 'Pays nothing to owning company. Close company to increase the' \
                  ' bank stock price by one horizontal space.',
            sym: 'C9',
          },
        ].freeze

        SUBSIDIES = [
          {
            id: 'S0',
            name: '+10',
            desc: 'Increase value of starting city by 10 (for all companies)',
            value: 0,
            icon: '18_eus/subsidy_plus_ten',
            abilities: [],
          },
          {
            id: 'S1',
            name: '$40',
            desc: 'Company receives extra $40 into its treasury',
            value: 40,
            icon: '18_eus/subsidy_forty',
            abilities: [],
          },
          {
            id: 'S2',
            name: '$50 Subsidy',
            desc: 'Company receives extra $50 into its treasury',
            value: 50,
            icon: '18_eus/subsidy_fifty',
            abilities: [],
          },
          {
            id: 'S3',
            name: '+Loan Interest',
            desc: 'Company receives income at the beginning of each OR (when private' \
                  ' companies pay) equal to the current interest.',
            value: 0,
            icon: '18_eus/subsidy_plus_loan_interest',
            abilities: [],
          },
          {
            id: 'S4',
            name: '+Stock Price',
            desc: 'Company increases its stock price one horizontal at the end of its' \
                  ' first operating turn.',
            value: 0,
            icon: '18_eus/subsidy_plus_stock_price',
            abilities: [],
          },
          {
            id: 'S5',
            name: '+$40 One Run',
            desc: 'If company has train (including private A7, “Little Engine That Could”,' \
                  ' then company may use this subsidy to add $40 to revenue. This is a' \
                  ' one-time use.',
            value: 0,
            icon: '18_eus/subsidy_plus_forty_run',
            abilities: [],
          },
          {
            id: 'S6',
            name: 'Free Token',
            desc: 'Company receives extra token that may be placed for free.',
            value: 0,
            icon: '18_eus/subsidy_free_token',
            abilities: [
              {
                type: 'token',
                when: 'owning_corp_or_turn',
                owner_type: 'corporation',
                price: 0,
                count: 1,
                from_owner: false,
                cheater: true,
                special_only: true,
              },
            ],
          },
          {
            id: 'S7',
            name: 'Rural Junction Tile',
            desc: 'Company receives "K" rural junction tile.' \
                  ' See private company A4 for more details.',
            value: 0,
            icon: '18_eus/subsidy_rural_junction',
            abilities: [],
          },
          {
            id: 'S8',
            name: 'Two Tile Lays',
            desc: 'Company may lay 2 extra free yellow tiles' \
                  ' (these can be taken on first operating turn or later).',
            value: 0,
            icon: '18_eus/subsidy_two_tiles',
            abilities: [],
          },
          {
            id: 'S9',
            name: 'Green City',
            desc: 'On first operating turn, company may place green city' \
                  ' tile on home location instead of yellow.  This may be' \
                  ' any of the three regular green cities.',
            value: 0,
            icon: '18_eus/subsidy_green_city',
            abilities: [
              {
                type: 'tile_lay',
                when: 'track',
                owner_type: 'corporation',
                closed_when_used_up: true,
                count: 1,
                hexes: [], # assigned when claimed
                tiles: %w[14 15 619],
              },
              {
                type: 'close',
                when: 'operated',
                corporation: nil, # assigned when claimed
              },
            ],
          },
        ].freeze

        CORPORATIONS = [
          {
            sym: 'B&O',
            name: 'Baltimore and Ohio Railroad',
            logo: '18_eus/BO',
            simple_logo: '18_eus/BO.alt',
            shares: [40, 20, 20, 20],
            float_percent: 40,
            max_ownership_percent: 100,
            tokens: [0, 50, 100],
            always_market_price: true,
            color: '#025aaa',
          },
          {
            sym: 'C&O',
            name: 'Chesapeake and Ohio',
            logo: '18_eus/CO',
            simple_logo: '18_eus/CO.alt',
            shares: [40, 20, 20, 20],
            float_percent: 40,
            max_ownership_percent: 100,
            tokens: [0, 50, 100],
            always_market_price: true,
            color: '#ADD8E6',
            text_color: 'navy',
          },
          {
            sym: 'ERIE',
            name: 'Erie Railroad',
            logo: '18_eus/ERIE',
            simple_logo: '18_eus/ERIE.alt',
            shares: [40, 20, 20, 20],
            float_percent: 40,
            max_ownership_percent: 100,
            tokens: [0, 50, 100],
            always_market_price: true,
            color: :'#FFF500',
            text_color: 'black',
          },
          {
            sym: 'GT',
            name: 'Grand Trunk',
            logo: '18_eus/GT',
            simple_logo: '18_eus/GT.alt',
            shares: [40, 20, 20, 20],
            float_percent: 40,
            max_ownership_percent: 100,
            tokens: [0, 50, 100],
            always_market_price: true,
            color: '#f58121',
          },
          {
            sym: 'IC',
            name: 'Illinois Central Railroad',
            logo: '18_eus/IC',
            simple_logo: '18_eus/IC.alt',
            shares: [40, 20, 20, 20],
            float_percent: 40,
            max_ownership_percent: 100,
            tokens: [0, 50, 100],
            always_market_price: true,
            color: '#32763f',
          },
          {
            sym: 'NYC',
            name: 'New York Central Railroad',
            logo: '18_eus/NYC',
            simple_logo: '18_eus/NYC.alt',
            shares: [40, 20, 20, 20],
            float_percent: 40,
            max_ownership_percent: 100,
            tokens: [0, 50, 100],
            always_market_price: true,
            color: 'black',
          },
          {
            sym: 'PRR',
            name: 'Pennsylvania Railroad',
            logo: '18_eus/PRR',
            simple_logo: '18_eus/PRR.alt',
            shares: [40, 20, 20, 20],
            float_percent: 40,
            max_ownership_percent: 100,
            tokens: [0, 50, 100],
            always_market_price: true,
            color: :'#FF0000',
          },
          {
            sym: 'SR',
            name: 'Southern Railway',
            logo: '18_eus/SR',
            simple_logo: '18_eus/SR.alt',
            shares: [40, 20, 20, 20],
            float_percent: 40,
            max_ownership_percent: 100,
            tokens: [0, 50, 100],
            always_market_price: true,
            color: '#00984c',
          },
        ].freeze
      end
    end
  end
end
