# frozen_string_literal: true

module Engine
  module Game
    module G1822PNW
      module Entities
        COMPANIES = [
          {
            name: 'P1-The Olympian Hiawatha (5-Train)',
            sym: 'P1',
            value: 0,
            revenue: 5,
            desc: 'MAJOR, Phase 5. 5-Train. Once a company acquires it, this is a notmal 5-train that is subject to '\
                  'all of the normal rules.  It is not a "special train" and is not subject to the rules that are '\
                  'specific to special trains.  A company can acquire this private company at the start of its turn, '\
                  'even if it is already at it\'s train limit, as this counts as an acquisition action, not a train '\
                  'buying action.  However, once acquired the acquiring company must check whether it as at the '\
                  'train limit and must discard any trains held in excess of limit.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P2-J.S. Ruckle OSNC 4-4-0 (Permanent 2T)',
            sym: 'P2',
            value: 0,
            revenue: 0,
            desc: 'MAJOR, Phase 2. Permanent 2-Train. The 2P-train is a permanent 2-train. It is a “special train.” '\
                  'It cannot be sold to another company. It does not count against the train limit. '\
                  'It does not count as a train for the purpose of mandatory train ownership and '\
                  'purchase. A company cannot own more than one special train. Dividends can '\
                  'be separated from other trains and may be split, paid in full, or retained. If '\
                  'a company runs a 2P-train and pays a dividend (split or full), but retains its '\
                  'dividend from other train operations, this still counts as a normal dividend '\
                  'for share price movement purposes. Vice-versa, if a company pays a dividend '\
                  '(split or full) with its other trains, but retains the dividend from the 2P-train, '\
                  'this also still counts as a normal dividend for share price movement purposes. '\
                  'Does not close.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P3-Portland Streetcar (Permanent LT)',
            sym: 'P3',
            value: 0,
            revenue: 0,
            desc: 'MAJOR/MINOR, Phase 1. Permanent L-Train.  It is a “special train.” '\
                  'It cannot be sold to another company. It does not count against the train limit. '\
                  'It does not count as a train for the purpose of mandatory train ownership and '\
                  'purchase. A company cannot own more than one special train. Dividends can '\
                  'be separated from other trains and may be split, paid in full, or retained. If '\
                  'a company runs a LP-train and pays a dividend (split or full), but retains its '\
                  'dividend from other train operations, this still counts as a normal dividend '\
                  'for share price movement purposes. Vice-versa, if a company pays a dividend '\
                  '(split or full) with its other trains, but retains the dividend from the LP-train, '\
                  'this also still counts as a normal dividend for share price movement purposes. '\
                  'Does not close.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P4-South Lake Union Trolley (Permanent LT)',
            sym: 'P4',
            value: 0,
            revenue: 0,
            desc: 'MAJOR/MINOR, Phase 1. Permanent L-Train.  It is a “special train.” '\
                  'It cannot be sold to another company. It does not count against the train limit. '\
                  'It does not count as a train for the purpose of mandatory train ownership and '\
                  'purchase. A company cannot own more than one special train. Dividends can '\
                  'be separated from other trains and may be split, paid in full, or retained. If '\
                  'a company runs a LP-train and pays a dividend (split or full), but retains its '\
                  'dividend from other train operations, this still counts as a normal dividend '\
                  'for share price movement purposes. Vice-versa, if a company pays a dividend '\
                  '(split or full) with its other trains, but retains the dividend from the LP-train, '\
                  'this also still counts as a normal dividend for share price movement purposes. '\
                  'Does not close.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P5-Pullman (Pullman)',
            sym: 'P5',
            value: 0,
            revenue: 10,
            desc: 'MAJOR/MINOR, Phase 3. Pullman. A “Pullman” car that can be attached to another train owned by the '\
                  'company. It is not a train. A train with a Pullman attached to it counts any '\
                  'number of towns in addition to its standard number of large stations. Does '\
                  'not count toward the train limit. Cannot be sold to another company. Does '\
                  'not close. No company may own more than one Pullman.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P6-Pullman (Pullman)',
            sym: 'P6',
            value: 0,
            revenue: 10,
            desc: 'MAJOR/MINOR, Phase 3. Pullman. A “Pullman” car that can be attached to another train owned by the '\
                  'company. It is not a train. A train with a Pullman attached to it counts any '\
                  'number of towns in addition to its standard number of large stations. Does '\
                  'not count toward the train limit. Cannot be sold to another company. Does '\
                  'not close. No company may own more than one Pullman.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P7-Dit Crusher (Remove Town)',
            sym: 'P7',
            value: 0,
            revenue: 10,
            desc: 'MAJOR/MINOR, Phase 1. Remove Town. Allows the owning company to place a plain yellow track '\
                  'tile directly on an undeveloped town hex location or upgrade a town tile '\
                  'of one color to a plain track tile of the next color. This closes the company '\
                  'and counts as the company’s normal track laying step. All other normal '\
                  'track laying restrictions apply. Cannot be used in hexes with two small '\
                  'towns. Once acquired, the private company pays its revenue to the owning '\
                  'company until the power is exercised and the company is closed.',
            abilities: [
            {
              type: 'tile_lay',
              owner_type: 'corporation',
              when: 'track',
              count: 1,
              reachable: true,
              closed_when_used_up: true,
              hexes: [],
              tiles: %w[7 8 9 80 81 82 83 544 545 546 60 169],
            },
            ],
            color: nil,
          },
          {
            name: 'P8-Dit Crusher (Remove Town)',
            sym: 'P8',
            value: 0,
            revenue: 10,
            desc: 'MAJOR/MINOR, Phase 1. Remove Town. Allows the owning company to place a plain yellow track '\
                  'tile directly on an undeveloped town hex location or upgrade a town tile '\
                  'of one color to a plain track tile of the next color. This closes the company '\
                  'and counts as the company’s normal track laying step. All other normal '\
                  'track laying restrictions apply. Cannot be used in hexes with two small '\
                  'towns. Once acquired, the private company pays its revenue to the owning '\
                  'company until the power is exercised and the company is closed.',
            abilities: [
              {
                type: 'tile_lay',
                owner_type: 'corporation',
                when: 'track',
                count: 1,
                reachable: true,
                closed_when_used_up: true,
                hexes: [],
                tiles: %w[7 8 9 80 81 82 83 544 545 546 60 169],
              },
            ],
            color: nil,
          },
          {
            name: 'P9-USPS Mail Service (Mail Contract)',
            sym: 'P9',
            value: 0,
            revenue: 10,
            desc: 'MAJOR, Phase 3. Mail Contract. After running trains, the owning company receives income '\
                  'into its treasury equal to one half of the base value of the start and end '\
                  'stations from one of the trains operated. Modifications to values (for '\
                  'E-trains, a 3/2-train, or destination tokens) do not apply. An L-train may '\
                  'deliver mail within a single city. The company is not required to maximize '\
                  'the dividend from its run if it wishes to maximize its revenue from the mail '\
                  'contract by stopping at a large city and not running beyond it to include '\
                  'towns. A company that owns more than one Mail Contract may not use '\
                  'more than one on any train.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P10-American Bridge Company (Three Builder Cubes)',
            sym: 'P10',
            value: 0,
            revenue: 10,
            desc: 'MAJOR/MINOR, Phase 1. Three Builder Cubes. When acquired by a company, the private company '\
                  'closes and is exchanged for three of the builder cubes from the cube pool. '\
                  'The company may spend one or more of the cubes to place them on the '\
                  'board during their lay track action. These placements are in addition to the '\
                  'tile placement. These cube placements may occur at any time during the '\
                  'action and can be split among turns.',
            abilities: [
              {
                type: 'tile_lay',
                owner_type: 'corporation',
                when: 'track',
                count: 3,
                reachable: true,
                closed_when_used_up: true,
                hexes: [],
                tiles: [],
              },
            ],
            color: nil,
          },
          {
            name: 'P11-Surveyors (Extra Tile Lay)',
            sym: 'P11',
            value: 0,
            revenue: 10,
            desc: 'MAJOR/MINOR, Phase 3. Extra Tile Lay. The owning company may lay an additional yellow tile (or '\
                  'two for major companies beginning in Phase 3), or make one additional '\
                  'tile upgrade in its track laying step. The upgrade can be to a tile laid in its '\
                  'normal tile laying step. All other normal track laying restrictions apply. Once '\
                  'acquired, the private company pays its revenue to the owning company until '\
                  'the power is exercised and the company closes.',
            abilities: [
              {
                type: 'tile_lay',
                owner_type: 'corporation',
                when: 'track',
                count: 2,
                reachable: true,
                closed_when_used_up: true,
                hexes: [],
                tiles: [],
              },
            ],
            color: nil,
          },
          {
            name: 'P12-Dock Upgrades (Small Port)',
            sym: 'P12',
            value: 0,
            revenue: 10,
            desc: 'MAJOR/MINOR, Phase 2. Small Port. Replace a spike going to water with this tile. Lay this tile on '\
                  'a spike that does not already have a port. The spike now counts as a 30 '\
                  '(yellow)/40 (green and later) and is treated like a gray off-board area for '\
                  'counting train runs for all companies. This is in addition to the company’s '\
                  'normal tile placement and the company does not need a route to the '\
                  'spike. Once acquired, the private company pays its revenue to the owning '\
                  'company until the power is exercised and the company is closed.',
            abilities: [
              {
                type: 'tile_lay',
                owner_type: 'corporation',
                when: 'track',
                count: 1,
                closed_when_used_up: true,
                # hexes: %w[F7 G8 H5 H9 I10 J7 J11 M28 M40 Q28],
                tiles: %w[P1],
                cost: 0,
                consume_tile_lay: false,
              },
            ],
            color: nil,
          },
          {
            name: 'P13-Harbor Improvements (Large Port)',
            sym: 'P13',
            value: 0,
            revenue: 10,
            desc: 'MAJOR, Phase 3. Replace a spike going to water with this tile. Lay this tile on '\
                  'a spike that does not already have a port. The spike now counts as a 40 '\
                  '(gren)/50 (brown)/60 (gray) and is treated like a gray off-board area for '\
                  'counting train runs for all companies. This is in addition to the company’s '\
                  'normal tile placement and the company does not need a route to the '\
                  'spike. Once acquired, the private company pays its revenue to the owning '\
                  'company until the power is exercised and the company is closed.',
            abilities: [
              {
                type: 'tile_lay',
                owner_type: 'corporation',
                when: 'track',
                count: 1,
                closed_when_used_up: true,
                # hexes: %w[F7 G8 H5 H9 I10 J7 J11 M28 M40 Q28],
                tiles: %w[P2],
                cost: 0,
                consume_tile_lay: false,
              },
            ],
            color: nil,
          },
          {
            name: 'P14-Lumber Baron',
            sym: 'P14',
            value: 0,
            revenue: 10,
            desc: 'Lumber Baron Description',
            abilities: [],
            color: nil,
          },
          {
            name: 'P15-Paper Mill',
            sym: 'P15',
            value: 0,
            revenue: 10,
            desc: 'Paper Mill Description',
            abilities: [],
            color: nil,
          },
          {
            name: 'P16-Pacific Portage Company',
            sym: 'P16',
            value: 0,
            revenue: 10,
            desc: 'Pacific Portage Company Description',
            abilities: [],
            color: nil,
          },
          {
            name: 'P17-Ski Haus',
            sym: 'P17',
            value: 0,
            revenue: 10,
            desc: 'Ski Haus Description',
            abilities: [],
            color: nil,
          },
          {
            name: 'P18-Boom Town',
            sym: 'P18',
            value: 0,
            revenue: 10,
            desc: 'Boom Town Description',
            abilities: [],
            color: nil,
          },
          {
            name: 'P19-Rockport Coal Mine',
            sym: 'P19',
            value: 0,
            revenue: 10,
            desc: 'Boom Town Description',
            abilities: [],
            color: nil,
          },
          {
            name: 'P20-Backoom Negotiations',
            sym: 'P20',
            value: 0,
            revenue: 0,
            desc: 'Backoom Negotiations Description',
            abilities: [],
            color: nil,
          },
          {
            name: 'P21-Credit Mobilier',
            sym: 'P21',
            value: 0,
            revenue: 10,
            desc: 'Credit Mobilier Description',
            abilities: [],
            color: nil,
          },
          {
            name: 'MINOR: 1. Pacfic Great Eastern Railway',
            sym: 'M1',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. '\
                  'Associated with the Canadian Pacific Railway (CPR). Starting location is A8.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 2. Spokane & British Columbia Railway',
            sym: 'M2',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is B19.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 3. Bellingham Bay @ British Columbia Railroad',
            sym: 'M3',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is D11.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 4. Brewster @ Davenport Railroad',
            sym: 'M4',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. '\
                  'Associated with the Great Northern (GNR). Starting location is D19.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 5. Idaho @ Washington Northern Railway',
            sym: 'M5',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. '\
                  'Associated with the Chicago, Milwaukee & Puget Sound (CMPS). Starting location is D23.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 6. Port Townsend and Southern Railroad',
            sym: 'M6',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is F9.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 7. SPokane Falls and Northern Railway',
            sym: 'M7',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. '\
                  'Associated with the Seattle & Walla Walla (SWW). Starting location is F23.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 8. Puget Sound Shore Railroad',
            sym: 'M8',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is H11.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 9. Wenatchee Valley Railroad',
            sym: 'M9',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is H19.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 10. Tacoma, Olympia and Grays Harbor Railroad Company',
            sym: 'M10',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is I12.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 11. Aberdeen & Oakville Railroad',
            sym: 'M11',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is J5.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 12. Connell Northern Railway Company',
            sym: 'M12',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is J23.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 13. North Yakima Valley Railroad',
            sym: 'M13',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is L19.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 14. Camas Prarie Railroad',
            sym: 'M14',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is L23.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 15. Ilwaco Railroad Company',
            sym: 'M15',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. '\
                  'Associated with the Northen Pacific Failway (NP). Starting location is M4.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 16. Astoria and Columbia River Railroad Company',
            sym: 'M16',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is N5.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 17. Oregon Central Railroad',
            sym: 'M17',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is O8.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 18. Portland and Willamette Valley Railway',
            sym: 'M18',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. '\
                  'Associated with the Spokane, Portland & Seattle (SPS). Starting location is O8.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 19. Cascade Portage Railway',
            sym: 'M19',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. '\
                  'Associated with the Oregon Railroad & Navigation Co. (ORNC). Starting location is O14.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 20. Walla Walla Valley Railway',
            sym: 'M20',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is O20.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 21. The Great Southern Railroad',
            sym: 'M21',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is P21.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: A',
            sym: 'MA',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is A22.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: B',
            sym: 'MB',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is I12.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: C',
            sym: 'MC',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is O10.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
        ].freeze

        CORPORATIONS = [
          {
            sym: '1',
            name: '1',
            logo: '1822/1',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'A8',
            city: 0,
            color: '#d1232a',
            text_color: '#ffffff',
            reservation_color: nil,
          },
          {
            sym: '2',
            name: '2',
            logo: '1822/2',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'B19',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '3',
            name: '3',
            logo: '1822/3',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'D11',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '4',
            name: '4',
            logo: '1822/4',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'D19',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '5',
            name: '5',
            logo: '1822/5',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'D23',
            city: 0,
            color: '#8dd7f6',
            text_color: '#000000',
            reservation_color: nil,
          },
          {
            sym: '6',
            name: '6',
            logo: '1822/6',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'F9',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '7',
            name: '7',
            logo: '1822/7',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'F23',
            city: 0,
            color: '#f58121',
            text_color: '#ffffff',
            reservation_color: nil,
          },
          {
            sym: '8',
            name: '8',
            logo: '1822/8',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'H11',
            city: 0,
            color: '#32763f',
            text_color: '#ffffff',
            reservation_color: nil,
          },
          {
            sym: '9',
            name: '9',
            logo: '1822/9',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'H19',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '10',
            name: 'Grand Junction Railway',
            logo: '1822/10',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'I12',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '11',
            name: '11',
            logo: '1822/11',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'J5',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '12',
            name: '12',
            logo: '1822/12',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'J23',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '13',
            name: '13',
            logo: '1822/13',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'L19',
            city: 1,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '14',
            name: '14',
            logo: '1822/14',
            tokens: [20],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'L23',
            city: 1,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '15',
            name: '15',
            logo: '1822/15',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'M4',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '16',
            name: '16',
            logo: '1822/16',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'N5',
            city: 2,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '17',
            name: '17',
            logo: '1822/17',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'O8',
            city: 0, ## Todo - Check
            color: '#680b26',
            text_color: '#ffffff',
            reservation_color: nil,
          },
          {
            sym: '18',
            name: '18',
            logo: '1822/18',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'O8',
            city: 1, ## Todo - Check
            color: '#025aaa',
            text_color: '#ffffff',
            reservation_color: nil,
          },
          {
            sym: '19',
            name: '19',
            logo: '1822/19',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'O14',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '20',
            name: '20',
            logo: '1822/20',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'O20',
            city: 0,
            color: '#000000',
            text_color: '#ffffff',
            reservation_color: nil,
          },
          {
            sym: '21',
            name: '21',
            logo: '1822/21',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'P21',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: 'A',
            name: 'A',
            logo: '1822_pnw/a',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'A22',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: 'B',
            name: 'B',
            logo: '1822_pnw/b',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'I12',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: 'C',
            name: 'C',
            logo: '1822_pnw/c',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'O10',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: 'NP',
            name: 'Northern Pacific Railway',
            logo: '1822_pnw/NP',
            tokens: [0, 100],
            type: 'major',
            float_percent: 20,
            always_market_price: true,
            coordinates: 'O20',
            city: 4,
            color: '#e51c00',
            reservation_color: nil,
            destination_coordinates: 'I12',
            destination_icon: '1822_pnw/NP_DEST',
          },
          {
            sym: 'CPR',
            name: 'Canadian Pacific Railway',
            logo: '1822_mx/CPR',
            tokens: [0, 100],
            type: 'major',
            float_percent: 20,
            always_market_price: true,
            coordinates: 'A8',
            city: 2,
            color: '#000000',
            reservation_color: nil,
            destination_coordinates: 'A22',
            destination_icon: '1822_pnw/CPR_DEST',
          },
          {
            sym: 'GNR',
            name: 'Great Northern Railway',
            logo: '1822_pnw/GNR',
            tokens: [0, 100],
            type: 'major',
            float_percent: 20,
            always_market_price: true,
            coordinates: 'D11',
            color: '#ff7b93',
            text_color: 'black',
            reservation_color: nil,
            destination_coordinates: 'D23',
            destination_icon: '1822_pnw/GNR_DEST',
          },
          {
            sym: 'ORNC',
            name: 'Oregon Railroad and Navigation Company',
            logo: '1822_pnw/ORNC',
            tokens: [0, 100],
            type: 'major',
            float_percent: 20,
            always_market_price: true,
            coordinates: 'O8',
            city: 3,
            color: '#850040',
            reservation_color: nil,
            destination_coordinates: 'O20',
            destination_icon: '1822_pnw/ORNC_DEST',
          },
          {
            sym: 'SPS',
            name: 'Spokane, Portland, and Seattle Railway',
            logo: '1822_pnw/SPS',
            tokens: [0, 100],
            type: 'major',
            float_percent: 20,
            always_market_price: true,
            coordinates: 'O8',
            color: '#ff3600',
            reservation_color: nil,
            destination_coordinates: 'F23',
            destination_icon: '1822_pnw/SPS_DEST',
          },
          {
            sym: 'CMPS',
            name: 'Chicago, Milwaukee and Puget Sound',
            logo: '1822_pnw/CMPS',
            tokens: [0, 100],
            type: 'major',
            float_percent: 20,
            always_market_price: true,
            coordinates: 'F23',
            color: '#fab506',
            reservation_color: nil,
            destination_coordinates: 'H11',
            destination_icon: '1822_pnw/CMPS_DEST',
          },
          {
            sym: 'SWW',
            name: 'Seattle and Walla Walla Railroad',
            logo: '1822_pnw/SWW',
            tokens: [0, 100],
            type: 'major',
            float_percent: 20,
            always_market_price: true,
            coordinates: 'H11',
            city: 5,
            color: '#004c6c',
            reservation_color: nil,
            destination_coordinates: 'O22',
            destination_icon: '1822_pnw/SWW_DEST',
          },
        ].freeze
      end
    end
  end
end
