# frozen_string_literal: true

module Engine
  module Game
    module G1840
      module Entities
        MARKET = [
            %w[100 105 110 115 121 128 136 145 155 167 180 195 210 230 250 275 300 330 360 400],
            %w[90 95p 100z 105 111 118 126 135 145 157 170 185 200 220 240 265 290 320 350 380],
            %w[80 85p 90z 95 101 108 116 125 135 147 160 175 190 210 230],
            %w[70 75p 80z 85 91 98 106 115 125 137],
            %w[60 65p 70z 75 81],
        ].freeze

        PHASES = [
            {
              name: '1',
              train_limit: 3,
              tiles: %i[yellow],
              operating_rounds: 2,
            },
            {
              name: '2',
              train_limit: 3,
              tiles: %i[yellow green],
              status: ['can_buy_companies'],
              operating_rounds: 2,
            },
            {
              name: '3',
              train_limit: 3,
              tiles: %i[yellow green brown],
              status: ['can_buy_companies'],
              operating_rounds: 2,
            },
            {
              name: '4',
              train_limit: 3,
              tiles: %i[yellow green brown gray],
              status: ['can_buy_companies'],
              operating_rounds: 3,
            },

          ].freeze

        TRAINS = [
            {
              name: 'Y1',
              distance: 99,
              price: 100,
              available_on: '1',
              variants: [
                {
                  name: 'Y2',
                  price: 50,
                },
              ],
            },
            {
              name: 'O1',
              distance: 99,
              price: 300,
              available_on: '1',
              variants: [
                {
                  name: 'O2',
                  price: 200,
                },
                {
                  name: 'O3',
                  price: 100,
                },
              ],
            },
            {
              name: 'R1',
              distance: 99,
              price: 500,
              available_on: '1',
              variants: [
                {
                  name: 'R2',
                  price: 400,
                },
                {
                  name: 'R3',
                  price: 300,
                },
              ],
            },
            {
              name: 'Pi1',
              distance: 99,
              price: 600,
              available_on: '1',
              variants: [
                {
                  name: 'Pi2',
                  price: 500,
                },
                {
                  name: 'Pi3',
                  price: 400,
                },
              ],
            },
            {
              name: 'Pu1',
              distance: 99,
              price: 800,
              available_on: '1',
              variants: [
                {
                  name: 'Pu2',
                  price: 600,
                },
              ],
            },
            {
              name: 'City',
              distance: 99,
              price: 0,
              num: 4,
            },
          ].freeze

        COMPANIES = [
            {
              name: 'Prater',
              sym: 'PR',
              value: 10,
              revenue: 5,
              desc: 'Increase income by 20 if tram route runs to or through D28',
              abilities: [
                {
                  type: 'hex_bonus',
                  owner_type: 'corporation',
                  hexes: ['D28'],
                  amount: 20,
                },
              ],
              color: nil,
            },
            {
              name: 'Karlskirche',
              sym: 'KK',
              value: 20,
              revenue: 10,
              desc: 'Increase income by 20 if tram route runs to or through E21 (when red tile is placed)',
              abilities: [
                {
                  type: 'hex_bonus',
                  owner_type: 'corporation',
                  hexes: ['E21'],
                  amount: 20,
                },
              ],
              color: nil,
            },
            {
              name: 'Schloss Belvedere',
              sym: 'SB',
              value: 30,
              revenue: 15,
              desc: 'Increase income by 20 if tram route runs to or through H22',
              abilities: [
                {
                  type: 'hex_bonus',
                  owner_type: 'corporation',
                  hexes: ['H22'],
                  amount: 20,
                },
              ],
              color: nil,
            },
            {
              name: 'Hofburg',
              sym: 'HB',
              value: 40,
              revenue: 20,
              desc: 'Increase income by 20 if tram route runs to or through E19 (when red tile is placed)',
              abilities: [
                {
                  type: 'hex_bonus',
                  owner_type: 'corporation',
                  hexes: ['E19'],
                  amount: 20,
                },
              ],
              color: nil,
            },
            {
              name: 'Stephansdom',
              sym: 'SD',
              value: 50,
              revenue: 25,
              desc: 'Increase income by 20 if tram route runs to or through D20 (when red tile is placed)',
              abilities: [
                {
                  type: 'hex_bonus',
                  owner_type: 'corporation',
                  hexes: ['D20'],
                  amount: 20,
                },
              ],
              color: nil,
            },
            {
              name: 'Schloss Schönbrunn',
              sym: 'SSB',
              value: 60,
              revenue: 30,
              desc: 'Increase income by 20 if tram route runs to or through K7',
              abilities: [
                {
                  type: 'hex_bonus',
                  owner_type: 'corporation',
                  hexes: ['K7'],
                  amount: 20,
                },
              ],
              color: nil,
            },
          ].freeze

        CORPORATIONS = [
          {
            sym: '1',
            name: 'Linie 1',
            logo: '1840/1',
            tokens: [0, 20, 40, 60, 80, 100],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'D18',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '2',
            name: 'Linie 2',
            logo: '1840/2',
            tokens: [0, 20, 40, 60, 80, 100],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'D18',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '3',
            name: 'Linie 3',
            logo: '1840/3',
            tokens: [0, 20, 40, 60, 80, 100],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'E17',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '4',
            name: 'Linie 4',
            logo: '1840/4',
            tokens: [0, 20, 40, 60, 80, 100],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'H28',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '5',
            name: 'Linie 5',
            logo: '1840/5',
            tokens: [0, 20, 40, 60, 80, 100],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'G15',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '6',
            name: 'Linie 6',
            logo: '1840/6',
            tokens: [0, 20, 40, 60, 80, 100],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'K27',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '7',
            name: 'Linie 7',
            logo: '1840/7',
            tokens: [0, 20, 40, 60, 80, 100],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'F18',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '8',
            name: 'Linie 8',
            logo: '1840/8',
            tokens: [0, 20, 40, 60, 80, 100],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'J10',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '9',
            name: 'Linie 9',
            logo: '1840/9',
            tokens: [0, 20, 40, 60, 80, 100],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'C7',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '10',
            name: 'Linie 10',
            logo: '1840/10',
            tokens: [0, 20, 40, 60, 80, 100],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'D4',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '11',
            name: 'Linie 11',
            logo: '1840/11',
            tokens: [0, 20, 40, 60, 80, 100],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'B12',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '12',
            name: 'Linie 12',
            logo: '1840/12',
            tokens: [0, 20, 40, 60, 80, 100],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'E11',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '13',
            name: 'Linie 13',
            logo: '1840/13',
            tokens: [0, 20, 40, 60, 80, 100],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'G3',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '14',
            name: 'Linie 14',
            logo: '1840/14',
            tokens: [0, 20, 40, 60, 80, 100],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'E3',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '15',
            name: 'Linie 15',
            logo: '1840/15',
            tokens: [0, 20, 40, 60, 80, 100],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'J16',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '16',
            name: 'Linie 16',
            logo: '1840/16',
            tokens: [0, 20, 40, 60, 80, 100],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'D26',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '17',
            name: 'Linie 17',
            logo: '1840/17',
            tokens: [0, 20, 40, 60, 80, 100],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'A29',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '18',
            name: 'Linie 18',
            logo: '1840/18',
            tokens: [0, 20, 40, 60, 80, 100],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'I21',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            float_percent: 50,
            sym: 'WT',
            name: 'Wiener Tramway Gesellschaft',
            logo: '1840/WT',
            tokens: [],
            color: '#1A1A18',
            type: 'major',
            reservation_color: nil,
            shares: [50, 10, 10, 10, 10, 10],
            always_market_price: true,
          },
          {
            float_percent: 50,
            sym: 'DT K&C',
            name: 'Dampftramway Krauss & Comp.',
            logo: '1840/DTKC',
            tokens: [],
            color: '#AD4382',
            type: 'major',
            reservation_color: nil,
            shares: [50, 10, 10, 10, 10, 10],
            always_market_price: true,
          },
          {
            float_percent: 50,
            sym: 'SJE',
            name: 'Schaeck-Jaquet & Comp',
            logo: '1840/SJE',
            tokens: [],
            color: '#2F2483',
            type: 'major',
            reservation_color: nil,
            shares: [50, 10, 10, 10, 10, 10],
            always_market_price: true,
          },
          {
            float_percent: 50,
            sym: 'BBG',
            name: 'Bau- und Betriebsgesellschaft für städtische
              Straßenbahnen in Wien',
            logo: '1840/BBG',
            tokens: [],
            color: '#FECC00',
            text_color: 'black',
            type: 'major',
            reservation_color: nil,
            shares: [50, 10, 10, 10, 10, 10],
            always_market_price: true,
          },
          {
            float_percent: 50,
            sym: 'WKB',
            name: 'Wien-Kagraner Bahn',
            logo: '1840/WKB',
            tokens: [],
            color: '#00963F',
            type: 'major',
            reservation_color: nil,
            shares: [50, 10, 10, 10, 10, 10],
            always_market_price: true,
          },
          {
            float_percent: 50,
            sym: 'GWStStB',
            name: 'Gemeinde Wien - Städtische Straßenbahnen',
            logo: '1840/GWStStB',
            tokens: [],
            color: '#E3000F',
            type: 'major',
            reservation_color: nil,
            shares: [50, 10, 10, 10, 10, 10],
            always_market_price: true,
          },
          {
            float_percent: 0,
            sym: 'W',
            name: 'Wiental-Linie',
            logo: '1840/W',
            tokens: [0, 0, 0, 0],
            color: '#A15E48',
            type: 'city',
            reservation_color: nil,
            shares: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
            always_market_price: true,
          },
          {
            float_percent: 0,
            sym: 'V',
            name: 'Vororte-Linie',
            logo: '1840/V',
            tokens: [0, 0, 0, 0, 0, 0],
            color: '#DAB06E',
            text_color: 'black',
            type: 'city',
            reservation_color: nil,
            shares: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
            always_market_price: true,
          },
          {
            float_percent: 0,
            sym: 'G',
            name: 'Gürtel-Linie',
            logo: '1840/G',
            tokens: [0, 0, 0],
            color: '#F58220',
            text_color: 'black',
            type: 'city',
            reservation_color: nil,
            shares: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
            always_market_price: true,
          },
          {
            float_percent: 0,
            sym: 'D',
            name: 'Donaukanal-Linie',
            logo: '1840/D',
            tokens: [0, 0, 0, 0],
            color: '#FFCB1C',
            text_color: 'black',
            type: 'city',
            reservation_color: nil,
            shares: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
            always_market_price: true,
          },
          ].freeze
      end
    end
  end
end
