# frozen_string_literal: true

module Engine
  module Game
    module G18Ireland
      module Entities
        COMPANIES = [
          {
            name: 'Dalkey Atmospheric Railway',
            value: 20,
            revenue: 5,
            desc: 'No company can build in the Wicklow hex until this company is either bought by'\
            ' any company or closed.',
            sym: 'DAR',
            abilities: [{ type: 'blocks_hexes', owner_type: 'player', hexes: ['G13'] }], # @todo: update to Wicklow
            color: nil,
          },
          # @todo: add other privates
        ].freeze

        CORPORATIONS = [
          {
            float_percent: 20,
            sym: 'GSWR',
            name: 'Great Southern & Western Railway',
            logo: '18_ireland/GSWR',
            tokens: [0, 20, 50],
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            always_market_price: true,
            color: 'red',
            reservation_color: nil,
          },
          {
            float_percent: 20,
            sym: 'GNRI',
            name: 'Great Northern Railway (Ireland)',
            logo: '18_ireland/GNRI',
            tokens: [0, 20, 50],
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            always_market_price: true,
            color: 'blue',
            reservation_color: nil,
          },
          {
            float_percent: 20,
            sym: 'DSER',
            name: 'Dublin & South Eastern Railway',
            logo: '18_ireland/DSER',
            tokens: [0, 20, 50],
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            always_market_price: true,
            color: 'black',
            reservation_color: nil,
          },
          {
            float_percent: 20,
            sym: 'MGWR',
            name: 'Midland Great Western Railway',
            logo: '18_ireland/MGWR',
            tokens: [0, 20, 50],
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            always_market_price: true,
            color: 'green',
            reservation_color: nil,
          },
          {
            float_percent: 20,
            sym: 'MRNCC',
            name: 'Midland Railway North Counties Committee',
            logo: '18_ireland/MRNCC',
            tokens: [0, 20, 50],
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            always_market_price: true,
            color: 'pink',
            reservation_color: nil,
          },
          {
            float_percent: 20,
            sym: 'WLWR',
            name: 'Waterford, Limerick & Western Railway',
            logo: '18_ireland/WLWR',
            tokens: [0, 20, 50],
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            always_market_price: true,
            color: 'yellow',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            float_percent: 20,
            sym: 'CBSCR',
            name: 'Cork, Bandon & South Coast Railway',
            logo: '18_ireland/CBSCR',
            tokens: [0, 20, 50],
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            always_market_price: true,
            color: 'brown',
            reservation_color: nil,
          },
          # @todo: home token locations
          {
            float_percent: 40,
            sym: 'LER',
            name: 'Londonderry & Enniskillen',
            logo: '18_ireland/LER',
            tokens: [0],
            shares: [40, 20, 20, 20],
            always_market_price: true,
            color: 'red', # @todo: rouge
            reservation_color: nil,
          },
          {
            float_percent: 40,
            sym: 'CBPR',
            name: 'Cork, Blackrock & Passage Railway',
            logo: '18_ireland/CBPR',
            tokens: [0],
            shares: [40, 20, 20, 20],
            always_market_price: true,
            color: 'black',
            reservation_color: nil,
          },
          {
            float_percent: 40,
            sym: 'EBSR',
            name: 'Einniskillen, Bundoran & Sligo Railway',
            logo: '18_ireland/EBSR',
            tokens: [0],
            shares: [40, 20, 20, 20],
            always_market_price: true,
            color: 'yellow',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            float_percent: 40,
            sym: 'SLNCR',
            name: 'Sligo, Leitrim & Northern Counties Railway',
            logo: '18_ireland/SLNCR',
            tokens: [0],
            shares: [40, 20, 20, 20],
            always_market_price: true,
            color: 'gray',
            reservation_color: nil,
          },
          {
            float_percent: 40,
            sym: 'DDR',
            name: 'Dublin & Drogheda Railway',
            logo: '18_ireland/DDR',
            tokens: [0],
            shares: [40, 20, 20, 20],
            always_market_price: true,
            color: 'yellow', # @todo: more mustardy
            text_color: 'black',
            reservation_color: nil,
          },
          {
            float_percent: 40,
            sym: 'GJR',
            name: 'Grand Junction Railway',
            logo: '18_ireland/GJR',
            tokens: [0],
            shares: [40, 20, 20, 20],
            always_market_price: true,
            color: 'white',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            float_percent: 40,
            sym: 'UR',
            name: 'Ulster Railway',
            logo: '18_ireland/UR',
            tokens: [0],
            shares: [40, 20, 20, 20],
            always_market_price: true,
            color: 'brown', # @todo: not quite right
            text_color: 'black',
            reservation_color: nil,
          },
          {
            float_percent: 40,
            sym: 'DER',
            name: 'Dundalt & Enniskillen Railway',
            logo: '18_ireland/DER',
            tokens: [0],
            shares: [40, 20, 20, 20],
            always_market_price: true,
            color: 'pink',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            float_percent: 40,
            sym: 'GNWR',
            name: 'Great Northern & Western Railway',
            logo: '18_ireland/GNWR',
            tokens: [0],
            shares: [40, 20, 20, 20],
            always_market_price: true,
            color: 'blue', # @todo: more navy blue
            reservation_color: nil,
          },
          {
            float_percent: 40,
            sym: 'WKR',
            name: 'Waterford & Kilkenny Railway',
            logo: '18_ireland/WKR',
            tokens: [0],
            shares: [40, 20, 20, 20],
            always_market_price: true,
            color: 'blue', # @todo: light blue
            reservation_color: nil,
          },
          {
            float_percent: 40,
            sym: 'CIR',
            name: 'Central Ireland Railway',
            logo: '18_ireland/CIR',
            tokens: [0],
            shares: [40, 20, 20, 20],
            always_market_price: true,
            color: 'green',
            reservation_color: nil,
          },
          {
            float_percent: 40,
            sym: 'KJR',
            name: 'Kilkenny Junction Railway',
            logo: '18_ireland/KJR',
            tokens: [0],
            shares: [40, 20, 20, 20],
            always_market_price: true,
            color: 'red',
            reservation_color: nil,
          },
          {
            float_percent: 40,
            sym: 'WLR',
            name: 'Waterford & Limerick Railway',
            logo: '18_ireland/WLR',
            tokens: [0],
            shares: [40, 20, 20, 20],
            always_market_price: true,
            color: 'red',
            reservation_color: nil,
          },
        ].freeze
      end
    end
  end
end
