# frozen_string_literal: true

module Engine
  module Game
    module G1807
      module Entities
        COMPANIES = [
          {
            name: 'Swansea and Mumbles',
            sym: 'P1',
            type: 'railway',
            value: 30,
            min_price: 1,
            max_price: 30,
            revenue: 10,
            discount: 10,
            desc: 'P1. No special abilities.',
            color: 'white',
          },
          {
            name: 'Stockton and Darlington',
            sym: 'P2',
            type: 'railway',
            value: 45,
            min_price: 1,
            max_price: 45,
            revenue: 15,
            discount: 15,
            desc: 'P2. Gives an extra, free, track lay in Darlington (I17) when owned by a player.',
            color: 'white',
            abilities: [
              {
                type: 'tile_lay',
                when: 'owning_player_track',
                free: true,
                owner_type: 'player',
                hexes: %w[I17],
                tiles: %w[3 4 58],
              },
            ],
          },
          {
            name: 'Monkland and Kirkintilloch',
            sym: 'P3',
            type: 'railway',
            value: 45,
            min_price: 1,
            max_price: 45,
            revenue: 15,
            discount: 15,
            desc: 'P3. Gives an extra, free, track lay in Falkirk (D8) when owned by a player.',
            color: 'white',
            abilities: [
              {
                type: 'tile_lay',
                when: 'owning_player_track',
                free: true,
                owner_type: 'player',
                hexes: %w[D8],
                tiles: %w[3 4 58],
              },
            ],
          },
          {
            name: 'Canterbury and Whistable',
            sym: 'P4',
            type: 'railway',
            value: 45,
            min_price: 1,
            max_price: 45,
            revenue: 15,
            discount: 15,
            desc: 'P4. Gives an extra, free, track lay in Canterbury (V28) when owned by a player.',
            color: 'white',
            abilities: [
              {
                type: 'tile_lay',
                when: 'owning_player_track',
                free: true,
                owner_type: 'player',
                hexes: %w[V28],
                tiles: %w[3 4 58],
              },
            ],
          },
          {
            name: 'Leicester and Swannington',
            sym: 'P5',
            type: 'railway',
            value: 60,
            min_price: 1,
            max_price: 60,
            revenue: 20,
            discount: 20,
            desc: 'P5. Gives an extra, free, track lay in Leicester (P18) when owned by a player.',
            color: 'white',
            abilities: [
              {
                type: 'tile_lay',
                when: 'owning_player_track',
                free: true,
                owner_type: 'player',
                hexes: %w[P18],
                tiles: %w[3 4 58],
              },
            ],
          },
          {
            name: 'Newcastle and Carlisle',
            sym: 'P6',
            type: 'railway',
            value: 60,
            min_price: 1,
            max_price: 60,
            revenue: 20,
            discount: 20,
            desc: 'P6. Gives a £10 revenue bonus for Newcastle (G17).',
            color: 'white',
            abilities: [
              {
                type: 'hex_bonus',
                owner_type: 'corporation',
                amount: 10,
                hexes: %w[G17],
              },
            ],
          },
          {
            name: 'London and Greenwich',
            sym: 'P7',
            type: 'railway',
            value: 75,
            min_price: 1,
            max_price: 75,
            revenue: 25,
            discount: 25,
            desc: 'P7. Gives a £10 revenue bonus for London.',
            color: 'white',
            abilities: [
              {
                type: 'hex_bonus',
                owner_type: 'corporation',
                amount: 10,
                hexes: %w[K27 K29 L26 L30 M27 M29],
              },
            ],
          },
          {
            name: 'London and Blackwall',
            sym: 'P8',
            type: 'railway',
            value: 75,
            min_price: 1,
            max_price: 75,
            revenue: 25,
            discount: 25,
            desc: 'P8. Gives a £10 revenue bonus for London.',
            color: 'white',
            abilities: [
              {
                type: 'hex_bonus',
                owner_type:
                'corporation',
                amount: 10,
                hexes: %w[K27 K29 L26 L30 M27 M29],
              },
            ],
          },
          {
            name: 'West London',
            sym: 'P9',
            type: 'railway',
            value: 75,
            min_price: 1,
            max_price: 75,
            revenue: 25,
            discount: 25,
            desc: 'P9. Gives a £10 revenue bonus for London.',
            color: 'white',
            abilities: [
              {
                type: 'hex_bonus',
                owner_type: 'corporation',
                amount: 10,
                hexes: %w[K27 K29 L26 L30 M27 M29],
              },
            ],
          },
          {
            name: 'Liverpool and Manchester',
            sym: 'P10',
            type: 'railway',
            value: 90,
            min_price: 1,
            max_price: 90,
            revenue: 30,
            discount: 30,
            desc: 'P10. Gives a £10 revenue bonus for Liverpool (M11).',
            color: 'white',
            abilities: [
              {
                type: 'hex_bonus',
                owner_type: 'corporation',
                amount: 10,
                hexes: %w[M11],
              },
            ],
          },
          {
            name: 'Irish Sea Ferry',
            sym: 'F1',
            type: 'ferry',
            value: 50,
            min_price: 1,
            max_price: 50,
            revenue: 10,
            desc: 'F1. Gives a £10 revenue bonus for one of the Ireland off-board areas.',
            color: '#9fd9f7',
            abilities: [
              { type: 'revenue_change', revenue: 15, on_phase: '3' },
              { type: 'revenue_change', revenue: 20, on_phase: '5' },
              { type: 'revenue_change', revenue: 25, on_phase: '7' },
              {
                type: 'hex_bonus',
                owner_type: 'corporation',
                amount: 10,
                hexes: %w[H2 N4 S3],
              },
            ],
          },
          {
            name: 'Irish Sea Ferry',
            sym: 'F2',
            type: 'ferry',
            value: 50,
            min_price: 1,
            max_price: 50,
            revenue: 10,
            desc: 'F2. Gives a £10 revenue bonus for one of the Ireland off-board areas.',
            color: '#9fd9f7',
            abilities: [
              { type: 'revenue_change', revenue: 15, on_phase: '3' },
              { type: 'revenue_change', revenue: 20, on_phase: '5' },
              { type: 'revenue_change', revenue: 25, on_phase: '7' },
              {
                type: 'hex_bonus',
                owner_type: 'corporation',
                amount: 10,
                hexes: %w[H2 N4 S3],
              },
            ],
          },
          {
            name: 'Irish Sea Ferry',
            sym: 'F3',
            type: 'ferry',
            value: 50,
            min_price: 1,
            max_price: 50,
            revenue: 10,
            desc: 'F3. Gives a £10 revenue bonus for one of the Ireland off-board areas.',
            color: '#9fd9f7',
            abilities: [
              { type: 'revenue_change', revenue: 15, on_phase: '3' },
              { type: 'revenue_change', revenue: 20, on_phase: '5' },
              { type: 'revenue_change', revenue: 25, on_phase: '7' },
              {
                type: 'hex_bonus',
                owner_type: 'corporation',
                amount: 10,
                hexes: %w[H2 N4 S3],
              },
            ],
          },
          {
            name: 'Hull Ferry',
            sym: 'F4',
            type: 'ferry',
            value: 100,
            min_price: 1,
            max_price: 100,
            revenue: 20,
            desc: 'F4. Gives a £20 revenue bonus for the Hull off-board area (L22).',
            color: '#9fd9f7',
            abilities: [
              { type: 'revenue_change', revenue: 30, on_phase: '3' },
              { type: 'revenue_change', revenue: 40, on_phase: '5' },
              { type: 'revenue_change', revenue: 50, on_phase: '7' },
              {
                type: 'hex_bonus',
                owner_type: 'corporation',
                amount: 20,
                hexes: %w[L22],
              },
            ],
          },
          {
            name: 'Harwich Ferry',
            sym: 'F5',
            type: 'ferry',
            value: 100,
            min_price: 1,
            max_price: 100,
            revenue: 20,
            desc: 'F5. Gives a £20 revenue bonus for the Harwich off-board area (S29).',
            color: '#9fd9f7',
            abilities: [
              { type: 'revenue_change', revenue: 30, on_phase: '3' },
              { type: 'revenue_change', revenue: 40, on_phase: '5' },
              { type: 'revenue_change', revenue: 50, on_phase: '7' },
              {
                type: 'hex_bonus',
                owner_type: 'corporation',
                amount: 20,
                hexes: %w[S29],
              },
            ],
          },
          {
            name: 'Plymouth Ferry',
            sym: 'F6',
            type: 'ferry',
            value: 100,
            min_price: 1,
            max_price: 100,
            revenue: 20,
            desc: 'F6. Gives a £20 revenue bonus for the Plymouth off-board area (X8).',
            color: '#9fd9f7',
            abilities: [
              { type: 'revenue_change', revenue: 30, on_phase: '3' },
              { type: 'revenue_change', revenue: 40, on_phase: '5' },
              { type: 'revenue_change', revenue: 50, on_phase: '7' },
              {
                type: 'hex_bonus',
                owner_type: 'corporation',
                amount: 20,
                hexes: %w[X8],
              },
            ],
          },
          {
            name: 'Dover Ferry',
            sym: 'F7',
            type: 'ferry',
            value: 150,
            min_price: 1,
            max_price: 150,
            revenue: 30,
            desc: 'F7. Gives a £30 revenue bonus for the Dover off-board area (V30).',
            color: '#9fd9f7',
            abilities: [
              { type: 'revenue_change', revenue: 45, on_phase: '3' },
              { type: 'revenue_change', revenue: 60, on_phase: '5' },
              { type: 'revenue_change', revenue: 75, on_phase: '7' },
              {
                type: 'hex_bonus',
                owner_type: 'corporation',
                amount: 30,
                hexes: %w[V30],
              },
            ],
          },
          {
            name: 'Aberdeen Ferry',
            sym: 'F8',
            type: 'ferry',
            value: 150,
            min_price: 1,
            max_price: 150,
            revenue: 30,
            desc: 'F8. Gives a £30 revenue bonus for the Aberdeen off-board area (A13).',
            color: '#9fd9f7',
            abilities: [
              { type: 'revenue_change', revenue: 45, on_phase: '3' },
              { type: 'revenue_change', revenue: 60, on_phase: '5' },
              { type: 'revenue_change', revenue: 75, on_phase: '7' },
              {
                type: 'hex_bonus',
                owner_type: 'corporation',
                amount: 30,
                hexes: %w[A13],
              },
            ],
          },
          {
            name: 'Metropolitan Railway',
            sym: 'U1',
            type: 'underground',
            value: 100,
            min_price: 1,
            max_price: 100,
            revenue: 40,
            desc: 'U1. Gives a £10 revenue bonus for London.',
            color: '#f7b7a8',
            abilities: [
              { type: 'revenue_change', revenue: 50, on_phase: '7' },
              {
                type: 'hex_bonus',
                owner_type: 'corporation',
                amount: 10,
                hexes: %w[K27 K29 L26 L30 M27 M29],
              },
            ],
          },
          {
            name: 'City and South London',
            sym: 'U2',
            type: 'underground',
            value: 150,
            min_price: 1,
            max_price: 150,
            revenue: 75,
            desc: 'U2. Gives a £10 revenue bonus for London.',
            color: '#f7b7a8',
            abilities: [
              {
                type: 'hex_bonus',
                owner_type: 'corporation',
                amount: 10,
                hexes: %w[K27 K29 L26 L30 M27 M29],
              },
            ],
          },
        ].freeze

        CORPORATIONS = [
          {
            sym: 'BE',
            name: 'Bristol and Exeter Railway',
            logo: '1807/BE',
            float_percent: 100,
            always_market_price: true,
            tokens: [0],
            type: 'minor',
            coordinates: 'U13',
            shares: [100],
            max_ownership_percent: 100,
            color: '#ffed00',
            text_color: 'black',
          },
          {
            sym: 'BG',
            name: 'Birmingham and Gloucester Railway',
            logo: '1807/BG',
            float_percent: 100,
            always_market_price: true,
            tokens: [0],
            type: 'minor',
            coordinates: 'Q15',
            city: 0,
            shares: [100],
            max_ownership_percent: 100,
            color: '#ffed00',
            text_color: 'black',
          },
          {
            sym: 'EC',
            name: 'Eastern Counties Railway',
            logo: '1807/EC',
            float_percent: 100,
            always_market_price: true,
            tokens: [0],
            type: 'minor',
            coordinates: 'L30',
            city: 1,
            shares: [100],
            max_ownership_percent: 100,
            color: '#ffed00',
            text_color: 'black',
          },
          {
            sym: 'EG',
            name: 'Edinburgh and Glasgow Railway',
            logo: '1807/EG',
            float_percent: 100,
            always_market_price: true,
            tokens: [0],
            type: 'minor',
            coordinates: 'D10',
            shares: [100],
            max_ownership_percent: 100,
            color: '#1a1a18',
            text_color: 'white',
          },
          {
            sym: 'EK',
            name: 'East Kent Railway',
            logo: '1807/EK',
            float_percent: 100,
            always_market_price: true,
            tokens: [0],
            type: 'minor',
            coordinates: 'M29',
            city: 1,
            shares: [100],
            max_ownership_percent: 100,
            color: '#ffed00',
            text_color: 'black',
          },
          {
            sym: 'EPD',
            name: 'Edinburgh, Perth and Dundee Railway',
            logo: '1807/EPD',
            float_percent: 100,
            always_market_price: true,
            tokens: [0],
            type: 'minor',
            coordinates: 'C11',
            shares: [100],
            max_ownership_percent: 100,
            color: '#ef7c00',
            text_color: 'black',
          },
          {
            sym: 'GA',
            name: 'Glasgow and Ayr Railway',
            logo: '1807/GA',
            float_percent: 100,
            always_market_price: true,
            tokens: [0],
            type: 'minor',
            coordinates: 'D6',
            city: 0,
            shares: [100],
            max_ownership_percent: 100,
            color: '#e3000f',
            text_color: 'white',
          },
          {
            sym: 'GC',
            name: 'Glasgow and Carlisle Railway',
            logo: '1807/GC',
            float_percent: 100,
            always_market_price: true,
            tokens: [0],
            type: 'minor',
            coordinates: 'D6',
            city: 1,
            shares: [100],
            max_ownership_percent: 100,
            color: '#afca05',
            text_color: 'black',
          },
          {
            sym: 'GJ',
            name: 'Grand Junction Railway',
            logo: '1807/GJ',
            float_percent: 100,
            always_market_price: true,
            tokens: [0],
            type: 'minor',
            coordinates: 'P14',
            shares: [100],
            max_ownership_percent: 100,
            color: '#007ab5',
            text_color: 'white',
          },
          {
            sym: 'LB',
            name: 'London and Brighton Railway',
            logo: '1807/LB',
            float_percent: 100,
            always_market_price: true,
            tokens: [0],
            type: 'minor',
            coordinates: 'M27',
            city: 1,
            shares: [100],
            max_ownership_percent: 100,
            color: '#007ab5',
            text_color: 'white',
          },
          {
            sym: 'LH',
            name: 'London and Birmingham Railway',
            logo: '1807/LH',
            float_percent: 100,
            always_market_price: true,
            tokens: [0],
            type: 'minor',
            coordinates: 'K27',
            city: 0,
            shares: [100],
            max_ownership_percent: 100,
            color: '#1a1a18',
            text_color: 'white',
          },
          {
            sym: 'LR',
            name: 'London and Bristol Railway',
            logo: '1807/LR',
            float_percent: 100,
            always_market_price: true,
            tokens: [0],
            type: 'minor',
            coordinates: 'L26',
            city: 1,
            shares: [100],
            max_ownership_percent: 100,
            color: '#afca05',
            text_color: 'black',
          },
          {
            sym: 'LS',
            name: 'London and Southampton Railway',
            logo: '1807/LS',
            float_percent: 100,
            always_market_price: true,
            tokens: [0],
            type: 'minor',
            coordinates: 'M27',
            city: 0,
            shares: [100],
            max_ownership_percent: 100,
            color: '#afca05',
            text_color: 'black',
          },
          {
            sym: 'LY',
            name: 'London and York Railway',
            logo: '1807/LY',
            float_percent: 100,
            always_market_price: true,
            tokens: [0],
            type: 'minor',
            coordinates: 'K29',
            city: 0,
            shares: [100],
            max_ownership_percent: 100,
            color: '#ad4482',
            text_color: 'white',
          },
          {
            sym: 'MC',
            name: 'Midland Counties Railway',
            logo: '1807/MC',
            float_percent: 100,
            always_market_price: true,
            tokens: [0],
            type: 'minor',
            coordinates: 'O19',
            shares: [100],
            max_ownership_percent: 100,
            color: '#00963f',
            text_color: 'white',
          },
          {
            sym: 'ML',
            name: 'Manchester and Leeds Railway',
            logo: '1807/ML',
            float_percent: 100,
            always_market_price: true,
            tokens: [0],
            type: 'minor',
            coordinates: 'M15',
            city: 1,
            shares: [100],
            max_ownership_percent: 100,
            color: '#ffffff',
            text_color: 'black',
          },
          {
            sym: 'ND',
            name: 'Newcastle and Darlington Junction Railway',
            logo: '1807/ND',
            float_percent: 100,
            always_market_price: true,
            tokens: [0],
            type: 'minor',
            coordinates: 'G17',
            shares: [100],
            max_ownership_percent: 100,
            color: '#007ab5',
            text_color: 'white',
          },
          {
            sym: 'NM',
            name: 'North Midland Railway',
            logo: '1807/NM',
            float_percent: 100,
            always_market_price: true,
            tokens: [0],
            type: 'minor',
            coordinates: 'O17',
            shares: [100],
            max_ownership_percent: 100,
            color: '#ffed00',
            text_color: 'black',
          },
          {
            sym: 'NU',
            name: 'North Union Railway',
            logo: '1807/NU',
            float_percent: 100,
            always_market_price: true,
            tokens: [0],
            type: 'minor',
            coordinates: 'L12',
            shares: [100],
            max_ownership_percent: 100,
            color: '#9c9c9c',
            text_color: 'white',
          },
          {
            sym: 'SAM',
            name: 'Sheffield, Ashton-under-Lyne and Manchester Railway',
            logo: '1807/SAM',
            float_percent: 100,
            always_market_price: true,
            tokens: [0],
            type: 'minor',
            coordinates: 'M17',
            shares: [100],
            max_ownership_percent: 100,
            color: '#ffed00',
            text_color: 'black',
          },
          {
            sym: 'SE',
            name: 'South Eastern Railway',
            logo: '1807/SE',
            float_percent: 100,
            always_market_price: true,
            tokens: [0],
            type: 'minor',
            coordinates: 'M29',
            city: 0,
            shares: [100],
            max_ownership_percent: 100,
            color: '#00963f',
            text_color: 'white',
          },
          {
            sym: 'TV',
            name: 'Taff Vale Railway',
            logo: '1807/TV',
            float_percent: 100,
            always_market_price: true,
            tokens: [0],
            type: 'minor',
            coordinates: 'U11',
            shares: [100],
            max_ownership_percent: 100,
            color: '#e3000f',
            text_color: 'white',
          },
          {
            sym: 'VN',
            name: 'Vale of Neath Railway',
            logo: '1807/VN',
            float_percent: 100,
            always_market_price: true,
            tokens: [0],
            type: 'minor',
            coordinates: 'U7',
            shares: [100],
            max_ownership_percent: 100,
            color: '#1a1a18',
            text_color: 'white',
          },
          {
            sym: 'YNM',
            name: 'York and North Midland Railway',
            logo: '1807/YNM',
            float_percent: 100,
            always_market_price: true,
            tokens: [0],
            type: 'minor',
            coordinates: 'K19',
            shares: [100],
            max_ownership_percent: 100,
            color: '#ffed00',
            text_color: 'black',
          },
          {
            sym: 'CR',
            name: 'Caledonian Railway',
            logo: '1807/CR',
            float_percent: 20,
            always_market_price: true,
            tokens: [0, 20, 20, 20],
            type: 'public',
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            color: '#008bd2',
            text_color: 'white',
          },
          {
            sym: 'GER',
            name: 'Great Eastern Railway',
            logo: '1807/GER',
            float_percent: 20,
            always_market_price: true,
            tokens: [0, 20, 20, 20],
            type: 'public',
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            color: '#c2e6fb',
            text_color: 'black',
          },
          {
            sym: 'GNR',
            name: 'Great Northern Railway',
            logo: '1807/GNR',
            float_percent: 20,
            always_market_price: true,
            tokens: [0, 20, 20, 20],
            type: 'public',
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            color: '#a7d3ae',
            text_color: 'black',
          },
          {
            sym: 'LBSC',
            name: 'London, Brighton and South Coast Railway',
            logo: '1807/LBSC',
            float_percent: 20,
            always_market_price: true,
            tokens: [0, 20, 20, 20],
            type: 'public',
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            color: '#ffcc00',
            text_color: 'black',
          },
          {
            sym: 'LNW',
            name: 'London and North Western Railway',
            logo: '1807/LNW',
            float_percent: 20,
            always_market_price: true,
            tokens: [0, 20, 20, 20],
            type: 'public',
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            color: '#878786',
            text_color: 'white',
          },
          {
            sym: 'LSW',
            name: 'London and South Western Railway',
            logo: '1807/LSW',
            float_percent: 20,
            always_market_price: true,
            tokens: [0, 20, 20, 20],
            type: 'public',
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            color: '#f2f1ed',
            text_color: 'black',
          },
          {
            sym: 'LYR',
            name: 'Lancashire and Yorkshire Railway',
            logo: '1807/LYR',
            float_percent: 20,
            always_market_price: true,
            tokens: [0, 20, 20, 20],
            type: 'public',
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            color: '#d1999c',
            text_color: 'black',
          },
          {
            sym: 'MR',
            name: 'Midland Railway',
            logo: '1807/MR',
            float_percent: 20,
            always_market_price: true,
            tokens: [0, 20, 20, 20],
            type: 'public',
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            color: '#fdaf94',
            text_color: 'black',
          },
          {
            sym: 'NBR',
            name: 'North British Railway',
            logo: '1807/NBR',
            float_percent: 20,
            always_market_price: true,
            tokens: [0, 20, 20, 20],
            type: 'public',
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            color: '#ae9675',
            text_color: 'white',
          },
          {
            sym: 'NER',
            name: 'North Eastern Railway',
            logo: '1807/NER',
            float_percent: 20,
            always_market_price: true,
            tokens: [0, 20, 20, 20],
            type: 'public',
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            color: '#dbe283',
            text_color: 'black',
          },
          {
            sym: 'SECR',
            name: 'South Eastern and Chatham Railway',
            logo: '1807/SECR',
            float_percent: 20,
            always_market_price: true,
            tokens: [0, 20, 20, 20],
            type: 'public',
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            color: '#fff7b2',
            text_color: 'black',
          },
          {
            sym: 'GCR',
            name: 'Great Central Railway',
            logo: '1807/GCR',
            float_percent: 20,
            always_market_price: true,
            tokens: [0, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
            type: 'system',
            shares: [20, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
            color: '#fdf39a',
            text_color: 'black',
          },
          {
            sym: 'GWR',
            name: 'Great Western Railway',
            logo: '1807/GWR',
            float_percent: 20,
            always_market_price: true,
            tokens: [0, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
            type: 'system',
            shares: [20, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
            color: '#9c9c9c',
            text_color: 'white',
          },
          {
            sym: 'LMS',
            name: 'London, Midlands and Scottish Railway',
            logo: '1807/LMS',
            float_percent: 20,
            always_market_price: true,
            tokens: [0, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
            type: 'system',
            shares: [20, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
            color: '#965256',
            text_color: 'white',
          },
          {
            sym: 'LNE',
            name: 'London and North Eastern Railway',
            logo: '1807/LNE',
            float_percent: 20,
            always_market_price: true,
            tokens: [0, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
            type: 'system',
            shares: [20, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
            color: '#999bb3',
            text_color: 'white',
          },
          {
            sym: 'SR',
            name: 'Southern Railway',
            logo: '1807/SR',
            float_percent: 20,
            always_market_price: true,
            tokens: [0, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
            type: 'system',
            shares: [20, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
            color: '#948f63',
            text_color: 'white',
          },
        ].freeze

        CORPORATION_SIZES = { 2 => :small, 10 => :medium, 20 => :large }.freeze
        MINORS_GROUP_A = %w[EG EPD GA GC ML ND NU YNM].freeze
        MINORS_GROUP_B = %w[BE BG GJ NM MC SAM TV VN EC EK LB LH LR LS LY SE].freeze
        MINORS_COLOR_BATCH1 = '#ffffff' # minors available from the start of the game
        MINORS_COLOR_BATCH2 = '#fff381' # minors available from the second stock round
        MINORS_COLOR_BATCH3 = '#d7ead8' # minors available phase 3
        IRISH_FERRIES = %w[F1 F2 F3].freeze

        def company_header(company)
          case company.type
          when :railway
            'PRIVATE RAILWAY COMPANY'
          when :ferry
            'FERRY COMPANY'
          when :underground
            'UNDERGROUND RAILWAY'
          end
        end

        def unstarted_corporation_summary
          unipoed = (@corporations + @future_corporations).reject(&:ipoed)
          minor = unipoed.select { |c| c.type == :minor }
          major = unipoed.select { |c| c.type == :public }
          system = unipoed.select { |c| c.type == :system }
          summary = "#{minor.size} #{minor.one? ? 'minor' : 'minors'}, " \
                    "#{major.size} public, " \
                    "#{system.size} #{system.one? ? 'system' : 'systems'}"
          [summary, unipoed]
        end

        def maximum_loans(entity)
          case entity.type
          when :minor
            2
          when :public
            5
          when :system
            10
          end
        end

        def setup_companies
          msg = 'The three private railway companies removed from play are: '
          rejected = @companies.select { |c| c.type == :railway }.sort_by { rand }.take(3)
          rejected.sort_by { |c| @companies.index(c) }.each do |company|
            msg += "#{company.sym} (#{company.name}), "
            @companies.delete(company)
          end
          @log << msg.sub(/, $/, '.')
        end

        def setup_minors
          group_a = MINORS_GROUP_A.sort_by { rand }.map do |sym|
            @corporations.find { |c| c.id == sym }
          end
          group_b = MINORS_GROUP_B.sort_by { rand }.map do |sym|
            @corporations.find { |c| c.id == sym }
          end

          minors_start = group_a.pop(4) + group_b.pop(8)
          minors_sr2 = group_a.pop(2) + group_b.pop(4)
          minors_phase3 = group_a + group_b

          minors_start.each { |minor| minor.reservation_color = MINORS_COLOR_BATCH1 }
          minors_sr2.each { |minor| minor.reservation_color = MINORS_COLOR_BATCH2 }
          minors_phase3.each { |minor| minor.reservation_color = MINORS_COLOR_BATCH3 }

          @log << 'The minor companies available from the start of the game are: ' \
                  "#{minors_start.map(&:id).sort.join(', ')}."
          @log << 'The minor companies available from the second stock round are: ' \
                  "#{minors_sr2.map(&:id).sort.join(', ')}."
          @log << 'The minor companies available from phase 3 are: ' \
                  "#{minors_phase3.map(&:id).sort.join(', ')}."
        end

        def irish_ferry?(company)
          IRISH_FERRIES.include?(company.sym)
        end
      end
    end
  end
end
