Layout/FirstArgumentIndentation:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: False

Layout/LineLength:
  Max: 120
  Exclude:
    - 'assets/js/view/svg_tokens/**/*'

Layout/MultilineMethodCallIndentation:
  Enabled: False

Layout/MultilineOperationIndentation:
  Enabled: False

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: False

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/CommandLiteral:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/MultipleComparison:
  Enabled: false

Style/MultilineIfModifier:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/DoubleNegation:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.7
