AllCops:
  TargetRubyVersion: 3.0

Layout/FirstArgumentIndentation:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: true

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/LineLength:
  Max: 120
  Exclude:
    - 'assets/js/view/svg_tokens/**/*'

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/MultilineHashBraceLayout:
  Enabled: true
  EnforcedStyle: new_line

Layout/MultilineHashKeyLineBreaks:
  Enabled: true

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/SpaceBeforeBrackets:
  Enabled: false

Lint/AmbiguousAssignment:
  Enabled: true

Lint/ConstantDefinitionInBlock: # TODO enable & check offenses
  Enabled: false

Lint/DuplicateBranch: # TODO enable & check offenses
  Enabled: false

Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true

Lint/EmptyBlock:
  Enabled: true

Lint/EmptyClass:
  Enabled: true

Lint/FloatComparison: # TODO enable & check offenses
  Enabled: false

Lint/MissingSuper: # TODO enable & check offenses
  Enabled: false

Lint/NoReturnInBeginEndBlocks:
  Enabled: true

Lint/RedundantSafeNavigation: # TODO enable & check offenses
  Enabled: false

Lint/ToEnumArguments:
  Enabled: true

Lint/UnexpectedBlockArity:
  Enabled: false

Lint/UnmodifiedReduceAccumulator:
  Enabled: true

Lint/UselessMethodDefinition: # TODO enable & check offenses
  Enabled: false

Lint/UselessTimes: # TODO enable & check offenses
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/VariableNumber: # TODO enable & check offenses, default or snake_case?
  Enabled: false
  # EnforcedStyle: snake_case

Naming/MethodParameterName:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: true

Style/CaseLikeIf: # TODO enable & check offenses
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/CollectionCompact:
  Enabled: false

Style/CombinableLoops: # TODO enable & check offenses
  Enabled: false

Style/CommandLiteral:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentDynamicEvalDefinition:
  Enabled: true

Style/EmptyCaseCondition:
  Enabled: false

Style/ExplicitBlockArgument: # TODO enable & check offenses, EnforcedStyle?
  Enabled: false
  # EnforcedStyle: no_braces

Style/HashAsLastArrayItem: # TODO enable & check offenses
  Enabled: false

Style/HashEachMethods: # TODO enable & check offenses
  Enabled: false

Style/HashExcept:
  Enabled: true

Style/HashLikeCase: # TODO enable & check offenses
  Enabled: false

Style/HashTransformKeys: # TODO enable & check offenses
  Enabled: false

Style/HashTransformValues: # TODO enable & check offenses
  Enabled: false

Style/MultipleComparison:
  Enabled: false

Style/MultilineIfModifier:
  Enabled: false

Style/NegatedIfElseCondition:
  Enabled: false

Style/NilLambda:
  Enabled: true

Style/OptionalBooleanParameter: # TODO enable & check offenses
  Enabled: false

Style/RedundantArgument:
  Enabled: false

Style/RedundantFreeze: # conflicts with Style/MutableConstant
  Enabled: false

Style/RedundantRegexpEscape: # TODO enable & check offenses
  Enabled: false

Style/SlicingWithRange: # TODO enable & check offenses
  Enabled: false

Style/SoleNestedConditional: # TODO enable & check offenses
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/SwapValues:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/DoubleNegation:
  Enabled: false
