x-rack: &rack
  image: 18xx_rack:dev
  environment:
    DATABASE_URL: postgres://root:password@db:5432/18xx_development
    RACK_ENV: development
    RUBYOPTS: --yjit
    OPAL_PREFORK_DISABLE: "true"
    # debug/info/warn/error/fatal
    DB_LOG_LEVEL: fatal
  build:
    args:
      RACK_ENV: development
  volumes:
    - .:/18xx:z
    - /18xx/vendor

services:
  rack:
    <<: *rack
    ports:
      - 9292:9292

  queue:
    <<: *rack
    command: bundle exec ruby queue.rb # bundle exec rerun --background -i 'build/*' -i 'public/*' 'ruby queue.rb'

  db:
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: 18xx_development
