x-rack: &rack
  image: 18xx_rack:dev
  environment:
    DATABASE_URL: postgres://root:password@db:5432/18xx_development
    RACK_ENV: development
    RUBYOPT: --yjit
    OPAL_PREFORK_DISABLE: "true"
    DB_LOG_LEVEL: fatal
    BUNDLE_APP_CONFIG: /usr/local/bundle
  build:
    args:
      RACK_ENV: development
    dockerfile: ${DEV_DOCKERFILE:-Dockerfile}
  volumes:
    - .:/18xx:z
    - rack_vendor:/18xx/vendor   
    - rack_bundle:/18xx/.bundle  
    - /18xx/desktop-shell

services:
  rack:
    <<: *rack
    ports:
      - 9292:9292
    depends_on:
      - db
      - redis

  queue:
    <<: *rack
    command: bundle exec ruby queue.rb
    depends_on:
      - db
      - redis

  db:
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: 18xx_development
    build:
      context: ./db/
      dockerfile: ${DEV_DOCKERFILE:-Dockerfile}

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379

volumes:
  rack_vendor:
  rack_bundle: