version: '3.5'

services:
  rack:
    image: 18xx_rack:dev
    environment:
      DATABASE_URL: postgres://root:password@db:5432/18xx_development
      RACK_ENV: development
    ports:
      - 9292:9292
    volumes:
      - .:/18xx
      - /18xx/vendor

  queue:
    image: 18xx_queue:dev
    command: bundle exec ruby queue.rb # bundle exec rerun --background -i 'build/*' -i 'public/*' 'ruby queue.rb'
    environment:
      DATABASE_URL: postgres://root:password@db:5432/18xx_development
      RACK_ENV: development
    volumes:
      - .:/18xx
      - /18xx/vendor

  db:
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: 18xx_development
