# frozen_string_literal: true

module Engine
  module Game
    module G1888
      module Entities
        # rubocop:disable Layout/LineLength
        COMPANIES = [
          {
            name: 'Kaiping Tramway',
            value: 25,
            revenue: 5,
            desc: 'No special ability',
            sym: 'KT',
          },
          {
            name: 'Terracotta Army',
            value: 50,
            revenue: 10,
            desc: 'Comes with the red Xi’an tile which shows higher value for this off-board location. A company owning this private may lay this tile in addition to it’s normal tile lay step. No connection is required. This does not close the company. If it wasn’t laid when the company closes the red tile is out of the game.',
            sym: 'TA',
            abilities: [{
              type: 'tile_lay',
              when: 'owning_corp_or_turn',
              owner_type: 'corporation',
              free: true,
              special: true,
              hexes: ['H2'],
              tiles: ['L39'],
              count: 1,
            }],
            color: nil,
          },
          {
            name: 'Heng Shan',
            value: 75,
            revenue: 15,
            desc: 'Comes with the yellow mountain tile.  A company owning this private may lay the mine on hex C5 in addition to it’s normal tile laying step. No connection is required. If it wasn’t laid when the company closes the mountain tile is out of the game. If a train runs to or through the mine the company treasury gets ¥40 from the bank. It counts against the range of a train.  Any company may lay a normal tile on hex C5 after this private company was sold to a company or closed at the cost of ¥40. Then the yellow mountain tile can’t be placed.',
            sym: 'HS',
            abilities: [{ type: 'blocks_hexes', owner_type: 'player', hexes: ['C5'] },
                        {
                          type: 'tile_lay',
                          when: 'owning_corp_or_turn',
                          owner_type: 'corporation',
                          free: true,
                          hexes: ['C5'],
                          tiles: ['L41'],
                          count: 1,
                        }],
            color: nil,
          },
          {
            name: 'Great Wall of China',
            value: 100,
            revenue: 20,
            desc: 'A company owning this private may lay one or two yellow tiles for free onto hexes with the Great Wall in addition to the normal tile lay step. No connection is required. This does not close the company. If laying two tiles, both tiles must be laid during the same turn and must be connected.',
            sym: 'CW',
            abilities: [{
              type: 'tile_lay',
              when: 'owning_corp_or_turn',
              owner_type: 'corporation',
              free: true,
              must_lay_together: true,
              special: false,
              hexes: %w[B4 B6 B8 B10 B16 C3 C7 C11 C13 C15 D2 D4 D6 E3 F4],
              tiles: %w[1 2 3 4 5 6 7 8 9 55 56 57 58 69],
              count: 2,
            }],
          },
          {
            name: 'Yanda Railway Ferry',
            value: 125,
            revenue: 25,
            desc: 'Comes with the blue ferry tiles. A company owning this private may lay these tiles in addition to it’s normal tile laying step on both of the Dalian and Yantai hexes. No connection is required. If they are not laid when the company closes the ferry tiles are out of the game.',
            sym: 'YRF',
            abilities: [{
              type: 'tile_lay',
              when: 'owning_corp_or_turn',
              owner_type: 'corporation',
              tiles: %w[L40a L40b],
              hexes: %w[E17 F16],
              special: true,
              blocks: true,
              connect: false,
              must_lay_together: true,
              must_lay_all: true,
              count: 2,
            }],
            color: nil,
          },
          {
            name: 'Forbidden City',
            value: 150,
            revenue: 30,
            desc: 'A player owning this private company may exchange it into an IPO share of a company with a token in Beijing (at the time of exchange). If sold to a company this ability is lost.',
            sym: 'FC',
            abilities: [{
              type: 'exchange',
              owner_type: 'player',
              corporations: 'any',
              from: 'ipo',
            }],
            color: nil,
          },
        ].freeze
        # rubocop:enable Layout/LineLength

        CORPORATIONS = [
          {
            float_percent: 60,
            sym: 'JHR',
            name: 'Jingha Railway',
            logo: '1888/JHR',
            simple_logo: '1888/JHR.alt',
            tokens: [0, 40, 60],
            coordinates: 'C9',
            city: 1,
            color: '#C93A1E',
            text_color: 'white',
            reservation_color: nil,
          },
          {
            float_percent: 60,
            sym: 'SSL',
            name: 'Shenshan Line',
            logo: '1888/SSL',
            simple_logo: '1888/SSL.alt',
            tokens: [0, 40, 60],
            coordinates: 'B18',
            city: 0,
            color: '#A7A6A6',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            float_percent: 60,
            sym: 'CDL',
            name: 'Changda Line',
            logo: '1888/CDL',
            simple_logo: '1888/CDL.alt',
            tokens: [0, 40, 60, 80],
            coordinates: 'A19',
            color: '#44BC4F',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            float_percent: 60,
            sym: 'HJR',
            name: 'Hanji Ralwway',
            logo: '1888/HJR',
            simple_logo: '1888/HJR.alt',
            tokens: [0, 40, 60, 80],
            coordinates: 'F6',
            color: '#CBA375',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            float_percent: 60,
            sym: 'TJL',
            name: 'Taijiao Line',
            logo: '1888/TJL',
            simple_logo: '1888/TJL.alt',
            tokens: [0, 40, 60, 80],
            coordinates: 'E3',
            color: '#231F20',
            text_color: 'white',
            reservation_color: nil,
          },
          {
            float_percent: 60,
            sym: 'LYR',
            name: 'Lanyan Railway',
            logo: '1888/LYR',
            simple_logo: '1888/LYR.alt',
            tokens: [0, 40, 60],
            coordinates: 'F16',
            color: '#FCC707',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            float_percent: 60,
            sym: 'JZR',
            name: 'Jingzhan Railway',
            logo: '1888/JZR',
            simple_logo: '1888/JZR.alt',
            tokens: [0, 40, 60],
            coordinates: 'C9',
            city: 0,
            color: '#9D65B9',
            text_color: 'white',
            reservation_color: nil,
          },
          {
            float_percent: 60,
            sym: 'ZDR',
            name: 'Zidong Railway',
            logo: '1888/ZDR',
            simple_logo: '1888/ZDR.alt',
            tokens: [0, 40, 60],
            coordinates: 'G11',
            color: '#00ACD0',
            text_color: 'white',
            reservation_color: nil,
          },
        ].freeze
      end
    end
  end
end
