# frozen_string_literal: true

module Engine
  module Game
    module G1847AE
      module Map
        # TEMPORARY, TAKEN FROM 1894
        TILES = {
          '1' => 1,
          '3' => 2,
          '4' => 2,
          '5' => 4,
          '6' => 4,
          '7' => 5,
          '8' => 7,
          '9' => 7,
          '12' => 3,
          '13' => 3,
          '14' => 3,
          '15' => 3,
          '16' => 1,
          '18' => 1,
          '19' => 1,
          '20' => 1,
          '23' => 2,
          '24' => 2,
          '25' => 1,
          '26' => 2,
          '27' => 2,
          '28' => 1,
          '29' => 1,
          '39' => 1,
          '40' => 1,
          '41' => 1,
          '42' => 1,
          '43' => 1,
          '44' => 1,
          '45' => 1,
          '46' => 1,
          '47' => 1,
          '55' => 2,
          '56' => 2,
          '57' => 2,
          '58' => 5,
          '63' => 4,
          '69' => 2,
          '70' => 1,
          '87' => 5,
          '88' => 4,
          '201' => 2,
          '202' => 2,
          '203' => 2,
          '204' => 4,
          '205' => 3,
          '206' => 3,
          '207' => 4,
          '208' => 4,
          '216' => 4,
        }.freeze

        LOCATION_NAMES = {
          'B2' => 'Rheinland',
          'B14' => 'Köln',
          'B18' => 'Mainz',
          'B22' => 'Frankfurt',
          'C1' => 'Luxemburg',
          'C3' => 'Trier',
          'C9' => 'Birkenfeld',
          'C13' => 'Bad Kreuznach',
          'C21' => 'Darmstadt',
          'D18' => 'Worms',
          'F12' => 'Kaiserslautern',
          'F16' => 'Bad Dürkheim',
          'F18' => 'Ludwigshafen',
          'F20' => 'Mannheim',
          'G7' => 'Neunkirchen',
          'G9' => 'Homburg',
          'G15' => 'Neunstadt',
          'G19' => 'Speyer',
          'G21' => 'Stuttgart/München',
          'H2' => 'Thionville',
          'H4' => 'Völklingen',
          'H10' => 'Zweibrücken',
          'H16' => 'Landau',
          'I3' => 'Paris',
          'I11' => 'Pirmasens',
          'I13' => 'Strassburg',
          'I21' => 'Karlsruhe',
        }.freeze

        HEXES = {
          white: {
            %w[F6 G5] => 'icon=image:1847_ae/pink',
            %w[B16 C15 E21] => 'icon=image:1847_ae/green',
            %w[H12 H14 H18 H20 I9 I17] => 'icon=image:1847_ae/blue',
            %w[G9 H10 H16] => 'city=revenue:0;icon=image:1847_ae/blue',
            %w[G17 H8] => 'town=revenue:0;icon=image:1847_ae/blue',
            %w[F10 F14] => 'town=revenue:0;town=revenue:0;upgrade=cost:40,terrain:mountain;icon=image:1847_ae/blue',
            %w[B4 F4] => 'upgrade=cost:40,terrain:mountain;icon=image:1847_ae/pink',
            %w[C5 D4 D8 E3 E7] => 'upgrade=cost:70,terrain:mountain;icon=image:1847_ae/pink',
            %w[D10 D12 E11 E15 G11 G13] => 'upgrade=cost:70,terrain:mountain;icon=image:1847_ae/blue',
            %w[C3 H4] => 'city=revenue:0;upgrade=cost:50,terrain:water;icon=image:1847_ae/pink',
            ['B18'] => 'city=revenue:0;upgrade=cost:40,terrain:water;label=Y;icon=image:1847_ae/green',
            ['B20'] => 'town=revenue:0;upgrade=cost:40,terrain:water;icon=image:1847_ae/green',
            ['C13'] => 'city=revenue:0;icon=image:1847_ae/pink',
            ['C17'] => 'border=edge:4,type:impassable;icon=image:1847_ae/green',
            ['C19'] => 'border=edge:0,type:impassable;border=edge:1,type:impassable;icon=image:1847_ae/green',
            ['C21'] => 'city=revenue:0;icon=image:1847_ae/green',
            ['D14'] => 'upgrade=cost:70,terrain:mountain;icon=image:1847_ae/blue;icon=image:1847_ae/green',
            ['D16'] => 'town=revenue:0;icon=image:1847_ae/green',
            ['D20'] => 'town=revenue:0;town=revenue:0;upgrade=cost:40,terrain:mountain;icon=image:1847_ae/green',
            ['E5'] => 'town=revenue:0;upgrade=cost:40,terrain:mountain;icon=image:1847_ae/pink',
            ['E9'] => 'town=revenue:0;upgrade=cost:40,terrain:mountain;frame=color:green',
            ['E17'] => 'town=revenue:0;town=revenue:0;icon=image:1847_ae/blue;icon=image:1847_ae/green',
            ['F8'] => 'icon=image:1847_ae/pink;icon=image:1847_ae/blue',
            ['G7'] => 'city=revenue:0;icon=image:1847_ae/mine,sticky:1;icon=image:1847_ae/pink',
            ['G3'] => 'town=revenue:0;town=revenue:0;upgrade=cost:50,terrain:water;icon=image:1847_ae/pink',
            ['G19'] => 'city=revenue:0;upgrade=cost:80,terrain:water;border=edge:3,type:impassable;icon=image:1847_ae/blue',
            ['H6'] => 'city=revenue:0;label=Y;icon=image:1847_ae/mine,sticky:1;icon=image:1847_ae/pink',
            ['I5'] => 'upgrade=cost:50,terrain:water;icon=image:1847_ae/pink',
            ['I7'] => 'town=revenue:0;icon=image:1847_ae/pink;icon=image:1847_ae/blue',
            ['I15'] => 'upgrade=cost:40,terrain:mountain;icon=image:1847_ae/blue',
            ['I19'] => 'town=revenue:0;upgrade=cost:80,terrain:water;icon=image:1847_ae/blue',
          },
          yellow: {
            ['C7'] => 'path=a:0,b:4;upgrade=cost:40,terrain:mountain',
            ['C11'] => 'path=a:1,b:4',
            ['D6'] => 'path=a:0,b:3;upgrade=cost:40,terrain:mountain',
            ['D18'] => 'city=revenue:20;path=a:2,b:_0;upgrade=cost:40,terrain:water;border=edge:3,type:impassable',
            ['F12'] => 'city=revenue:30;path=a:1,b:_0;path=a:4,b:_0;label=Y',
            ['F18'] => 'city=revenue:30;path=a:0,b:_0;path=a:5,b:_0;upgrade=cost:40,terrain:water;label=Y',
            ['F20'] => 'city=revenue:30;path=a:2,b:_0;upgrade=cost:40,terrain:water;label=Y;border=edge:0,type:impassable',
            ['I11'] => 'city=revenue:20;path=a:2,b:_0;path=a:3,b:_0',
          },
          gray: {
            %w[J6 J18] => 'path=a:2,b:3',
            ['C9'] => 'city=revenue:20,loc:2.5;town=revenue:10;path=a:1,b:_0;path=a:4,b:_0;path=a:1,b:_1;path=a:4,b:_1',
            ['A17'] => 'path=a:5,b:0',
            ['D2'] => 'path=a:3,b:5',
            ['D22'] => 'path=a:0,b:2',
            ['E13'] => 'path=a:0,b:3;path=a:3,b:5',
            ['E19'] => 'town=revenue:10;path=a:0,b:_0;path=a:2,b:_0;path=a:3,b:5',
            ['F2'] => 'town=revenue:10;path=a:3,b:_0;path=a:5,b:_0',
            ['F16'] => 'city=revenue:20,loc:1.5;town=revenue:10;path=a:0,b:_0;path=a:3,b:_0;path=a:0,b:_1;path=a:3,b:_1',
            ['F22'] => 'path=a:1,b:2',
            ['G15'] => 'city=revenue:30,slots:3;path=a:2,b:_0;path=a:3,b:_0;path=a:4,b:_0;path=a:5,b:_0',
          },
          red: {
            ['B2'] => 'offboard=revenue:yellow_30|green_40|brown_50;path=a:4,b:_0;path=a:5,b:_0;label=A',
            ['B14'] => 'offboard=revenue:yellow_30|green_40|brown_50;path=a:0,b:_0;path=a:4,b:_0;label=A',
            ['B22'] => 'offboard=revenue:yellow_20|green_40|brown_50;path=a:1,b:_0;label=A',
            ['C1'] => 'offboard=revenue:yellow_30|green_20|brown_10;path=a:4,b:_0',
            ['G21'] => 'offboard=revenue:yellow_10|green_20|brown_50;path=a:1,b:_0;path=a:2,b:_0;label=Z',
            ['H2'] => 'offboard=revenue:yellow_10|green_30|brown_40;path=a:3,b:_0',
            ['I3'] => 'offboard=revenue:yellow_20|green_40|brown_50;path=a:4,b:_0;label=B',
            ['I13'] => 'offboard=revenue:yellow_30|green_40|brown_50;path=a:4,b:_0;label=B',
            ['I21'] => 'offboard=revenue:yellow_0|green_30|brown_40;path=a:1,b:_0;label=Z',
          },
        }.freeze
      end
    end
  end
end
