# frozen_string_literal: true

module Engine
  module Game
    module G18West
      module Entities
        COMPANIES = [].freeze

        CORPORATIONS = [
          {
            float_percent: 60,
            sym: 'UP',
            name: 'Union Pacific Railroad',
            type: 'major',
            logo: '18_tokaido/TYR',
            simple_logo: '18_tokaido/TYR.alt',
            tokens: [0, 0, 0, 100, 100, 100],
            coordinates: 'F21',
            color: '#efe73f',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            float_percent: 60,
            sym: 'GN',
            name: 'Great Northern Railway',
            type: 'major',
            logo: '18_tokaido/TYR',
            simple_logo: '18_tokaido/TYR.alt',
            tokens: [0, 0, 100, 100, 100, 100],
            coordinates: 'D23',
            city: 0,
            color: '#bfd7ff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            float_percent: 60,
            sym: 'DRG',
            name: 'Denver & Rio Grande Railroad',
            type: 'major',
            logo: '18_tokaido/TYR',
            simple_logo: '18_tokaido/TYR.alt',
            tokens: [0, 100, 100, 100, 100],
            coordinates: 'G14',
            color: '#af6f2f',
            text_color: 'white',
            reservation_color: nil,
          },
          {
            float_percent: 60,
            sym: 'TP',
            name: 'Texas Pacific Railroad',
            type: 'major',
            logo: '18_tokaido/TYR',
            simple_logo: '18_tokaido/TYR.alt',
            tokens: [0, 0, 100, 100, 100],
            coordinates: 'K20',
            color: '#8f3f8f',
            text_color: 'white',
            reservation_color: nil,
          },
          {
            float_percent: 60,
            sym: 'SP',
            name: 'Southern Pacific Railroad',
            type: 'major',
            logo: '18_tokaido/TYR',
            simple_logo: '18_tokaido/TYR.alt',
            tokens: [0, 0, 100, 100, 100],
            coordinates: 'G2',
            city: 1,
            color: '#ffaf2f',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            float_percent: 60,
            sym: 'NP',
            name: 'Northern Pacific Railroad',
            type: 'major',
            logo: '18_tokaido/TYR',
            simple_logo: '18_tokaido/TYR.alt',
            tokens: [0, 0, 100, 100, 100],
            coordinates: 'A4',
            color: '#000',
            text_color: 'white',
            reservation_color: nil,
          },
          {
            float_percent: 60,
            sym: 'KP',
            name: 'Kansas Pacific Railroad',
            type: 'major',
            logo: '18_tokaido/TYR',
            simple_logo: '18_tokaido/TYR.alt',
            tokens: [0, 0, 100, 100, 100],
            coordinates: 'G22',
            city: 1,
            color: '#9f9fcf',
            text_color: 'white',
            reservation_color: nil,
          },
          {
            float_percent: 60,
            sym: 'ATSF',
            name: 'Atchison, Topeka & Santa Fe',
            type: 'major',
            logo: '18_tokaido/TYR',
            simple_logo: '18_tokaido/TYR.alt',
            tokens: [0, 0, 100, 100, 100],
            coordinates: 'G22',
            city: 0,
            color: '#007fbf',
            text_color: 'white',
            reservation_color: nil,
          },
          {
            float_percent: 60,
            sym: 'MKT',
            name: 'Missouri-Kansas-Texas RR',
            type: 'minor',
            logo: '18_tokaido/TYR',
            simple_logo: '18_tokaido/TYR.alt',
            tokens: [0],
            coordinates: 'L21',
            color: '#009f00',
            text_color: 'white',
            reservation_color: nil,
          },
          {
            float_percent: 60,
            sym: 'CBQ',
            name: 'Chicago, Burlington & Quincy',
            type: 'minor',
            logo: '18_tokaido/TYR',
            simple_logo: '18_tokaido/TYR.alt',
            tokens: [0],
            coordinates: 'F27',
            city: 0,
            color: '#9f9f9f',
            text_color: 'white',
            reservation_color: nil,
          },
          {
            float_percent: 60,
            sym: 'MP',
            name: 'Missouri Pacific',
            type: 'minor',
            logo: '18_tokaido/TYR',
            simple_logo: '18_tokaido/TYR.alt',
            tokens: [0],
            coordinates: 'H25',
            city: 0,
            color: '#3f009f',
            text_color: 'white',
            reservation_color: nil,
          },
          {
            float_percent: 60,
            sym: 'MR',
            name: 'Milwaukee Road',
            type: 'minor',
            logo: '18_tokaido/TYR',
            simple_logo: '18_tokaido/TYR.alt',
            tokens: [0],
            coordinates: 'E26',
            color: '#ef7f00',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            float_percent: 60,
            sym: 'SLS',
            name: 'St. Louis - Southwestern RR',
            type: 'minor',
            logo: '18_tokaido/TYR',
            simple_logo: '18_tokaido/TYR.alt',
            tokens: [0],
            coordinates: 'I26',
            color: '#af7faf',
            text_color: 'white',
            reservation_color: nil,
          },
          {
            float_percent: 60,
            sym: 'RI',
            name: 'Chicago, Rock Island & Pacific',
            type: 'minor',
            logo: '18_tokaido/TYR',
            simple_logo: '18_tokaido/TYR.alt',
            tokens: [0],
            coordinates: 'F25',
            color: '#9f4f0f',
            text_color: 'white',
            reservation_color: nil,
          },
          {
            float_percent: 60,
            sym: 'SLSF',
            name: 'St. Louis - San Francisco',
            type: 'minor',
            logo: '18_tokaido/TYR',
            simple_logo: '18_tokaido/TYR.alt',
            tokens: [0],
            coordinates: 'H25',
            city: 1,
            color: '#ef3f3f',
            text_color: 'white',
            reservation_color: nil,
          },
          {
            float_percent: 60,
            sym: 'CNW',
            name: 'Chicago North Western RR',
            type: 'minor',
            logo: '18_tokaido/TYR',
            simple_logo: '18_tokaido/TYR.alt',
            tokens: [0],
            coordinates: 'F27',
            city: 1,
            color: '#bfbf00',
            text_color: 'black',
            reservation_color: nil,
          },
        ].freeze
      end
    end
  end
end
