# frozen_string_literal: true

module Engine
  module Game
    module G18EU
      module Entities
        CORPORATIONS = [
          {
            float_percent: 50,
            always_market_price: true,
            sym: 'BNR',
            name: 'Belgian National Railways',
            logo: '18_eu/BNR',
            simple_logo: '18_eu/BNR.alt',
            tokens: [0, 0, 0, 0, 0],
            color: '#ffcb05',
            text_color: 'black',
          },
          {
            float_percent: 50,
            always_market_price: true,
            sym: 'DR',
            name: 'Dutch Railways',
            logo: '18_eu/DR',
            simple_logo: '18_eu/DR.alt',
            tokens: [0, 0, 0, 0, 0],
            color: '#fff200',
            text_color: 'black',
          },
          {
            float_percent: 50,
            always_market_price: true,
            sym: 'FS',
            name: 'Italian State Railways',
            logo: '18_eu/FS',
            simple_logo: '18_eu/FS.alt',
            tokens: [0, 0, 0, 0, 0],
            color: '#00a651',
          },
          {
            float_percent: 50,
            always_market_price: true,
            sym: 'RBSR',
            name: 'Royal Bavarian State Railroad',
            logo: '18_eu/RBSR',
            simple_logo: '18_eu/RBSR.alt',
            tokens: [0, 0, 0, 0, 0],
            color: '#8ed8f8',
            text_color: 'black',
          },
          {
            float_percent: 50,
            always_market_price: true,
            sym: 'RPR',
            name: 'Royal Prussian Railway',
            logo: '18_eu/RPR',
            simple_logo: '18_eu/RPR.alt',
            tokens: [0, 0, 0, 0, 0],
            color: '#00a4e4',
          },
          {
            float_percent: 50,
            always_market_price: true,
            sym: 'AIRS',
            name: 'Austrian Imperial Royal State',
            logo: '18_eu/AIRS',
            simple_logo: '18_eu/AIRS.alt',
            tokens: [0, 0, 0, 0, 0],
            color: '#fffcd5',
            text_color: 'black',
          },
          {
            float_percent: 50,
            always_market_price: true,
            sym: 'SNCF',
            name: 'SNCF',
            logo: '18_eu/SNCF',
            simple_logo: '18_eu/SNCF.alt',
            tokens: [0, 0, 0, 0, 0],
            color: '#ed1c24',
          },
          {
            float_percent: 50,
            always_market_price: true,
            sym: 'GSR',
            name: 'German State Railways',
            logo: '18_eu/GSR',
            simple_logo: '18_eu/GSR.alt',
            tokens: [0, 0, 0, 0, 0],
            color: '#231f20',
          },
        ].freeze

        MINORS = [
          {
            sym: '1',
            name: 'Chemin de Fer du Nord',
            coordinates: 'A10',
            city: 0,
            logo: '18_eu/1',
            simple_logo: '18_eu/1.alt',
            tokens: [0],
            color: 'black',
            text_color: 'white',
            abilities: [
            {
              type: 'exchange',
              corporations: %w[BNR DR FS RBSR RPR AIRS SNCF GSR],
              owner_type: 'player',
              from: %w[ipo market],
            },
          ],
          },
          {
            sym: '2',
            name: 'État Belge',
            coordinates: 'C8',
            logo: '18_eu/2',
            simple_logo: '18_eu/2.alt',
            tokens: [0],
            color: 'black',
            text_color: 'white',
            abilities: [
              {
                type: 'exchange',
                corporations: %w[BNR DR FS RBSR RPR AIRS SNCF GSR],
                owner_type: 'player',
                from: %w[ipo market],
              },
            ],
          },
          {
            sym: '3',
            name: 'Paris-Lyon-Méditerranée',
            coordinates: 'A10',
            city: 1,
            logo: '18_eu/3',
            simple_logo: '18_eu/3.alt',
            tokens: [0],
            color: 'black',
            text_color: 'white',
            abilities: [
              {
                type: 'exchange',
                corporations: %w[BNR DR FS RBSR RPR AIRS SNCF GSR],
                owner_type: 'player',
                from: %w[ipo market],
              },
            ],
          },
          {
            sym: '4',
            name: 'Leipzig-Dresdner-Bahn',
            coordinates: 'J7',
            city: 0,
            logo: '18_eu/4',
            simple_logo: '18_eu/4.alt',
            tokens: [0],
            color: 'black',
            text_color: 'white',
            abilities: [
              {
                type: 'exchange',
                corporations: %w[BNR DR FS RBSR RPR AIRS SNCF GSR],
                owner_type: 'player',
                from: %w[ipo market],
              },
            ],
          },
          {
            sym: '5',
            name: 'Ferrovia Adriatica',
            coordinates: 'H19',
            city: 0,
            logo: '18_eu/5',
            simple_logo: '18_eu/5.alt',
            tokens: [0],
            color: 'black',
            text_color: 'white',
            abilities: [
              {
                type: 'exchange',
                corporations: %w[BNR DR FS RBSR RPR AIRS SNCF GSR],
                owner_type: 'player',
                from: %w[ipo market],
              },
            ],
          },
          {
            sym: '6',
            name: 'Kaiser-Ferdinand-Nordbahn',
            coordinates: 'K14',
            city: 1,
            logo: '18_eu/6',
            simple_logo: '18_eu/6.alt',
            tokens: [0],
            color: 'black',
            text_color: 'white',
            abilities: [
              {
                type: 'exchange',
                corporations: %w[BNR DR FS RBSR RPR AIRS SNCF GSR],
                owner_type: 'player',
                from: %w[ipo market],
              },
            ],
          },
          {
            sym: '7',
            name: 'Berlin-Potsdamer-Bahn',
            coordinates: 'J5',
            city: 1,
            logo: '18_eu/7',
            simple_logo: '18_eu/7.alt',
            tokens: [0],
            color: 'black',
            text_color: 'white',
            abilities: [
              {
                type: 'exchange',
                corporations: %w[BNR DR FS RBSR RPR AIRS SNCF GSR],
                owner_type: 'player',
                from: %w[ipo market],
              },
            ],
          },
          {
            sym: '8',
            name: 'Ungarische Staatsbahn',
            coordinates: 'M16',
            city: 0,
            logo: '18_eu/8',
            simple_logo: '18_eu/8.alt',
            tokens: [0],
            color: 'black',
            text_color: 'white',
            abilities: [
              {
                type: 'exchange',
                corporations: %w[BNR DR FS RBSR RPR AIRS SNCF GSR],
                owner_type: 'player',
                from: %w[ipo market],
              },
            ],
          },
          {
            sym: '9',
            name: 'Berlin-Stettiner-Bahn',
            coordinates: 'J5',
            city: 0,
            logo: '18_eu/9',
            simple_logo: '18_eu/9.alt',
            tokens: [0],
            color: 'black',
            text_color: 'white',
            abilities: [
              {
                type: 'exchange',
                corporations: %w[BNR DR FS RBSR RPR AIRS SNCF GSR],
                owner_type: 'player',
                from: %w[ipo market],
              },
            ],
          },
          {
            sym: '10',
            name: 'Strade Ferrate Alta Italia',
            coordinates: 'E18',
            city: 0,
            logo: '18_eu/10',
            simple_logo: '18_eu/10.alt',
            tokens: [0],
            color: 'black',
            text_color: 'white',
            abilities: [
              {
                type: 'exchange',
                corporations: %w[BNR DR FS RBSR RPR AIRS SNCF GSR],
                owner_type: 'player',
                from: %w[ipo market],
              },
            ],
          },
          {
            sym: '11',
            name: 'Südbahn',
            coordinates: 'K14',
            city: 0,
            logo: '18_eu/11',
            simple_logo: '18_eu/11.alt',
            tokens: [0],
            color: 'black',
            text_color: 'white',
            abilities: [
              {
                type: 'exchange',
                corporations: %w[BNR DR FS RBSR RPR AIRS SNCF GSR],
                owner_type: 'player',
                from: %w[ipo market],
              },
            ],
          },
          {
            sym: '12',
            name: 'Hollandsche Maatschappij',
            coordinates: 'D3',
            city: 0,
            logo: '18_eu/12',
            simple_logo: '18_eu/12.alt',
            tokens: [0],
            color: 'black',
            text_color: 'white',
            abilities: [
              {
                type: 'exchange',
                corporations: %w[BNR DR FS RBSR RPR AIRS SNCF GSR],
                owner_type: 'player',
                from: %w[ipo market],
              },
            ],
          },
          {
            sym: '13',
            name: 'Ludwigsbahn',
            coordinates: 'G12',
            city: 0,
            logo: '18_eu/13',
            simple_logo: '18_eu/13.alt',
            tokens: [0],
            color: 'black',
            text_color: 'white',
            abilities: [
              {
                type: 'exchange',
                corporations: %w[BNR DR FS RBSR RPR AIRS SNCF GSR],
                owner_type: 'player',
                from: %w[ipo market],
              },
            ],
          },
          {
            sym: '14',
            name: 'Ligne Strasbourg-Bâle',
            coordinates: 'D13',
            city: 0,
            logo: '18_eu/14',
            simple_logo: '18_eu/14.alt',
            tokens: [0],
            color: 'black',
            text_color: 'white',
            abilities: [
              {
                type: 'exchange',
                corporations: %w[BNR DR FS RBSR RPR AIRS SNCF GSR],
                owner_type: 'player',
                from: %w[ipo market],
              },
            ],
          },
          {
            sym: '15',
            name: 'Grand Central',
            coordinates: 'B17',
            city: 0,
            logo: '18_eu/15',
            simple_logo: '18_eu/15.alt',
            tokens: [0],
            color: 'black',
            text_color: 'white',
            abilities: [
              {
                type: 'exchange',
                corporations: %w[BNR DR FS RBSR RPR AIRS SNCF GSR],
                owner_type: 'player',
                from: %w[ipo market],
              },
            ],
          },
        ].freeze
      end
    end
  end
end
