# frozen_string_literal: true

module Engine
  module Game
    module G1822CA
      module Entities
        COMPANIES = [
          {
            name: 'P1-MLW (5-Train)',
            sym: 'P1',
            value: 0,
            revenue: 5,
            desc: 'MAJOR, Phase 5. 5-Train. This is a normal 5-train that is subject to all of the normal rules. '\
                  'Note that a company can acquire this private company at the start of its turn, even if it is '\
                  'already at its train limit as this counts as an acquisition action, not a train buying action. '\
                  'However, once acquired the acquiring company needs to check whether it is at train limit and '\
                  'discard any trains held in excess of limit.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P2-RS&C (Perm. L Train)',
            sym: 'P2',
            value: 0,
            revenue: 0,
            desc: 'MAJOR/MINOR, Phase 1. Permanent L-Train. An L-train cannot be sold to another company. It does '\
                  'not count as a train for the purposes of mandatory train ownership. It does not count against '\
                  'train ownership limit. A company cannot own both a permanent L-train and a permanent 2-train. '\
                  'Dividends can be separated from other trains and may be split, paid in full, or retained. If a '\
                  'company runs a permanent L-train and pays a dividend (split or full), but retains its dividend '\
                  'from other train operations this still counts as a normal dividend for stock price movement '\
                  'purposes. Vice-versa, if a company pays a dividend (split or full) with its other trains, but '\
                  'retains the dividend from the permanent L, this also still counts as a normal dividend for stock '\
                  'price movement purposes. Does not close.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P3-TLW (Permanent 2T)',
            sym: 'P3',
            value: 0,
            revenue: 0,
            desc: 'MAJOR, Phase 2. Permanent 2-Train. 2P-train is a permanent 2-train. It can’t be sold to another '\
                  'company. It does not count against train limit. It does not count as a train for the purpose of '\
                  'mandatory train ownership and purchase. A company may not own more than one 2P train. '\
                  'A company cannot own both a permanent L-train and a permanent 2-train. Dividends '\
                  'can be separated from other trains and may be split, paid in full, or retained. If a company '\
                  'runs a 2P-train and pays a dividend (split or full), but retains its dividend from other train '\
                  'operations this still counts as a normal dividend for stock price movement purposes. Vice-versa, '\
                  'if a company pays a dividend (split or full) with its other trains, but retains the dividend '\
                  'from the 2P, this also still counts as a normal dividend for stock price movement purposes. Does '\
                  'not close.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P4-CoD (Permanent 2T)',
            sym: 'P4',
            value: 0,
            revenue: 0,
            desc: 'MAJOR, Phase 2. Permanent 2-Train. 2P-train is a permanent 2-train. It can’t be sold to another '\
                  'company. It does not count against train limit. It does not count as a train for the purpose of '\
                  'mandatory train ownership and purchase. A company may not own more than one 2P train. '\
                  'A company cannot own both a permanent L-train and a permanent 2-train. Dividends '\
                  'can be separated from other trains and may be split, paid in full, or retained. If a company '\
                  'runs a 2P-train and pays a dividend (split or full), but retains its dividend from other train '\
                  'operations this still counts as a normal dividend for stock price movement purposes. Vice-versa, '\
                  'if a company pays a dividend (split or full) with its other trains, but retains the dividend '\
                  'from the 2P, this also still counts as a normal dividend for stock price movement purposes. '\
                  'Does not close.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P5-PCCo (Pullman)',
            sym: 'P5',
            value: 0,
            revenue: 10,
            desc: 'MAJOR, Phase 5. Pullman. A “Pullman” carriage train that can be added to another train '\
                  'owned by the company. It converts the train into a + train. Does not count against train limit '\
                  'and does not count as a train for the purposes of train ownership. Can’t be sold to another '\
                  'company. Does not close. May include a maximum of [2 × the train size] number of towns.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P6-FCW (Pullman)',
            sym: 'P6',
            value: 0,
            revenue: 10,
            desc: 'MAJOR, Phase 5. Pullman. A “Pullman” carriage train that can be added to another train '\
                  'owned by the company. It converts the train into a + train. Does not count against train limit '\
                  'and does not count as a train for the purposes of train ownership. Can’t be sold to another '\
                  'company. Does not close. May include a maximum of [2 × the train size] number of towns.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P7-TSE (Double Cash)',
            sym: 'P7',
            value: 0,
            revenue: 10,
            desc: 'MAJOR, Phase 3. Declare 2x Cash Holding. If held by a player, the holding player may '\
                  'declare double their actual cash holding at the end of a stock round to determine player turn '\
                  'order in the next stock round. If held by a company it pays revenue of '\
                  '$20 (green)/$40 (brown)/$60 (grey). Does not close.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P8-HR ($10x Phase)',
            sym: 'P8',
            value: 0,
            revenue: 0,
            desc: 'MAJOR/MINOR, Phase 2. $10x Phase. Pays revenue of $10 x phase number to the player, and pays '\
                  'treasury credits of $10 x phase number to the private company. This credit is retained on the '\
                  'private company charter. When acquired, the acquiring company receives this treasury money and '\
                  'this private company closes. If not acquired beforehand, this company closes at the start of '\
                  'Phase 7 and all treasury credits are returned to the bank.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P9-GMA ($5x Phase)',
            sym: 'P9',
            value: 0,
            revenue: 0,
            desc: 'MAJOR/MINOR, Phase 2. $5x Phase. Pays revenue of $5 x phase number to the player, and pays '\
                  'treasury credits of $5 x phase number to the private company. This credit is retained on the '\
                  'private company charter. When acquired, the acquiring company receives this treasury money and '\
                  'this private company closes. If not acquired beforehand, this company closes at the start of '\
                  'Phase 7 and all treasury credits are returned to the bank.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P10-MSWCR (Winnipeg Token)',
            sym: 'P10',
            value: 0,
            revenue: 10,
            desc: 'MAJOR, Phase 3. Winnipeg Station. The owning company may place an exchange station token on the '\
                  'map, free of charge, in a token space in Winnipeg. The company does NOT need to be able to trace '\
                  'a route to the station in Winnipeg. Token must be specifically conjoined to one of the five '\
                  'Station slots. Pays company $10 until used. The company does not need to be able to trace a route '\
                  'to Winnipeg to use this property (i.e. any company can use this power to place a token in the '\
                  'Winnipeg hex).',
            abilities: [],
            color: nil,
          },
          {
            name: 'P11-TSE (RRSP)',
            sym: 'P11',
            value: 0,
            revenue: 0,
            desc: 'CAN NOT BE ACQUIRED. Tax Haven. As a stock round action, under the direction and funded by the '\
                  'owning player, the off-shore Tax Haven may purchase an available share certificate and place it '\
                  'onto P7’s charter. The certificate is not counted for determining directorship of a company. '\
                  'The share held in the tax haven does NOT count against the 60% share limit for purchasing '\
                  'shares. If at 60% (or more) in hand in a company, a player can still purchase an additional '\
                  'share in that company and place it in the tax haven. Similarly, if a player holds 50% of a '\
                  'company, plus has 10% of the same company in the tax haven, they can buy a further 10% share. '\
                  'A company with a share in the off-shore tax haven CAN be “all sold out” at the end of a stock '\
                  'round. Dividends paid to the share are also placed onto the off-shore tax haven charter. At the '\
                  'end of the game, the player receives the share certificate from the off-shore tax haven charter '\
                  'and includes it in their portfolio for determining final worth. The player also receives the '\
                  'cash from dividend income accumulated on the charter. Can’t be acquired. Does not count against '\
                  'the certificate limit.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P12-SirSF (Adv. Tile Lay)',
            sym: 'P12',
            value: 0,
            revenue: 10,
            desc: 'MAJOR/MINOR, Phase 1. Advanced Tile Lay. The owning company may lay one plain or town '\
                  'track upgrade using the next colour of track to be available, before it is actually made '\
                  'available by phase progression. The normal rules for progression of track lay must be followed '\
                  '(i.e. grey upgrades brown upgrades green upgrades yellow) it is not possible to skip a colour '\
                  'using this private. All other normal track laying restrictions apply. This is in place of its '\
                  'normal track lay action. Once acquired, the private company pays its revenue to the owning '\
                  'company until the power is exercised and the company closes. May be used in conjunction with '\
                  'P29 and/or P30 as part of the same tile placement step.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P13-JRB (Sawmill)',
            sym: 'P13',
            value: 0,
            revenue: 10,
            desc: 'MAJOR, Phase 3. Sawmill Bonus. Close this company to place a +$10 (closed) or +$20 (open to '\
                  'all) token in a town or city. Token placement is restricted and may not be placed in a grey '\
                  'pre-printed hex nor any labeled city (A, B, L, M, O, Q, T, W, Y). The placing company does not '\
                  'have to have a route to the city where the token is placed. The token increases the value of the '\
                  'revenue center by the indicated amount when running a train there. If the token is “open” then '\
                  'all companies receive the +20 bonus; if “closed” only the owning company receives the +10 bonus. '\
                  'Destination runs and E-trains both double the value of this token. A company may only include the '\
                  'token bonus to the run of one train per operating round. A town with a sawmill may not be removed '\
                  'by P29 or P30.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P14-SM&HUR (Toronto Upgrade)',
            sym: 'P14',
            value: 0,
            revenue: 10,
            desc: 'MAJOR/MINOR, Phase 1. Free Toronto Upgrades. Owner pays no upgrade fee or terrain costs for the '\
                  'tile placement. This tile placement is in addition to the company’s normal tile placement(s), but '\
                  'happens during the company’s tile laying step. Does not close. Minor may place yellow or green '\
                  'only. The company upgrading the city must be connected to it in order to exercise the private company.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P15-PPJR (Ottawa Upgrade)',
            sym: 'P15',
            value: 0,
            revenue: 10,
            desc: 'MAJOR/MINOR, Phase 1. Free Ottawa Upgrades. Owner pays no upgrade fee or terrain costs for the '\
                  'tile placement. This tile placement is in addition to the company’s normal tile placement(s), but '\
                  'happens during the company’s tile laying step. Does not close. Minor may place yellow or green '\
                  'only. The company upgrading the city must be connected to it in order to exercise the private company.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P16-SER (Montreal Upgrade)',
            sym: 'P16',
            value: 0,
            revenue: 10,
            desc: 'MAJOR/MINOR, Phase 1. Free Montreal Upgrades. Owner pays no upgrade fee or terrain costs for the '\
                  'tile placement. This tile placement is in addition to the company’s normal tile placement(s), but '\
                  'happens during the company’s tile laying step. Does not close. Minor may place yellow or green '\
                  'only. The company upgrading the city must be connected to it in order to exercise the private company.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P17-QRR (Quebec Upgrade)',
            sym: 'P17',
            value: 0,
            revenue: 10,
            desc: 'MAJOR/MINOR, Phase 1. Free Quebec Upgrades. Owner pays no upgrade fee or terrain costs for the '\
                  'tile placement. This tile placement is in addition to the company’s normal tile placement(s), but '\
                  'happens during the company’s tile laying step. Does not close. Minor may place yellow or green '\
                  'only. The company upgrading the city must be connected to it in order to exercise the private company.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P18-W&PAR (Winnipeg Upgrade)',
            sym: 'P18',
            value: 0,
            revenue: 10,
            desc: 'MAJOR/MINOR, Phase 1. Free Winnipeg Upgrades. Owner pays no upgrade fee or terrain costs for the '\
                  'tile placement. This tile placement is in addition to the company’s normal tile placement(s), but '\
                  'happens during the company’s tile laying step. Does not close. Minor may place yellow or green '\
                  'only. The company upgrading the city must be connected to it in order to exercise the private company.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P19-CP (Crowsnest Pass)',
            sym: 'P19',
            value: 0,
            revenue: 10,
            desc: 'MAJOR, Phase 3. Crowsnest Pass Tile. Allows the owning company to place a tile into the Crowsnest '\
                  'Pass (CP) and ignore the terrain fee. This tile placement counts as the company’s full track '\
                  'laying step. Closed when used. The CP hex is not reserved; any company may pay to lay a tile '\
                  'there irrespective of the ownership of P19.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P20-CP (Yellowhead Pass)',
            sym: 'P20',
            value: 0,
            revenue: 10,
            desc: 'MAJOR, Phase 3. Yellowhead Pass Tile. Allows the owning company to place a tile into the Yellowhead '\
                  'Pass (YP) and ignore the terrain fee. This tile placement counts as the company’s full track '\
                  'laying step. Closed when used. The YP hex is not reserved; any company may pay to lay a tile '\
                  'there irrespective of the ownership of P20.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P21-NatDrm (National Dream)',
            sym: 'P21',
            value: 0,
            revenue: 10,
            desc: 'MAJOR, Phase 3. 3-Tile Grant. The owning company may close this company to place three yellow '\
                  'tiles in addition to its normal track lay. The owning company’s normal track lay and each of '\
                  'the three extra yellow tile lays may be done in any order. These lays are exempt from terrain '\
                  'fees, but may not be used to build on hexes with mountainous terrain ($120) or in Montreal, '\
                  'Ottawa, Quebec, Toronto or Winnipeg.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P22-NM (National Mail Contract)',
            sym: 'P22',
            value: 0,
            revenue: 10,
            desc: 'MAJOR, Phase 3. Large mail Contract. After running trains, the owning company receives income into '\
                  'its treasury equal to one half of the base value of the start and end stations from one of the '\
                  'trains operated. Doubled values (for E trains or destination tokens) do not count. The company '\
                  'is not required to maximise the dividend from its run if it wishes to maximise its revenue from '\
                  'the mail contract by stopping at a large city and not running beyond it to include towns. A company '\
                  'may own multiple Large Mail Contracts, but may only use one per train. Does not close.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P23-NM (National Mail Contract)',
            sym: 'P23',
            value: 0,
            revenue: 10,
            desc: 'MAJOR, Phase 3. Large mail Contract. After running trains, the owning company receives income into '\
                  'its treasury equal to one half of the base value of the start and end stations from one of the '\
                  'trains operated. Doubled values (for E trains or destination tokens) do not count. The company '\
                  'is not required to maximise the dividend from its run if it wishes to maximise its revenue from '\
                  'the mail contract by stopping at a large city and not running beyond it to include towns. A company '\
                  'may own multiple Large Mail Contracts, but may only use one per train. Does not close.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P24-RM (Regional Mail Contract)',
            sym: 'P24',
            value: 0,
            revenue: 10,
            desc: 'MAJOR, Phase 3. Samll mail Contract. Pay phase-based rate of $10 (yellow)/$20 (green)/$30 (brown)'\
                  '/$40 (grey) to the treasury of the company. The company must operate a train to claim the mail '\
                  'income. Does not close.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P25-RM (Regional Mail Contract)',
            sym: 'P25',
            value: 0,
            revenue: 10,
            desc: 'MAJOR, Phase 3. Samll mail Contract. Pay phase-based rate of $10 (yellow)/$20 (green)/$30 (brown)'\
                  '/$40 (grey) to the treasury of the company. The company must operate a train to claim the mail '\
                  'income. Does not close.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P26-SWP (Grain Train)',
            sym: 'P26',
            value: 0,
            revenue: 10,
            desc: 'MAJOR, Phase 3. Grain Train. A grain train can be added to a train owned by the company. It '\
                  'converts the train into a grain train, which can deliver grain from the grain elevators to a '\
                  'port city. Does not count against the train limit and does not count as a train for the purposes '\
                  'of train ownership. Does not close. Cannot be sold to another company. Adds $10 to company revenue '\
                  'for each grain elevator on the run. Does not count the town revenue. Towns with grain elevators '\
                  'do not count as stops. Runs may extend beyond the start and end city. If the route route run by '\
                  'the grain train includes at least one grain elevator and a port city, the port city adds $20 to '\
                  'the run revenue.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P27-AWP (Grain Train)',
            sym: 'P27',
            value: 0,
            revenue: 10,
            desc: 'MAJOR, Phase 3. Grain Train. A grain train can be added to a train owned by the company. It '\
                  'converts the train into a grain train, which can deliver grain from the grain elevators to a '\
                  'port city. Does not count against the train limit and does not count as a train for the purposes '\
                  'of train ownership. Does not close. Cannot be sold to another company. Adds $10 to company revenue '\
                  'for each grain elevator on the run. Does not count the town revenue. Towns with grain elevators '\
                  'do not count as stops. Runs may extend beyond the start and end city. If the route route run by '\
                  'the grain train includes at least one grain elevator and a port city, the port city adds $20 to '\
                  'the run revenue.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P28-GSR (Station Swap)',
            sym: 'P28',
            value: 0,
            revenue: 10,
            desc: 'MAJOR/MINOR, Phase 3. Station Marker Swap. Allows the owning company to move a token from the exchange '\
                  'token area of its charter to the available token area, or vice versa. This company closes when '\
                  'its power is exercised.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P29-CMH (Remove Town)',
            sym: 'P29',
            value: 0,
            revenue: 10,
            desc: 'MAJOR/MINOR, Phase 1. Remove Single Town. Allows the owning company to place a plain yellow track '\
                  'tile directly on an undeveloped single town hex location or upgrade a single town tile of one '\
                  'colour to a plain track tile of the next colour. This closes the company and counts as the '\
                  'company’s normal track laying step. All other normal track laying restrictions apply. Once '\
                  'acquired, the private company pays its revenue to the owning company until the power is exercised '\
                  'and the company is closed. May be used in conjunction with P12 and/or P30 as part of the same tile '\
                  'placement step. May not be used to remove a town with a sawmill token (P13).',
            abilities: [],
            color: nil,
          },
          {
            name: 'P30-WCvH (Remove Town)',
            sym: 'P30',
            value: 0,
            revenue: 10,
            desc: 'MAJOR/MINOR, Phase 1. Remove Single Town. Allows the owning company to place a plain yellow track '\
                  'tile directly on an undeveloped single town hex location or upgrade a single town tile of one '\
                  'colour to a plain track tile of the next colour. This closes the company and counts as the '\
                  'company’s normal track laying step. All other normal track laying restrictions apply. Once '\
                  'acquired, the private company pays its revenue to the owning company until the power is exercised '\
                  'and the company is closed. May be used in conjunction with P12 and/or P30 as part of the same tile '\
                  'placement step. May not be used to remove a town with a sawmill token (P13).',
            abilities: [],
            color: nil,
          },
          {
            name: 'CONCESSION: CNoR',
            sym: 'C1',
            value: 100,
            revenue: 10,
            desc: 'Has a face value of £100 and contributes £100 to conversion into the CNoR director’s certificate.',
            abilities: [
              {
                type: 'exchange',
                corporations: ['CNoR'],
                owner_type: 'player',
                from: 'par',
              },
            ],
            color: '#9fce63',
            text_color: 'black',
          },
          {
            name: 'CONCESSION: CPR',
            sym: 'C2',
            value: 100,
            revenue: 10,
            desc: 'Has a face value of £100 and converts into the CPR’s 10% director certificate. CPR may also put '\
                  'its destination token into Vancouver when converted.',
            abilities: [
              {
                type: 'exchange',
                corporations: ['CPR'],
                owner_type: 'player',
                from: 'par',
              },
            ],
            color: '#ed242a',
            text_color: 'white',
          },
          {
            name: 'CONCESSION: GNWR',
            sym: 'C3',
            value: 100,
            revenue: 10,
            desc: 'Has a face value of £100 and contributes £100 to conversion into the GNWR director’s '\
                  'certificate.',
            abilities: [
              {
                type: 'exchange',
                corporations: ['GNWR'],
                owner_type: 'player',
                from: 'par',
              },
            ],
            color: '#8dd8f8',
            text_color: 'black',
          },
          {
            name: 'CONCESSION: GT',
            sym: 'C4',
            value: 100,
            revenue: 10,
            desc: 'Has a face value of £100 and contributes £100 to conversion into the GT director’s '\
                  'certificate.',
            abilities: [
              {
                type: 'exchange',
                corporations: ['GT'],
                owner_type: 'player',
                from: 'par',
              },
            ],
            color: '#000000',
            text_color: 'white',
          },
          {
            name: 'CONCESSION: GTP',
            sym: 'C5',
            value: 100,
            revenue: 10,
            desc: 'Has a face value of £100 and contributes £100 to conversion into the GTP director’s certificate.',
            abilities: [
              {
                type: 'exchange',
                corporations: ['GTP'],
                owner_type: 'player',
                from: 'par',
              },
            ],
            color: '#f47d20',
            text_color: 'white',
          },
          {
            name: 'CONCESSION: GWR',
            sym: 'C6',
            value: 100,
            revenue: 10,
            desc: 'Has a face value of £100 and contributes £100 to conversion into the GWR director’s certificate.',
            abilities: [
              {
                type: 'exchange',
                corporations: ['GWR'],
                owner_type: 'player',
                from: 'par',
              },
            ],
            color: '#395aa8',
            text_color: 'white',
          },
          {
            name: 'CONCESSION: ICR',
            sym: 'C7',
            value: 100,
            revenue: 10,
            desc: 'Has a face value of £100 and contributes £100 to conversion into the ICR director’s certificate.',
            abilities: [
              {
                type: 'exchange',
                corporations: ['ICR'],
                owner_type: 'player',
                from: 'par',
              },
            ],
            color: '#eee91e',
            text_color: 'black',
          },
          {
            name: 'CONCESSION: NTR',
            sym: 'C8',
            value: 100,
            revenue: 10,
            desc: 'Has a face value of £100 and contributes £100 to conversion into the NTR director’s certificate.',
            abilities: [
              {
                type: 'exchange',
                corporations: ['NTR'],
                owner_type: 'player',
                from: 'par',
              },
            ],
            color: '#9a6733',
            text_color: 'white',
          },
          {
            name: 'CONCESSION: PGE',
            sym: 'C9',
            value: 100,
            revenue: 10,
            desc: 'Has a face value of £100 and contributes £100 to conversion into the PGE director’s certificate.',
            abilities: [
              {
                type: 'exchange',
                corporations: ['PGE'],
                owner_type: 'player',
                from: 'par',
              },
            ],
            color: '#199d4a',
            text_color: 'white',
          },
          {
            name: 'CONCESSION: QMOO',
            sym: 'C10',
            value: 100,
            revenue: 10,
            desc: 'Has a face value of £100 and contributes £100 to conversion into the QMOO director’s certificate.',
            abilities: [
              {
                type: 'exchange',
                corporations: ['QMOO'],
                owner_type: 'player',
                from: 'par',
              },
            ],
            color: '#7f3881',
            text_color: 'white',
          },
          {
            name: 'MINOR: 1. Dominion Atlantic Railway',
            sym: 'M1',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is AP4.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 2. European & North American Railway',
            sym: 'M2',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is AN6.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 3. Quebec & New Brunswick Railway',
            sym: 'M3',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is AK3.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 4. Quebec Central Railway',
            sym: 'M4',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is AH12.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 5. North Shore Railway',
            sym: 'M5',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is AH8.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 6. Champlain & St Lawrence Railroad',
            sym: 'M6',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is AG13.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 7. Montreal & Lachine Railway',
            sym: 'M7',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is AF12.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 8. Bytown & Prescott Railway',
            sym: 'M8',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is AE15.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 9. Canada Atlantic Railway',
            sym: 'M9',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is AE15.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 10. Midland Railway',
            sym: 'M10',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is AD20.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 11. Canada Southern Railway',
            sym: 'M11',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is AC23.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 12. Toronto, Hamilton & Buffalo Railway',
            sym: 'M12',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is AC21.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 13. Ontario & Quebec Railway',
            sym: 'M13',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is AC21. Home '\
                  'token cost £20, placing home token counts as first tile lay.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 14. London & Port Stanley Railway',
            sym: 'M14',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is AA25.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 15. Lake Nipissing & James’ Bay Railway',
            sym: 'M15',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is AA15.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 16. Windsor, Chatham & London Railway',
            sym: 'M16',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is Z28.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 17. Canada Central Railway',
            sym: 'M17',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is Y15.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 18. Ontario & Abitibi Railway',
            sym: 'M18',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is X12.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 19. Algoma Central Railway',
            sym: 'M19',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is V18.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 20. Port Arthur, Duluth & Western Railway',
            sym: 'M20',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is P18.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 21. Winnipeg & Atlantic Railway',
            sym: 'M21',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is N16.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 22. Winnipeg & Hudson’s Bay Railway',
            sym: 'M22',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is N6.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 23. Prince Albert & North Saskatchewan Railway',
            sym: 'M23',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is K15.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 24. Saskatoon & Northern Railway',
            sym: 'M24',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is J12.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 25. Northern Empire Railway',
            sym: 'M25',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is G17.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 26. Calgary & Fort McMurray Railway',
            sym: 'M26',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is G15.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 27. Athabaska Northern Railway',
            sym: 'M27',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is G11.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 28. Kamloops & Yellow Head Pass Railway',
            sym: 'M28',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is D14.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 29. Kootenay, Cariboo & Pacific Railway',
            sym: 'M29',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is D10.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 30. Pacific Northern & Omineca Railway',
            sym: 'M30',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is A7.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
        ].freeze

        CORPORATIONS = [
          {
            sym: '1',
            name: 'Dominion Atlantic Railway',
            logo: '1822_ca/1',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'AP4',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '2',
            name: 'European & North American Railway',
            logo: '1822_ca/2',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'AN6',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '3',
            name: 'Quebec & New Brunswick Railway',
            logo: '1822_ca/3',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'AK3',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '4',
            name: 'Quebec Central Railway',
            logo: '1822_ca/4',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'AH12',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '5',
            name: 'North Shore Railway',
            logo: '1822_ca/5',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            city: 0,
            coordinates: 'AH8',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '6',
            name: 'Champlain & St Lawrence Railroad',
            logo: '1822_ca/6',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'AG13',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '7',
            name: 'Montreal & Lachine Railway',
            logo: '1822_ca/7',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'AF12',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '8',
            name: 'Bytown & Prescott Railway',
            logo: '1822_ca/8',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'AE15',
            city: 1,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '9',
            name: 'Canada Atlantic Railway',
            logo: '1822_ca/9',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'AE15',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '10',
            name: 'Midland Railway',
            logo: '1822_ca/10',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'AD20',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '11',
            name: 'Canada Southern Railway',
            logo: '1822_ca/11',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'AC23',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '12',
            name: 'Toronto, Hamilton & Buffalo Railway',
            logo: '1822_ca/12',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'AC21',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '13',
            name: 'Ontario & Quebec Railway',
            logo: '1822_ca/13',
            tokens: [20],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '14',
            name: 'London & Port Stanley Railway',
            logo: '1822_ca/14',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'AA25',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '15',
            name: 'Lake Nipissing & James’ Bay Railway',
            logo: '1822_ca/15',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'AA15',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '16',
            name: 'Windsor, Chatham & London Railway',
            logo: '1822_ca/16',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'Z28',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '17',
            name: 'Canada Central Railway',
            logo: '1822_ca/17',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'Y15',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '18',
            name: 'Ontario & Abitibi Railway',
            logo: '1822_ca/18',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'X12',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '19',
            name: 'Algoma Central Railway',
            logo: '1822_ca/19',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'V18',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '20',
            name: 'Port Arthur, Duluth & Western Railway',
            logo: '1822_ca/20',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'P18',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '21',
            name: 'Winnipeg & Atlantic Railway',
            logo: '1822_ca/21',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'N16',
            city: 2,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '22',
            name: 'Winnipeg & Hudson’s Bay Railway',
            logo: '1822_ca/22',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'N6',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '23',
            name: 'Prince Albert & North Saskatchewan Railway',
            logo: '1822_ca/23',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'K15',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '24',
            name: 'Saskatoon & Northern Railway',
            logo: '1822_ca/24',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'J12',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '25',
            name: 'Northern Empire Railway',
            logo: '1822_ca/25',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'G17',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '26',
            name: 'Calgary & Fort McMurray Railway',
            logo: '1822_ca/26',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'G15',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '27',
            name: 'Athabaska Northern Railway',
            logo: '1822_ca/27',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'G11',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '28',
            name: 'Kamloops & Yellow Head Pass Railway',
            logo: '1822_ca/28',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'D14',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '29',
            name: 'Kootenay, Cariboo & Pacific Railway',
            logo: '1822_ca/29',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'D10',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '30',
            name: 'Pacific Northern & Omineca Railway',
            logo: '1822_ca/30',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'A7',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: 'CNoR',
            name: 'Canadian Northern Railway',
            logo: '1822_ca/CNoR',
            tokens: [0, 100],
            type: 'major',
            float_percent: 20,
            always_market_price: true,
            coordinates: 'N16',
            city: 0,
            color: '#9fce63',
            text_color: 'black',
            reservation_color: nil,
            destination_coordinates: 'C15',
            destination_icon: '1822_ca/CNoR_DEST',
          },
          {
            sym: 'CPR',
            name: 'Canadian Pacific Railway',
            logo: '1822_ca/CPR',
            tokens: [0, 100],
            type: 'major',
            float_percent: 10,
            shares: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
            always_market_price: true,
            coordinates: 'AF12',
            city: 1,
            color: '#ed242a',
            reservation_color: nil,
            destination_coordinates: 'C15',
            destination_icon: '1822_ca/CPR_DEST',
          },
          {
            sym: 'GNWR',
            name: 'Great North West Railway',
            logo: '1822_ca/GNWR',
            tokens: [0, 100],
            type: 'major',
            float_percent: 20,
            always_market_price: true,
            coordinates: 'R16',
            color: '#8dd8f8',
            text_color: 'black',
            reservation_color: nil,
            destination_coordinates: 'N16',
            destination_icon: '1822_ca/GNWR_DEST',
          },
          {
            sym: 'GT',
            name: 'Grand Trunk Railway',
            logo: '1822_ca/GT',
            tokens: [0, 100],
            type: 'major',
            float_percent: 20,
            always_market_price: true,
            coordinates: 'AC21',
            city: 1,
            color: '#000000',
            reservation_color: nil,
            destination_coordinates: 'AF12',
            destination_icon: '1822_ca/GT_DEST',
          },
          {
            sym: 'GTP',
            name: 'Caledonian Railway',
            logo: '1822_ca/GTP',
            tokens: [0, 100],
            type: 'major',
            float_percent: 20,
            always_market_price: true,
            coordinates: 'N16',
            city: 0,
            color: '#f47d20',
            reservation_color: nil,
            destination_coordinates: 'A7',
            destination_icon: '1822_ca/GTP_DEST',
          },
          {
            sym: 'GWR',
            name: 'Great Western Railway',
            logo: '1822_ca/GWR',
            tokens: [0, 100],
            type: 'major',
            float_percent: 20,
            always_market_price: true,
            coordinates: 'AB24',
            color: '#395aa8',
            reservation_color: nil,
            destination_coordinates: 'Z28',
            destination_icon: '1822_ca/GWR_DEST',
          },
          {
            sym: 'ICR',
            name: 'Intercolonial Railway',
            logo: '1822_ca/ICR',
            tokens: [0, 100],
            type: 'major',
            float_percent: 20,
            always_market_price: true,
            coordinates: 'AP4',
            color: '#eee91e',
            text_color: 'black',
            reservation_color: nil,
            destination_coordinates: 'AH8',
            destination_icon: '1822_ca/ICR_DEST',
          },
          {
            sym: 'NTR',
            name: 'National Transcontinental Railway',
            logo: '1822_ca/NTR',
            tokens: [0, 100],
            type: 'major',
            float_percent: 20,
            always_market_price: true,
            coordinates: 'AO3',
            color: '#9a6733',
            reservation_color: nil,
            destination_coordinates: 'N16',
            destination_icon: '1822_ca/NTR_DEST',
          },
          {
            sym: 'PGE',
            name: 'Pacific Great Eastern Railway',
            logo: '1822_ca/PGE',
            tokens: [0, 100],
            type: 'major',
            float_percent: 20,
            always_market_price: true,
            coordinates: 'C15',
            color: '#199d4a',
            reservation_color: nil,
            destination_coordinates: 'D10',
            destination_icon: '1822_ca/PGE_DEST',
          },
          {
            sym: 'QMOO',
            name: 'Quebec, Montreal, Ottawa and Occidental Railway',
            logo: '1822_ca/QMOO',
            tokens: [0, 100],
            type: 'major',
            float_percent: 20,
            always_market_price: true,
            coordinates: 'AH8',
            city: 1,
            color: '#7f3881',
            reservation_color: nil,
            destination_coordinates: 'AA15',
            destination_icon: '1822_ca/QMOO_DEST',
          },
        ].freeze
      end
    end
  end
end
