# frozen_string_literal: true

require_relative 'meta'
require_relative '../base'
require_relative 'step/charter_auction'

module Engine
  module Game
    module G1862
      module Entities
        COMPANIES = [].freeze

        CORPORATIONS = [
          {
            sym: 'E&H',
            name: 'Ely & Huntingdon',
            logo: '1862/EH',
            simple_logo: '1862/EH.alt',
            float_percent: 50,
            shares: [30, 10, 10, 10, 10, 10, 10, 10],
            max_ownership_percent: 100,
            tokens: [0, 0, 0],
            coordinates: 'C8',
            color: '#FFFF00',
            text_color: '#DD571C',
            reservation_color: nil,
          },
          {
            sym: 'ECR',
            name: 'Eastern Counties Railway',
            logo: '1862/ECR',
            simple_logo: '1862/ECR.alt',
            float_percent: 50,
            shares: [30, 10, 10, 10, 10, 10, 10, 10],
            max_ownership_percent: 100,
            tokens: [0, 0, 0],
            coordinates: 'D13',
            color: '#0A1172',
            text_color: '#FFFFFF',
            reservation_color: nil,
          },
          {
            sym: 'ENR',
            name: 'East Norfolk Railway',
            logo: '1862/ENR',
            simple_logo: '1862/ENR.alt',
            float_percent: 50,
            shares: [30, 10, 10, 10, 10, 10, 10, 10],
            max_ownership_percent: 100,
            tokens: [0, 0, 0],
            coordinates: 'F3',
            color: '#FFFF00',
            text_color: '#0492C2',
            reservation_color: nil,
          },
          {
            sym: 'ESR',
            name: 'East Suffolk Railway',
            logo: '1862/ESR',
            simple_logo: '1862/ESR.alt',
            float_percent: 50,
            shares: [30, 10, 10, 10, 10, 10, 10, 10],
            max_ownership_percent: 100,
            tokens: [0, 0, 0],
            coordinates: 'F11',
            color: '#5DBB63',
            text_color: '#30430E',
            reservation_color: nil,
          },
          {
            sym: 'EUR',
            name: 'Eastern Union Railway',
            logo: '1862/EUR',
            simple_logo: '1862/EUR.alt',
            float_percent: 50,
            shares: [30, 10, 10, 10, 10, 10, 10, 10],
            max_ownership_percent: 100,
            tokens: [0, 0, 0],
            coordinates: 'E12',
            color: '#FF3030',
            text_color: '#710193',
            reservation_color: nil,
          },
          {
            sym: 'FDR',
            name: 'Felixstowe Dock & Railway',
            logo: '1862/FDR',
            simple_logo: '1862/FDR.alt',
            float_percent: 50,
            shares: [30, 10, 10, 10, 10, 10, 10, 10],
            max_ownership_percent: 100,
            tokens: [0, 0, 0],
            coordinates: 'G12',
            color: '#FF6A06',
            text_color: '#C00000',
            reservation_color: nil,
          },
          {
            sym: 'I&B',
            name: 'Ipswich & Bury Railway',
            logo: '1862/IB',
            simple_logo: '1862/IB.alt',
            float_percent: 50,
            shares: [30, 10, 10, 10, 10, 10, 10, 10],
            max_ownership_percent: 100,
            tokens: [0, 0, 0],
            coordinates: 'D9',
            color: '#A0A0A0',
            text_color: '#000000',
            reservation_color: nil,
          },
          {
            sym: 'L&D',
            name: 'Lynn & Dereham Railway',
            logo: '1862/LD',
            simple_logo: '1862/LD.alt',
            float_percent: 50,
            shares: [30, 10, 10, 10, 10, 10, 10, 10],
            max_ownership_percent: 100,
            tokens: [0, 0, 0],
            coordinates: 'D5',
            color: '#FF6A06',
            text_color: '#0A1172',
            reservation_color: nil,
          },
          {
            sym: 'L&E',
            name: 'Lynn & Ely Railway',
            logo: '1862/LE',
            simple_logo: '1862/LE.alt',
            float_percent: 50,
            shares: [30, 10, 10, 10, 10, 10, 10, 10],
            max_ownership_percent: 100,
            tokens: [0, 0, 0],
            coordinates: 'C6',
            color: '#FFFF00',
            text_color: '#D00000',
            reservation_color: nil,
          },
          {
            sym: 'L&H',
            name: 'Lynn & Hunstanton Railway',
            logo: '1862/LH',
            simple_logo: '1862/LH.alt',
            float_percent: 50,
            shares: [30, 10, 10, 10, 10, 10, 10, 10],
            max_ownership_percent: 100,
            tokens: [0, 0, 0],
            coordinates: 'C4',
            color: '#A1CAF1',
            text_color: '#B00000',
            reservation_color: nil,
          },
          {
            sym: 'N&B',
            name: 'Norwich & Brandon Railway',
            logo: '1862/NB',
            simple_logo: '1862/NB.alt',
            float_percent: 50,
            shares: [30, 10, 10, 10, 10, 10, 10, 10],
            max_ownership_percent: 100,
            tokens: [0, 0, 0],
            coordinates: 'E8',
            color: '#C0C0C0',
            text_color: '#B64900',
            reservation_color: nil,
          },
          {
            sym: 'N&E',
            name: 'Northern & Eastern Railway',
            logo: '1862/NE',
            simple_logo: '1862/NE.alt',
            float_percent: 50,
            shares: [30, 10, 10, 10, 10, 10, 10, 10],
            max_ownership_percent: 100,
            tokens: [0, 0, 0],
            coordinates: 'B13',
            color: '#C0C0C0',
            text_color: '#355E3B',
            reservation_color: nil,
          },
          {
            sym: 'N&S',
            name: 'Norfolk & Suffolk, Joint Railway',
            logo: '1862/NS',
            simple_logo: '1862/NS.alt',
            float_percent: 50,
            shares: [30, 10, 10, 10, 10, 10, 10, 10],
            max_ownership_percent: 100,
            tokens: [0, 0, 0],
            coordinates: 'H7',
            color: '#A1CAF1',
            text_color: '#082567',
            reservation_color: nil,
          },
          {
            sym: 'Y&N',
            name: 'Yarmouth & Norwich Railway',
            logo: '1862/YN',
            simple_logo: '1862/YN.alt',
            float_percent: 50,
            shares: [30, 10, 10, 10, 10, 10, 10, 10],
            max_ownership_percent: 100,
            tokens: [0, 0, 0],
            coordinates: 'H5',
            color: '#ff0000',
            text_color: '#000000',
            reservation_color: nil,
          },
          {
            sym: 'NGC',
            name: 'Newmarket and Great Chesterford Railway',
            logo: '1862/NGC',
            simple_logo: '1862/NGC.alt',
            float_percent: 50,
            shares: [30, 10, 10, 10, 10, 10, 10, 10],
            max_ownership_percent: 100,
            tokens: [0, 0, 0],
            coordinates: 'C10',
            color: '#FFFF00',
            text_color: '#000000',
            reservation_color: nil,
          },
          {
            sym: 'SVR',
            name: 'Colchester, Stour Valley, Sudbury & Halstead',
            logo: '1862/SVR',
            simple_logo: '1862/SVR.alt',
            float_percent: 50,
            shares: [30, 10, 10, 10, 10, 10, 10, 10],
            max_ownership_percent: 100,
            tokens: [0, 0, 0],
            coordinates: 'D11',
            color: '#D2B55B',
            text_color: '#355E3B',
            reservation_color: nil,
          },
          {
            sym: 'WNR',
            name: 'West Norfolk Railway',
            logo: '1862/WNR',
            simple_logo: '1862/WNR.alt',
            float_percent: 50,
            shares: [30, 10, 10, 10, 10, 10, 10, 10],
            max_ownership_percent: 100,
            tokens: [0, 0, 0],
            coordinates: 'E2',
            color: '#D2B55B',
            text_color: '#FF0000',
            reservation_color: nil,
          },
          {
            sym: 'W&F',
            name: 'Wells & Fakenham Railway',
            logo: '1862/WF',
            simple_logo: '1862/WF.alt',
            float_percent: 50,
            shares: [30, 10, 10, 10, 10, 10, 10, 10],
            max_ownership_percent: 100,
            tokens: [0, 0, 0],
            coordinates: 'E4',
            color: '#C7EA46',
            text_color: '#0B6623',
            reservation_color: nil,
          },
          {
            sym: 'WVR',
            name: 'Waveney Valley Railway',
            logo: '1862/WVR',
            simple_logo: '1862/WVR.alt',
            float_percent: 50,
            shares: [30, 10, 10, 10, 10, 10, 10, 10],
            max_ownership_percent: 100,
            tokens: [0, 0, 0],
            coordinates: 'G8',
            color: '#FFC0C0',
            text_color: '#8B008B',
            reservation_color: nil,
          },
          {
            sym: 'WStI',
            name: 'Wisbech, St Ives & Cambridge Junction Rwy',
            logo: '1862/WSTI',
            simple_logo: '1862/WSTI.alt',
            float_percent: 50,
            shares: [30, 10, 10, 10, 10, 10, 10, 10],
            max_ownership_percent: 100,
            tokens: [0, 0, 0],
            coordinates: 'B5',
            color: '#FFFF00',
            text_color: '#8B008B',
            reservation_color: nil,
          },
        ].freeze
      end
    end
  end
end
