# frozen_string_literal: true

# logo map 50x50
# dest

module Engine
  module Game
    module G18Uruguay
      module Corporations
        # FCE = {
        #  float_percent: 20,
        #  sym: 'FCE',
        #  name: 'Los Ferrocarriles y Tranvias del Estado',
        #  logo: '18_uruguay/FCE.alt',
        #  simple_logo: '18_uruguay/FCE.alt',
        #  color: '#025aaa',
        #  floatable: false,
        #  tokens: [0, 40, 60, 100],
        #  text_color: 'white',
        #  abilities: [],
        # }

        CORPORATIONS = [
          {
            float_percent: 20,
            sym: 'FCE',
            name: 'Los Ferrocarriles y Tranvias del Estado',
            logo: '18_uruguay/FCE.alt',
            simple_logo: '18_uruguay/FCE.alt',
            color: '#025aaa',
            floatable: false,
            ipoed: false,
            tokens: [0, 40, 60, 100],
            text_color: 'white',
            abilities: [],
          },
          {
            float_percent: 20,
            sym: 'RPTLA',
            name: 'The River Plate Trust, Loan & Agency Company, ltd',
            logo: '1848/BOE',
            simple_logo: '18_uruguay/RPTLA.alt',
            color: '#FF0000',
            tokens: [0],
            coordinates: 'K15',
            text_color: 'black',
            abilities: [],
            type: :bank,
            capitalization: :incremental,
            always_market_price: true,
          },
          {
            float_percent: 50,
            sym: 'FCCU',
            name: 'FC Central del Uruguay',
            logo: '18_uruguay/FCCU.alt',
            simple_logo: '18_uruguay/FCCU.alt',
            color: :'#1a1919',
            reservation_color: '#1a1919',
            text_color: 'white',
            tokens: [0, 40, 60, 100],
            coordinates: 'J6',
            city: 1,
            abilities: [],
            destination_coordinates: 'F6',
            destination_icon: '18_uruguay/FCCU.alt',
          },
          {
            float_percent: 50,
            sym: 'FCNE',
            name: 'FC Nordeste del Uruguay',
            logo: '18_uruguay/FCNE.alt',
            simple_logo: '18_uruguay/FCNE.alt',
            color: :'#fff104',
            text_color: 'black',
            reservation_color: '#fff104',
            tokens: [0, 40, 60, 100],
            coordinates: 'I9',
            destination_coordinates: 'E13',
            destination_icon: '18_uruguay/FCNE.alt',
          },
          {
            float_percent: 50,
            sym: 'WER',
            name: 'Western Extension Railway',
            logo: '18_uruguay/WER.alt',
            simple_logo: '18_uruguay/WER.alt',
            color: :'#f47d20',
            reservation_color: '#f47d20',
            tokens: [0, 40, 60],
            coordinates: 'G3',
            destination_coordinates: 'J12',
            destination_icon: '18_uruguay/WER.alt',
          },
          {
            float_percent: 50,
            sym: 'FCNO',
            name: 'FC Nordueste de Montevideo',
            logo: '18_uruguay/FCNO',
            simple_logo: '18_uruguay/FCNO.alt',
            color: '#12a969',
            reservation_color: '#12a969',
            tokens: [0, 40, 60],
            coordinates: 'D2',
            destination_coordinates: 'C9',
            destination_icon: '18_uruguay/FCNO.alt',
          },
          {
            float_percent: 50,
            sym: 'FCMU',
            name: 'FC Midland del Uruguay',
            logo: '18_uruguay/FCMU.alt',
            simple_logo: '18_uruguay/FCMU.alt',
            color: :'#e1ad01',
            text_color: 'black',
            reservation_color: '#e1ad01',
            tokens: [0, 40, 60],
            coordinates: 'F6',
            destination_coordinates: 'I3',
            destination_icon: '18_uruguay/FCMU.alt',
          },
          {
            float_percent: 50,
            sym: 'EER',
            name: 'Eastern Extension Railway',
            logo: '18_uruguay/EER.alt',
            simple_logo: '18_uruguay/EER.alt',
            color: '#772c7b',
            reservation_color: '#772c7b',
            tokens: [0, 40, 60],
            coordinates: 'E13',
            destination_coordinates: 'D6',
            destination_icon: '18_uruguay/EER.alt',
          },
          {
            float_percent: 50,
            sym: 'FCNU',
            name: 'FC del Norte del Uruguay',
            logo: '18_uruguay/FCNU.alt',
            simple_logo: '18_uruguay/FCNU.alt',
            color: '#0189c4',
            reservation_color: '#0189c4',
            tokens: [0, 40, 60],
            coordinates: 'B6',
            destination_coordinates: 'E3',
            destination_icon: '18_uruguay/FCNU.alt',
          },
          {
            float_percent: 50,
            sym: 'PTC',
            name: 'Panamerican Trans-Continental Railway',
            logo: '18_uruguay/PTC.alt',
            simple_logo: '18_uruguay/PTC.alt',
            color: :'#fad5e4',
            text_color: 'black',
            reservation_color: '#fad5e4',
            tokens: [0, 40, 60],
            coordinates: 'H14',
            destination_coordinates: 'G3',
            destination_icon: '18_uruguay/BM',
          },
          {
            float_percent: 50,
            sym: 'ECR',
            name: 'East Coast Railways',
            logo: '18_uruguay/ECR.alt',
            simple_logo: '18_uruguay/ECR.alt',
            color: '#43c6db',
            text_color: 'black',
            reservation_color: '#43c6db',
            tokens: [0, 40, 60],
            coordinates: 'J6',
            city: 3,
            destination_coordinates: 'H14',
            destination_icon: '18_uruguay/CO',
          },
        ].freeze
      end
    end
  end
end
