# frozen_string_literal: true

# logo map 50x50
# dest

module Engine
  module Game
    module G18Uruguay
      module Corporations
        CORPORATIONS = [
          {
            float_percent: 20,
            sym: 'FCE',
            name: 'Los Ferrocarriles y Tranvias del Estado',
            logo: '18_uruguay/FCE',
            simple_logo: '18_uruguay/FCE.alt',
            color: '#025aaa',
            floatable: false,
            ipoed: false,
            tokens: [100, 100, 100, 100, 100],
            text_color: 'white',
            abilities: [],
          },
          {
            float_percent: 30,
            sym: 'RPTLA',
            name: 'The River Plate Trust, Loan & Agency Company, ltd',
            logo: '1848/BOE',
            simple_logo: '18_uruguay/RPTLA.alt',
            color: '#FF0000',
            tokens: [0],
            coordinates: 'K15',
            text_color: 'black',
            shares: [30, 10, 10, 10, 10, 10, 10, 10],
            abilities: [],
            type: :bank,
            capitalization: :incremental,
            always_market_price: true,
          },
          {
            float_percent: 50,
            sym: 'FCCU',
            name: 'FC Central del Uruguay',
            logo: '18_uruguay/FCCU',
            simple_logo: '18_uruguay/FCCU.alt',
            color: :'#1a1919',
            text_color: 'white',
            tokens: [0, 40, 60, 100],
            coordinates: 'J6',
            city: 1,
            abilities: [],
            destination_coordinates: 'F6',
            destination_icon: '18_uruguay/FCCU',
          },
          {
            float_percent: 50,
            sym: 'FCNE',
            name: 'FC Nordeste del Uruguay',
            logo: '18_uruguay/FCNE',
            simple_logo: '18_uruguay/FCNE.alt',
            color: :'#fff104',
            text_color: 'black',
            tokens: [0, 40, 60, 100],
            coordinates: 'I9',
            destination_coordinates: 'E13',
            destination_icon: '18_uruguay/FCNE',
          },
          {
            float_percent: 50,
            sym: 'WER',
            name: 'Western Extension Railway',
            logo: '18_uruguay/WER',
            simple_logo: '18_uruguay/WER.alt',
            color: :'#f47d20',
            tokens: [0, 40, 60],
            coordinates: 'G3',
            destination_coordinates: 'J12',
            destination_icon: '18_uruguay/WER',
          },
          {
            float_percent: 50,
            sym: 'FCNO',
            name: 'FC Nordueste de Montevideo',
            logo: '18_uruguay/FCNO',
            simple_logo: '18_uruguay/FCNO.alt',
            color: '#12a969',
            tokens: [0, 40, 60],
            coordinates: 'D2',
            destination_coordinates: 'C9',
            destination_icon: '18_uruguay/FCNO',
          },
          {
            float_percent: 50,
            sym: 'FCMU',
            name: 'FC Midland del Uruguay',
            logo: '18_uruguay/FCMU',
            simple_logo: '18_uruguay/FCMU.alt',
            color: :'#e1ad01',
            text_color: 'black',
            tokens: [0, 40, 60],
            coordinates: 'F6',
            destination_coordinates: 'I3',
            destination_icon: '18_uruguay/FCMU',
          },
          {
            float_percent: 50,
            sym: 'EER',
            name: 'Eastern Extension Railway',
            logo: '18_uruguay/EER',
            simple_logo: '18_uruguay/EER.alt',
            color: '#772c7b',
            tokens: [0, 40, 60],
            coordinates: 'E13',
            destination_coordinates: 'D6',
            destination_icon: '18_uruguay/EER',
          },
          {
            float_percent: 50,
            sym: 'FCNU',
            name: 'FC del Norte del Uruguay',
            logo: '18_uruguay/FCNU',
            simple_logo: '18_uruguay/FCNU.alt',
            color: '#0189c4',
            tokens: [0, 40, 60],
            coordinates: 'B6',
            destination_coordinates: 'E3',
            destination_icon: '18_uruguay/FCNU',
          },
          {
            float_percent: 50,
            sym: 'PTC',
            name: 'Panamerican Trans-Continental Railway',
            logo: '18_uruguay/PTC',
            simple_logo: '18_uruguay/PTC.alt',
            color: :'#fad5e4',
            text_color: 'black',
            tokens: [0, 40, 60],
            coordinates: 'H14',
            destination_coordinates: 'G3',
            destination_icon: '18_uruguay/PTC',
          },
          {
            float_percent: 50,
            sym: 'ECR',
            name: 'East Coast Railways',
            logo: '18_uruguay/ECR',
            simple_logo: '18_uruguay/ECR.alt',
            color: '#43c6db',
            text_color: 'black',
            tokens: [0, 40, 60],
            coordinates: 'J6',
            city: 3,
            destination_coordinates: 'H14',
            destination_icon: '18_uruguay/ECR',
          },
        ].freeze
      end
    end
  end
end
