# frozen_string_literal: true

module Engine
  class GameError < RuntimeError
  end

  # errors generated by route.revenue and used by auto_router

  class NoToken < GameError
  end

  class RouteTooShort < GameError
  end

  class RouteTooLong < GameError
  end

  class ReusesCity < GameError
  end

  # errors generated by the auto_router

  class PathTimeout < GameError
  end
end
