# frozen_string_literal: true

# rubocop:disable Lint/RedundantCopDisableDirective, Layout/LineLength, Layout/HeredocIndentation

module Engine
  module Config
    module Game
      module G18GA
        JSON = <<-'DATA'
{
   "filename":"18_ga",
   "modulename":"18GA",
   "currencyFormatStr":"$%d",
   "bankCash":8000,
   "certLimit":{
      "3":15,
      "4":12,
      "5":10
   },
   "startingCash":{
      "3":600,
      "4":450,
      "5":360
   },
   "capitalization":"full",
   "layout":"pointy",
   "mustSellInBlocks":false,
   "locationNames":{
      "I11":"Brunswick",
      "C3":"Rome",
      "D4":"Atlanta",
      "D10":"Augusta",
      "E7":"Milledgeville",
      "F6":"Macon",
      "G3":"Columbus",
      "H4":"Albany",
      "I9":"Waycross",
      "J12":"Jacksonville",
      "E1":"Montgomery",
      "J4":"Talahassee",
      "A3":"Chattanooga",
      "B10":"Greeneville",
      "G13":"Savannah",
      "G11":"Statesboro",
      "I7":"Valdosta"
   },
   "tiles":{
      "3":3,
      "4":3,
      "5":2,
      "6":2,
      "7":5,
      "8":11,
      "9":10,
      "57":4,
      "58":3,
      "14":4,
      "15":4,
      "16":1,
      "17":1,
      "19":1,
      "20":1,
      "23":4,
      "24":4,
      "25":1,
      "26":1,
      "27":1,
      "28":2,
      "29":2,
      "141":2,
      "142":2,
      "143":2,
      "452":1,
      "453":1,
      "454":1,
      "39":2,
      "40":1,
      "41":3,
      "42":3,
      "43":2,
      "44":1,
      "45":2,
      "46":2,
      "47":2,
      "63":4,
      "70":1,
      "455":1,
      "457":1,
      "458":1,
      "459":1
   },
   "market":[
      [
         "60",
         "70",
         "80",
         "90",
         "100",
         "110p",
         "120",
         "135",
         "150",
         "170",
         "190",
         "210",
         "230",
         "250",
         "275",
         "300b"
      ],
      [
         "55",
         "60",
         "70",
         "80",
         "90p",
         "100",
         "110",
         "120",
         "135",
         "150",
         "170",
         "190",
         "210",
         "230",
         "250"
      ],
      [
         "50y",
         "55",
         "60",
         "70p",
         "80",
         "90",
         "100",
         "110",
         "120",
         "135",
         "150",
         "170",
         "190"
      ],
      [
         "45y",
         "50y",
         "55p",
         "60",
         "70",
         "80",
         "90",
         "100",
         "110",
         "120",
         "135"
      ],
      [
         "40y",
         "45y",
         "50y",
         "55",
         "60",
         "70",
         "80",
         "90"
      ],
      [
         "35y",
         "40y",
         "45y",
         "50y",
         "55y"
      ],
      [
         "30y",
         "35y",
         "40y",
         "45y",
         "50y"
      ]
   ],
   "companies":[
      {
         "name":"Lexington Terminal RR",
         "value":20,
         "revenue":5,
         "desc":"No special ability.",
         "sym":"LTR"
      },
      {
         "name":"Midland Railroad Co.",
         "value":40,
         "revenue":10,
         "desc":"A corporation that owns the Midland may lay a tile in the Midland's hex for free, once. The tile need not be connected to an existing station of the corporation. The corporation need not pay the $40 cost of the swamp. And it does not count as the corporation's one tile lay per turn. (But it still must be laid during the tile-laying step of the corporation's turn, and it must not dead-end into a blank side of a red or gray hex, or off the map.) This action does not close the Midland. ",
         "sym":"MRC",
         "abilities":[
            {
               "type":"blocks_hexes",
               "owner_type":"player",
               "hexes":[
                  "F12"
               ]
            },
            {
               "type":"tile_lay",
               "owner_type":"corporation",
               "hexes":[
                  "F12"
               ],
               "tiles":[
                  "7",
                  "8",
                  "9"
               ],
               "when":"track"
            }
         ]
      },
      {
         "name":"Waycross & Southern RR",
         "value":70,
         "revenue":15,
         "desc":"A corporation that owns the Waycross & Southern may place a station token in Waycross at no cost, if there is room. The corporation need not connect to Waycross to use this special ability. However, it can only be done during the token-placement step of the corporation's turn, and only if the corporation has a token left, and it counts as the corporation's one station placement allowed per turn (excluding the home station). This action does not close the Waycross & Southern. As an exception to rule 4.2.1(k), any corporation is free to lay tiles in the Waycross hex even if the Waycross & Southern is still owned by a player. ",
         "sym":"W&SR",
         "abilities":[
            {
               "type":"blocks_hexes",
               "owner_type":"player",
               "hexes":[
                  "I9"
               ]
            },
            {
               "type":"teleport",
               "owner_type":"corporation",
               "tiles":[
                  "5",
                  "6",
                  "57"
               ],
               "hexes":[
                  "I9"
               ]
            }
         ]
      },
      {
         "name":"Ocilla Southern RR",
         "value":100,
         "revenue":20,
         "desc":"When a Corporation purchases the Ocilla Southern, the corporation immediately gets the 2 Train marked Free (unless a 4 Train has been purchased or the corporation already has four trains, in which case the free train is removed from play). This acquisition is not considered a train purchase (so it does not prevent the corporation from also purchasing a train on the same turn), and does not close the Ocilla Southern. The free train cannot be sold to another corporation. In all other respects it is a normal 2 Train. ",
         "sym":"OSR"
      }
   ],
   "corporations":[
      {
         "float_percent":60,
         "sym":"ACL",
         "name":"Atlantic Coast Line",
         "logo":"18_ga/ACL",
         "tokens":[
            0,
            40,
            100,
            100
         ],
         "coordinates":"J12",
         "color":"black"
      },
      {
         "float_percent":60,
         "sym":"CoG",
         "name":"Central of Georgia Railroad",
         "logo":"18_ga/CoG",
         "tokens":[
            0,
            40,
            100,
            100
         ],
         "coordinates":"F6",
         "color":"red"
      },
      {
         "float_percent":60,
         "sym":"G&F",
         "name":"Georgia and Florida Railroad",
         "logo":"18_ga/G&F",
         "tokens":[
            0,
            40
         ],
         "coordinates":"H4",
         "color":"deepskyblue"
      },
      {
         "float_percent":60,
         "sym":"GA",
         "name":"Georgia Railroad",
         "logo":"18_ga/GA",
         "tokens":[
            0,
            40,
            100,
            100
         ],
         "coordinates":"D10",
         "city":0,
         "color":"green"
      },
      {
         "float_percent":60,
         "sym":"W&A",
         "name":"Western and Atlantic Railroad",
         "logo":"18_ga/W&A",
         "tokens":[
            0,
            40
         ],
         "coordinates":"D4",
         "color":"purple",
         "city":0
      },
      {
         "float_percent":60,
         "sym":"SAL",
         "name":"Seaboard Air Line",
         "logo":"18_ga/SAL",
         "tokens":[
            0,
            40,
            100
         ],
         "coordinates":"G13",
         "color":"gold",
         "text_color":"black"
      }
   ],
   "trains":[
      {
         "name":"2",
         "distance":[
            {
               "nodes":[
                  "city",
                  "town",
                  "offboard"
               ],
               "pay":2,
               "visit":2
            },
            {
               "nodes":[
                  "town"
               ],
               "pay":99,
               "visit":99
            }
         ],
         "price":100,
         "rusts_on":"4",
         "num":5
      },
      {
         "name":"3",
         "distance":[
            {
               "nodes":[
                  "city",
                  "town",
                  "offboard"
               ],
               "pay":3,
               "visit":3
            },
            {
               "nodes":[
                  "town"
               ],
               "pay":99,
               "visit":99
            }
         ],
         "price":180,
         "rusts_on":"6",
         "num":4
      },
      {
         "name":"4",
         "distance":[
            {
               "nodes":[
                  "city",
                  "town",
                  "offboard"
               ],
               "pay":4,
               "visit":4
            },
            {
               "nodes":[
                  "town"
               ],
               "pay":99,
               "visit":99
            }
         ],
         "price":300,
         "rusts_on":"8",
         "num":3
      },
      {
         "name":"5",
         "distance":[
            {
               "nodes":[
                  "city",
                  "town",
                  "offboard"
               ],
               "pay":5,
               "visit":5
            },
            {
               "nodes":[
                  "town"
               ],
               "pay":99,
               "visit":99
            }
         ],
         "price":450,
         "num":2
      },
      {
         "name":"6",
         "distance":[
            {
               "nodes":[
                  "city",
                  "town",
                  "offboard"
               ],
               "pay":6,
               "visit":6
            },
            {
               "nodes":[
                  "town"
               ],
               "pay":99,
               "visit":99
            }
         ],
         "price":630,
         "num":2
      },
      {
         "name":"8",
         "distance":[
            {
               "nodes":[
                  "city",
                  "town",
                  "offboard"
               ],
               "pay":8,
               "visit":8
            },
            {
               "nodes":[
                  "town"
               ],
               "pay":99,
               "visit":99
            }
         ],
         "price":800,
         "num":5
      }
   ],
   "hexes":{
      "white":{
         "":[
            "B4",
            "C7",
            "C9",
            "D2",
            "D6",
            "D8",
            "E5",
            "E9",
            "F4",
            "F10",
            "G1",
            "G5",
            "G7",
            "H6",
            "H8",
            "I5",
            "J6",
            "J8",
            "E11"
         ],
         "upgrade=cost:20,terrain:water":[
            "C5",
            "F8",
            "G9",
            "H10",
            "H12"
         ],
         "upgrade=cost:40,terrain:water":[
            "E3",
            "F2",
            "F12",
            "H2",
            "I3",
            "J10"
         ],
         "upgrade=cost:60,terrain:water":[
            "B2",
            "B6",
            "B8",
            "C1"
         ],
         "city=revenue:0;city=revenue:0;city=revenue:0;":[
            "D4"
         ],
         "city=revenue:0":[
            "I11",
            "C3",
            "D10",
            "F6",
            "G3",
            "H4",
            "I9",
            "G13"
         ],
         "town=revenue:0":[
            "G11",
            "I7"
         ],
         "town=revenue:0;upgrade=cost:20,terrain:water":[
            "E7"
         ]
      },
      "red":{
         "city=revenue:yellow_30|brown_60;path=a:1,b:_0;path=a:2,b:_0":[
            "J12"
         ],
         "offboard=revenue:yellow_30|brown_60;path=a:0,b:_0;path=a:5,b:_0":[
            "A3"
         ],
         "offboard=revenue:yellow_30|brown_40;path=a:0,b:_0;path=a:1,b:_0":[
            "B10"
         ]
      },
      "gray":{
         "city=revenue:yellow_30|brown_40;path=a:3,b:_0;path=a:4,b:_0;path=a:5,b:_0":[
            "E1"
         ],
         "city=revenue:yellow_20|brown_50;path=a:2,b:_0;path=a:3,b:_0;path=a:4,b:_0":[
            "J4"
         ]
      }
   },
   "phases":[
      {
         "name":"2",
         "train_limit":4,
         "tiles":[
            "yellow"
         ],
         "operating_rounds":1
      },
      {
         "name":"3",
         "on":"3",
         "train_limit":4,
         "tiles":[
            "yellow",
            "green"
         ],
         "operating_rounds":2,
         "buy_companies":true
      },
      {
         "name":"4",
         "on":"4",
         "train_limit":3,
         "tiles":[
            "yellow",
            "green"
         ],
         "operating_rounds":2,
         "buy_companies":true
      },
      {
         "name":"5",
         "on":"5",
         "train_limit":2,
         "tiles":[
            "yellow",
            "green",
            "brown"
         ],
         "operating_rounds":3,
         "events":{
            "close_companies":true
         }
      },
      {
         "name":"6",
         "on":"6",
         "train_limit":2,
         "tiles":[
            "yellow",
            "green",
            "brown"
         ],
         "operating_rounds":3
      },
      {
         "name":"8",
         "on":"8",
         "train_limit":2,
         "tiles":[
            "yellow",
            "green",
            "brown",
            "gray"
         ],
         "operating_rounds":3
      }
   ]
}
        DATA
      end
    end
  end
end

# rubocop:enable Lint/RedundantCopDisableDirective, Layout/LineLength, Layout/HeredocIndentation
