# frozen_string_literal: true

# File original exported from 18xx-maker/export-rb
# https://github.com/18xx-maker/export-rb
# rubocop:disable Lint/RedundantCopDisableDirective, Layout/LineLength, Layout/HeredocIndentation

module Engine
  module Config
    module Game
      module G18TE
        JSON = <<-'DATA'
{
   "filename":"18_te",
   "modulename":"18TE",
   "currencyFormatStr":"%dℳ",
   "bankCash":4000,
   "certLimit":{
      "2":15,
      "3":10
   },
   "startingCash":{
      "2":500,
      "3":350
   },
   "capitalization":"incremental",
   "layout":"flat",
   "mustSellInBlocks":false,
   "locationNames":{
      "B10":"Emsdetten",
      "F10":"Lengerich",
      "C13":"Greven",
      "C3":"Hopsten",
      "D4":"Recke",
      "E5":"Mettingen",
      "F4":"Westerkappeln",
      "F6":"Lotte",
      "C7":"Hörstel",
      "D8":"Brochterbeck",
      "E11":"Ladbergen",
      "G11":"Lienen",
      "E13":"Brook",
      "D6":"Ibbenbüren",
      "G3":"Hamburg",
      "A5":"Emden",
      "H6":"Löhne",
      "H12":"Hövelhof",
      "C15":"Venlo",
      "D16":"Wanne",
      "E15":"Hamm",
      "G5":"Osnabrück",
      "A7":"Rheine",
      "E9":"Tecklenburg",
      "D14":"Münster"
   },
   "tiles":{
      "3":4,
      "4":4,
      "5":1,
      "6":4,
      "7":7,
      "8":8,
      "9":8,
      "12":2,
      "14":2,
      "15":1,
      "16":1,
      "17":1,
      "18":1,
      "19":1,
      "20":1,
      "21":1,
      "22":1,
      "23":1,
      "24":1,
      "25":1,
      "26":1,
      "27":1,
      "28":1,
      "29":1,
      "30":1,
      "31":1,
      "39":1,
      "40":1,
      "41":1,
      "42":1,
      "43":1,
      "44":1,
      "45":1,
      "46":1,
      "47":1,
      "57":2,
      "58":4,
      "804":2,
      "TE1":{
         "count":1,
         "color":"green",
         "code":"city=revenue:30;path=a:5,b:_0;label=TE"
      },
      "TE2":{
         "count":1,
         "color":"green",
         "code":"city=revenue:30,slots:3;path=a:0,b:_0;path=a:1,b:_0;path=a:2,b:_0;path=a:5,b:_0;label=OS"
      },
      "TE3":{
         "count":1,
         "color":"green",
         "code":"city=revenue:30,slots:2;path=a:2,b:_0;path=a:4,b:_0;path=a:5,b:_0;label=MS"
      },
      "TE4":{
         "count":1,
         "color":"green",
         "code":"city=revenue:30,slots:3;path=a:3,b:_0;path=a:4,b:_0;path=a:5,b:_0;label=RH"
      },
      "TE5":{
         "count":1,
         "color":"brown",
         "code":"city=revenue:50;path=a:2,b:_0;path=a:5,b:_0;label=TE"
      },
      "TE6":{
         "count":1,
         "color":"brown",
         "code":"city=revenue:50,slots:3;path=a:0,b:_0;path=a:1,b:_0;path=a:2,b:_0;path=a:3,b:_0;path=a:5,b:_0;label=OS"
      },
      "TE7":{
         "count":1,
         "color":"brown",
         "code":"city=revenue:50,slots:2;path=a:0,b:_0;path=a:1,b:_0;path=a:2,b:_0;path=a:4,b:_0;path=a:5,b:_0;label=MS"
      },
      "TE8":{
         "count":1,
         "color":"brown",
         "code":"city=revenue:50,slots:3;path=a:3,b:_0;path=a:4,b:_0;path=a:5,b:_0;label=RH"
      }
   },
   "market":[
      [
         "",
         "",
         "",
         "",
         "",
         "100",
         "110",
         "120",
         "130",
         "140",
         "150",
         "160",
         "180",
         "210",
         "250",
         "300",
         ""
      ],
      [
         "",
         "",
         "",
         "",
         "80",
         "90",
         "100p",
         "110",
         "120",
         "130",
         "140",
         "150",
         "160",
         "180",
         "210"
      ],
      [
         "",
         "",
         "",
         "60",
         "70",
         "80",
         "90p",
         "100",
         "110",
         "120",
         "130",
         "140",
         "150"
      ],
      [
         "",
         "",
         "40y",
         "50",
         "60",
         "70",
         "80p",
         "90",
         "100",
         "110",
         "120"
      ],
      [
         "",
         "20y",
         "30y",
         "40y",
         "50",
         "60",
         "70p",
         "80",
         "90"
      ],
      [
         "0",
         "10y",
         "20y",
         "30y",
         "40y",
         "50",
         "60p"
      ]
   ],
   "companies":[

   ],
   "corporations":[
      {
         "sym":"KHS",
         "name":"Königlich Hannöversche Staatseisenbahnen",
         "logo":"18_te/KHS",
         "tokens":[
            0,
            50,
            0
         ],
         "coordinates":"G5",
         "city":1,
         "color":"purple",
         "abilities": [
            {
               "type": "assign_hexes",
               "hexes": [
                 "A7"
               ],
               "count": 1
            }]
      },
      {
         "sym":"KWE",
         "name":"Königlich-Westfälische Eisenbahn-Gesellschaft",
         "logo":"18_te/KWE",
         "tokens":[
            0,
            50,
            0
         ],
         "coordinates":"D14",
         "city":0,
         "color":"green",
         "abilities": [
            {
               "type": "assign_hexes",
               "hexes": [
                 "A7"
               ],
               "count": 1
            }]
      },
      {
         "sym":"CME",
         "name":"Cöln-Mindener Eisenbahn-Gesellschaft",
         "logo":"18_te/CME",
         "tokens":[
            0,
            50,
            0
         ],
         "coordinates":"D14",
         "city":1,
         "color":"red",
         "abilities": [
            {
               "type": "assign_hexes",
               "hexes": [
                 "G5"
               ],
               "count": 1
            }]
      },
      {
         "sym":"TWE",
         "name":"Teutoburger Wald-Eisenbahn",
         "logo":"18_te/TWE",
         "tokens":[
            0,
            50
         ],
         "coordinates":"E9",
         "color":"yellow",
         "text_color":"black",
         "abilities": [
            {
               "type": "assign_hexes",
               "hexes": [
                 "H12"
               ],
               "count": 1
            }]
      },
      {
         "sym":"KPR",
         "name":"Kleinbahn Piesberg-Rheine A.G.",
         "logo":"18_te/KPR",
         "tokens":[
            0,
            0
         ],
         "coordinates":"G5",
         "color":"blue",
         "abilities": [
            {
               "type": "assign_hexes",
               "hexes": [
                 "A7"
               ],
               "count": 1
            }]
      }
   ],
   "trains":[
      {
         "name":"2",
         "distance":2,
         "price":100,
         "rusts_on":"4",
         "num":7,
         "variants":[
            {
               "name":"1+1",
               "distance":[
                  {
                     "nodes":[
                        "city",
                        "offboard",
                        "town"
                     ],
                     "pay":1,
                     "visit":1
                  },
                  {
                     "nodes":[
                        "town"
                     ],
                     "pay":1,
                     "visit":1
                  }
               ],
               "price":80
            }
         ]
      },
      {
         "name":"3",
         "distance":3,
         "price":200,
         "rusts_on":"D",
         "num":5,
         "variants":[
            {
               "name":"2+2",
               "distance":[
                  {
                     "nodes":[
                        "city",
                        "offboard",
                        "town"
                     ],
                     "pay":2,
                     "visit":2
                  },
                  {
                     "nodes":[
                        "town"
                     ],
                     "pay":2,
                     "visit":2
                  }
               ],
               "price":180
            }
         ]
      },
      {
         "name":"4",
         "distance":4,
         "price":400,
         "num":4,
         "variants":[
            {
               "name":"3+3",
               "distance":[
                  {
                     "nodes":[
                        "city",
                        "offboard",
                        "town"
                     ],
                     "pay":3,
                     "visit":3
                  },
                  {
                     "nodes":[
                        "town"
                     ],
                     "pay":3,
                     "visit":3
                  }
               ],
               "price":380
            }
         ]
      },
      {
         "name":"D",
         "distance":999,
         "price":800,
         "num":2
      }
   ],
   "hexes":{
      "white":{
         "":[
            "C1",
            "D2",
            "E3",
            "G7",
            "F12"
         ],
         "border=edge:3,type:water,cost:30;border=edge:4,type:water,cost:30;border=edge:5,type:water,cost:30":[
            "B8",
            "C11"
         ],
         "border=edge:0,type:water,cost:30;border=edge:1,type:water,cost:30":[
            "B6"
         ],
         "border=edge:0,type:water,cost:30;border=edge:1,type:water,cost:30;border=edge:2,type:water,cost:30":[
            "C9"
         ],
         "border=edge:1,type:water,cost:30 ":[
            "D10"
         ],
         "border=edge:1,type:water,cost:30;border=edge:2,type:water,cost:30":[
            "D12"
         ],
         "upgrade=cost:50,terrain:mountain":[
            "B4",
            "C5",
            "E7",
            "F8"
         ],
         "city=revenue:0":[
            "F10"
         ],
         "city=revenue:0;border=edge:4,type:water,cost:30":[
            "B10",
            "C13"
         ],
         "town=revenue:0":[
            "C3",
            "D4",
            "E5",
            "F4",
            "F6",
            "D8",
            "E11",
            "G11",
            "E13"
         ],
         "town=revenue:0;border=edge:1,type:water,cost:30 ":[
            "C7"
         ],
         "city=revenue:0;upgrade=cost:50,terrain:mountain":[
            "D6"
         ]
      },
      "red":{
         "offboard=revenue:yellow_20|green_40|brown_80;path=a:0,b:_0":[
            "G3"
         ],
         "offboard=revenue:yellow_20|green_30|brown_50;path=a:0,b:_0":[
            "A5"
         ],
         "offboard=revenue:yellow_20|green_30|brown_50;path=a:2,b:_0":[
            "H6",
            "H12",
            "E15"
         ],
         "offboard=revenue:yellow_20|green_30|brown_50;path=a:4,b:_0":[
            "C15"
         ],
         "offboard=revenue:yellow_20|green_30|brown_50;path=a:3,b:_0":[
            "D16"
         ]
      },
      "yellow":{
         "city=revenue:20;city=revenue:20;path=a:0,b:_0;path=a:1,b:_1;label=OS":[
            "G5"
         ],
         "city=revenue:20;city=revenue:20;path=a:4,b:_0;path=a:5,b:_1;label=RH;border=edge:4,type:water,cost:30":[
            "A7"
         ],
         "city=revenue:0;label=TE":[
            "E9"
         ],
         "city=revenue:20;city=revenue:20;path=a:2,b:_0;path=a:4,b:_1;label=MS":[
            "D14"
         ]
      }
   },
   "phases":[
      {
         "name":"2",
         "train_limit":3,
         "tiles":[
            "yellow"
         ]
      },
      {
         "name":"3",
         "train_limit":3,
         "tiles":[
            "yellow",
            "green"
         ]
      },
      {
         "name":"4",
         "train_limit":2,
         "tiles":[
            "yellow",
            "green",
            "brown"
         ]
      },
      {
         "name":"D",
         "train_limit":2,
         "tiles":[
            "yellow",
            "green",
            "brown",
            "gray"
         ]
      }
   ]
}
        DATA
      end
    end
  end
end

# rubocop:enable Lint/RedundantCopDisableDirective, Layout/LineLength, Layout/HeredocIndentation
