# frozen_string_literal: true

module Engine
  module Game
    module G1866
      module Entities
        COMPANIES = [
          {
            name: 'Stockton & Darlington',
            sym: 'P1',
            value: 0,
            revenue: 0,
            desc: 'Gives priority in ISR. Closes at end of IAR when ISR priority determined.',
            abilities: [],
            color: nil,
          },
          {
            name: 'Great Britain',
            sym: 'P2',
            value: 0,
            revenue: 10,
            desc: 'Concession for Great Britain National Company. Closes when concession exercised to purchase '\
                  'company.',
            abilities: [
              {
                type: 'exchange',
                corporations: ['GBN'],
                owner_type: 'player',
                from: 'par',
              },
            ],
            color: nil,
          },
          {
            name: 'France',
            sym: 'P3',
            value: 0,
            revenue: 10,
            desc: 'Concession for France National Company. Closes when concession exercised to purchase company.',
            abilities: [
              {
                type: 'exchange',
                corporations: ['FN'],
                owner_type: 'player',
                from: 'par',
              },
            ],
            color: nil,
          },
          {
            name: 'Austro-Hungarian Empire',
            sym: 'P4',
            value: 0,
            revenue: 10,
            desc: 'Concession for Austro-Hungarian Empire Company. Closes when concession exercised to purchase '\
                  'company.',
            abilities: [
              {
                type: 'exchange',
                corporations: ['AHN'],
                owner_type: 'player',
                from: 'par',
              },
            ],
            color: nil,
          },
          {
            name: 'Luxembourg',
            sym: 'P5',
            value: 0,
            revenue: 10,
            desc: 'Revenue paid to owning player. Can be acquired by a public company. When held by a public company '\
                  'gives that company operating rights in Luxembourg.',
            abilities: [],
            color: nil,
          },
          {
            name: 'Stock turn token',
            sym: 'ST1',
            value: 0,
            revenue: 0,
            desc: 'Give the player the ability to purchase Stock turn tokens during ISR and as a Stock turn token '\
                  'action.',
            abilities: [],
            color: nil,
          },
          {
            name: 'Stock turn token',
            sym: 'ST2',
            value: 0,
            revenue: 0,
            desc: 'Give the player the ability to purchase Stock turn tokens during ISR and as a Stock turn token '\
                  'action.',
            abilities: [],
            color: nil,
          },
          {
            name: 'Stock turn token',
            sym: 'ST3',
            value: 0,
            revenue: 0,
            desc: 'Give the player the ability to purchase Stock turn tokens during ISR and as a Stock turn token '\
                  'action.',
            abilities: [],
            color: nil,
          },
          {
            name: 'Stock turn token',
            sym: 'ST4',
            value: 0,
            revenue: 0,
            desc: 'Give the player the ability to purchase Stock turn tokens during ISR and as a Stock turn token '\
                  'action.',
            abilities: [],
            color: nil,
          },
          {
            name: 'Stock turn token',
            sym: 'ST5',
            value: 0,
            revenue: 0,
            desc: 'Give the player the ability to purchase Stock turn tokens during ISR and as a Stock turn token '\
                  'action.',
            abilities: [],
            color: nil,
          },
          {
            name: 'Stock turn token',
            sym: 'ST6',
            value: 0,
            revenue: 0,
            desc: 'Give the player the ability to purchase Stock turn tokens during ISR and as a Stock turn token '\
                  'action.',
            abilities: [],
            color: nil,
          },
          {
            name: 'Stock turn token',
            sym: 'ST7',
            value: 0,
            revenue: 0,
            desc: 'Give the player the ability to purchase Stock turn tokens during ISR and as a Stock turn token '\
                  'action.',
            abilities: [],
            color: nil,
          },
        ].freeze

        CORPORATIONS = [
          {
            sym: 'GBN',
            name: 'Great Britain National',
            logo: '1866/GBN',
            tokens: [],
            type: 'national',
            float_percent: 20,
            always_market_price: true,
            color: '#fde2c5',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: 'FN',
            name: 'France National',
            logo: '1866/FN',
            tokens: [],
            type: 'national',
            float_percent: 20,
            always_market_price: true,
            color: '#fffbcc',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: 'AHN',
            name: 'Austro-Hungary National',
            logo: '1866/AHN',
            tokens: [],
            type: 'national',
            float_percent: 20,
            always_market_price: true,
            color: '#e2ceb6',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: 'GN',
            name: 'Germany National',
            logo: '1866/GN',
            tokens: [],
            type: 'national',
            float_percent: 20,
            always_market_price: true,
            color: '#d0c1de',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: 'IN',
            name: 'Italy National',
            logo: '1866/IN',
            tokens: [],
            type: 'national',
            float_percent: 20,
            always_market_price: true,
            color: '#ff7ffe',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: 'ASC',
            name: 'Atlantic Shipping Company',
            logo: '1866/ASC',
            tokens: [],
            type: 'shipping',
            float_percent: 10,
            shares: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
            always_market_price: true,
            color: '#00b0f0',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: 'MSC',
            name: 'Mediterranean Shipping Company',
            logo: '1866/MSC',
            tokens: [],
            type: 'shipping',
            float_percent: 10,
            shares: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
            always_market_price: true,
            color: '#04a94f',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: 'BMN',
            name: 'Belgium Minor National',
            logo: '1866/BMN',
            tokens: [],
            type: 'minor',
            float_percent: 40,
            shares: [40, 20, 20, 20],
            always_market_price: true,
            color: '#7eff80',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: 'NMN',
            name: 'Netherlands Minor National',
            logo: '1866/NMN',
            tokens: [],
            type: 'minor',
            float_percent: 40,
            shares: [40, 20, 20, 20],
            always_market_price: true,
            color: '#f8931d',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: 'SWMN',
            name: 'Switzerland Minor National',
            logo: '1866/SWMN',
            tokens: [],
            type: 'minor',
            float_percent: 40,
            shares: [40, 20, 20, 20],
            always_market_price: true,
            color: '#d6cf81',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: 'SPMN',
            name: 'Spain Minor National',
            logo: '1866/SPMN',
            tokens: [],
            type: 'minor',
            float_percent: 40,
            shares: [40, 20, 20, 20],
            always_market_price: true,
            color: '#bea481',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: 'G1',
            name: 'Germany Prussia Minor National',
            logo: '1866/G1',
            tokens: [],
            type: 'minor',
            float_percent: 50,
            shares: [50, 25, 25],
            always_market_price: true,
            color: '#d0c1de',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: 'G2',
            name: 'Germany Hannover Minor National',
            logo: '1866/G2',
            tokens: [],
            type: 'minor',
            float_percent: 50,
            shares: [50, 25, 25],
            always_market_price: true,
            color: '#a764a9',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: 'G3',
            name: 'Germany Bavaria Minor National',
            logo: '1866/G3',
            tokens: [],
            type: 'minor',
            float_percent: 50,
            shares: [50, 25, 25],
            always_market_price: true,
            color: '#8781bf',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: 'G4',
            name: 'Germany Wurttemburg Minor National',
            logo: '1866/G4',
            tokens: [],
            type: 'minor',
            float_percent: 50,
            shares: [50, 25, 25],
            always_market_price: true,
            color: '#855fa8',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: 'G5',
            name: 'Germany Saxony Minor National',
            logo: '1866/G5',
            tokens: [],
            type: 'minor',
            float_percent: 50,
            shares: [50, 25, 25],
            always_market_price: true,
            color: '#bd8dbf',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: 'I1',
            name: 'Italy Kgdm 2 Sicilies Minor National',
            logo: '1866/I1',
            tokens: [],
            type: 'minor',
            float_percent: 50,
            shares: [50, 25, 25],
            always_market_price: true,
            color: '#ffcfe5',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: 'I2',
            name: 'Italy Sardinia Minor National',
            logo: '1866/I2',
            tokens: [],
            type: 'minor',
            float_percent: 50,
            shares: [50, 25, 25],
            always_market_price: true,
            color: '#f41097',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: 'I3',
            name: 'Italy Lom-Venetia Minor National',
            logo: '1866/I3',
            tokens: [],
            type: 'minor',
            float_percent: 50,
            shares: [50, 25, 25],
            always_market_price: true,
            color: '#ff7ffe',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: 'I4',
            name: 'Italy Papal States Minor National',
            logo: '1866/I4',
            tokens: [],
            type: 'minor',
            float_percent: 50,
            shares: [50, 25, 25],
            always_market_price: true,
            color: '#f26eaa',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: 'I5',
            name: 'Italy Tuscany Minor National',
            logo: '1866/I5',
            tokens: [],
            type: 'minor',
            float_percent: 50,
            shares: [50, 25, 25],
            always_market_price: true,
            color: '#f996c3',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: 'LNWR',
            name: 'London and North Western Railway',
            logo: '1866/LNWR',
            tokens: [0, 20, 40, 60, 80, 100],
            type: 'major',
            float_percent: 40,
            shares: [40, 20, 20, 20],
            always_market_price: true,
            coordinates: 'D4',
            color: '#0072bc',
            text_color: 'white',
            reservation_color: nil,
          },
          {
            sym: 'GWR',
            name: 'Great Western Railway',
            logo: '1866/GWR',
            tokens: [0, 20, 40, 60, 80, 100],
            type: 'major',
            float_percent: 40,
            shares: [40, 20, 20, 20],
            always_market_price: true,
            coordinates: 'F2',
            color: '#007236',
            text_color: 'white',
            reservation_color: nil,
          },
          {
            sym: 'NBR',
            name: 'North British Railway',
            logo: '1866/NBR',
            tokens: [0, 20, 40, 60, 80, 100],
            type: 'major',
            float_percent: 40,
            shares: [40, 20, 20, 20],
            always_market_price: true,
            coordinates: 'A3',
            color: '#7d4900',
            text_color: 'white',
            reservation_color: nil,
          },
          {
            sym: 'PLM',
            name: 'Chemins de fer de Paris à Lyon et à la Méditerranée',
            logo: '1866/PLM',
            tokens: [0, 0, 20, 40, 60, 80],
            type: 'major',
            float_percent: 40,
            shares: [40, 20, 20, 20],
            always_market_price: true,
            coordinates: %w[M9 P10],
            color: '#630460',
            text_color: 'white',
            reservation_color: nil,
          },
          {
            sym: 'MIDI',
            name: 'Chemin de Fer du Midi',
            logo: '1866/MIDI',
            tokens: [0, 20, 40, 60, 80, 100],
            type: 'major',
            float_percent: 40,
            shares: [40, 20, 20, 20],
            always_market_price: true,
            coordinates: 'N2',
            color: '#acd473',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: 'OU',
            name: 'Compagnie des chemins de fer del`Ouest',
            logo: '1866/OU',
            tokens: [0, 20, 40, 60, 80, 100],
            type: 'major',
            float_percent: 40,
            shares: [40, 20, 20, 20],
            always_market_price: true,
            coordinates: 'I5',
            color: '#fbaf5d',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: 'KPS',
            name: 'Königlich Preußische Staatseisenbahnen',
            logo: '1866/KPS',
            tokens: [0, 20, 40, 60, 80, 100],
            type: 'major',
            float_percent: 40,
            shares: [40, 20, 20, 20],
            always_market_price: true,
            coordinates: 'F22',
            color: '#000000',
            text_color: 'white',
            reservation_color: nil,
          },
          {
            sym: 'BY',
            name: 'Bayrische Staatsbahn',
            logo: '1866/BY',
            tokens: [0, 20, 40, 60, 80, 100],
            type: 'major',
            float_percent: 40,
            shares: [40, 20, 20, 20],
            always_market_price: true,
            coordinates: 'K19',
            color: '#6dd0f7',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: 'KHS',
            name: 'Königlich Hannöversche Staatseisenbahnen',
            logo: '1866/KHS',
            tokens: [0, 20, 40, 60, 80, 100],
            type: 'major',
            float_percent: 40,
            shares: [40, 20, 20, 20],
            always_market_price: true,
            coordinates: 'F18',
            color: '#fff200',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: 'SB',
            name: 'Sudbahn',
            logo: '1866/SB',
            tokens: [0, 20, 40, 60, 80, 100],
            type: 'major',
            float_percent: 40,
            shares: [40, 20, 20, 20],
            always_market_price: true,
            coordinates: 'N22',
            color: '#f26522',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: 'BH',
            name: 'Bosnia-Herzegowinische Landesbahn',
            logo: '1866/BH',
            tokens: [0, 20, 40, 60, 80, 100],
            type: 'major',
            float_percent: 40,
            shares: [40, 20, 20, 20],
            always_market_price: true,
            coordinates: 'Q25',
            color: '#ff0000',
            text_color: 'white',
            reservation_color: nil,
          },
          {
            sym: 'FNR',
            name: 'Emperor Ferdinand Northern Railway',
            logo: '1866/FNR',
            tokens: [0, 20, 40, 60, 80, 100],
            type: 'major',
            float_percent: 40,
            shares: [40, 20, 20, 20],
            always_market_price: true,
            coordinates: 'L24',
            color: '#a3d49c',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: 'SSFL',
            name: 'Societa per la Strada Ferrata Leopolda',
            logo: '1866/SSFL',
            tokens: [0, 20, 40, 60, 80, 100],
            type: 'major',
            float_percent: 40,
            shares: [40, 20, 20, 20],
            always_market_price: true,
            coordinates: 'Q17',
            color: '#48e293',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: 'IFT',
            name: 'Impresa Ferroviaria Trinacria',
            logo: '1866/IFT',
            tokens: [0, 20, 40, 60, 80, 100],
            type: 'major',
            float_percent: 40,
            shares: [40, 20, 20, 20],
            always_market_price: true,
            coordinates: 'V20',
            color: '#ff7ffe',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: 'SFAI',
            name: 'Società per le strade ferrate dell`Alta Italia',
            logo: '1866/SFAI',
            tokens: [0, 20, 40, 60, 80, 100],
            type: 'major',
            float_percent: 40,
            shares: [40, 20, 20, 20],
            always_market_price: true,
            coordinates: 'N14',
            color: '#a4610a',
            text_color: 'white',
            reservation_color: nil,
          },
          {
            sym: 'SBB',
            name: 'Chemins de fer fédéraux suisses',
            logo: '1866/SBB',
            tokens: [0, 20, 40, 60, 80, 100],
            type: 'major',
            float_percent: 40,
            shares: [40, 20, 20, 20],
            always_market_price: true,
            coordinates: 'L16',
            color: '#9e0b0f',
            text_color: 'white',
            reservation_color: nil,
          },
          {
            sym: 'AVTR',
            name: 'Almanza, Valencia & Tarragona Railway',
            logo: '1866/AVTR',
            tokens: [0, 20, 40, 60, 80, 100],
            type: 'major',
            float_percent: 40,
            shares: [40, 20, 20, 20],
            always_market_price: true,
            coordinates: 'S1',
            color: '#aba000',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: 'GL',
            name: 'Chemins de Fer Guillaume Luxembourg',
            logo: '1866/GL',
            tokens: [0, 20, 40, 60, 80, 100],
            type: 'major',
            float_percent: 40,
            shares: [40, 20, 20, 20],
            always_market_price: true,
            coordinates: 'I11',
            color: '#ffcd03',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: 'NRS',
            name: 'Nederlandsche Rhijnspoorweg-Maatschappij',
            logo: '1866/NRS',
            tokens: [0, 20, 40, 60, 80, 100],
            type: 'major',
            float_percent: 40,
            shares: [40, 20, 20, 20],
            always_market_price: true,
            coordinates: 'F12',
            color: '#d54427',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: 'B',
            name: 'Chemin De Fer de L’Etat Belge',
            logo: '1866/B',
            tokens: [0, 20, 40, 60, 80, 100],
            type: 'major',
            float_percent: 40,
            shares: [40, 20, 20, 20],
            always_market_price: true,
            coordinates: 'H10',
            color: '#e2e2e2',
            text_color: 'black',
            reservation_color: nil,
          },
        ].freeze
      end
    end
  end
end
