# frozen_string_literal: true

module Engine
  module Game
    module G1837
      module Entities
        COMPANIES = [
          {
            name: 'Semmering Railway',
            sym: 'Semmering',
            desc: 'Mountain Railway (H16)',
            value: 100,
            revenue: 5,
            abilities: [
              { type: 'no_buy' },
              {
                type: 'tile_lay',
                owner_type: 'player',
                when: 'owning_player_track',
                consume_tile_lay: true,
                reachable: true,
                special: false,
                discount: 110,
                hexes: %w[H16],
                tiles: %w[7 8 9],
                count: 1,
              },
              {
                type: 'blocks_hexes',
                remove: '3',
                hexes: %w[H16],
              },
            ],
          },
          {
            name: 'Karst Railway',
            sym: 'Karst',
            desc: 'Mountain Railway (K13)',
            value: 70,
            revenue: 10,
            abilities: [
              { type: 'no_buy' },
              {
                type: 'tile_lay',
                owner_type: 'player',
                when: 'owning_player_track',
                consume_tile_lay: true,
                reachable: true,
                special: false,
                discount: 110,
                hexes: %w[K13],
                tiles: %w[3 4 58],
                count: 1,
              },
              {
                type: 'blocks_hexes',
                remove: '3',
                hexes: %w[K13],
              },
            ],
          },
          {
            name: 'Brenner Railway',
            sym: 'Brenner',
            desc: 'Mountain Railway (J6)',
            value: 90,
            revenue: 15,
            abilities: [
              { type: 'no_buy' },
              {
                type: 'tile_lay',
                owner_type: 'player',
                when: 'owning_player_track',
                consume_tile_lay: true,
                reachable: true,
                special: false,
                discount: 110,
                hexes: %w[J6],
                tiles: %w[7 8 9],
                count: 1,
              },
              {
                type: 'blocks_hexes',
                remove: '3',
                hexes: %w[J6],
              },
            ],
          },
          {
            name: 'Arlberg Railway',
            sym: 'Arlberg',
            desc: 'Mountain Railway (I5)',
            value: 135,
            revenue: 20,
            abilities: [
              { type: 'no_buy' },
              {
                type: 'tile_lay',
                owner_type: 'player',
                when: 'owning_player_track',
                consume_tile_lay: true,
                reachable: true,
                special: false,
                discount: 110,
                hexes: %w[I5],
                tiles: %w[7 8 9],
                count: 1,
              },
              {
                type: 'blocks_hexes',
                remove: '3',
                hexes: %w[I5],
              },
            ],
          },
          {
            name: 'Karawanken Railway',
            sym: 'Karawanken',
            desc: 'Mountain Railway (J12)',
            value: 120,
            revenue: 25,
            abilities: [
              { type: 'no_buy' },
              {
                type: 'tile_lay',
                owner_type: 'player',
                when: 'owning_player_track',
                consume_tile_lay: true,
                reachable: true,
                special: false,
                discount: 110,
                hexes: %w[J12],
                tiles: %w[1 2 55 56 69],
                count: 1,
              },
              {
                type: 'blocks_hexes',
                remove: '3',
                hexes: %w[J12],
              },
            ],
          },
          {
            name: 'Wocheiner Railway',
            sym: 'Wocheiner',
            desc: 'Mountain Railway (K11)',
            value: 50,
            revenue: 30,
            abilities: [
              { type: 'no_buy' },
              {
                type: 'tile_lay',
                owner_type: 'player',
                when: 'owning_player_track',
                consume_tile_lay: true,
                reachable: true,
                special: false,
                discount: 110,
                hexes: %w[K11],
                tiles: %w[7 8 9],
                count: 1,
              },
              {
                type: 'blocks_hexes',
                remove: '3',
                hexes: %w[K11],
              },
            ],
          },
          {
            name: 'Tauern Railway',
            sym: 'Tauern',
            desc: 'Mountain Railway (J10)',
            value: 70,
            revenue: 35,
            abilities: [
              { type: 'no_buy' },
              {
                type: 'tile_lay',
                owner_type: 'player',
                when: 'owning_player_track',
                consume_tile_lay: true,
                reachable: true,
                special: false,
                discount: 110,
                hexes: %w[J10],
                tiles: %w[7 8 9],
                count: 1,
              },
              {
                type: 'blocks_hexes',
                remove: '3',
                hexes: %w[J10],
              },
            ],
          },
        ].freeze

        MINORS = [
          {
            name: 'Pilsen-Priesen Railway',
            sym: 'EPP',
            logo: '1837/epp',
            tokens: [0],
            coordinates: 'E11',
            color: :black,
          },
          {
            name: 'Reichenberg-Gablonz-Tannwalder Railway',
            sym: 'RGTE',
            logo: '1837/rgte',
            tokens: [0],
            coordinates: 'A13',
            color: :black,
          },
          {
            name: 'Oderberg-Dombran Railway',
            sym: 'EOD',
            logo: '1837/eod',
            tokens: [0],
            coordinates: 'C19',
            color: :black,
          },
          {
            name: 'Karwin-Teschen Railway',
            sym: 'EKT',
            logo: '1837/ekt',
            tokens: [0],
            coordinates: 'C21',
            color: :black,
          },
          {
            name: 'Mosty-Lemberg Railway',
            sym: 'MLB',
            logo: '1837/mlb',
            tokens: [0],
            coordinates: 'B32',
            color: :black,
          },
          {
            name: 'Zarnesti-Kronstadt Railway',
            sym: 'ZKB',
            logo: '1837/zkb',
            tokens: [0],
            coordinates: 'J34',
            color: :black,
          },
          {
            name: 'Simeria-Petroseni Railway',
            sym: 'SPB',
            logo: '1837/spb',
            tokens: [0],
            coordinates: 'K31',
            color: :black,
          },
          {
            name: 'Lugoj-Resita Railway',
            sym: 'LRB',
            logo: '1837/lrb',
            tokens: [0],
            coordinates: 'L30',
            color: :black,
          },
          {
            name: 'Bosna-Bahn',
            sym: 'BB',
            logo: '1837/bb',
            tokens: [0],
            coordinates: 'P20',
            color: :black,
          },
          {
            name: 'Hatvan-Salgotarjan Railway',
            sym: 'EHS',
            logo: '1837/ebs',
            tokens: [0],
            coordinates: 'F26',
            color: :black,
          },
          {
            name: 'Vienna-Gloggnitzer Railway',
            sym: 'SD1',
            logo: '1837/sd1',
            tokens: [0],
            coordinates: 'G17',
            city: 0,
            color: :orange,
          },
          {
            name: 'Kärntner Railway',
            sym: 'SD2',
            logo: '1837/sd2',
            tokens: [0],
            coordinates: 'J16',
            color: :orange,
          },
          {
            name: 'North Tyrol Railway',
            sym: 'SD3',
            logo: '1837/sd3',
            tokens: [0],
            coordinates: 'I7',
            color: :orange,
          },
          {
            name: 'South Tyrol Railway',
            sym: 'SD4',
            logo: '1837/sd4',
            tokens: [0],
            coordinates: 'K5',
            color: :orange,
          },
          {
            name: 'Venice-Lombardy Railway',
            sym: 'SD5',
            logo: '1837/sd5',
            tokens: [0],
            coordinates: 'L2',
            color: :orange,
          },
          {
            name: 'Kaiser Ferdinand North Railway',
            sym: 'KK1',
            logo: '1837/kk1',
            tokens: [0],
            coordinates: 'G17',
            city: 3,
            color: :brown,
          },
          {
            name: 'Kaiserin Elisabeth-Railway',
            sym: 'KK2',
            logo: '1837/kk2',
            tokens: [0],
            coordinates: 'G17',
            city: 1,
            color: :brown,
          },
          {
            name: 'Kaiser Franz Joseph-Railway',
            sym: 'KK3',
            logo: '1837/kk3',
            tokens: [0],
            coordinates: 'G17',
            city: 2,
            color: :brown,
          },
          {
            name: 'Pest-Waitzen Railway',
            sym: 'UG1',
            logo: '1837/ug1',
            tokens: [0],
            coordinates: 'H22',
            city: 1,
            color: :pink,
          },
          {
            name: 'Mohacs-Fünfkirchener Railway',
            sym: 'UG2',
            logo: '1837/ug2',
            tokens: [0],
            coordinates: 'K21',
            color: :pink,
          },
          {
            name: 'Pest-Czegled Railway',
            sym: 'UG3',
            logo: '1837/ug3',
            tokens: [0],
            coordinates: 'H22',
            city: 0,
            color: :pink,
          },
        ].freeze

        CORPORATIONS = [
          {
            name: 'Bohemian Commercial Railway',
            sym: 'BK',
            logo: '1837/bk',
            simple_logo: '1837/bk.alt',
            tokens: [0, 20, 40],
            float_percent: 50,
            type: 'major',
            coordinates: 'C11',
            color: :blue,
          },
          {
            name: 'Moravian-Silesian Railway',
            sym: 'MS',
            logo: '1837/ms',
            simple_logo: '1837/ms.alt',
            tokens: [0, 20, 40],
            float_percent: 50,
            type: 'major',
            coordinates: 'E17',
            color: :yellow,
            text_color: :black,
          },
          {
            name: 'Bosnia-Herzegovina Railway',
            sym: 'BH',
            logo: '1837/bh',
            simple_logo: '1837/bh.alt',
            tokens: [0, 20, 40],
            float_percent: 50,
            type: 'major',
            coordinates: 'N20',
            color: :red,
          },
          {
            sym: 'CL',
            name: 'Carl Ludwig’s Railway',
            logo: '1837/cl',
            simple_logo: '1837/cl.alt',
            tokens: [0, 20, 40],
            float_percent: 50,
            type: 'major',
            coordinates: 'C33',
            color: :black,
          },
          {
            name: 'Tisza Railway',
            sym: 'TI',
            logo: '1837/ti',
            simple_logo: '1837/ti.alt',
            tokens: [0, 20, 40],
            float_percent: 50,
            type: 'major',
            coordinates: 'F28',
            color: :lightblue,
          },
          {
            name: 'Galician Transverse Railway',
            sym: 'GT',
            logo: '1837/gt',
            simple_logo: '1837/gt.alt',
            tokens: [0, 20, 40],
            float_percent: 50,
            type: 'major',
            coordinates: 'D36',
            color: :green,
          },
          {
            name: 'Transylvanian Railway',
            sym: 'TR',
            logo: '1837/tr',
            simple_logo: '1837/tr.alt',
            tokens: [0, 20, 40],
            float_percent: 50,
            type: 'major',
            coordinates: 'J36',
            color: :lightgreen,
          },
          {
            name: 'Southern Railway',
            sym: 'SD',
            logo: '1837/sd',
            simple_logo: '1837/sd.alt',
            shares: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
            tokens: [],
            type: 'national',
            floatable: false,
            color: :orange,
          },
          {
            name: 'Imperial Royal Austrian State Railways',
            sym: 'KK',
            logo: '1837/kk',
            simple_logo: '1837/kk.alt',
            shares: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
            tokens: [],
            type: 'national',
            floatable: false,
            color: :brown,
          },
          {
            name: 'Hungarian National Railway',
            sym: 'UG',
            logo: '1837/ug',
            simple_logo: '1837/ug.alt',
            shares: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
            tokens: [],
            type: 'national',
            floatable: false,
            color: :pink,
          },
        ].freeze
      end
    end
  end
end
