# frozen_string_literal: true

module Engine
  module Game
    module G18TS
      module Entities
        UNIT1_COMPANIES = [
          {
            name: "Montresor's Tramway",
            sym: 'MT',
            value: 30,
            revenue: 5,
            color: :Green,
          },
          {
            name: 'The Associates of the New York & Elizabethport Ferry Company',
            sym: 'NY&E',
            value: 75,
            revenue: 12,
            color: :Green,
          },
          {
            name: 'Leiper Railroad',
            sym: 'LR',
            value: 130,
            revenue: 20,
            color: :Green,
          },
          {
            name: 'New Jersey Railroad Company',
            sym: 'NJR',
            value: 160,
            revenue: 25,
            color: :Green,
          },
          {
            name: 'Lehigh Coal and Navigation Company',
            sym: 'LC',
            value: 210,
            revenue: 30,
            color: :Green,
          },
        ].freeze

        UNIT2_COMPANIES = [
          {
            name: "Montresor's Tramway",
            sym: 'MT',
            value: 30,
            revenue: 5,
            color: :Green,
          },
          {
            name: 'Schuylkill and Susquehanna Navigation Company',
            sym: 'SSN',
            value: 60,
            revenue: 10,
            color: :Green,
          },
          {
            name: 'The Associates of the New York & Elizabethport Ferry Company',
            sym: 'NY&E',
            value: 75,
            revenue: 12,
            color: :Green,
          },
          {
            name: 'New Jersey Railroad Company',
            sym: 'NJR',
            value: 160,
            revenue: 25,
            color: :Green,
          },
          {
            name: 'Lehigh Coal and Navigation Company',
            sym: 'LC',
            value: 210,
            revenue: 30,
            color: :Green,
          },
        ].freeze

        UNIT3_COMPANIES = [
          {
            name: "Montresor's Tramway",
            sym: 'MT',
            value: 30,
            revenue: 5,
            color: :Green,
          },
          {
            name: 'Schuylkill and Susquehanna Navigation Company',
            sym: 'SSN',
            value: 60,
            revenue: 10,
            color: :Green,
          },
          {
            name: 'The Associates of the New York & Elizabethport Ferry Company',
            sym: 'NY&E',
            value: 75,
            revenue: 12,
            color: :Green,
          },
          {
            name: 'Leiper Railroad',
            sym: 'LR',
            value: 130,
            revenue: 20,
            color: :Green,
          },
          {
            name: 'New Jersey Railroad Company',
            sym: 'NJR',
            value: 160,
            revenue: 25,
            color: :Green,
          },
          {
            name: 'Lehigh Coal and Navigation Company',
            sym: 'LC',
            value: 210,
            revenue: 30,
            color: :Green,
          },
        ].freeze

        UNIT1_CORPORATIONS = [
          {
            sym: 'PRR',
            name: 'Pennsylvania Railroad',
            logo: '18_ts/PRR',
            simple_logo: '18_ts/PRR.alt',
            capitalization: :full,
            max_ownership_percent: 100,
            tokens: [0, 0, 40, 100, 100],
            coordinates: ['O17','R12'],
            city: 0,
            color: '#D83512',
            text_color: '#ffffff',
            abilities: [{ type: 'blocks_hexes', owner_type: nil, hexes: ['S11'] }],
          },
          {
            sym: 'CNJ',
            name: 'Central Railroad of New Jersey',
            logo: '18_ts/CNJ',
            simple_logo: '18_ts/CNJ.alt',
            capitalization: :full,
            max_ownership_percent: 100,
            tokens: [0, 0, 40, 100, 100],
            coordinates: ['T14','W21'],
            city: 0,
            color: '#004225',
            text_color: '#ffffff',
            abilities: [{ type: 'blocks_hexes', owner_type: nil, hexes: ['T10'] }],
          },    
          {
            sym: 'RR',
            name: 'Reading Railroad',
            logo: '18_ts/RR',
            simple_logo: '18_ts/RR.alt',
            capitalization: :full,
            max_ownership_percent: 100,
            tokens: [0, 40, 100, 100],
            coordinates: 'O13',
            city: 0,
            color: '#be2ed6',
            text_color: '#ffffff',
            abilities: [{ type: 'blocks_hexes', owner_type: nil, hexes: ['O13','P14'] }],
          },
          {
            sym: 'P&E',
            name: 'Phialdelphia and Erie Railroad',
            logo: '18_ts/PE',
            simple_logo: '18_ts/PE.alt',
            capitalization: :full,
            max_ownership_percent: 100,
            tokens: [0, 40, 100, 100],
            coordinates: 'J14',
            city: 0,
            color: '#00ff00',
            text_color: '#000000',
            abilities: [{ type: 'blocks_hexes', owner_type: nil, hexes: ['J14'] }],
          },
          {
            sym: 'NYC',
            name: 'New York Central Railroad',
            logo: '18_ts/NYC',
            simple_logo: '18_ts/NYC.alt',
            capitalization: :full,
            max_ownership_percent: 100,
            tokens: [0, 40, 100, 100],
            coordinates: 'T8',
            city: 3,
            color: '#000000',
            text_color: '#ffffff',
            abilities: [{ type: 'blocks_hexes', owner_type: nil, hexes: ['S5'] }],
          },
          {
            sym: 'C&A',
            name: 'Camden and Amboy Railroad',
            logo: '18_ts/C&A',
            simple_logo: '18_ts/C&A.alt',
            capitalization: :full,
            max_ownership_percent: 100,
            tokens: [0, 40, 100, 100],
            coordinates: 'T8',
            city: 5,
            color: '#d0f0c0',
            text_color: '#000000',
            abilities: [{ type: 'blocks_hexes', owner_type: nil, hexes: ['U9'] }],
          },
          {
            sym: 'NCRY',
            name: 'Northern Central Railway',
            logo: '18_ts/NCRY',
            simple_logo: '18_ts/NCRY.alt',
            capitalization: :full,
            max_ownership_percent: 100,
            tokens: [0, 40, 100],
            coordinates: 'M13',
            city: 0,
            color: '#89cff0',
            text_color: '#000000',
          },
          {
            sym: 'LC&SC',
            name: 'Lewisburg, Centre and Spruce Creek Railroad',
            logo: '18_ts/LCSC',
            simple_logo: '18_ts/LCSC.alt',
            capitalization: :full,
            max_ownership_percent: 100,
            tokens: [0, 40, 100],
            coordinates: 'M13',
            city: 1,
            color: '#228c22',
            text_color: '#ffffff',
          },
          {
            sym: 'LV',
            name: 'Lehigh Valley Railroad',
            logo: '18_ts/LV',
            simple_logo: '18_ts/LV.alt',
            capitalization: :full,
            max_ownership_percent: 100,
            tokens: [0, 40, 100],
            coordinates: 'M17',
            city: 0,
            color: '#6c0ba9',
            text_color: '#ffffff',
            abilities: [{ type: 'blocks_hexes', owner_type: nil, hexes: ['L18'] }],
          },
          {
            sym: 'NH',
            name: 'New York, New Haven and Hartford Railroad',
            logo: '18_ts/NH',
            simple_logo: '18_ts/NH.alt',
            capitalization: :full,
            max_ownership_percent: 100,
            tokens: [0, 40, 100, 100],
            coordinates: 'U5',
            city: 0,
            color: '#d98e3a',
            text_color: '#000000',
            abilities: [],
          },
          {
            sym: 'LI',
            name: 'Long Island Rail Road',
            logo: '18_ts/LI',
            simple_logo: '18_ts/LI.alt',
            capitalization: :full,
            max_ownership_percent: 100,
            tokens: [0, 40, 100],
            coordinates: 'V8',
            city: 0,
            color: '#ffef00',
            text_color: 'black',
            abilities: [{ type: 'blocks_hexes', owner_type: nil, hexes: ['V8'] }],
          },
          {
          sym: 'IRT',
          name: 'Interborough Rapid Transit Company',
          logo: '18_ts/IRT',
          simple_logo: '18_ts/IRT.alt',
          capitalization: :incremental,
          float_percent: 40,
          shares: [40, 20, 20, 20],
          price_percent: 10,
          max_ownership_percent: 100,
          tokens: [0],
          coordinates: 'T6',
          color: '#1b967a',
          text_color: '#ffffff',
        },
        {
          sym: 'SRC',
          name: 'Strasburg Rail Road',
          logo: '18_ts/SRC',
          simple_logo: '18_ts/SRC.alt',
          capitalization: :incremental,
          float_percent: 40,
          shares: [40, 20, 20, 20],
          price_percent: 10,
          max_ownership_percent: 100,
          tokens: [0],
          coordinates: 'P20',
          color: '#48260d',
          text_color: '#ffffff',
          abilities: [{ type: 'blocks_hexes', owner_type: nil, hexes: ['P20'] }],
        },
        {
          sym: 'ACR',
          name: 'Atlantic City Railroad',
          logo: '18_ts/ACR',
          simple_logo: '18_ts/ACR.alt',
          capitalization: :incremental,
          float_percent: 40,
          shares: [40, 20, 20, 20],
          price_percent: 10,
          max_ownership_percent: 100,
          tokens: [0],
          coordinates: 'U19',
          color: '#4666ff',
          text_color: '#ffffff',
        },
        {
          sym: 'L&W',
          name: 'Lackawanna and Western Railroad',
          logo: '18_ts/LW',
          simple_logo: '18_ts/LW.alt',
          capitalization: :incremental,
          float_percent: 40,
          shares: [40, 20, 20, 20],
          price_percent: 10,
          max_ownership_percent: 100,
          tokens: [0],
          coordinates: 'O5',
          color: '#cc5500',
          text_color: '#ffffff',
        },
        {
          sym: 'CVRR',
          name: 'Cumberland Valley Railroad',
          logo: '18_ts/CVRR',
          simple_logo: '18_ts/CVRR.alt',
          capitalization: :incremental,
          float_percent: 40,
          shares: [40, 20, 20, 20],
          price_percent: 10,
          max_ownership_percent: 100,
          tokens: [0],
          coordinates: 'K19',
          color: '#fafad2',
          text_color: '#000000',
        },
        {
          sym: 'DS',
          name: 'Delaware Shore Railroad',
          logo: '18_ts/DS',
          simple_logo: '18_ts/DS.alt',
          capitalization: :incremental,
          float_percent: 40,
          shares: [40, 20, 20, 20],
          price_percent: 10,
          max_ownership_percent: 100,
          tokens: [0],
          coordinates: 'S19',
          color: '#ffa6c9',
          text_color: '#000000',
        },
        {
          sym: 'P&L',
          name: 'Portsmouth and Lancaster Railroad',
          logo: '18_ts/PL',
          simple_logo: '18_ts/PL.alt',
          capitalization: :incremental,
          float_percent: 40,
          shares: [40, 20, 20, 20],
          price_percent: 10,
          max_ownership_percent: 100,
          tokens: [0],
          coordinates: 'O15',
          color: '#404040',
          text_color: '#ffffff',
        },
        ].freeze

        UNIT2_CORPORATIONS = [
          {
            sym: 'PRR',
            name: 'Pennsylvania Railroad',
            logo: '18_ts/PRR',
            simple_logo: '18_ts/PRR.alt',
            capitalization: :full,
            max_ownership_percent: 100,
            tokens: [0, 40, 100, 100, 100],
            coordinates: ['O17'],
            city: 0,
            color: '#D83512',
            text_color: '#ffffff',
            abilities: [{ type: 'blocks_hexes', owner_type: nil, hexes: ['S11'] }],
          },   
          {
            sym: 'RR',
            name: 'Reading Railroad',
            logo: '18_ts/RR',
            simple_logo: '18_ts/RR.alt',
            capitalization: :full,
            max_ownership_percent: 100,
            tokens: [0, 40, 100, 100],
            coordinates: 'O13',
            city: 0,
            color: '#be2ed6',
            text_color: '#ffffff',
          },
          {
            sym: 'P&E',
            name: 'Phialdelphia and Erie Railroad',
            logo: '18_ts/PE',
            simple_logo: '18_ts/PE.alt',
            capitalization: :full,
            max_ownership_percent: 100,
            tokens: [0, 40, 100, 100],
            coordinates: 'J14',
            city: 0,
            color: '#00ff00',
            text_color: '#000000',
            abilities: [{ type: 'blocks_hexes', owner_type: nil, hexes: ['J14'] }],
          },
          {
            sym: 'NCRY',
            name: 'Northern Central Railway',
            logo: '18_ts/NCRY',
            simple_logo: '18_ts/NCRY.alt',
            capitalization: :full,
            max_ownership_percent: 100,
            tokens: [0, 40, 100],
            coordinates: 'M13',
            city: 0,
            color: '#89cff0',
            text_color: '#000000',
          },
          {
            sym: 'LC&SC',
            name: 'Lewisburg, Centre and Spruce Creek Railroad',
            logo: '18_ts/LCSC',
            simple_logo: '18_ts/LCSC.alt',
            capitalization: :full,
            max_ownership_percent: 100,
            tokens: [0, 40, 100],
            coordinates: 'M13',
            city: 1,
            color: '#228c22',
            text_color: '#ffffff',
          },
          {
            sym: 'LV',
            name: 'Lehigh Valley Railroad',
            logo: '18_ts/LV',
            simple_logo: '18_ts/LV.alt',
            capitalization: :full,
            max_ownership_percent: 100,
            tokens: [0, 40, 100],
            coordinates: 'M17',
            city: 0,
            color: '#6c0ba9',
            text_color: '#ffffff',
            abilities: [{ type: 'blocks_hexes', owner_type: nil, hexes: ['L18'] }],
          },  
          {
            sym: 'B&O',
            name: 'Baltimore and Ohio Railroad',
            logo: '18_ts/BO',
            simple_logo: '18_ts/BO.alt',
            capitalization: :full,
            max_ownership_percent: 100,
            tokens: [0, 40, 100],
            coordinates: 'G21',
            city: 0,
            color: '#0047ab',
            text_color: '#ffffff',
            abilities: [{ type: 'blocks_hexes', owner_type: nil, hexes: ['H22'] }],
          },        
          {
          sym: 'CVRR',
          name: 'Cumberland Valley Railroad',
          logo: '18_ts/CVRR',
          simple_logo: '18_ts/CVRR.alt',
          capitalization: :incremental,
          float_percent: 40,
          shares: [40, 20, 20, 20],
          price_percent: 10,
          max_ownership_percent: 100,
          tokens: [0],
          coordinates: 'K19',
          color: '#fafad2',
          text_color: '#000000',
        },
        {
          sym: 'P&L',
          name: 'Portsmouth and Lancaster Railroad',
          logo: '18_ts/PL',
          simple_logo: '18_ts/PL.alt',
          capitalization: :incremental,
          float_percent: 40,
          shares: [40, 20, 20, 20],
          price_percent: 10,
          max_ownership_percent: 100,
          tokens: [0],
          coordinates: 'O15',
          color: '#404040',
          text_color: '#ffffff',
        }, 
        {
          sym: 'NC&F',
          name: 'New Castle and Franklin Railroad',
          logo: '18_ts/NCF',
          simple_logo: '18_ts/NCF.alt',
          capitalization: :incremental,
          float_percent: 40,
          shares: [40, 20, 20, 20],
          price_percent: 10,
          max_ownership_percent: 100,
          tokens: [0],
          coordinates: 'C15',
          city: 0,
          color: '#299617',
          text_color: '#000000',
        },
        {
          sym: 'OC&C',
          name: 'Oil City and Chicago Railroad',
          logo: '18_ts/OCC',
          simple_logo: '18_ts/OCC.alt',
          capitalization: :incremental,
          float_percent: 40,
          shares: [40, 20, 20, 20],
          price_percent: 10,
          max_ownership_percent: 100,
          tokens: [0],
          coordinates: 'C19',
          city: 0,
          color: '#ffd300',
          text_color: '#000000',
        },
        {
          sym: 'B&B',
          name: 'Bedford and Bridgeport Railroad',
          logo: '18_ts/BB',
          simple_logo: '18_ts/BB.alt',
          capitalization: :incremental,
          float_percent: 40,
          shares: [40, 20, 20, 20],
          price_percent: 10,
          max_ownership_percent: 100,
          tokens: [0],
          coordinates: 'J20',
          city: 0,
          color: '#00ffef',
          text_color: '#000000',
        },
        {
          sym: 'PW',
          name: 'Pittsburgh and Western Railroad',
          logo: '18_ts/PW',
          simple_logo: '18_ts/PW.alt',
          capitalization: :full,
          max_ownership_percent: 100,
          tokens: [0, 40, 100, 100],
          coordinates: 'G21',
          city: 1,
          color: '#7c4700',
          text_color: '#ffffff',
        },
        {
          sym: 'AV',
          name: 'Allegheny Valley Railroad',
          logo: '18_ts/AV',
          simple_logo: '18_ts/AV.alt',
          capitalization: :full,
          max_ownership_percent: 100,
          tokens: [0, 40, 100, 100],
          coordinates: 'G21',
          city: 2,
          color: '#001800',
          text_color: '#ffff00',
        },
        ].freeze

        UNIT3_CORPORATIONS = [
          {
            sym: 'PRR',
            name: 'Pennsylvania Railroad',
            logo: '18_ts/PRR',
            simple_logo: '18_ts/PRR.alt',
            capitalization: :full,
            max_ownership_percent: 100,
            tokens: [0, 0, 40, 100, 100],
            coordinates: ['O17','R12'],
            city: 0,
            color: '#D83512',
            text_color: '#ffffff',
            abilities: [{ type: 'blocks_hexes', owner_type: nil, hexes: ['S11'] }],
          },
          {
            sym: 'CNJ',
            name: 'Central Railroad of New Jersey',
            logo: '18_ts/CNJ',
            simple_logo: '18_ts/CNJ.alt',
            capitalization: :full,
            max_ownership_percent: 100,
            tokens: [0, 0, 40, 100, 100],
            coordinates: ['T14','W21'],
            city: 0,
            color: '#004225',
            text_color: '#ffffff',
            abilities: [{ type: 'blocks_hexes', owner_type: nil, hexes: ['T10'] }],
          },    
          {
            sym: 'RR',
            name: 'Reading Railroad',
            logo: '18_ts/RR',
            simple_logo: '18_ts/RR.alt',
            capitalization: :full,
            max_ownership_percent: 100,
            tokens: [0, 40, 100, 100],
            coordinates: 'O13',
            city: 0,
            color: '#be2ed6',
            text_color: '#ffffff',
            abilities: [{ type: 'blocks_hexes', owner_type: nil, hexes: ['O13','P14'] }],
          },
          {
            sym: 'P&E',
            name: 'Phialdelphia and Erie Railroad',
            logo: '18_ts/PE',
            simple_logo: '18_ts/PE.alt',
            capitalization: :full,
            max_ownership_percent: 100,
            tokens: [0, 40, 100, 100],
            coordinates: 'J14',
            city: 0,
            color: '#00ff00',
            text_color: '#000000',
            abilities: [{ type: 'blocks_hexes', owner_type: nil, hexes: ['J14'] }],
          },
          {
            sym: 'NYC',
            name: 'New York Central Railroad',
            logo: '18_ts/NYC',
            simple_logo: '18_ts/NYC.alt',
            capitalization: :full,
            max_ownership_percent: 100,
            tokens: [0, 40, 100, 100],
            coordinates: 'T8',
            city: 3,
            color: '#000000',
            text_color: '#ffffff',
            abilities: [{ type: 'blocks_hexes', owner_type: nil, hexes: ['S5'] }],
          },
          {
            sym: 'C&A',
            name: 'Camden and Amboy Railroad',
            logo: '18_ts/C&A',
            simple_logo: '18_ts/C&A.alt',
            capitalization: :full,
            max_ownership_percent: 100,
            tokens: [0, 40, 100, 100],
            coordinates: 'T8',
            city: 5,
            color: '#d0f0c0',
            text_color: '#000000',
            abilities: [{ type: 'blocks_hexes', owner_type: nil, hexes: ['U9'] }],
          },
          {
            sym: 'NCRY',
            name: 'Northern Central Railway',
            logo: '18_ts/NCRY',
            simple_logo: '18_ts/NCRY.alt',
            capitalization: :full,
            max_ownership_percent: 100,
            tokens: [0, 40, 100],
            coordinates: 'M13',
            city: 0,
            color: '#89cff0',
            text_color: '#000000',
          },
          {
            sym: 'LC&SC',
            name: 'Lewisburg, Centre and Spruce Creek Railroad',
            logo: '18_ts/LCSC',
            simple_logo: '18_ts/LCSC.alt',
            capitalization: :full,
            max_ownership_percent: 100,
            tokens: [0, 40, 100],
            coordinates: 'M13',
            city: 1,
            color: '#228c22',
            text_color: '#ffffff',
          },
          {
            sym: 'LV',
            name: 'Lehigh Valley Railroad',
            logo: '18_ts/LV',
            simple_logo: '18_ts/LV.alt',
            capitalization: :full,
            max_ownership_percent: 100,
            tokens: [0, 40, 100],
            coordinates: 'M17',
            city: 0,
            color: '#6c0ba9',
            text_color: '#ffffff',
            abilities: [{ type: 'blocks_hexes', owner_type: nil, hexes: ['L18'] }],
          },
          {
            sym: 'NH',
            name: 'New York, New Haven and Hartford Railroad',
            logo: '18_ts/NH',
            simple_logo: '18_ts/NH.alt',
            capitalization: :full,
            max_ownership_percent: 100,
            tokens: [0, 40, 100, 100],
            coordinates: 'U5',
            city: 0,
            color: '#d98e3a',
            text_color: '#000000',
            abilities: [],
          },
          {
            sym: 'LI',
            name: 'Long Island Rail Road',
            logo: '18_ts/LI',
            simple_logo: '18_ts/LI.alt',
            capitalization: :full,
            max_ownership_percent: 100,
            tokens: [0, 40, 100],
            coordinates: 'V8',
            city: 0,
            color: '#ffef00',
            text_color: 'black',
            abilities: [{ type: 'blocks_hexes', owner_type: nil, hexes: ['V8'] }],
        },
        {
          sym: 'B&O',
          name: 'Baltimore and Ohio Railroad',
          logo: '18_ts/BO',
          simple_logo: '18_ts/BO.alt',
          capitalization: :full,
          max_ownership_percent: 100,
          tokens: [0, 40, 100],
          coordinates: 'G21',
          city: 0,
          color: '#0047ab',
          text_color: '#ffffff',
          abilities: [{ type: 'blocks_hexes', owner_type: nil, hexes: ['H22'] }],
        },
        {
          sym: 'IRT',
          name: 'Interborough Rapid Transit Company',
          logo: '18_ts/IRT',
          simple_logo: '18_ts/IRT.alt',
          capitalization: :incremental,
          float_percent: 40,
          shares: [40, 20, 20, 20],
          price_percent: 10,
          max_ownership_percent: 100,
          tokens: [0],
          coordinates: 'T6',
          color: '#1b967a',
          text_color: '#ffffff',
        },
        {
          sym: 'SRC',
          name: 'Strasburg Rail Road',
          logo: '18_ts/SRC',
          simple_logo: '18_ts/SRC.alt',
          capitalization: :incremental,
          float_percent: 40,
          shares: [40, 20, 20, 20],
          price_percent: 10,
          max_ownership_percent: 100,
          tokens: [0],
          coordinates: 'P20',
          color: '#48260d',
          text_color: '#ffffff',
          abilities: [{ type: 'blocks_hexes', owner_type: nil, hexes: ['P20'] }],
        },
        {
          sym: 'ACR',
          name: 'Atlantic City Railroad',
          logo: '18_ts/ACR',
          simple_logo: '18_ts/ACR.alt',
          capitalization: :incremental,
          float_percent: 40,
          shares: [40, 20, 20, 20],
          price_percent: 10,
          max_ownership_percent: 100,
          tokens: [0],
          coordinates: 'U19',
          color: '#4666ff',
          text_color: '#ffffff',
        },
        {
          sym: 'L&W',
          name: 'Lackawanna and Western Railroad',
          logo: '18_ts/LW',
          simple_logo: '18_ts/LW.alt',
          capitalization: :incremental,
          float_percent: 40,
          shares: [40, 20, 20, 20],
          price_percent: 10,
          max_ownership_percent: 100,
          tokens: [0],
          coordinates: 'O5',
          color: '#cc5500',
          text_color: '#ffffff',
        },
        {
          sym: 'CVRR',
          name: 'Cumberland Valley Railroad',
          logo: '18_ts/CVRR',
          simple_logo: '18_ts/CVRR.alt',
          capitalization: :incremental,
          float_percent: 40,
          shares: [40, 20, 20, 20],
          price_percent: 10,
          max_ownership_percent: 100,
          tokens: [0],
          coordinates: 'K19',
          color: '#fafad2',
          text_color: '#000000',
        },
        {
          sym: 'DS',
          name: 'Delaware Shore Railroad',
          logo: '18_ts/DS',
          simple_logo: '18_ts/DS.alt',
          capitalization: :incremental,
          float_percent: 40,
          shares: [40, 20, 20, 20],
          price_percent: 10,
          max_ownership_percent: 100,
          tokens: [0],
          coordinates: 'S19',
          color: '#ffa6c9',
          text_color: '#000000',
        },
        {
          sym: 'P&L',
          name: 'Portsmouth and Lancaster Railroad',
          logo: '18_ts/PL',
          simple_logo: '18_ts/PL.alt',
          capitalization: :incremental,
          float_percent: 40,
          shares: [40, 20, 20, 20],
          price_percent: 10,
          max_ownership_percent: 100,
          tokens: [0],
          coordinates: 'O15',
          color: '#404040',
          text_color: '#ffffff',
        },
        {
          sym: 'NC&F',
          name: 'New Castle and Franklin Railroad',
          logo: '18_ts/NCF',
          simple_logo: '18_ts/NCF.alt',
          capitalization: :incremental,
          float_percent: 40,
          shares: [40, 20, 20, 20],
          price_percent: 10,
          max_ownership_percent: 100,
          tokens: [0],
          coordinates: 'C15',
          city: 0,
          color: '#299617',
          text_color: '#000000',
        },
        {
          sym: 'OC&C',
          name: 'Oil City and Chicago Railroad',
          logo: '18_ts/OCC',
          simple_logo: '18_ts/OCC.alt',
          capitalization: :incremental,
          float_percent: 40,
          shares: [40, 20, 20, 20],
          price_percent: 10,
          max_ownership_percent: 100,
          tokens: [0],
          coordinates: 'C19',
          city: 0,
          color: '#ffd300',
          text_color: '#000000',
        },
        {
          sym: 'B&B',
          name: 'Bedford and Bridgeport Railroad',
          logo: '18_ts/BB',
          simple_logo: '18_ts/BB.alt',
          capitalization: :incremental,
          float_percent: 40,
          shares: [40, 20, 20, 20],
          price_percent: 10,
          max_ownership_percent: 100,
          tokens: [0],
          coordinates: 'J20',
          city: 0,
          color: '#00ffef',
          text_color: '#000000',
        },
        {
          sym: 'PW',
          name: 'Pittsburgh and Western Railroad',
          logo: '18_ts/PW',
          simple_logo: '18_ts/PW.alt',
          capitalization: :full,
          max_ownership_percent: 100,
          tokens: [0, 40, 100, 100],
          coordinates: 'G21',
          city: 1,
          color: '#7c4700',
          text_color: '#ffffff',
        },
        {
          sym: 'AV',
          name: 'Allegheny Valley Railroad',
          logo: '18_ts/AV',
          simple_logo: '18_ts/AV.alt',
          capitalization: :full,
          max_ownership_percent: 100,
          tokens: [0, 40, 100, 100],
          coordinates: 'G21',
          city: 2,
          color: '#001800',
          text_color: '#ffff00',
        },
        ].freeze

        

       

       

       

        PAR_BY_CORPORATION = {
          'PRR' => 100,
          'CNJ' => 90,
          'RR' => 82,
          'P&E' => 82,
          'AV' => 76,
          'NYC' => 76,
          'C&A' => 76,
          'PW' => 76,
          'NCRY' => 71,
          'LC&SC' => 71,
          'LV' => 71,
          'NH' => 71,
          'B&O' => 67,
          'LI' => 67,
        }.freeze

        def game_par_values
          par_values = PAR_BY_CORPORATION.dup
          par_values['SECR'] = 67 if @optional_rules.include?(:db2)
          par_values
        end

        REQUIRED_TRAIN = {
          'NC&F' => '5',
          'OC&C' => '4',
          'B&B' => 'P3',
          'SRC' => '3+',
          'CVRR' => '5',
          'IRT' => '2D',
          'L&W' => '4',
          'P&L' => 'P3',
          'ACR' => '5',
          'DS' => '4',
        }.freeze

        def add_entities(corps, clist)
          clist.each do |chash|
            corps << chash.dup
          end
        end

        # combining is based on http://fwtwr.com/fwtwr/18xx/1825/privates.asp
        def game_companies
          comps = []
          add_entities(comps, UNIT1_COMPANIES) if @units[1]
          add_entities(comps, UNIT3_COMPANIES.reject { |c| comps.any? { |comp| comp[:value] == c[:value] } }) if @units[3]
          add_entities(comps, UNIT2_COMPANIES.reject { |c| comps.any? { |comp| comp[:value] == c[:value] } }) if @units[2]
          comps
        end

        def game_corporations
          corps = []
          add_entities(corps, UNIT1_CORPORATIONS) if @units[1]     
          add_entities(corps, UNIT2_CORPORATIONS) if @units[2]
          add_entities(corps, UNIT3_CORPORATIONS) if @units[3]
          corps
        end
      end
    end
  end
end
