# frozen_string_literal: true

module Engine
  module Game
    module G1822Africa
      module Entities
        COMPANIES = [].freeze

        CORPORATIONS = [
          {
            sym: '1',
            name: '1',
            logo: '1822/1',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'B2',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '2',
            name: '2',
            logo: '1822/2',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'G3',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '3',
            name: '3',
            logo: '1822/3',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'G7',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '4',
            name: '4',
            logo: '1822/4',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'H8',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '5',
            name: '5',
            logo: '1822/5',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'H10',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '6',
            name: '6',
            logo: '1822/6',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'H12',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '7',
            name: '7',
            logo: '1822/7',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'G17',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '8',
            name: '8',
            logo: '1822/8',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'E13',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '9',
            name: '9',
            logo: '1822/9',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'E11',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '10',
            name: '10',
            logo: '1822/10',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'C9',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '11',
            name: '11',
            logo: '1822/11',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'B10',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '12',
            name: '12',
            logo: '1822/12',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'A7',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: 'NAR',
            name: 'NAR',
            # logo: '1822_africa/NAR',
            tokens: [0, 50],
            type: 'major',
            float_percent: 20,
            always_market_price: true,
            coordinates: 'D2',
            color: '#ff7b93',
            text_color: 'black',
            reservation_color: nil,
            destination_coordinates: 'C9',
            # destination_icon: '1822_africa/NAR_DEST',
          },
          {
            sym: 'WAR',
            name: 'WAR',
            # logo: '1822_africa/WAR',
            tokens: [0, 50],
            type: 'major',
            float_percent: 20,
            always_market_price: true,
            coordinates: 'A7',
            color: '#ff7b93',
            text_color: 'black',
            reservation_color: nil,
            destination_coordinates: 'G7',
            # destination_icon: '1822_africa/WAR_DEST',
          },
          {
            sym: 'EAR',
            name: 'EAR',
            # logo: '1822_africa/EAR',
            tokens: [0, 50],
            type: 'major',
            float_percent: 20,
            always_market_price: true,
            coordinates: 'I7',
            color: '#ff7b93',
            text_color: 'black',
            reservation_color: nil,
            destination_coordinates: 'E9',
            # destination_icon: '1822_africa/EAR_DEST',
          },
          {
            sym: 'CAR',
            name: 'CAR',
            # logo: '1822_africa/CAR',
            tokens: [0, 50],
            type: 'major',
            float_percent: 20,
            always_market_price: true,
            coordinates: 'E9',
            color: '#ff7b93',
            text_color: 'black',
            reservation_color: nil,
            destination_coordinates: 'D2',
            # destination_icon: '1822_africa/CAR_DEST',
          },
          {
            sym: 'SAR',
            name: 'SAR',
            # logo: '1822_africa/SAR',
            tokens: [0, 50],
            type: 'major',
            float_percent: 20,
            always_market_price: true,
            coordinates: 'F18',
            color: '#ff7b93',
            text_color: 'black',
            reservation_color: nil,
            destination_coordinates: 'H10',
            # destination_icon: '1822_africa/SAR_DEST',
          },
        ].freeze
      end
    end
  end
end
