# frozen_string_literal: true

module Engine
  module Game
    module G1858
      module Entities
        CORPORATIONS = [
          {
            sym: 'A',
            name: 'Andalucian Railway',
            color: '#3751dc',
            text_color: 'white',
            logo: '1858/A',
            float_percent: 40,
            type: 'medium',
            shares: [40, 20, 20, 20],
            always_market_price: true,
            capitalization: :incremental,
            tokens: [0, 20, 20],
          },
          {
            sym: 'AVT',
            name: 'Almanza, Valencia and Tarragona Railway',
            color: '#18a6d8',
            text_color: 'white',
            logo: '1858/AVT',
            float_percent: 40,
            type: 'medium',
            shares: [40, 20, 20, 20],
            always_market_price: true,
            capitalization: :incremental,
            tokens: [0, 20, 20],
          },
          {
            sym: 'MZA',
            name: 'Madrid, Zaragoza and Alicante Railway',
            logo: '1858/MZA',
            color: '#fff114',
            text_color: 'black',
            float_percent: 40,
            type: 'medium',
            shares: [40, 20, 20, 20],
            always_market_price: true,
            capitalization: :incremental,
            tokens: [0, 20, 20],
            city: 2,
          },
          {
            sym: 'N',
            name: 'Northern Railway',
            logo: '1858/N',
            color: '#000000',
            text_color: 'white',
            float_percent: 40,
            type: 'medium',
            shares: [40, 20, 20, 20],
            always_market_price: true,
            capitalization: :incremental,
            tokens: [0, 20, 20],
          },
          {
            sym: 'RP',
            name: 'Royal Portugese Railway',
            logo: '1858/RP',
            color: '#e51f2e',
            text_color: 'white',
            float_percent: 40,
            type: 'medium',
            shares: [40, 20, 20, 20],
            always_market_price: true,
            capitalization: :incremental,
            tokens: [0, 20, 20],
          },
          {
            sym: 'TBF',
            name: 'Tarragona, Barcelona and France Railway',
            logo: '1858/TBF',
            color: '#59227f',
            text_color: 'white',
            float_percent: 40,
            type: 'medium',
            shares: [40, 20, 20, 20],
            always_market_price: true,
            capitalization: :incremental,
            tokens: [0, 20, 20],
          },
          {
            sym: 'W',
            name: 'Western Railway',
            logo: '1858/W',
            color: '#109538',
            text_color: 'white',
            float_percent: 40,
            type: 'medium',
            shares: [40, 20, 20, 20],
            always_market_price: true,
            capitalization: :incremental,
            tokens: [0, 20, 20],
          },
          {
            sym: 'ZPB',
            name: 'Zaragoza, Pamplona and Barcelona Railway',
            logo: '1858/ZPB',
            color: '#ff7700',
            text_color: 'white',
            float_percent: 40,
            type: 'medium',
            shares: [40, 20, 20, 20],
            always_market_price: true,
            capitalization: :incremental,
            tokens: [0, 20, 20],
          },
        ].freeze

        COMPANIES = [
          {
            sym: 'H&G',
            name: 'Havana and Güines Railway',
            desc: 'P1. Revenue 30. ' \
                  'Cannot be used to start a major company or exchanged for a share.',
            value: 30,
            discount: 0,
            revenue: 10,
            color: :yellow,
            text_color: :black,
            abilities: [{ type: 'no_buy' }],
          },
          {
            sym: 'B&M',
            name: 'Barcelona and Mataró Railway',
            desc: 'P2. Revenue 23/35. Home hex is O8. ' \
                  'Can be used to start a public company in Barcelona.',
            value: 115,
            discount: 25,
            revenue: 23,
            color: :yellow,
            text_color: :black,
            abilities: [
              { type: 'no_buy' },
              { type: 'revenue_change', revenue: 35, on_phase: '3' },
              { type: 'reservation', hex: 'O8' },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'any',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'M&A',
            name: 'Madrid and Aranjuez Railway',
            desc: 'P3. Revenue 25/38. Home hexes are H9 and H11. ' \
                  'Can be used to start a public company in Madrid.',
            value: 125,
            discount: 25,
            revenue: 25,
            color: :yellow,
            text_color: :black,
            city: 2,
            abilities: [
              { type: 'no_buy' },
              { type: 'revenue_change', revenue: 38, on_phase: '3' },
              { type: 'reservation', hex: 'H11', city: 2 },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'any',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'P&L',
            name: 'Porto and Lisbon Railway',
            desc: 'P4. Revenue 22/33. Home hexes are B9 and B11. ' \
                  'Can be used to start a public company in Porto.',
            value: 110,
            discount: 20,
            revenue: 22,
            color: :yellow,
            text_color: :black,
            abilities: [
              { type: 'no_buy' },
              { type: 'revenue_change', revenue: 33, on_phase: '3' },
              { type: 'reservation', hex: 'B9' },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'any',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'V&J',
            name: 'Valencia and Jativa Railway',
            desc: 'P5. Revenue 20/30. Home hex is L11. ' \
                  'Can be used to start a public company in Valencia.',
            value: 100,
            discount: 20,
            revenue: 20,
            color: :yellow,
            text_color: :black,
            abilities: [
              { type: 'no_buy' },
              { type: 'revenue_change', revenue: 30, on_phase: '3' },
              { type: 'reservation', hex: 'L13' },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'any',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'R&T',
            name: 'Reus and Tarragona Railway',
            desc: 'P6. Revenue 12/18. Home hex is N9. ' \
                  'Cannot be used to start a public company.',
            value: 60,
            discount: 10,
            revenue: 12,
            color: :yellow,
            text_color: :black,
            abilities: [
              { type: 'no_buy' },
              { type: 'revenue_change', revenue: 18, on_phase: '3' },
            ],
          },
          {
            sym: 'L&C',
            name: 'Lisbon and Carregado Railway',
            desc: 'P7. Revenue 18/27. Home hexes are A14 and B13. ' \
                  'Can be used to start a public company in Lisboa.',
            value: 90,
            discount: 20,
            revenue: 18,
            color: :yellow,
            text_color: :black,
            abilities: [
              { type: 'no_buy' },
              { type: 'revenue_change', revenue: 27, on_phase: '3' },
              { type: 'reservation', hex: 'A14', slot: 0 },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'any',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'M&V',
            name: 'Madrid and Valladolid Railway',
            desc: 'P8. Revenue 24/36. Home hexes are G8, G10 and H11. ' \
                  'Can be used to start a public company in either Madrid or Valladolid.',
            value: 120,
            discount: 25,
            revenue: 24,
            color: :yellow,
            text_color: :black,
            city: [0, 1],
            abilities: [
              { type: 'no_buy' },
              { type: 'revenue_change', revenue: 36, on_phase: '3' },
              { type: 'reservation', hex: 'G8' },
              { type: 'reservation', hex: 'H11', city: 1 },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'any',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'M&Z',
            name: 'Madrid and Zaragoza Railway',
            desc: 'P9. Revenue 19/29. Home hexes are I10, J9, K8 and L7. ' \
                  'Can be used to start a public company in Zaragoza.',
            value: 95,
            discount: 20,
            revenue: 19,
            color: :yellow,
            text_color: :black,
            abilities: [
              { type: 'no_buy' },
              { type: 'revenue_change', revenue: 29, on_phase: '3' },
              { type: 'reservation', hex: 'L7' },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'any',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'C&S',
            name: 'Córdoba and Seville Railway',
            desc: 'P10. Revenue 21/32. Home hexes are E18, F17 and G18. ' \
                  'Can be used to start a public company in either Sevilla or Córdoba.',
            value: 105,
            discount: 20,
            revenue: 21,
            color: :yellow,
            text_color: :black,
            abilities: [
              { type: 'no_buy' },
              { type: 'revenue_change', revenue: 32, on_phase: '3' },
              { type: 'reservation', hex: 'E18' },
              { type: 'reservation', hex: 'G18' },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'any',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'SJ&C',
            name: 'Seville, Jerez and Cadiz Railway',
            desc: 'P11. Revenue 14/21. Home hexes are E18 and E20. ' \
                  'Can be used to start a public company in either Sevilla or Cádiz.',
            value: 70,
            discount: 15,
            revenue: 14,
            color: :yellow,
            text_color: :black,
            abilities: [
              { type: 'no_buy' },
              { type: 'revenue_change', revenue: 21, on_phase: '3' },
              { type: 'reservation', hex: 'E18' },
              { type: 'reservation', hex: 'E20' },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'any',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'Z&P',
            name: 'Zaragoza and Pamplona Railway',
            desc: 'P12. Revenue 16/24. Home hexes are K4, K6 and L7. ' \
                  'Can be used to start a public company in Zaragoza.',
            value: 80,
            discount: 15,
            revenue: 16,
            color: :yellow,
            text_color: :black,
            abilities: [
              { type: 'no_buy' },
              { type: 'revenue_change', revenue: 24, on_phase: '3' },
              { type: 'reservation', hex: 'L7' },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'any',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'C&B',
            name: 'Castejón and Bilbao Railway',
            desc: 'P13. Revenue 15/23. Home hex is I2. ' \
                  'Can be used to start a public company in Bilbao.',
            value: 75,
            discount: 15,
            revenue: 15,
            color: :yellow,
            text_color: :black,
            abilities: [
              { type: 'no_buy' },
              { type: 'revenue_change', revenue: 23, on_phase: '3' },
              { type: 'reservation', hex: 'I2' },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'any',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'C&M',
            name: 'Córdoba and Málaga Railway',
            desc: 'P14. Revenue 17/26. Home hexes are G18 and G20. ' \
                  'Can be used to start a public company in either Córdoba or Málaga.',
            value: 85,
            discount: 15,
            revenue: 17,
            color: :yellow,
            text_color: :black,
            abilities: [
              { type: 'no_buy' },
              { type: 'revenue_change', revenue: 26, on_phase: '3' },
              { type: 'reservation', hex: 'G18' },
              { type: 'reservation', hex: 'G20' },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'any',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'M&C',
            name: 'Murcia and Cartagena Railway',
            desc: 'P15. Revenue 14/21. Home hex is K18. ' \
                  'Can be used to start a public company in Murcia.',
            value: 70,
            discount: 15,
            revenue: 14,
            color: :yellow,
            text_color: :black,
            abilities: [
              { type: 'no_buy' },
              { type: 'revenue_change', revenue: 21, on_phase: '3' },
              { type: 'reservation', hex: 'K18' },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'any',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'A&S',
            name: 'Alar and Santander Railway',
            desc: 'P16. Revenue 16/24. Home hexes are G4 and H3. ' \
                  'Can be used to start a public company in Santander.',
            value: 80,
            discount: 15,
            revenue: 16,
            color: :yellow,
            text_color: :black,
            abilities: [
              { type: 'no_buy' },
              { type: 'revenue_change', revenue: 24, on_phase: '3' },
              { type: 'reservation', hex: 'H3' },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'any',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'B&CR',
            name: 'Badajoz and Ciudad Real Railway',
            desc: 'P17. Revenue 13/20. Home hexes are D15, E14 and F15. ' \
                  'Cannot be used to start a public company.',
            value: 65,
            discount: 15,
            revenue: 13,
            color: :yellow,
            text_color: :black,
            abilities: [
              { type: 'no_buy' },
              { type: 'revenue_change', revenue: 20, on_phase: '3' },
            ],
          },
          {
            sym: 'S&C',
            name: 'Santiago and La Coruña Railway',
            desc: 'P18. Revenue 30. Home hexes are C2 and C4. ' \
                  'Can be used to start a public company in La Coruña.',
            value: 100,
            discount: 0,
            revenue: 30,
            color: :green,
            text_color: :black,
            abilities: [
              { type: 'no_buy' },
              { type: 'reservation', hex: 'C2' },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'any',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'M&S',
            name: 'Medina and Salamanca Railway',
            desc: 'P19. Revenue 27. Home hex is F9. ' \
                  'Cannot be used to start a public company.',
            value: 90,
            discount: 0,
            revenue: 27,
            color: :green,
            text_color: :black,
            abilities: [{ type: 'no_buy' }],
          },
          {
            sym: 'C&MP',
            name: 'Cáceres, Madrid and Portugal Railway',
            desc: 'P20. Revenue 40. Home hexes are D13, E12, F13, G12 and H11. ' \
                  'Can be used to start a public company in Madrid.',
            value: 135,
            discount: -30,
            revenue: 40,
            color: :green,
            text_color: :black,
            city: 0,
            abilities: [
              { type: 'no_buy' },
              { type: 'reservation', hex: 'H11', city: 0 },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'any',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'O&V',
            name: 'Orense and Vigo Railway',
            desc: 'P21. Revenue 33. Home hexes are B5 and C4. ' \
                  'Can be used to start a public company in Vigo.',
            value: 110,
            discount: 0,
            revenue: 33,
            color: :green,
            text_color: :black,
            abilities: [
              { type: 'no_buy' },
              { type: 'reservation', hex: 'B5' },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'any',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'L&G',
            name: 'León and Gijón Railway',
            desc: 'P22. Revenue 36. Home hexes are F1, F3 and F5. ' \
                  'Can be used to start a public company in Gijón.',
            value: 120,
            discount: 0,
            revenue: 36,
            color: :green,
            text_color: :black,
            abilities: [
              { type: 'no_buy' },
              { type: 'reservation', hex: 'F1', slot: 0 },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'any',
                from: 'ipo',
              },
            ],
          },
        ].freeze

        MINORS = [
          {
            sym: 'B&M',
            name: 'Barcelona and Mataró Railway',
            tokens: [],
            color: :yellow,
            text_color: :black,
            logo: '1858/BM',
            coordinates: %w[O8],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[O8] },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'M&A',
            name: 'Madrid and Aranjuez Railway',
            tokens: [],
            color: :yellow,
            text_color: :black,
            logo: '1858/MA',
            coordinates: %w[H11 H13],
            city: 2,
            abilities: [
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'P&L',
            name: 'Porto and Lisbon Railway',
            tokens: [],
            color: :yellow,
            text_color: :black,
            logo: '1858/PL',
            coordinates: %w[B9 B11],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[B9 B11] },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'V&J',
            name: 'Valencia and Jativa Railway',
            tokens: [],
            color: :yellow,
            text_color: :black,
            logo: '1858/VJ',
            coordinates: %w[L13],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[L13] },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'R&T',
            name: 'Reus and Tarragona Railway',
            tokens: [],
            color: :yellow,
            text_color: :black,
            logo: '1858/RT',
            coordinates: %w[N9],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[N9] },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'L&C',
            name: 'Lisbon and Carregado Railway',
            tokens: [],
            color: :yellow,
            text_color: :black,
            logo: '1858/LC',
            coordinates: %w[A14 B13],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[B13] },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'M&V',
            name: 'Madrid and Valladolid Railway',
            tokens: [],
            color: :yellow,
            text_color: :black,
            logo: '1858/MV',
            coordinates: %w[G8 H11 G10],
            city: [0, 1],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[G8 G10] },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'M&Z',
            name: 'Madrid and Zaragoza Railway',
            tokens: [],
            color: :yellow,
            text_color: :black,
            logo: '1858/MZ',
            coordinates: %w[I10 J9 K8 L7],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[I10 J9 K8] },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'C&S',
            name: 'Córdoba and Seville Railway',
            tokens: [],
            color: :yellow,
            text_color: :black,
            logo: '1858/CS',
            coordinates: %w[E18 F17 G18],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[E18 F17 G18] },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'SJ&C',
            name: 'Seville, Jerez and Cadiz Railway',
            tokens: [],
            color: :yellow,
            text_color: :black,
            logo: '1858/SJC',
            coordinates: %w[E18 E20],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[E18 E20] },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'Z&P',
            name: 'Zaragoza and Pamplona Railway',
            tokens: [],
            color: :yellow,
            text_color: :black,
            logo: '1858/ZP',
            coordinates: %w[K4 K6 L7],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[K4 K6] },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'C&B',
            name: 'Castejón and Bilbao Railway',
            tokens: [],
            color: :yellow,
            text_color: :black,
            logo: '1858/CB',
            coordinates: %w[I2],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[I2] },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'C&M',
            name: 'Córdoba and Málaga Railway',
            tokens: [],
            color: :yellow,
            text_color: :black,
            logo: '1858/CM',
            coordinates: %w[G18 G20],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[G18 G20] },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'M&C',
            name: 'Murcia and Cartagena Railway',
            tokens: [],
            color: :yellow,
            text_color: :black,
            logo: '1858/MC',
            coordinates: %w[K18 L19],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[K18] },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'A&S',
            name: 'Alar and Santander Railway',
            tokens: [],
            color: :yellow,
            text_color: :black,
            logo: '1858/AS',
            coordinates: %w[G4 H3],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[G4 H3] },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'B&CR',
            name: 'Badajoz and Ciudad Real Railway',
            tokens: [],
            color: :yellow,
            text_color: :black,
            logo: '1858/BCR',
            coordinates: %w[D15 E14 F15],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[D15 E14 F15] },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'S&C',
            name: 'Santiago and La Coruña Railway',
            tokens: [],
            color: :green,
            text_color: :black,
            logo: '1858/SC',
            coordinates: %w[C2 C4],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[C2 C4] },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'M&S',
            name: 'Medina and Salamanca Railway',
            tokens: [],
            color: :green,
            text_color: :black,
            logo: '1858/MS',
            coordinates: %w[F9],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[F9] },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'C&MP',
            name: 'Cáceres, Madrid and Portugal Railway',
            tokens: [],
            color: :green,
            text_color: :black,
            logo: '1858/CMP',
            coordinates: %w[H11 D13 E12 F13 G12],
            city: 0,
            abilities: [
              { type: 'blocks_hexes', hexes: %w[D13 E12 F13 G12] },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'O&V',
            name: 'Orense and Vigo Railway',
            tokens: [],
            color: :green,
            text_color: :black,
            logo: '1858/OV',
            coordinates: %w[B5 C4],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[B5 C4] },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'L&G',
            name: 'León and Gijón Railway',
            tokens: [],
            color: :green,
            text_color: :black,
            logo: '1858/LG',
            coordinates: %w[F1 F3 F5],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[F3 F5] },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
        ].freeze

        PRIVATE_ORDER = {
          'H&G' => 1,
          'B&M' => 2,
          'M&A' => 3,
          'P&L' => 4,
          'V&J' => 5,
          'R&T' => 6,
          'L&C' => 7,
          'M&V' => 8,
          'M&Z' => 9,
          'C&S' => 10,
          'SJ&C' => 11,
          'Z&P' => 12,
          'C&B' => 13,
          'C&M' => 14,
          'M&C' => 15,
          'A&S' => 16,
          'B&CR' => 17,
          'S&C' => 18,
          'M&S' => 19,
          'C&MP' => 20,
          'O&V' => 21,
          'L&G' => 22,
        }.freeze

        QUICK_START_PACKETS_A = {
          3 => [
            { companies: ['M&A', 'V&J', 'M&C', 'B&M', 'R&T', 'H&G'], cost: 500 },
            { companies: ['M&V', 'A&S', 'C&B', 'P&L', 'L&C'], cost: 475 },
            { companies: ['C&S', 'C&M', 'SJ&C', 'B&CR', 'M&Z', 'Z&P'], cost: 500 },
          ],
          4 => [
            { companies: ['M&A', 'V&J', 'M&C', 'B&CR'], cost: 360 },
            { companies: ['B&M', 'R&T', 'M&Z', 'Z&P'], cost: 350 },
            { companies: ['M&V', 'A&S', 'C&B', 'L&C'], cost: 365 },
            { companies: ['C&S', 'C&M', 'SJ&C', 'P&L'], cost: 370 },
          ],
          5 => [
            { companies: ['M&A', 'V&J', 'M&C'], cost: 295 },
            { companies: ['B&M', 'R&T', 'M&Z'], cost: 270 },
            { companies: ['M&V', 'A&S', 'C&B'], cost: 275 },
            { companies: ['C&S', 'C&M', 'SJ&C'], cost: 260 },
            { companies: ['P&L', 'L&C', 'B&CR', 'H&G'], cost: 295 },
          ],
          6 => [
            { companies: ['M&A', 'M&Z'], cost: 220 },
            { companies: ['B&M', 'R&T', 'C&B'], cost: 250 },
            { companies: ['M&V', 'A&S'], cost: 200 },
            { companies: ['C&S', 'B&CR', 'SJ&C'], cost: 240 },
            { companies: ['P&L', 'L&C', 'H&G'], cost: 230 },
            { companies: ['V&J', 'M&C', 'Z&P'], cost: 250 },
          ],
        }.freeze

        QUICK_START_PACKETS_B = QUICK_START_PACKETS_A.merge({
          4 => [
            { companies: ['M&A', 'V&J', 'M&C', 'B&CR'], cost: 360 },
            { companies: ['B&M', 'R&T', 'P&L', 'L&C'], cost: 375 },
            { companies: ['M&V', 'A&S', 'C&B', 'Z&P'], cost: 355 },
            { companies: ['C&S', 'C&M', 'SJ&C', 'M&Z'], cost: 355 },
          ],
        }.freeze)

        def quick_start
          packets = option_quick_start_packets[@players.size].sort_by { rand }
          @players.zip(packets).each do |player, packet|
            cost = packet[:cost]
            player.spend(cost, @bank)
            companies = packet[:companies]
            companies.each do |sym|
              company = @companies.find { |c| c.sym == sym }
              purchase_company(player, company, 0)
            end
            @log << "#{player.name} spends #{format_currency(cost)} and " \
                    "buys private companies #{companies.join(', ')}"
          end
        end
      end
    end
  end
end
