# frozen_string_literal: true

module Engine
  module Game
    module G1858India
      module Entities
        CORPORATIONS = [
          {
            sym: 'ABR',
            name: 'Assam Bengal Railway',
            color: 'lightblue',
            text_color: 'black',
            logo: '1858_india/ABR',
            float_percent: 40,
            type: '5-share',
            shares: [40, 20, 20, 20],
            always_market_price: true,
            capitalization: :incremental,
            tokens: [0, 20, 20],
          },
          {
            sym: 'BBC',
            name: 'Bombay, Baroda and Central India',
            color: 'darkblue',
            text_color: 'white',
            logo: '1858_india/BBC',
            float_percent: 40,
            type: '5-share',
            shares: [40, 20, 20, 20],
            always_market_price: true,
            capitalization: :incremental,
            tokens: [0, 20, 20],
          },
          {
            sym: 'BNR',
            name: 'Bengal Nagpur Railway',
            color: 'yellow',
            text_color: 'black',
            logo: '1858_india/BNR',
            float_percent: 40,
            type: '5-share',
            shares: [40, 20, 20, 20],
            always_market_price: true,
            capitalization: :incremental,
            tokens: [0, 20, 20],
          },
          {
            sym: 'EIR',
            name: 'East Indian Railway',
            color: 'black',
            text_color: 'white',
            logo: '1858_india/EIR',
            float_percent: 40,
            type: '5-share',
            shares: [40, 20, 20, 20],
            always_market_price: true,
            capitalization: :incremental,
            tokens: [0, 20, 20],
          },
          {
            sym: 'EBR',
            name: 'Eastern Bengal Railway',
            color: 'brown',
            text_color: 'white',
            logo: '1858_india/EBR',
            float_percent: 40,
            type: '5-share',
            shares: [40, 20, 20, 20],
            always_market_price: true,
            capitalization: :incremental,
            tokens: [0, 20, 20],
          },
          {
            sym: 'GIP',
            name: 'Great Indian Peninsular',
            color: 'orange',
            text_color: 'black',
            logo: '1858_india/GIP',
            float_percent: 40,
            type: '5-share',
            shares: [40, 20, 20, 20],
            always_market_price: true,
            capitalization: :incremental,
            tokens: [0, 20, 20],
          },
          {
            sym: 'MSM',
            name: 'Madras and Southern Mahratta',
            color: 'green',
            text_color: 'black',
            logo: '1858_india/MSM',
            float_percent: 40,
            type: '5-share',
            shares: [40, 20, 20, 20],
            always_market_price: true,
            capitalization: :incremental,
            tokens: [0, 20, 20],
          },
          {
            sym: 'PNS',
            name: 'Punjab Northern State Railway',
            color: 'gray',
            text_color: 'black',
            logo: '1858_india/PNS',
            float_percent: 40,
            type: '5-share',
            shares: [40, 20, 20, 20],
            always_market_price: true,
            capitalization: :incremental,
            tokens: [0, 20, 20],
          },
          {
            sym: 'SPD',
            name: 'Scinde, Punjab and Delhi',
            color: 'gray',
            text_color: 'white',
            logo: '1858_india/SPD',
            float_percent: 40,
            type: '5-share',
            shares: [40, 20, 20, 20],
            always_market_price: true,
            capitalization: :incremental,
            tokens: [0, 20, 20],
          },
          {
            sym: 'SIR',
            name: 'South Indian Railway',
            color: 'red',
            text_color: 'black',
            logo: '1858_india/SIR',
            float_percent: 40,
            type: '5-share',
            shares: [40, 20, 20, 20],
            always_market_price: true,
            capitalization: :incremental,
            tokens: [0, 20, 20],
          },
        ].freeze

        COMPANIES = [
          {
            sym: 'BT',
            name: 'Bombay-Thana',
            type: 'private_batch1',
            desc: 'P1. Revenue 24/36, face value 120. Home hexes are K6 and K8. ' \
                  'Can be used to start a public company in Bombay.',
            value: 120,
            discount: 25,
            revenue: 24,
            color: :yellow,
            text_color: :black,
            abilities: [
              { type: 'no_buy' },
              { type: 'revenue_change', revenue: 36, on_phase: '3' },
              { type: 'reservation', hex: 'K6' },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'any',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'HH',
            name: 'Howrah-Howgly',
            type: 'private_batch1',
            desc: 'P2. Revenue 25/38, face value 125. Home hexes are I22 and H21. ' \
                  'Can be used to start a public company in Calcutta.',
            value: 125,
            discount: 25,
            revenue: 25,
            color: :yellow,
            text_color: :black,
            abilities: [
              { type: 'no_buy' },
              { type: 'revenue_change', revenue: 38, on_phase: '3' },
              { type: 'reservation', hex: 'I22', city: 1 },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'any',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'MA',
            name: 'Madras-Arcot',
            type: 'private_batch1',
            desc: 'P3. Revenue 24/36, face value 120. Home hexes are O14 and O12. ' \
                  'Can be used to start a public company in Bangalore or Madras.',
            value: 120,
            discount: 25,
            revenue: 24,
            color: :yellow,
            text_color: :black,
            abilities: [
              { type: 'no_buy' },
              { type: 'revenue_change', revenue: 36, on_phase: '3' },
              { type: 'reservation', hex: 'O12' },
              { type: 'reservation', hex: 'O14' },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'any',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'BS',
            name: 'Bombay-Surat',
            type: 'private_batch1',
            desc: 'P4. Revenue 23/35, face value 115. Home hexes are K6 and J7. ' \
                  'Can be used to start a public company in Bombay.',
            value: 115,
            discount: 25,
            revenue: 23,
            color: :yellow,
            text_color: :black,
            abilities: [
              { type: 'no_buy' },
              { type: 'revenue_change', revenue: 35, on_phase: '3' },
              { type: 'reservation', hex: 'K6' },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'any',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'AC',
            name: 'Allahabad-Cawnpore',
            type: 'private_batch1',
            desc: 'P5. Revenue 20/30, face value 100. Home hexes are G16, G14 and F13. ' \
                  'Can be used to start a public company in Allahabad or Cawnpore.',
            value: 100,
            discount: 20,
            revenue: 20,
            color: :yellow,
            text_color: :black,
            abilities: [
              { type: 'no_buy' },
              { type: 'revenue_change', revenue: 30, on_phase: '3' },
              { type: 'reservation', hex: 'F13', icon: '1858_india/AC+LC' },
              { type: 'reservation', hex: 'G16' },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'any',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'KK',
            name: 'Karachi-Kotri',
            type: 'private_batch1',
            desc: 'P6. Revenue 22/33, face value 110. Home hexes are G2 and F3. ' \
                  'Can be used to start a public company in Karachi.',
            value: 110,
            discount: 20,
            revenue: 22,
            color: :yellow,
            text_color: :black,
            abilities: [
              { type: 'no_buy' },
              { type: 'revenue_change', revenue: 33, on_phase: '3' },
              { type: 'reservation', hex: 'G2' },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'any',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'ML',
            name: 'Multan-Lahore',
            type: 'private_batch1',
            desc: 'P7. Revenue 22/33, face value 110. Home hexes are D5, D7 and C8. ' \
                  'Can be used to start a public company in Multan or Lahore.',
            value: 110,
            discount: 20,
            revenue: 22,
            color: :yellow,
            text_color: :black,
            abilities: [
              { type: 'no_buy' },
              { type: 'revenue_change', revenue: 33, on_phase: '3' },
              { type: 'reservation', hex: 'C8', icon: '1858_india/LA+ML' },
              { type: 'reservation', hex: 'D5', icon: '1858_india/MK+ML' },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'any',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'LA',
            name: 'Lahore-Amritsar',
            type: 'private_batch1',
            desc: 'P8. Revenue 18/27, face value 90. Home hexes are C8 and C10. ' \
                  'Can be used to start a public company in Lahore.',
            value: 90,
            discount: 20,
            revenue: 18,
            color: :yellow,
            text_color: :black,
            abilities: [
              { type: 'no_buy' },
              { type: 'revenue_change', revenue: 27, on_phase: '3' },
              { type: 'reservation', hex: 'C8', icon: '1858_india/LA+ML' },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'any',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'CPC',
            name: 'Calcutta-Port Canning',
            type: 'private_batch1',
            desc: 'P9. Revenue 19/29, face value 95. Home hexes are I22 and J21. ' \
                  'Can be used to start a public company in Calcutta.',
            value: 95,
            discount: 20,
            revenue: 19,
            color: :yellow,
            text_color: :black,
            abilities: [
              { type: 'no_buy' },
              { type: 'revenue_change', revenue: 29, on_phase: '3' },
              { type: 'reservation', hex: 'I22', city: 0 },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'any',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'TN',
            name: 'Trichinopoly-Nagapatnam',
            type: 'private_batch1',
            desc: 'P10. Revenue 21/32, face value 105. Home hex is P13. ' \
                  'Can be used to start a public company in Trichinopoly.',
            value: 105,
            discount: 20,
            revenue: 21,
            color: :yellow,
            text_color: :black,
            abilities: [
              { type: 'no_buy' },
              { type: 'revenue_change', revenue: 32, on_phase: '3' },
              { type: 'reservation', hex: 'P13' },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'any',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'AB',
            name: 'Ahmadabad-Baroda',
            type: 'private_batch1',
            desc: 'P11. Revenue 18/27, face value 90. Home hexes are H7 and I6. ' \
                  'Can be used to start a public company in Ahmadabad.',
            value: 90,
            discount: 20,
            revenue: 18,
            color: :yellow,
            text_color: :black,
            abilities: [
              { type: 'no_buy' },
              { type: 'revenue_change', revenue: 27, on_phase: '3' },
              { type: 'reservation', hex: 'H7' },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'any',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'NA',
            name: 'Nagpur-Amraoti',
            type: 'private_batch1',
            desc: 'P12. Revenue 14/21, face value 70. Home hexes are J13 and J11. ' \
                  'Can be used to start a public company in Nagpur.',
            value: 70,
            discount: 15,
            revenue: 14,
            color: :yellow,
            text_color: :black,
            abilities: [
              { type: 'no_buy' },
              { type: 'revenue_change', revenue: 21, on_phase: '3' },
              { type: 'reservation', hex: 'J13' },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'any',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'LC',
            name: 'Lucknow-Cawnpore',
            type: 'private_batch1',
            desc: 'P13. Revenue 16/24, face value 80. Home hexes are F15 and F13. ' \
                  'Can be used to start a public company in Cawnpore or Lucknow.',
            value: 80,
            discount: 15,
            revenue: 16,
            color: :yellow,
            text_color: :black,
            abilities: [
              { type: 'no_buy' },
              { type: 'revenue_change', revenue: 24, on_phase: '3' },
              { type: 'reservation', hex: 'F13', icon: '1858_india/AC+LC' },
              { type: 'reservation', hex: 'F15' },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'any',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'AD',
            name: 'Ambala-Delhi',
            type: 'private_batch1',
            desc: 'P14. Revenue 20/30, face value 100. Home hexes are E12 and D11. ' \
                  'Can be used to start a public company in Delhi.',
            value: 100,
            discount: 20,
            revenue: 20,
            color: :yellow,
            text_color: :black,
            abilities: [
              { type: 'no_buy' },
              { type: 'revenue_change', revenue: 30, on_phase: '3' },
              { type: 'reservation', hex: 'E12', city: 1 },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'any',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'AJ',
            name: 'Allahabad-Jubbalpore',
            type: 'private_batch1',
            desc: 'P15. Revenue 11/17, face value 55. Home hexes are H13 and H15. ' \
                  'Cannot be used to start a public company.',
            value: 55,
            discount: 10,
            revenue: 11,
            color: :yellow,
            text_color: :black,
            abilities: [
              { type: 'no_buy' },
              { type: 'revenue_change', revenue: 17, on_phase: '3' },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'any',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'PB',
            name: 'Patna-Benares',
            type: 'private_batch1',
            desc: 'P16. Revenue 17/26, face value 85. Home hexes are G20 and G18. ' \
                  'Can be used to start a public company in Patna.',
            value: 85,
            discount: 15,
            revenue: 17,
            color: :yellow,
            text_color: :black,
            abilities: [
              { type: 'no_buy' },
              { type: 'revenue_change', revenue: 26, on_phase: '3' },
              { type: 'reservation', hex: 'G20' },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'any',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'C',
            name: 'Coimbatore',
            type: 'private_batch1',
            desc: 'P17. Revenue 12/18, face value 60. Home hex is P11. ' \
                  'Cannot be used to start a public company.',
            value: 60,
            discount: 10,
            revenue: 12,
            color: :yellow,
            text_color: :black,
            abilities: [
              { type: 'no_buy' },
              { type: 'revenue_change', revenue: 18, on_phase: '3' },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'any',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'DA',
            name: 'Delhi-Agra',
            type: 'private_batch1',
            desc: 'P18. Revenue 20/30, face value 100. Home hexes are E12 and F11. ' \
                  'Can be used to start a public company in Delhi.',
            value: 100,
            discount: 20,
            revenue: 20,
            color: :yellow,
            text_color: :black,
            abilities: [
              { type: 'no_buy' },
              { type: 'revenue_change', revenue: 30, on_phase: '3' },
              { type: 'reservation', hex: 'E12', city: 0 },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'any',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'MB',
            name: 'Moradabad-Bareilly',
            type: 'private_batch1',
            desc: 'P19. Revenue 13/20, face value 65. Home hexes are D13 and E14. ' \
                  'Cannot be used to start a public company.',
            value: 65,
            discount: 15,
            revenue: 13,
            color: :yellow,
            text_color: :black,
            abilities: [
              { type: 'no_buy' },
              { type: 'revenue_change', revenue: 20, on_phase: '3' },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'any',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'LP',
            name: 'Lahore-Peshawar',
            type: 'private_batch1',
            desc: 'P20. Revenue 16/24, face value 80. Home hexes are A6 and B7. ' \
                  'Can be used to start a public company in Peshawar or Rawalpindi.',
            value: 80,
            discount: 15,
            revenue: 16,
            color: :yellow,
            text_color: :black,
            abilities: [
              { type: 'no_buy' },
              { type: 'revenue_change', revenue: 24, on_phase: '3' },
              { type: 'reservation', hex: 'A6' },
              { type: 'reservation', hex: 'B7' },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'any',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'MK',
            name: 'Multan-Kotri',
            type: 'private_batch1',
            desc: 'P21. Revenue 15/23, face value 75. Home hexes are D5 and E4. ' \
                  'Can be used to start a public company in Multan.',
            value: 75,
            discount: 15,
            revenue: 15,
            color: :yellow,
            text_color: :black,
            abilities: [
              { type: 'no_buy' },
              { type: 'revenue_change', revenue: 23, on_phase: '3' },
              { type: 'reservation', hex: 'D5', icon: '1858_india/MK+ML' },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'any',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'DS',
            name: 'Darjeeling-Siliguri',
            type: 'private_batch1',
            desc: 'P22. Revenue 12/18, face value 60. Home hex is F23. ' \
                  'Cannot be used to start a public company.',
            value: 60,
            discount: 10,
            revenue: 12,
            color: :yellow,
            text_color: :black,
            abilities: [
              { type: 'no_buy' },
              { type: 'revenue_change', revenue: 18, on_phase: '3' },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'any',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'M',
            name: 'Mysore',
            type: 'private_batch2',
            desc: 'P23. Revenue 33, face value 110. Home hex is O10. ' \
                  'Can be used to start a public company in Mysore.',
            value: 110,
            revenue: 33,
            color: :green,
            text_color: :black,
            abilities: [
              { type: 'no_buy' },
              { type: 'reservation', hex: 'O10' },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'any',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'DJ',
            name: 'Delhi-Jaipur',
            type: 'private_batch2',
            desc: 'P24. Revenue 27, face value 90. Home hexes are F9 and E10. ' \
                  'Can be used to start a public company in Jaipur.',
            value: 90,
            revenue: 27,
            color: :green,
            text_color: :black,
            abilities: [
              { type: 'no_buy' },
              { type: 'reservation', hex: 'F9' },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'any',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'DC',
            name: 'Dacca-Chittagong',
            type: 'private_batch2',
            desc: 'P25. Revenue 36, face value 120. Home hexes are H25 and I26. ' \
                  'Can be used to start a public company in Dacca.',
            value: 120,
            revenue: 36,
            color: :green,
            text_color: :black,
            abilities: [
              { type: 'no_buy' },
              { type: 'reservation', hex: 'H25' },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'any',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'CK',
            name: 'Calcutta-Khulna',
            type: 'private_batch2',
            desc: 'P26. Revenue 40, face value 135. Home hexes are I22 and I24. ' \
                  'Can be used to start a public company in Calcutta.',
            value: 135,
            revenue: 40,
            color: :green,
            text_color: :black,
            abilities: [
              { type: 'no_buy' },
              { type: 'reservation', hex: 'I22', city: 2 },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'any',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'G',
            name: 'Gorakhpur',
            type: 'private_batch2',
            desc: 'P27. Revenue 18, face value 60. Home hex is F17. ' \
                  'Cannot be used to start a public company.',
            value: 60,
            revenue: 18,
            color: :green,
            text_color: :black,
            abilities: [
              { type: 'no_buy' },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'any',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'BI',
            name: 'Bhopal-Indore',
            type: 'private_batch2',
            desc: 'P28. Revenue 21, face value 70. Home hexes are H11 and I10. ' \
                  'Cannot be used to start a public company.',
            value: 70,
            revenue: 21,
            color: :green,
            text_color: :black,
            abilities: [
              { type: 'no_buy' },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'any',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'JB',
            name: 'Jodhpur-Bikaner',
            type: 'private_batch2',
            desc: 'P29. Revenue 24, face value 80. Home hexes are F7 and E8. ' \
                  'Cannot be used to start a public company.',
            value: 80,
            revenue: 24,
            color: :green,
            text_color: :black,
            abilities: [
              { type: 'no_buy' },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'any',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'HB',
            name: 'Hyderabad-Bezawada',
            type: 'private_batch2',
            desc: 'P30. Revenue 30, face value 100. Home hexes are L13 and M14. ' \
                  'Can be used to start a public company in Hyderabad.',
            value: 100,
            revenue: 30,
            color: :green,
            text_color: :black,
            abilities: [
              { type: 'no_buy' },
              { type: 'reservation', hex: 'L13' },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'any',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'LW1',
            name: 'Locomotive works',
            type: 'locoworks',
            desc: 'Gives a £10 income each operating round and a 10% ' \
                  'discount on train purchases.',
            value: 100,
            min_price: 100,
            max_price: 100,
            revenue: 10,
            color: :black,
            text_color: :white,
            abilities: [
              {
                type: 'train_discount',
                discount: 0.1,
                trains: %w[4M 5E 5M 6E 6M 7E 5D],
              },
            ],
          },
          {
            sym: 'LW2',
            name: 'Locomotive works',
            type: 'locoworks',
            desc: 'Gives a £10 income each operating round and a 10% ' \
                  'discount on train purchases.',
            value: 100,
            min_price: 100,
            max_price: 100,
            revenue: 10,
            color: :black,
            text_color: :white,
            abilities: [
              {
                type: 'train_discount',
                discount: 0.1,
                trains: %w[4M 5E 5M 6E 6M 7E 5D],
              },
            ],
          },
        ].freeze

        MINORS = [
          {
            sym: 'BT',
            name: 'Bombay-Thana',
            tokens: [],
            color: :yellow,
            text_color: :black,
            logo: '1858_india/BT',
            coordinates: %w[K6 K8],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[K6 K8], hidden: true },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'HH',
            name: 'Howrah-Howgly',
            tokens: [],
            color: :yellow,
            text_color: :black,
            logo: '1858_india/HH',
            coordinates: %w[I22 H21],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[H21], hidden: true },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'MA',
            name: 'Madras-Arcot',
            tokens: [],
            color: :yellow,
            text_color: :black,
            logo: '1858_india/MA',
            coordinates: %w[O14 O12],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[O14 O12], hidden: true },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'BS',
            name: 'Bombay-Surat',
            tokens: [],
            color: :yellow,
            text_color: :black,
            logo: '1858_india/BS',
            coordinates: %w[K6 J7],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[K6 J7], hidden: true },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'AC',
            name: 'Allahabad-Cawnpore',
            tokens: [],
            color: :yellow,
            text_color: :black,
            logo: '1858_india/AC',
            coordinates: %w[G16 G14 F13],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[G16 G14 F13], hidden: true },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'KK',
            name: 'Karachi-Kotri',
            tokens: [],
            color: :yellow,
            text_color: :black,
            logo: '1858_india/KK',
            coordinates: %w[G2 F3],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[G2 F3], hidden: true },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'ML',
            name: 'Multan-Lahore',
            tokens: [],
            color: :yellow,
            text_color: :black,
            logo: '1858_india/ML',
            coordinates: %w[D5 D7 C8],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[D5 D7 C8], hidden: true },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'LA',
            name: 'Lahore-Amritsar',
            tokens: [],
            color: :yellow,
            text_color: :black,
            logo: '1858_india/LA',
            coordinates: %w[C8 C10],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[C8 C10], hidden: true },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'CPC',
            name: 'Calcutta-Port Canning',
            tokens: [],
            color: :yellow,
            text_color: :black,
            logo: '1858_india/CPC',
            coordinates: %w[I22 J21],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[J21], hidden: true },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'TN',
            name: 'Trichinopoly-Nagapatnam',
            tokens: [],
            color: :yellow,
            text_color: :black,
            logo: '1858_india/TN',
            coordinates: %w[P13],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[P13], hidden: true },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'AB',
            name: 'Ahmadabad-Baroda',
            tokens: [],
            color: :yellow,
            text_color: :black,
            logo: '1858_india/AB',
            coordinates: %w[H7 I6],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[H7 I6], hidden: true },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'NA',
            name: 'Nagpur-Amraoti',
            tokens: [],
            color: :yellow,
            text_color: :black,
            logo: '1858_india/NA',
            coordinates: %w[J13 J11],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[J13 J11], hidden: true },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'LC',
            name: 'Lucknow-Cawnpore',
            tokens: [],
            color: :yellow,
            text_color: :black,
            logo: '1858_india/LC',
            coordinates: %w[F15 F13],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[F15 F13], hidden: true },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'AD',
            name: 'Ambala-Delhi',
            tokens: [],
            color: :yellow,
            text_color: :black,
            logo: '1858_india/AD',
            coordinates: %w[E12 D11],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[D11], hidden: true },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'AJ',
            name: 'Allahabad-Jubbalpore',
            tokens: [],
            color: :yellow,
            text_color: :black,
            logo: '1858_india/AJ',
            coordinates: %w[H13 H15],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[H13 H15], hidden: true },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'PB',
            name: 'Patna-Benares',
            tokens: [],
            color: :yellow,
            text_color: :black,
            logo: '1858_india/PB',
            coordinates: %w[G20 G18],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[G20 G18], hidden: true },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'C',
            name: 'Coimbatore',
            tokens: [],
            color: :yellow,
            text_color: :black,
            logo: '1858_india/C',
            coordinates: %w[P11],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[P11], hidden: true },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'DA',
            name: 'Delhi-Agra',
            tokens: [],
            color: :yellow,
            text_color: :black,
            logo: '1858_india/DA',
            coordinates: %w[E12 F11],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[F11], hidden: true },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'MB',
            name: 'Moradabad-Bareilly',
            tokens: [],
            color: :yellow,
            text_color: :black,
            logo: '1858_india/MB',
            coordinates: %w[D13 E14],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[D13 E14], hidden: true },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'LP',
            name: 'Lahore-Peshawar',
            tokens: [],
            color: :yellow,
            text_color: :black,
            logo: '1858_india/LP',
            coordinates: %w[A6 B7],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[A6 B7], hidden: true },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'MK',
            name: 'Multan-Kotri',
            tokens: [],
            color: :yellow,
            text_color: :black,
            logo: '1858_india/MK',
            coordinates: %w[D5 E4],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[D5 E4], hidden: true },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'DS',
            name: 'Darjeeling-Siliguri',
            tokens: [],
            color: :yellow,
            text_color: :black,
            logo: '1858_india/DS',
            coordinates: %w[F23],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[F23], hidden: true },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'M',
            name: 'Mysore',
            tokens: [],
            color: :green,
            text_color: :black,
            logo: '1858_india/M',
            coordinates: %w[O10],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[O10], hidden: true },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'DJ',
            name: 'Delhi-Jaipur',
            tokens: [],
            color: :green,
            text_color: :black,
            logo: '1858_india/DJ',
            coordinates: %w[F9 E10],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[F9 E10], hidden: true },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'DC',
            name: 'Dacca-Chittagong',
            tokens: [],
            color: :green,
            text_color: :black,
            logo: '1858_india/DC',
            coordinates: %w[H25 I26],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[H25 I26], hidden: true },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'CK',
            name: 'Calcutta-Khulna',
            tokens: [],
            color: :green,
            text_color: :black,
            logo: '1858_india/CK',
            coordinates: %w[I22 I24],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[I24], hidden: true },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'G',
            name: 'Gorakhpur',
            tokens: [],
            color: :green,
            text_color: :black,
            logo: '1858_india/G',
            coordinates: %w[F17],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[F17], hidden: true },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'BI',
            name: 'Bhopal-Indore',
            tokens: [],
            color: :green,
            text_color: :black,
            logo: '1858_india/BI',
            coordinates: %w[H11 I10],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[H11 I10], hidden: true },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'JB',
            name: 'Jodhpur-Bikaner',
            tokens: [],
            color: :green,
            text_color: :black,
            logo: '1858_india/JB',
            coordinates: %w[F7 E8],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[F7 E8], hidden: true },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],
          },
          {
            sym: 'HB',
            name: 'Hyderabad-Bezawada',
            tokens: [],
            color: :green,
            text_color: :black,
            logo: '1858_india/HB',
            coordinates: %w[L13 M14],
            abilities: [
              { type: 'blocks_hexes', hexes: %w[L13 M14], hidden: true },
              {
                type: 'exchange',
                owner_type: 'player',
                when: 'owning_player_sr_turn',
                corporations: 'ipoed',
                from: 'ipo',
              },
            ],

          },
        ].freeze

        PRIVATE_ORDER = {
          'BT' => 1,
          'HH' => 2,
          'MA' => 3,
          'BS' => 4,
          'AC' => 5,
          'KK' => 6,
          'ML' => 7,
          'LA' => 8,
          'CPC' => 9,
          'TN' => 10,
          'AB' => 11,
          'NA' => 12,
          'LC' => 13,
          'AD' => 14,
          'AJ' => 15,
          'PB' => 16,
          'C' => 17,
          'DA' => 18,
          'MB' => 19,
          'LP' => 20,
          'MK' => 21,
          'DS' => 22,
          'M' => 23,
          'DJ' => 24,
          'DC' => 25,
          'CK' => 26,
          'G' => 27,
          'BI' => 28,
          'JB' => 29,
          'HB' => 30,
        }.freeze
      end
    end
  end
end
