# frozen_string_literal: true

module Engine
  module Game
    module G1858India
      module Map
        LAYOUT = :pointy
        AXES = { x: :number, y: :letter }.freeze

        LOCATION_NAMES = {
          'A4' => 'Kabul',
          'A6' => 'Peshawar',
          'B7' => 'Rawalapindi',
          'B9' => 'Srinigar',
          'C8' => 'Lahore',
          'C10' => 'Amritar & Ludhiana',
          'D1' => 'Quetta',
          'D5' => 'Multan',
          'D9' => 'Bhatinda',
          'D11' => 'Ambala & Saharanpur',
          'D13' => 'Meerut & Moradabad',
          'E2' => 'Shikapur',
          'E8' => 'Bikaner',
          'E12' => 'Delhi',
          'E14' => 'Bareilly',
          'E20' => 'Kathmandu',
          'E24' => 'Lhasa',
          'F7' => 'Jodhpur',
          'F9' => 'Jaipur',
          'F11' => 'Agra & Gwalior',
          'F13' => 'Cawnpore',
          'F15' => 'Lucknow',
          'F17' => 'Gorakhpur',
          'F21' => 'Darbhanga',
          'F23' => 'Darjeeling',
          'F25' => 'Gauhati',
          'G2' => 'Karachi',
          'G16' => 'Allahabad',
          'G18' => 'Benares',
          'G20' => 'Patna',
          'G22' => 'Bhagaipur',
          'H7' => 'Ahmadabad',
          'H11' => 'Bhopal',
          'H13' => 'Jubbulpore',
          'H21' => 'Assensole & Burdwan',
          'H25' => 'Dacca',
          'I4' => 'Jamnaga',
          'I6' => 'Baroda',
          'I10' => 'Indore',
          'I22' => 'Calcutta',
          'I24' => 'Khulna',
          'I26' => 'Chittagong',
          'J7' => 'Surat',
          'J11' => 'Amraoti',
          'J13' => 'Nagpur',
          'J15' => 'Raipur',
          'J19' => 'Cuttack',
          'K6' => 'Bombay',
          'K8' => 'Poona',
          'K14' => 'Warangal',
          'L7' => 'Kolhapur',
          'L9' => 'Solapur',
          'L13' => 'Hyderabad',
          'L17' => 'Visagapatam',
          'M10' => 'Bellary',
          'M14' => 'Bezawada',
          'O8' => 'Mangalore',
          'O10' => 'Mysore',
          'O12' => 'Bangalore',
          'O14' => 'Madras',
          'P11' => 'Coimbatore',
          'P13' => 'Trichinopoly',
          'Q10' => 'Cochin',
          'Q12' => 'Madura',
          'R11' => 'Trivandrum',

          # Province names.
          'B5' => 'NORTHWEST FRONTIER',
          'B11' => 'KASHMIR',
          'D3' => 'BALUCHISTAN',
          'D7' => 'PUNJAB',
          'E16' => 'NEPAL',
          'F3' => 'SIND',
          'F19' => 'UNITED PROVINCES',
          'G8' => 'RAJPUTANA',
          'G10' => 'CENTRAL INDIA',
          'H5' => 'GUJURAT',
          'H23' => 'ASSAM',
          'I14' => 'CENTRAL PROVINCES',
          'I20' => 'BENGAL',
          'K12' => 'HYDERABAD',
          'M8' => 'BOMBAY',
          'M12' => 'MADRAS',
          'N11' => 'MYSORE',
        }.freeze

        HEXES = {
          white: {
            %w[A6] =>
                    'city=revenue:0;' \
                    'upgrade=cost:40,terrain:mountain;' \
                    'border=type:province,edge:4;' \
                    'border=type:province,edge:5;',
            %w[A8] =>
                    'upgrade=cost:20,terrain:river;' \
                    'border=type:province,edge:0;' \
                    'border=type:province,edge:1;',
            %w[A10 A12 A14] =>
                    'upgrade=cost:120,terrain:mountain;',
            %w[B5] =>
                    'upgrade=cost:40,terrain:mountain;' \
                    'border=type:province,edge:0;' \
                    'border=type:province,edge:4;' \
                    'border=type:province,edge:5;',
            %w[B7] =>
                    'city=revenue:0;' \
                    'upgrade=cost:20,terrain:river;' \
                    'border=type:province,edge:1;' \
                    'border=type:province,edge:2;' \
                    'border=type:province,edge:3;' \
                    'border=type:province,edge:4;',
            %w[B9] =>
                    'town=revenue:0;' \
                    'upgrade=cost:80,terrain:mountain;' \
                    'border=type:province,edge:0;' \
                    'border=type:province,edge:1;' \
                    'border=type:province,edge:5;',
            %w[B11] =>
                    'upgrade=cost:120,terrain:mountain;' \
                    'border=type:province,edge:0;' \
                    'border=type:province,edge:5;',
            %w[B13] =>
                    'upgrade=cost:120,terrain:mountain;' \
                    'border=type:province,edge:0;',
            %w[C2] =>
                    'upgrade=cost:80,terrain:mountain;',
            %w[C4] =>
                    'upgrade=cost:40,terrain:mountain;' \
                    'border=type:province,edge:3;' \
                    'border=type:province,edge:4;' \
                    'border=type:province,edge:5;',
            %w[C6] =>
                    'upgrade=cost:40,terrain:river;' \
                    'border=type:province,edge:1;' \
                    'border=type:province,edge:2;',
            %w[C8] =>
                    'city=revenue:0;' \
                    'border=type:province,edge:3;',
            %w[C10] =>
                    'town=revenue:0;' \
                    'town=revenue:0;' \
                    'border=type:province,edge:2;' \
                    'border=type:province,edge:3;',
            %w[C12] =>
                    'upgrade=cost:80,terrain:mountain;' \
                    'border=type:province,edge:2;' \
                    'border=type:province,edge:3;' \
                    'border=type:province,edge:5;',
            %w[D1] =>
                    'town=revenue:0;' \
                    'upgrade=cost:40,terrain:mountain;' \
                    'border=type:province,edge:5;',
            %w[D3] =>
                    'upgrade=cost:40,terrain:mountain;' \
                    'border=type:province,edge:0;' \
                    'border=type:province,edge:4;' \
                    'border=type:province,edge:5;',
            %w[D5] =>
                    'city=revenue:0;' \
                    'upgrade=cost:40,terrain:river;' \
                    'border=type:province,edge:0;' \
                    'border=type:province,edge:1;' \
                    'border=type:province,edge:2;' \
                    'border=type:province,edge:5;',
            %w[D7] =>
                    'upgrade=cost:20,terrain:river;' \
                    'border=type:province,edge:0;' \
                    'border=type:province,edge:5;',
            %w[D9] =>
                    'town=revenue:0;' \
                    'border=type:province,edge:0;',
            %w[D11] =>
                    'town=revenue:0;' \
                    'town=revenue:0;' \
                    'border=type:province,edge:4;',
            %w[D13] =>
                    'town=revenue:0;' \
                    'town=revenue:0;' \
                    'border=type:province,edge:0;' \
                    'border=type:province,edge:1;' \
                    'border=type:province,edge:2;' \
                    'border=type:province,edge:4;',
            %w[D15] =>
                    'upgrade=cost:120,terrain:mountain;' \
                    'border=type:province,edge:0;' \
                    'border=type:province,edge:1;',
            %w[E2] =>
                    'town=revenue:0;' \
                    'border=type:province,edge:2;' \
                    'border=type:province,edge:3;',
            %w[E4] =>
                    'upgrade=cost:40,terrain:river;' \
                    'border=type:province,edge:2;' \
                    'border=type:province,edge:3;' \
                    'border=type:province,edge:4;',
            %w[E6] =>
                    'border=type:province,edge:0;' \
                    'border=type:province,edge:1;' \
                    'border=type:province,edge:2;' \
                    'border=type:province,edge:3;',
            %w[E8] =>
                    'town=revenue:0;' \
                    'border=type:province,edge:2;' \
                    'border=type:province,edge:3;' \
                    'border=type:province,edge:4;',
            %w[E10] =>
                    'border=type:province,edge:0;' \
                    'border=type:province,edge:1;' \
                    'border=type:province,edge:5;',
            %w[E14] =>
                    'town=revenue:0;' \
                    'upgrade=cost:20,terrain:river;' \
                    'border=type:province,edge:1;' \
                    'border=type:province,edge:3;' \
                    'border=type:province,edge:4;',
            %w[E16] =>
                    'upgrade=cost:120,terrain:mountain;' \
                    'border=type:province,edge:0;' \
                    'border=type:province,edge:1;' \
                    'border=type:province,edge:5;',
            %w[E18] =>
                    'upgrade=cost:120,terrain:mountain;' \
                    'border=type:province,edge:0;' \
                    'border=type:province,edge:5;',
            %w[F1] => '',
            %w[F3] =>
                    'upgrade=cost:40,terrain:river;',
            %w[F5] =>
                    'border=type:province,edge:3;' \
                    'border=type:province,edge:4;' \
                    'border=type:province,edge:5;',
            %w[F7] =>
                    'town=revenue:0;' \
                    'border=type:province,edge:1;',
            %w[F9] =>
                    'city=revenue:0;' \
                    'border=type:province,edge:3;' \
                    'border=type:province,edge:4;' \
                    'border=type:province,edge:5;',
            %w[F11] =>
                    'town=revenue:0;' \
                    'town=revenue:0;' \
                    'upgrade=cost:20,terrain:river;' \
                    'border=type:province,edge:1;' \
                    'border=type:province,edge:2;' \
                    'border=type:province,edge:3;' \
                    'border=type:province,edge:4;',
            %w[F13] =>
                    'city=revenue:0;' \
                    'upgrade=cost:20,terrain:river;' \
                    'border=type:province,edge:0;' \
                    'border=type:province,edge:1;' \
                    'border=type:province,edge:2;' \
                    'border=type:province,edge:5;',
            %w[F15] =>
                    'city=revenue:0;' \
                    'upgrade=cost:20,terrain:river;' \
                    'border=type:province,edge:0;' \
                    'border=type:province,edge:3;',
            %w[F17] =>
                    'town=revenue:0;' \
                    'upgrade=cost:20,terrain:river;' \
                    'border=type:province,edge:2;' \
                    'border=type:province,edge:3;',
            %w[F19] =>
                    'upgrade=cost:40,terrain:mountain;' \
                    'border=type:province,edge:2;' \
                    'border=type:province,edge:3;' \
                    'border=type:province,edge:4;' \
                    'border=type:province,edge:5;',
            %w[F21] =>
                    'town=revenue:0;' \
                    'upgrade=cost:20,terrain:river;' \
                    'border=type:province,edge:1;' \
                    'border=type:province,edge:2;',
            %w[F23] =>
                    'town=revenue:0;' \
                    'upgrade=cost:40,terrain:mountain;' \
                    'border=type:province,edge:4;' \
                    'border=type:province,edge:5;',
            %w[F25] =>
                    'town=revenue:0;' \
                    'upgrade=cost:40,terrain:river;' \
                    'border=type:province,edge:1;',
            %w[G2] =>
                    'city=revenue:0;' \
                    'label=Y;' \
                    'upgrade=cost:40,terrain:river;' \
                    'border=type:province,edge:5;',
            %w[G4] =>
                    'border=type:province,edge:0;' \
                    'border=type:province,edge:4;' \
                    'border=type:province,edge:5;',
            %w[G6] =>
                    'upgrade=cost:20,terrain:river;' \
                    'border=type:province,edge:0;' \
                    'border=type:province,edge:1;' \
                    'border=type:province,edge:2;' \
                    'border=type:province,edge:5;',
            %w[G8] =>
                    'upgrade=cost:40,terrain:mountain;' \
                    'border=type:province,edge:0;' \
                    'border=type:province,edge:4;' \
                    'border=type:province,edge:5;',
            %w[G10] =>
                    'border=type:province,edge:1;' \
                    'border=type:province,edge:2;',
            %w[G12] =>
                    'border=type:province,edge:3;' \
                    'border=type:province,edge:5;',
            %w[G14] =>
                    'upgrade=cost:20,terrain:river;' \
                    'border=type:province,edge:0;' \
                    'border=type:province,edge:2;' \
                    'border=type:province,edge:3;' \
                    'border=type:province,edge:4;' \
                    'border=type:province,edge:5;',
            %w[G16] =>
                    'city=revenue:0;' \
                    'upgrade=cost:40,terrain:river;' \
                    'border=type:province,edge:0;' \
                    'border=type:province,edge:1;' \
                    'border=type:province,edge:5;',
            %w[G18] =>
                    'town=revenue:0;' \
                    'upgrade=cost:40,terrain:river;' \
                    'border=type:province,edge:0;' \
                    'border=type:province,edge:4;' \
                    'border=type:province,edge:5;',
            %w[G20] =>
                    'city=revenue:0;' \
                    'upgrade=cost:40,terrain:river;' \
                    'border=type:province,edge:1;' \
                    'border=type:province,edge:2;',
            %w[G22] =>
                    'town=revenue:0;' \
                    'upgrade=cost:40,terrain:river;' \
                    'border=type:province,edge:4;' \
                    'border=type:province,edge:5;',
            %w[G24] =>
                    'upgrade=cost:40,terrain:river;' \
                    'border=type:province,edge:1;' \
                    'border=type:province,edge:2;',
            %w[G26] =>
                    'upgrade=cost:40,terrain:mountain;',
            %w[H3] =>
                    'upgrade=cost:40,terrain:river;' \
                    'border=type:province,edge:2;' \
                    'border=type:province,edge:3;' \
                    'border=type:impassible,edge:5;',
            %w[H5] =>
                    'upgrade=cost:40,terrain:river;' \
                    'border=type:province,edge:2;' \
                    'border=type:province,edge:3;',
            %w[H7] =>
                    'city=revenue:0;' \
                    'border=type:province,edge:2;' \
                    'border=type:province,edge:3;' \
                    'border=type:province,edge:4;' \
                    'border=type:province,edge:5;',
            %w[H9] =>
                    'border=type:province,edge:1;' \
                    'border=type:province,edge:2;',
            %w[H11] =>
                    'town=revenue:0;' \
                    'border=type:province,edge:4;' \
                    'border=type:province,edge:5;',
            %w[H13] =>
                    'town=revenue:0;' \
                    'border=type:province,edge:1;' \
                    'border=type:province,edge:2;' \
                    'border=type:province,edge:3;',
            %w[H15] =>
                    'border=type:province,edge:2;' \
                    'border=type:province,edge:3;' \
                    'border=type:province,edge:4;',
            %w[H17] =>
                    'upgrade=cost:40,terrain:mountain;' \
                    'border=type:province,edge:0;' \
                    'border=type:province,edge:1;' \
                    'border=type:province,edge:2;' \
                    'border=type:province,edge:3;',
            %w[H19] =>
                    'upgrade=cost:40,terrain:mountain;' \
                    'border=type:province,edge:2;',
            %w[H21] =>
                    'town=revenue:0;' \
                    'town=revenue:0;' \
                    'upgrade=cost:20,terrain:river;' \
                    'border=type:province,edge:4;',
            %w[H23] =>
                    'upgrade=cost:60,terrain:river;' \
                    'border=type:province,edge:0;' \
                    'border=type:province,edge:1;' \
                    'border=type:province,edge:2;',
            %w[H25] =>
                    'city=revenue:0;' \
                    'upgrade=cost:40,terrain:river;',
            %w[I4] =>
                    'town=revenue:0;' \
                    'border=type:impassible,edge:2;',
            %w[I6] =>
                    'town=revenue:0;' \
                    'border=type:province,edge:4;' \
                    'border=type:province,edge:5;',
            %w[I8] =>
                    'upgrade=cost:20,terrain:river;' \
                    'border=type:province,edge:0;' \
                    'border=type:province,edge:1;' \
                    'border=type:province,edge:2;' \
                    'border=type:province,edge:5;',
            %w[I10] =>
                    'town=revenue:0;' \
                    'border=type:province,edge:0;' \
                    'border=type:province,edge:4;' \
                    'border=type:province,edge:5;',
            %w[I12] =>
                    'upgrade=cost:40,terrain:mountain;' \
                    'border=type:province,edge:1;' \
                    'border=type:province,edge:2;',
            %w[I14] =>
                    'upgrade=cost:40,terrain:mountain;',
            %w[I16] =>
                    'upgrade=cost:40,terrain:mountain;' \
                    'border=type:province,edge:3;' \
                    'border=type:province,edge:4;',
            %w[I18] =>
                    'border=type:province,edge:0;' \
                    'border=type:province,edge:1;',
            %w[I20] => '',
            %w[I24] =>
                    'town=revenue:0;' \
                    'upgrade=cost:40,terrain:river;' \
                    'border=type:province,edge:1;',
            %w[J7] =>
                    'town=revenue:0;' \
                    'border=type:province,edge:2;' \
                    'border=type:province,edge:3;' \
                    'border=type:province,edge:4;',
            %w[J9] =>
                    'border=type:province,edge:0;' \
                    'border=type:province,edge:1;' \
                    'border=type:province,edge:2;' \
                    'border=type:province,edge:3;' \
                    'border=type:province,edge:5;',
            %w[J11] =>
                    'town=revenue:0;' \
                    'border=type:province,edge:0;' \
                    'border=type:province,edge:2;' \
                    'border=type:province,edge:5;',
            %w[J13] =>
                    'city=revenue:0;' \
                    'border=type:province,edge:0;' \
                    'border=type:province,edge:5;',
            %w[J15] =>
                    'town=revenue:0;' \
                    'border=type:province,edge:0;',
            %w[J17] =>
                    'upgrade=cost:20,terrain:river;' \
                    'border=type:province,edge:3;' \
                    'border=type:province,edge:4;',
            %w[J19] =>
                    'town=revenue:0;' \
                    'upgrade=cost:20,terrain:river;' \
                    'border=type:province,edge:0;' \
                    'border=type:province,edge:1;',
            %w[J21] =>
                    'upgrade=cost:40,terrain:river;',
            %w[K6] =>
                    'city=revenue:0;' \
                    'label=Y;',
            %w[K8] =>
                    'town=revenue:0;' \
                    'upgrade=cost:40,terrain:mountain;' \
                    'border=type:province,edge:3;' \
                    'border=type:province,edge:4;',
            %w[K10] =>
                    'border=type:province,edge:0;' \
                    'border=type:province,edge:1;' \
                    'border=type:province,edge:2;' \
                    'border=type:province,edge:3;',
            %w[K12] =>
                    'upgrade=cost:20,terrain:river;' \
                    'border=type:province,edge:2;' \
                    'border=type:province,edge:3;',
            %w[K14] =>
                    'town=revenue:0;' \
                    'upgrade=cost:20,terrain:river;' \
                    'border=type:province,edge:2;' \
                    'border=type:province,edge:3;' \
                    'border=type:province,edge:4;',
            %w[K16] =>
                    'upgrade=cost:40,terrain:mountain;' \
                    'border=type:province,edge:0;' \
                    'border=type:province,edge:1;',
            %w[K18] =>
                    'border=type:province,edge:3;' \
                    'border=type:province,edge:4;',
            %w[K20] =>
                    'upgrade=cost:40,terrain:river;' \
                    'border=type:province,edge:1;',
            %w[L7] =>
                    'town=revenue:0;' \
                    'upgrade=cost:40,terrain:mountain;',
            %w[L9] =>
                    'town=revenue:0;' \
                    'border=type:province,edge:3;' \
                    'border=type:province,edge:4;' \
                    'border=type:province,edge:5;',
            %w[L11] =>
                    'border=type:province,edge:0;' \
                    'border=type:province,edge:1;' \
                    'border=type:province,edge:5;',
            %w[L13] =>
                    'city=revenue:0;' \
                    'border=type:province,edge:0;',
            %w[L15] =>
                    'upgrade=cost:20,terrain:river;' \
                    'border=type:province,edge:3;' \
                    'border=type:province,edge:4;',
            %w[L17] =>
                    'town=revenue:0;' \
                    'border=type:province,edge:0;' \
                    'border=type:province,edge:1;',
            %w[M8] =>
                    'upgrade=cost:40,terrain:mountain;' \
                    'border=type:province,edge:4;' \
                    'border=type:province,edge:5;',
            %w[M10] =>
                    'town=revenue:0;' \
                    'border=type:province,edge:0;' \
                    'border=type:province,edge:1;' \
                    'border=type:province,edge:2;' \
                    'border=type:province,edge:3;' \
                    'border=type:province,edge:5;',
            %w[M12] =>
                    'border=type:province,edge:0;' \
                    'border=type:province,edge:2;' \
                    'border=type:province,edge:3;' \
                    'border=type:province,edge:4;',
            %w[M14] =>
                    'town=revenue:0;' \
                    'border=type:province,edge:0;' \
                    'border=type:province,edge:1;',
            %w[M16] =>
                    'upgrade=cost:40,terrain:river;' \
                    'border=type:province,edge:3;',
            %w[N7] =>
                    'border=type:province,edge:4;' \
                    'border=type:impassible,edge:5;',
            %w[N9] =>
                    'upgrade=cost:40,terrain:mountain;' \
                    'border=type:province,edge:0;' \
                    'border=type:province,edge:1;' \
                    'border=type:province,edge:2;' \
                    'border=type:province,edge:3;',
            %w[N11] =>
                    'border=type:province,edge:2;' \
                    'border=type:province,edge:3;' \
                    'border=type:province,edge:4;',
            %w[N13] =>
                    'upgrade=cost:20,terrain:river;' \
                    'border=type:province,edge:0;' \
                    'border=type:province,edge:1;' \
                    'border=type:province,edge:3;',
            %w[O8] =>
                    'town=revenue:0;' \
                    'border=type:impassible,edge:2;' \
                    'border=type:province,edge:3;' \
                    'border=type:province,edge:4;',
            %w[O10] =>
                    'city=revenue:0;' \
                    'upgrade=cost:40,terrain:mountain;' \
                    'border=type:province,edge:0;' \
                    'border=type:province,edge:1;' \
                    'border=type:province,edge:5;',
            %w[O12] =>
                    'city=revenue:0;' \
                    'border=type:province,edge:0;' \
                    'border=type:province,edge:3;' \
                    'border=type:province,edge:4;' \
                    'border=type:province,edge:5;',
            %w[O14] =>
                    'city=revenue:0;' \
                    'label=Y;' \
                    'border=type:province,edge:1;',
            %w[P9] =>
                    'border=type:province,edge:3;',
            %w[P11] =>
                    'town=revenue:0;' \
                    'upgrade=cost:40,terrain:mountain;' \
                    'border=type:province,edge:2;' \
                    'border=type:province,edge:3;',
            %w[P13] =>
                    'city=revenue:0;' \
                    'border=type:province,edge:2;',
            %w[Q10 Q12 R11] =>
                    'town=revenue:0;',
          },

          yellow: {
            %w[E12] =>
                    'city=revenue:30,groups:Delhi;' \
                    'city=revenue:30,groups:Delhi;' \
                    'city=revenue:30,groups:Delhi;' \
                    'path=a:0,b:_0;' \
                    'path=a:2,b:_1;' \
                    'path=a:4,b:_2;' \
                    'border=type:province,edge:0;' \
                    'border=type:province,edge:3;' \
                    'border=type:province,edge:4;' \
                    'border=type:province,edge:5;',
            %w[I22] =>
                    'city=revenue:30,groups:Calcutta;' \
                    'city=revenue:30,groups:Calcutta;' \
                    'city=revenue:30,groups:Calcutta;' \
                    'path=a:0,b:_0;' \
                    'path=a:2,b:_1;' \
                    'path=a:4,b:_2;' \
                    'border=type:province,edge:3;' \
                    'border=type:province,edge:4;',
          },

          red: {
            %w[A4] =>
                    'offboard=revenue:yellow_20|green_30|brown_40|gray_40;' \
                    'path=track:dual,a:4,b:_0;',
            %w[E20] =>
                    'offboard=revenue:yellow_20|green_30|brown_40|gray_40;' \
                    'path=track:dual,a:0,b:_0;' \
                    'border=type:province,edge:0;' \
                    'border=type:province,edge:5;',
            %w[E24] =>
                    'offboard=revenue:yellow_20|green_30|brown_40|gray_40;' \
                    'path=track:dual,a:0,b:_0;',
          },

          gray: {
            %w[I26] =>
                    'town=revenue:20;' \
                    'path=a:2,b:_0;',
          },

          blue: {
            %w[H1 I2 J3 J25 K22 L5 L19 L21 M6 M18 N5 N17 O6 O16 P7 Q8 Q14 R9 R13 S10 S12] => '',
            %w[J5] =>
                    'path=a:2,b:3;' \
                    'path=a:5,b:5,terminal:1,ignore:1;',
            %w[J23] =>
                    'path=a:2,b:2,terminal:1,ignore:1;',
            %w[K4] =>
                    'path=a:4,b:4,terminal:1,ignore:1;',
            %w[N15] =>
                    'path=a:0,b:0,terminal:1,ignore:1;',
            %w[P15] =>
                    'path=a:2,b:2,terminal:1,ignore:1;',
          },
        }.freeze
      end
    end
  end
end
