# frozen_string_literal: true

require_relative 'meta'
require_relative '../base'

module Engine
  module Game
    module G1841
      module Entities
        def game_companies
          companies = [
            {
              name: '1 Società della Strada di Ferro da Napoli a Nocera e Castellamunare',
              sym: 'Bayard',
              value: 50,
              revenue: 20,
              desc: 'Pays L.20 at the end of each Stock Round',
              corporation: nil,
              color: 'black',
              text_color: 'white',
            },
          ]
          unless lite?
            companies << {
              name: '2 Società della Strada Ferrata da Lucca a Pistoia',
              sym: 'SFLP',
              value: 50,
              revenue: 0,
              desc: 'Can start the SFLP Minor Corporation',
              corporation: 'SFLP',
              color: 'lightGreen',
            }
          end
          companies << {
            name: '3 Strada di Ferro da Torino a Cuneo',
            sym: 'SFTC',
            value: 50,
            revenue: 0,
            desc: "Can start the SFTC #{version == 1 ? 'Minor' : 'Major'} Corporation",
            corporation: 'SFTC',
            color: 'yellow',
          }
          unless lite?
            companies << {
              name: '4 Società per la Strada Ferrata Maria Antonia',
              sym: 'SFMA',
              value: 50,
              revenue: 0,
              desc: 'Can start the SFMA Minor Corporation',
              corporation: 'SFMA',
              color: 'red',
              text_color: 'white',
            }
          end
          companies << {
            name: '5 Strada di Ferro da Torino a Novara',
            sym: 'SFTN',
            value: 50,
            revenue: 0,
            desc: 'Can start the SFTN Major Corporation',
            corporation: 'SFTN',
            color: 'sandyBrown',
          }
          unless lite?
            companies << {
              name: '6 Società per la Strada Ferrata Leopolda',
              sym: 'SSFL',
              value: 50,
              revenue: 0,
              desc: 'Can start the SSFL Major Corporation',
              corporation: 'SSFL',
              color: 'purple',
              text_color: 'white',
            }
          end
          companies << {
            name: '7 Strada Ferrata da Torino a Genova',
            sym: 'SFTG',
            value: 50,
            revenue: 0,
            desc: 'Can start the SFTG Major Corporation',
            corporation: 'SFTG',
            color: 'blue',
            text_color: 'white',
          }
          companies << {
            name: '8 Imperial Regia Strada Ferrata Ferdinandea',
            sym: 'IRSFF',
            value: 50,
            revenue: 0,
            desc: 'Can start the IRSFF Major Corporation',
            corporation: 'IRSFF',
            color: 'orange',
            text_color: 'white',
          }
          companies
        end

        def game_corporations
          corporations = []
          unless lite?
            corporations << {
              sym: 'SFMA',
              name: 'Strada Ferrata Maria Antonia',
              logo: '1841/SFMA',
              simple_logo: '1841/SFMA.alt',
              coordinates: 'R14',
              city: version == 1 ? 1 : nil,
              color: 'red',
              tokens: [0],
              type: 'minor',
              shares: [40, 20, 20, 20],
              float_percent: 40,
              max_ownership_percent: 60,
              always_market_price: true,
              corporation_can_ipo: true,
              historical: true,
              startable: true,
            }
          end
          unless lite?
            corporations << {
              sym: 'SFLP',
              name: 'Strada Ferrata da Lucca a Pistoia',
              logo: '1841/SFLP',
              simple_logo: '1841/SFLP.alt',
              coordinates: 'P12',
              color: 'lightGreen',
              text_color: 'black',
              tokens: [0],
              type: 'minor',
              shares: [40, 20, 20, 20],
              float_percent: 40,
              max_ownership_percent: 60,
              always_market_price: true,
              corporation_can_ipo: true,
              historical: true,
              startable: true,
            }
          end
          unless lite?
            corporations << {
              sym: 'SSFL',
              name: 'Società per la Strada Ferrata Leopolda',
              logo: '1841/SSFL',
              simple_logo: '1841/SSFL.alt',
              coordinates: 'Q11',
              color: 'purple',
              text_color: 'white',
              tokens: [0, 0],
              type: 'major',
              shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
              float_percent: 20,
              max_ownership_percent: 60,
              always_market_price: true,
              corporation_can_ipo: true,
              historical: true,
              startable: true,
            }
          end
          corporations << {
            sym: 'IRSFF',
            name: 'Imperial Regia Strada Ferrata Ferdinandea',
            logo: '1841/IRSFF',
            simple_logo: '1841/IRSFF.alt',
            coordinates: %w[F8 F16],
            color: 'orange',
            tokens: [0, 0],
            type: 'major',
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            float_percent: 20,
            max_ownership_percent: 60,
            always_market_price: true,
            corporation_can_ipo: true,
            historical: true,
            startable: true,
          }
          corporations << {
            sym: 'SFTG',
            name: 'Strada Ferrata da Torino a Genova',
            logo: '1841/SFTG',
            simple_logo: '1841/SFTG.alt',
            coordinates: %w[H4 J6],
            city: 0,
            color: 'blue',
            tokens: [0, 0],
            type: 'major',
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            float_percent: 20,
            max_ownership_percent: 60,
            always_market_price: true,
            corporation_can_ipo: true,
            historical: true,
            startable: true,
          }
          corporations << {
            sym: 'SFTN',
            name: 'Strada di Ferro da Torino a Novara',
            logo: '1841/SFTN',
            simple_logo: '1841/SFTN.alt',
            coordinates: 'H4',
            city: 1,
            color: 'sandyBrown',
            text_color: 'black',
            tokens: [0, 0],
            type: 'major',
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            float_percent: 20,
            max_ownership_percent: 60,
            always_market_price: true,
            corporation_can_ipo: true,
            historical: true,
            startable: true,
          }
          corporations << {
            sym: 'SFTC',
            name: 'Strada di Ferro da Torino a Cuneo',
            logo: version == 1 ? '1841/SFTC_V1' : '1841/SFTC_V2',
            simple_logo: '1841/SFTC.alt',
            coordinates: 'M3',
            color: 'yellow',
            text_color: 'black',
            tokens: version == 1 ? [0] : [0, 0],
            type: version == 1 ? 'minor' : 'major',
            shares: version == 1 ? [40, 20, 20, 20] : [20, 10, 10, 10, 10, 10, 10, 10, 10],
            float_percent: version == 1 ? 40 : 20,
            max_ownership_percent: 60,
            always_market_price: true,
            corporation_can_ipo: true,
            historical: true,
            startable: true,
          }
          unless lite?
            corporations << {
              sym: 'SFLi',
              name: 'Strade Ferrate Livornesi',
              logo: '1841/SFLI',
              simple_logo: '1841/SFLI.alt',
              color: 'brown',
              tokens: [0, 0],
              type: 'major',
              shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
              float_percent: 20,
              max_ownership_percent: 60,
              always_market_price: true,
              corporation_can_ipo: true,
              historical: true,
              startable: false,
            }
          end
          if version == 1
            corporations << {
              # version 1
              sym: 'SFV',
              name: 'Strade di Ferro Venete',
              logo: '1841/SFV',
              simple_logo: '1841/SFV.alt',
              color: 'gold',
              text_color: 'black',
              tokens: [0],
              type: 'minor',
              shares: [40, 20, 20, 20],
              float_percent: 40,
              max_ownership_percent: 60,
              always_market_price: true,
              corporation_can_ipo: true,
              historical: true,
              startable: false,
            }
          end
          if version == 2
            corporations << {
              # version 2
              sym: 'SB',
              name: "Strade Ferrate del Sud dell'Austria",
              logo: '1841/SB',
              simple_logo: '1841/SB.alt',
              color: 'gold',
              text_color: 'black',
              tokens: [0, 0],
              type: 'major',
              shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
              float_percent: 20,
              max_ownership_percent: 60,
              always_market_price: true,
              corporation_can_ipo: true,
              historical: true,
              startable: false,
            }
          end
          corporations << {
            sym: 'SFL',
            name: "Strade Ferrate della Lombardia & dell'Italia Centrale",
            logo: version == 1 ? '1841/SFL_V1' : '1841/SFL_V2',
            simple_logo: '1841/SFL.alt',
            color: 'lightBlue',
            text_color: 'black',
            tokens: version == 1 ? [0] : [0, 0],
            type: version == 1 ? 'minor' : 'major',
            shares: version == 1 ? [40, 20, 20, 20] : [20, 10, 10, 10, 10, 10, 10, 10, 10],
            float_percent: version == 1 ? 40 : 20,
            max_ownership_percent: 60,
            always_market_price: true,
            corporation_can_ipo: true,
            historical: true,
            startable: false,
          }

          corporations.concat([{
                                sym: 'AFI',
                                name: 'Azienda Ferroviaria Italica',
                                logo: '1841/AFI',
                                simple_logo: '1841/AFI.alt',
                                color: 'red',
                                tokens: [0, 0],
                                type: 'major',
                                shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
                                float_percent: 20,
                                max_ownership_percent: 60,
                                always_market_price: true,
                                corporation_can_ipo: true,
                                historical: false,
                                startable: true,
                              },
                               {
                                 sym: 'ATFA',
                                 name: 'Azienda Trasporti Ferroviari Ausonia',
                                 logo: '1841/ATFA',
                                 simple_logo: '1841/ATFA.alt',
                                 color: 'orange',
                                 tokens: [0, 0],
                                 type: 'major',
                                 shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
                                 float_percent: 20,
                                 max_ownership_percent: 60,
                                 always_market_price: true,
                                 corporation_can_ipo: true,
                                 historical: false,
                                 startable: true,
                               },
                               {
                                 sym: 'CFCC',
                                 name: 'Compagnia Ferroviaria Conte di Cavour',
                                 logo: '1841/CFCC',
                                 simple_logo: '1841/CFCC.alt',
                                 color: 'lightGreen',
                                 text_color: 'black',
                                 tokens: [0, 0],
                                 type: 'major',
                                 shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
                                 float_percent: 20,
                                 max_ownership_percent: 60,
                                 always_market_price: true,
                                 corporation_can_ipo: true,
                                 historical: false,
                                 startable: true,
                               },
                               {
                                 sym: 'CGTF',
                                 name: 'Compagnia Garibaldi per i Trasporti Ferroviari',
                                 logo: '1841/CGTF',
                                 simple_logo: '1841/CGTF.alt',
                                 color: 'green',
                                 tokens: [0, 0],
                                 type: 'major',
                                 shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
                                 float_percent: 20,
                                 max_ownership_percent: 60,
                                 always_market_price: true,
                                 corporation_can_ipo: true,
                                 historical: false,
                                 startable: true,
                               },
                               {
                                 sym: 'CTDA',
                                 name: 'Compagnia Trasporti Dante Alighieri',
                                 logo: '1841/CTDA',
                                 simple_logo: '1841/CTDA.alt',
                                 color: 'lime',
                                 text_color: 'black',
                                 tokens: [0, 0],
                                 type: 'major',
                                 shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
                                 float_percent: 20,
                                 max_ownership_percent: 60,
                                 always_market_price: true,
                                 corporation_can_ipo: true,
                                 historical: false,
                                 startable: true,
                               },
                               {
                                 sym: 'CTS',
                                 name: 'Compagnia Trasporti Subalpini',
                                 logo: '1841/CTS',
                                 simple_logo: '1841/CTS.alt',
                                 color: 'turquoise',
                                 tokens: [0, 0],
                                 type: 'major',
                                 shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
                                 float_percent: 20,
                                 max_ownership_percent: 60,
                                 always_market_price: true,
                                 corporation_can_ipo: true,
                                 historical: false,
                                 startable: true,
                               },
                               {
                                 sym: 'ICSF',
                                 name: 'Impresa Centrale Strade Ferrate',
                                 logo: '1841/ICSF',
                                 simple_logo: '1841/ICSF.alt',
                                 color: 'navy',
                                 tokens: [0, 0],
                                 type: 'major',
                                 shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
                                 float_percent: 20,
                                 max_ownership_percent: 60,
                                 always_market_price: true,
                                 corporation_can_ipo: true,
                                 historical: false,
                                 startable: true,
                               },
                               {
                                 sym: 'IFAI',
                                 name: 'Impresa Ferroviaria Alta Italia',
                                 logo: '1841/IFAI',
                                 simple_logo: '1841/IFAI.alt',
                                 color: 'violet',
                                 tokens: [0, 0],
                                 type: 'major',
                                 shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
                                 float_percent: 20,
                                 max_ownership_percent: 60,
                                 always_market_price: true,
                                 corporation_can_ipo: true,
                                 historical: false,
                                 startable: true,
                               },
                               {
                                 sym: 'ILTF',
                                 name: 'Impresa Latina Trasporti su Ferro',
                                 logo: '1841/ILTF',
                                 simple_logo: '1841/ILTF.alt',
                                 color: 'pink',
                                 text_color: 'black',
                                 tokens: [0, 0],
                                 type: 'major',
                                 shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
                                 float_percent: 20,
                                 max_ownership_percent: 60,
                                 always_market_price: true,
                                 corporation_can_ipo: true,
                                 historical: false,
                                 startable: true,
                               },
                               {
                                 sym: 'RATF',
                                 name: 'Regia Azienda Trasporti Ferroviari',
                                 logo: '1841/RATF',
                                 simple_logo: '1841/RATF.alt',
                                 color: 'lavender',
                                 text_color: 'black',
                                 tokens: [0, 0],
                                 type: 'major',
                                 shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
                                 float_percent: 20,
                                 max_ownership_percent: 60,
                                 always_market_price: true,
                                 corporation_can_ipo: true,
                                 historical: false,
                                 startable: true,
                               },
                               {
                                 sym: 'RSFS',
                                 name: 'Reale Società Ferroviaria Sabauda',
                                 logo: '1841/RSFS',
                                 simple_logo: '1841/RSFS.alt',
                                 color: 'bisque',
                                 text_color: 'black',
                                 tokens: [0, 0],
                                 type: 'major',
                                 shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
                                 float_percent: 20,
                                 max_ownership_percent: 60,
                                 always_market_price: true,
                                 corporation_can_ipo: true,
                                 historical: false,
                                 startable: true,
                               },
                               {
                                 sym: 'CTLP',
                                 name: 'Compagnia Trasporti La Patria',
                                 logo: '1841/CTLP',
                                 simple_logo: '1841/CTLP.alt',
                                 color: 'white',
                                 text_color: 'black',
                                 tokens: [0],
                                 type: 'minor',
                                 shares: [40, 20, 20, 20],
                                 float_percent: 40,
                                 max_ownership_percent: 60,
                                 always_market_price: true,
                                 corporation_can_ipo: true,
                                 historical: false,
                                 startable: true,
                               },
                               {
                                 sym: 'FTP',
                                 name: 'Ferrovie Trans Padane',
                                 logo: '1841/FTP',
                                 simple_logo: '1841/FTP.alt',
                                 color: 'gray',
                                 tokens: [0],
                                 type: 'minor',
                                 shares: [40, 20, 20, 20],
                                 float_percent: 40,
                                 max_ownership_percent: 60,
                                 always_market_price: true,
                                 corporation_can_ipo: true,
                                 historical: false,
                                 startable: true,
                               },
                               {
                                 sym: 'SLDV',
                                 name: 'Società Leonardo Da Vinci',
                                 logo: '1841/SLDV',
                                 simple_logo: '1841/SLDV.alt',
                                 color: 'black',
                                 tokens: [0],
                                 type: 'minor',
                                 shares: [40, 20, 20, 20],
                                 float_percent: 40,
                                 max_ownership_percent: 60,
                                 always_market_price: true,
                                 corporation_can_ipo: true,
                                 historical: false,
                                 startable: true,
                               },
                               {
                                 sym: 'Holding',
                                 name: 'Tuscan Merge Holding',
                                 logo: '1841/H',
                                 simple_logo: '1841/H.alt',
                                 color: 'black',
                                 tokens: [0, 0],
                                 type: 'major',
                                 shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
                                 float_percent: 20,
                                 max_ownership_percent: 60,
                                 always_market_price: true,
                                 corporation_can_ipo: true,
                                 historical: true,
                                 startable: false,
                               }])
          corporations
        end
      end
    end
  end
end
