# frozen_string_literal: true

require_relative 'meta'
require_relative '../base'

module Engine
  module Game
    module G1841
      module Entities
        COMPANIES = [
          {
            name: 'Società della Strada di Ferro da Napoli a Nocera e Castellamunare',
            sym: 'Bayard',
            value: 50,
            revenue: 20,
            desc: 'Pays L.50 at the end of each Stock Round',
            corporation: nil,
          },
          {
            name: 'Società della Dtrada Ferrata da Lucca a Pistoia',
            sym: 'SFLP',
            value: 50,
            revenue: 0,
            desc: 'Can start the SFLP Minor Corporation',
            corporation: 'SFLP',
          },
          {
            name: 'Strada di Ferro da Torino a Cuneo',
            sym: 'SFTC',
            value: 50,
            revenue: 0,
            desc: 'Can start the SFTC Major Corporation', # version 2
            corporation: 'SFTC',
          },
          {
            name: 'Società per la Strada Ferrata Maria Autonia',
            sym: 'SFMA',
            value: 50,
            revenue: 0,
            desc: 'Can start the SFMA Minor Corporation',
            corporation: 'SFMA',
          },
          {
            name: 'Strada di Ferro da Torina a Novara',
            sym: 'SFTN',
            value: 50,
            revenue: 0,
            desc: 'Can start the SFTN Major Corporation',
            corporation: 'SFTN',
          },
          {
            name: 'Società per la Strada Ferrata Leopolda',
            sym: 'SSFL',
            value: 50,
            revenue: 0,
            desc: 'Can start the SSFL Major Corporation',
            corporation: 'SSFL',
          },
          {
            name: 'Strada Ferrata da Torino a Genova',
            sym: 'SFTG',
            value: 50,
            revenue: 0,
            desc: 'Can start the SFTG Major Corporation',
            corporation: 'SFTG',
          },
          {
            name: 'Imperial Regia Strada Ferrata Ferdinandea',
            sym: 'IRSFF',
            value: 50,
            revenue: 0,
            desc: 'Can start the IRSFF Major Corporation',
            corporation: 'IRSFF',
          },
        ].freeze

        CORPORATIONS = [
          {
            sym: 'SFMA',
            name: 'Strada Ferrata Maria Antonia',
            logo: '1841/SFMA',
            coordinates: 'R14',
            color: 'red',
            tokens: [50],
            type: 'minor',
            shares: [40, 20, 20, 20],
            float_percent: 40,
            max_ownership_percent: 60,
            always_market_price: true,
            historical: true,
            startable: true,
          },
          {
            sym: 'SFLP',
            name: 'Strada Ferrata da Lucca a Pistoia',
            logo: '1841/SFLP',
            coordinates: 'P12',
            color: 'lightGreen',
            text_color: 'black',
            tokens: [50],
            type: 'minor',
            shares: [40, 20, 20, 20],
            float_percent: 40,
            max_ownership_percent: 60,
            always_market_price: true,
            historical: true,
            startable: true,
          },
          {
            sym: 'SSFL',
            name: 'Società per la Strada Ferrata Leopolda',
            logo: '1841/SSFL',
            coordinates: 'Q11',
            color: 'violet',
            tokens: [50, 50],
            type: 'major',
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            float_percent: 20,
            max_ownership_percent: 60,
            always_market_price: true,
            historical: true,
            startable: true,
          },
          {
            sym: 'IRSFF',
            name: 'Imperial Regia Strada Ferrata Ferdinandea',
            logo: '1841/IRSFF',
            coordinates: %w[F8 F16],
            color: 'orange',
            tokens: [50, 50],
            type: 'major',
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            float_percent: 20,
            max_ownership_percent: 60,
            always_market_price: true,
            historical: true,
            startable: true,
          },
          {
            sym: 'SFTG',
            name: 'Strada Ferrata da Torina a Genova',
            logo: '1841/SFTG',
            coordinates: %w[H4 J6],
            city: 0,
            color: 'blue',
            tokens: [50, 50],
            type: 'major',
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            float_percent: 20,
            max_ownership_percent: 60,
            always_market_price: true,
            historical: true,
            startable: true,
          },
          {
            sym: 'SFTN',
            name: 'Strada di Ferro da Torina a Novara',
            logo: '1841/SFTN',
            coordinates: 'H4',
            city: 1,
            color: 'sandyBrown',
            text_color: 'black',
            tokens: [50, 50],
            type: 'major',
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            float_percent: 20,
            max_ownership_percent: 60,
            always_market_price: true,
            historical: true,
            startable: true,
          },
          {
            sym: 'SFTC',
            name: 'Strada di Ferro da Torino a Cuneo',
            logo: '1841/SFTC_V2',
            coordinates: 'M3',
            color: 'yellow',
            text_color: 'black',
            tokens: [50, 50],
            type: 'major', # version 2
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10], # version 2
            float_percent: 20, # version 2
            max_ownership_percent: 60,
            always_market_price: true,
            historical: true,
            startable: true,
          },
          {
            sym: 'SFLi',
            name: 'Strade Ferrate Livornesi',
            logo: '1841/SFLI',
            color: 'brown',
            tokens: [],
            type: 'major',
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            float_percent: 20,
            max_ownership_percent: 60,
            always_market_price: true,
            historical: true,
            startable: false,
          },
          # version 2
          {
            sym: 'SB',
            name: "Strade Ferrate del Sud dell'Austria",
            logo: '1841/SB',
            color: 'gold',
            text_color: 'black',
            tokens: [],
            type: 'major',
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            float_percent: 20,
            max_ownership_percent: 60,
            always_market_price: true,
            historical: true,
            startable: false,
          },
          {
            sym: 'SFL',
            name: "Strade Ferrate della Lombardia & dell'Italia Centrale",
            logo: '1841/SFL_V2',
            color: 'lightBlue',
            text_color: 'black',
            tokens: [],
            type: 'major',
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            float_percent: 20,
            max_ownership_percent: 60,
            always_market_price: true,
            historical: true,
            startable: false,
          },
          {
            sym: 'AFI',
            name: 'Azienda Ferroviaria Italica',
            logo: '1841/AFI',
            color: 'red',
            tokens: [],
            type: 'major',
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            float_percent: 20,
            max_ownership_percent: 60,
            always_market_price: true,
            historical: false,
            startable: true,
          },
          {
            sym: 'ATFA',
            name: 'Azienda Trasporti Ferroviari Ausonia',
            logo: '1841/ATFA',
            color: 'orange',
            tokens: [],
            type: 'major',
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            float_percent: 20,
            max_ownership_percent: 60,
            always_market_price: true,
            historical: false,
            startable: true,
          },
          {
            sym: 'CFCC',
            name: 'Compagnia Ferroviaria Conte di Cavour',
            logo: '1841/CFCC',
            color: 'lightGreen',
            text_color: 'black',
            tokens: [],
            type: 'major',
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            float_percent: 20,
            max_ownership_percent: 60,
            always_market_price: true,
            historical: false,
            startable: true,
          },
          {
            sym: 'CGTF',
            name: 'Compagnia Garibaldi per i Trasporti Ferroviari',
            logo: '1841/CGTF',
            color: 'green',
            tokens: [],
            type: 'major',
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            float_percent: 20,
            max_ownership_percent: 60,
            always_market_price: true,
            historical: false,
            startable: true,
          },
          {
            sym: 'CTDA',
            name: 'Compagnia Trasporti Dante Alighieri',
            logo: '1841/CTDA',
            color: 'lime',
            text_color: 'black',
            tokens: [],
            type: 'major',
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            float_percent: 20,
            max_ownership_percent: 60,
            always_market_price: true,
            historical: false,
            startable: true,
          },
          {
            sym: 'CTS',
            name: 'Compagnia Trasporti Subalpini',
            logo: '1841/CTS',
            color: 'turquoise',
            tokens: [],
            type: 'major',
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            float_percent: 20,
            max_ownership_percent: 60,
            always_market_price: true,
            historical: false,
            startable: true,
          },
          {
            sym: 'ICSF',
            name: 'Impresa Centrale Strade Ferrate',
            logo: '1841/ICSF',
            color: 'navy',
            tokens: [],
            type: 'major',
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            float_percent: 20,
            max_ownership_percent: 60,
            always_market_price: true,
            historical: false,
            startable: true,
          },
          {
            sym: 'IFAI',
            name: 'Impresa Ferroviaria Alta Italia',
            logo: '1841/IFAI',
            color: 'violet',
            tokens: [],
            type: 'major',
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            float_percent: 20,
            max_ownership_percent: 60,
            always_market_price: true,
            historical: false,
            startable: true,
          },
          {
            sym: 'ILTF',
            name: 'Impresa Latina Trasporti su Ferro',
            logo: '1841/ILTF',
            color: 'pink',
            text_color: 'black',
            tokens: [],
            type: 'major',
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            float_percent: 20,
            max_ownership_percent: 60,
            always_market_price: true,
            historical: false,
            startable: true,
          },
          {
            sym: 'RATF',
            name: 'Regia Azienda Trasporti Ferroviari',
            logo: '1841/RATF',
            color: 'lavender',
            text_color: 'black',
            tokens: [],
            type: 'major',
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            float_percent: 20,
            max_ownership_percent: 60,
            always_market_price: true,
            historical: false,
            startable: true,
          },
          {
            sym: 'RSFS',
            name: 'Reale Società Ferroviaria Sabauda',
            logo: '1841/RSFS',
            color: 'bisque',
            text_color: 'black',
            tokens: [],
            type: 'major',
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            float_percent: 20,
            max_ownership_percent: 60,
            always_market_price: true,
            historical: false,
            startable: true,
          },
          {
            sym: 'CTLP',
            name: 'Compagnia Trasporti La Patria',
            logo: '1841/CTLP',
            color: 'white',
            text_color: 'black',
            tokens: [],
            type: 'minor',
            shares: [40, 20, 20, 20],
            float_percent: 40,
            max_ownership_percent: 60,
            always_market_price: true,
            historical: false,
            startable: true,
          },
          {
            sym: 'FTP',
            name: 'Ferrovie Trans Padane',
            logo: '1841/FTP',
            color: 'gray',
            tokens: [],
            type: 'minor',
            shares: [40, 20, 20, 20],
            float_percent: 40,
            max_ownership_percent: 60,
            always_market_price: true,
            historical: false,
            startable: true,
          },
          {
            sym: 'SLDV',
            name: 'Società Leonardo Da Vinci',
            logo: '1841/SLDV',
            color: 'black',
            tokens: [],
            type: 'minor',
            shares: [40, 20, 20, 20],
            float_percent: 40,
            max_ownership_percent: 60,
            always_market_price: true,
            historical: false,
            startable: true,
          },
        ].freeze
      end
    end
  end
end
