# frozen_string_literal: true

require_relative 'meta'
require_relative '../base'

module Engine
  module Game
    module G1841
      module Map
        LAYOUT = :flat

        # rubocop:disable Layout/LineLength
        TILES = {
          '1' => 1,
          '2' => 1,
          '3' => 3,
          '4' => 3,
          '5' => 4,
          '6' => 4,
          '7' => 8,
          '8' => 16,
          '9' => 11,
          '12' => 1,
          '13' => 1,
          '14' => 2,
          '15' => 2,
          '16' => 2,
          '17' => 2,
          '18' => 2,
          '19' => 2,
          '20' => 2,
          '21' => 2,
          '22' => 2,
          '23' => 3,
          '24' => 3,
          '25' => 3,
          '26' => 2,
          '27' => 2,
          '28' => 2,
          '29' => 2,
          '30' => 2,
          '31' => 2,
          '39' => 2,
          '40' => 2,
          '41' => 2,
          '42' => 2,
          '43' => 2,
          '44' => 2,
          '45' => 2,
          '46' => 2,
          '47' => 2,
          '55' => 1,
          '56' => 1,
          '57' => 4,
          '58' => 3,
          '63' => 3,
          '69' => 1,
          '70' => 2,
          '87' => 2,
          '88' => 2,
          '144' => 2,
          '201' => 2,
          '202' => 2,
          '204' => 2,
          '205' => 1,
          '206' => 1,
          '207' => 2,
          '208' => 2,
          '216' => 2,
          '601' =>
          {
            'count' => 1,
            'color' => 'yellow',
            'code' => 'city=revenue:10,loc:center;town=revenue:20;path=a:0,b:_0;path=a:_1,b:4;path=a:_0,b:_1;label=V',
          },
          '602' =>
          {
            'count' => 1,
            'color' => 'green',
            'code' => 'city=revenue:10,loc:center;town=revenue:30;path=a:0,b:_0;path=a:2,b:_0;path=a:3,b:_0;path=a:_1,b:4;path=a:_0,b:_1;label=V',
          },
          '603' =>
          {
            'count' => 1,
            'color' => 'brown',
            'code' => 'city=revenue:20,loc:center;town=revenue:30;path=a:0,b:_0;path=a:1,b:_0;path=a:2,b:_0;path=a:3,b:_0;path=a:5,b:_0;path=a:_1,b:4;path=a:_0,b:_1;label=V',
          },
          '604' => 1,
          '605' => 1,
          '606' => 1,
          '607' => 1,
          '609' => 1,
          '610' =>
          {
            'count' => 2,
            'color' => 'brown',
            'code' => 'pass=revenue:0;path=a:0,b:_0;path=a:3,b:_0',
          },
          '611' => 3,
          '612' => 1,
          '613' =>
          {
            'count' => 3,
            'color' => 'green',
            'code' => 'pass=revenue:0;path=a:0,b:_0;path=a:3,b:_0;upgrade=cost:50',
          },
          '614' =>
          {
            'count' => 4,
            'color' => 'green',
            'code' => 'pass=revenue:0;path=a:0,b:_0;path=a:2,b:_0;upgrade=cost:50',
          },
          '615' =>
          {
            'count' => 1,
            'color' => 'green',
            'code' => 'pass=revenue:0;path=a:0,b:_0;path=a:1,b:_0;upgrade=cost:50',
          },
          '616' =>
          {
            'count' => 1,
            'color' => 'brown',
            'code' => 'pass=revenue:0;path=a:0,b:_0;path=a:1,b:_0;path=a:3,b:_0;path=a:4,b:_0',
          },
          '617' =>
          {
            'count' => 1,
            'color' => 'brown',
            'code' => 'pass=revenue:0;path=a:0,b:_0;path=a:1,b:_0;path=a:2,b:_0;path=a:3,b:_0',
          },
          '618' =>
          {
            'count' => 1,
            'color' => 'brown',
            'code' => 'pass=revenue:0;path=a:0,b:_0;path=a:2,b:_0;path=a:3,b:_0;path=a:4,b:_0',
          },
          '619' => 2,
          '621' => 2,
          '622' => 2,
          '623' => 2,
          '624' => 1,
          '625' => 1,
          '626' => 1,
          '627' => 2,
          '628' => 2,
          '629' => 2,
          '630' => 1,
          '631' => 1,
          '632' => 1,
          '633' => 1,
        }.freeze
        # rubocop:enable Layout/LineLength

        LOCATION_NAMES = {
          A6: 'Lyon',
          A8: 'Fréjus',
          C6: 'Aosta',
          C14: 'Cuneo',
          D1: 'Lausanne & Lötschberg',
          D9: 'Torino',
          D17: 'Marseille',
          E2: 'Simplon',
          E10: 'Asti',
          E16: 'Albena',
          F7: 'Vercelli & Novara',
          F11: 'Alessandria',
          F15: 'Savona',
          G2: 'Gotthard',
          G4: 'Lugano',
          G6: 'Buso Arsizio',
          G14: 'Genova',
          H5: 'Como',
          H7: 'Milano',
          H9: 'Pavia',
          I6: 'Bergamo',
          I10: 'Piacenza',
          J9: 'Cremona',
          J17: 'La Spezia',
          K2: 'Tirano & Edolo',
          K6: 'Brescia',
          K12: 'Parma',
          K18: 'Pisa',
          K20: 'Livorno',
          L9: 'Montova',
          L13: "Reggio nell'Emilia",
          L17: 'Lucca',
          M4: 'Trento & Brennero',
          M8: 'Verona',
          M12: 'Modena',
          M18: 'Pistoia & Prato',
          M22: 'Roma',
          N7: 'Vicenza',
          N13: 'Bologna',
          N19: 'Firenze',
          N21: 'Siena',
          O8: 'Padova',
          O10: 'Rovigo',
          O12: 'Ferrara',
          O20: 'Arezzo',
          P7: 'Venezia',
          P5: 'Treviso',
          P13: 'Ravenna',
          P15: 'Forli & Cesena',
          Q6: 'East',
          Q16: 'Adriatic Coast',
        }.freeze

        # rubocop:disable Layout/LineLength
        HEXES = {
          white: {
            # no cities, towns
            %w[D5 E6 O6 J7 E8 G8 I8 K8 F9 N9 P9 C10 G10 K10 M10 D11 L11 N11 C12 E12 D13 O14 L19 M20 L21] => '',
            %w[A10 B13 D15 H11 M14 O16 P17] => 'upgrade=cost:50,terrain:mountain',
            %w[I12] => 'border=edge:5,type:impassable;upgrade=cost:50,terrain:mountain',
            %w[P3 P11] => 'upgrade=cost:50,terrain:swamp',
            %w[I2 J11 N15] => 'border=edge:0,type:impassable',
            %w[D7] => 'border=edge:2,type:impassable',
            %w[F5] => 'border=edge:4,type:impassable',
            %w[F3] => 'border=edge:5,type:impassable',
            %w[H3] => 'border=edge:0,type:impassable;border=edge:1,type:impassable',
            %w[L7 J13] => 'border=edge:2,type:impassable;border=edge:3,type:impassable',
            %w[B9] => 'border=edge:2,type:impassable;border=edge:4,type:impassable;upgrade=cost:50,terrain:mountain',
            %w[H15 I16] => 'border=edge:3,type:impassable;border=edge:4,type:impassable;upgrade=cost:50,terrain:mountain',
            %w[C8] => 'border=edge:0,type:impassable;border=edge:1,type:impassable;border=edge:3,type:impassable',
            %w[J3] => 'border=edge:0,type:impassable;border=edge:1,type:impassable;border=edge:5,type:impassable',
            %w[I4] => 'border=edge:3,type:impassable;border=edge:4,type:impassable;border=edge:5,type:impassable',
            %w[K4] => 'border=edge:2,type:impassable;border=edge:5,type:impassable;border=edge:0,type:impassable',
            %w[M6] => 'border=edge:0,type:impassable;border=edge:2,type:impassable;border=edge:4,type:impassable;border=edge:5,type:impassable',
            # towns
            %w[E10 I10 O10] => 'town=revenue:0',
            %w[P13] => 'town=revenue:0;upgrade=cost:50,terrain:swamp',
            %w[F15 E16] => 'town=revenue:0;upgrade=cost:50,terrain:mountain;border=edge:3,type:impassable',
            %w[J17 N21] => 'town=revenue:0;border=edge:4,type:impassable',
            %w[O20] => 'town=revenue:0;border=edge:1,type:impassable;border=edge:3,type:impassable',
            %w[F7 P15 M18] => 'town=revenue:0;town=revenue:0',
            # cities
            %w[P5 G6 H9 J9 L9 F11 K12 M12 O12 L13 K20] => 'city=revenue:0',
            %w[I6 O8 N13] => 'city=revenue:0;label=Y',
            %w[P7] => 'city=revenue:0;upgrade=cost:50,terrain:swamp;label=V',
            %w[N7] => 'city=revenue:0;border=edge:2,type:impassable',
            %w[H5] => 'city=revenue:0;border=edge:3,type:impassable',
            %w[M8] => 'city=revenue:0;border=edge:3,type:impassable;label=Y',
            %w[G4] => 'city=revenue:0;border=edge:1,type:impassable;border=edge:2,type:impassable;border=edge:4,type:impassable',
            %w[K6] => 'city=revenue:0;border=edge:3,type:impassable;border=edge:5,type:impassable;label=Y',
          },
          yellow: {
            # passes
            %w[O4 G12 K14 L15 C16] => 'pass=revenue:0;upgrade=cost:100',
            %w[N5] => 'pass=revenue:0;border=edge:1,type:impassable;upgrade=cost:100',
            %w[F13 E14 O18] => 'pass=revenue:0;border=edge:0,type:impassable;upgrade=cost:100',
            %w[M16] => 'pass=revenue:0;border=edge:5,type:impassable;upgrade=cost:100',
            %w[K16] => 'pass=revenue:0;border=edge:0,type:impassable;border=edge:1,type:impassable;upgrade=cost:100',
            %w[J15] => 'pass=revenue:0;border=edge:1,type:impassable;border=edge:2,type:impassable;upgrade=cost:100',
            %w[N17] => 'pass=revenue:0;border=edge:2,type:impassable;border=edge:3,type:impassable;upgrade=cost:100',
            %w[L5] => 'pass=revenue:0;border=edge:0,type:impassable;border=edge:2,type:impassable;border=edge:5,type:impassable;upgrade=cost:100',
            %w[H13] => 'pass=revenue:0;border=edge:0,type:impassable;border=edge:1,type:impassable;border=edge:5,type:impassable;upgrade=cost:100',
            %w[I14] => 'pass=revenue:0;border=edge:0,type:impassable;border=edge:1,type:impassable;border=edge:2,type:impassable;border=edge:5,type:impassable;upgrade=cost:100',
            # cities
            %w[H7] => 'city=revenue:60;path=a:_0,b:3,terminal:1;path=a:_0,b:4,terminal:1;label=M',
            %w[L17] => 'city=revenue:20;path=a:_0,b:1;path=a:_0,b:5',
            %w[D9] => 'city=revenue:40,loc:1;city=revenue:40,loc:3.5;path=a:_0,b:1;path=a:_0,b:5;path=a:_1,b:4;label=T',
            %w[N19] => 'city=revenue:30,loc:5;city=revenue:30,loc:2.5;path=a:_0,b:1;path=a:_0,b:5;path=a:_1,b:2;label=Y',
            %w[C14] => 'city=revenue:30;path=a:_0,b:3;path=a:_0,b:4;path=a:_0,b:5;upgrade=cost:50,terrain:mountain;label=Y',
            %w[K18] => 'city=revenue:20;path=a:_0,b:0;path=a:_0,b:5;path=a:_0,b:4;border=edge:3,type:impassable',
            %w[G14] => 'city=revenue:0;border=edge:4,type:impassable;upgrade=cost:50,terrain:mountain;label=G',
          },
          green: {
            %w[E2] => 'pass=revenue:0,size:2;upgrade=cost:200',
            %w[A8] => 'pass=revenue:0,size:2;border=edge:5,type:impassable;upgrade=cost:200',
          },
          gray: {
            %w[K2] => 'town=revenue:20;town=revenue:10;path=a:_0,b:1;path=a:_1,b:0',
            %w[J5] => 'path=a:0,b:1;path=a:1,b:4;path=a:4,b:5;border=edge:2,type:impassable;border=edge:3,type:impassable',
            %w[C6] => 'town=revenue:10;path=a:_0,b:4;border=edge:0,type:impassable;border=edge:5,type:impassable',
          },
          red: {
            %w[D1] => 'offboard=revenue:white_0|gray_90|black_150;path=a:_0,b:5',
            %w[G2] => 'offboard=revenue:white_20|gray_30|black_150;path=a:_0,b:0',
            %w[M4] => 'offboard=revenue:white_20|gray_70|black_140,groups:Trento;path=a:_0,b:0;path=a:_0,b:1;path=a:_0,b:5',
            %w[N3] => 'offboard=revenue:white_20|gray_70|black_140,groups:Trento,hide:1;path=a:_0,b:5',
            %w[A6] => 'offboard=revenue:white_0|gray_140|black_200;path=a:_0,b:0',
            %w[Q6] => 'offboard=revenue:white_50|gray_80|black_120,groups:East;path=a:_0,b:1;path=a:_0,b:2',
            %w[Q4] => 'offboard=revenue:white_50|gray_80|black_120,groups:East,hide:1;path=a:_0,b:1',
            %w[Q16] => 'offboard=revenue:white_10|gray_70|black_150;path=a:_0,b:1;path=a:_0,b:2',
            %w[D17] => 'offboard=revenue:white_60|gray_100|black_150,groups:Marseille',
            %w[C18 E18] => 'offboard=revenue:white_60|gray_100|black_150,groups:Marseille,hide:1;path=a:_0,b:3',
            %w[M22] => 'offboard=revenue:white_10|gray_40|black_200,groups:Roma',
            %w[O22 L23 N23] => 'offboard=revenue:white_10|gray_40|black_200,groups:Rmoe,hide:1;path=a:_0,b:3',
          },
          blue: {
            %w[Q8] => 'town=revenue:40,loc:2;path=a:_0,b:2;icon=image:port',
            %w[Q14] => 'town=revenue:20,loc:2;path=a:_0,b:2;icon=image:port',
            %w[G16] => 'town=revenue:70,loc:3;path=a:_0,b:3;icon=image:port',
            %w[F17] => 'town=revenue:10,loc:3;path=a:_0,b:3;icon=image:port',
            %w[I18] => 'town=revenue:10,loc:4;path=a:_0,b:4;icon=image:port',
            %w[J21] => 'town=revenue:20,loc:4;path=a:_0,b:4;icon=image:port',
          },
        }.freeze
        # rubocop:enable Layout/LineLength
      end
    end
  end
end
