# frozen_string_literal: true

module Engine
  module Game
    module G1822MX
      module Entities
        COMPANIES = [
          {
            name: 'P1-BLWC (5-Train)',
            sym: 'P1',
            value: 0,
            revenue: 5,
            desc: 'MAJOR, Phase 5. 5-Train. Once a company acquires it, this is a normal 5-train that is subject to '\
                  'all of the normal rules.  It is not a "special train" and is not subject to the rules that are '\
                  'specific to special trains.  A company can acquire this private company at the start of its turn, '\
                  'even if it is already at it\'s train limit, as this counts as an acquisition action, not a train '\
                  'buying action.  However, once acquired the acquiring company must check whether it as at the '\
                  'train limit and must discard any trains held in excess of limit.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P2-MCSL (Permanent 2T)',
            sym: 'P2',
            value: 0,
            revenue: 0,
            desc: 'MAJOR, Phase 2. Permanent 2-Train. The 2P-train is a permanent 2-train. It is a “special train.” '\
                  'It cannot be sold to another company. It does not count against the train limit. '\
                  'It does not count as a train for the purpose of mandatory train ownership and '\
                  'purchase. A company cannot own more than one special train. Dividends can '\
                  'be separated from other trains and may be split, paid in full, or retained. If '\
                  'a company runs a 2P-train and pays a dividend (split or full), but retains its '\
                  'dividend from other train operations, this still counts as a normal dividend '\
                  'for share price movement purposes. Vice-versa, if a company pays a dividend '\
                  '(split or full) with its other trains, but retains the dividend from the 2P-train, '\
                  'this also still counts as a normal dividend for share price movement purposes. '\
                  'Does not close.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P3-IGT (Permanent 3/2T)',
            sym: 'P3',
            value: 0,
            revenue: 0,
            desc: 'MAJOR/MINOR, Phase 1. Permanent 3/2-Train. It is a “special train.” '\
                  'It cannot be sold to another company. It does not count against the train limit. '\
                  'It does not count as a train for the purpose of mandatory train ownership and '\
                  'purchase. A company cannot own more than one special train. Dividends can '\
                  'be separated from other trains and may be split, paid in full, or retained. Runs like a '\
                  'normal 3-train, but its earnings are halved after all bonuses/Pullman revenue are '\
                  'included (round up to a multiple of $10). '\
                  'If a company runs a 3/2-train and pays a dividend (split or full), but retains its '\
                  'dividend from other train operations, this still counts as a normal dividend '\
                  'for share price movement purposes. Vice-versa, if a company pays a dividend '\
                  '(split or full) with its other trains, but retains the dividend from the 3/2-train, '\
                  'this also still counts as a normal dividend for share price movement purposes. '\
                  'Does not close.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P4-MCST (Permanent LT)',
            sym: 'P4',
            value: 0,
            revenue: 0,
            desc: 'MAJOR/MINOR, Phase 1. Permanent L-Train.  It is a “special train.” '\
                  'It cannot be sold to another company. It does not count against the train limit. '\
                  'It does not count as a train for the purpose of mandatory train ownership and '\
                  'purchase. A company cannot own more than one special train. Dividends can '\
                  'be separated from other trains and may be split, paid in full, or retained. If '\
                  'a company runs a LP-train and pays a dividend (split or full), but retains its '\
                  'dividend from other train operations, this still counts as a normal dividend '\
                  'for share price movement purposes. Vice-versa, if a company pays a dividend '\
                  '(split or full) with its other trains, but retains the dividend from the LP-train, '\
                  'this also still counts as a normal dividend for share price movement purposes. '\
                  'Does not close.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P5-Pullman (Pullman)',
            sym: 'P5',
            value: 0,
            revenue: 10,
            desc: 'MAJOR/MINOR, Phase 3. Pullman. A “Pullman” car that can be attached to another train owned by the '\
                  'company. It is not a train. A train with a Pullman attached to it counts any '\
                  'number of towns in addition to its standard number of large stations. Does '\
                  'not count toward the train limit. Cannot be sold to another company. Does '\
                  'not close. No company may own more than one Pullman.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P6-Pullman (Pullman)',
            sym: 'P6',
            value: 0,
            revenue: 10,
            desc: 'MAJOR/MINOR, Phase 3. Pullman. A “Pullman” car that can be attached to another train owned by the '\
                  'company. It is not a train. A train with a Pullman attached to it counts any '\
                  'number of towns in addition to its standard number of large stations. Does '\
                  'not count toward the train limit. Cannot be sold to another company. Does '\
                  'not close. No company may own more than one Pullman.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P7-EI (Double Cash)',
            sym: 'P7',
            value: 0,
            revenue: 10,
            desc: 'MAJOR, Phase 3. Declare 2x Cash Holding. If held by a player, the holding player may declare '\
                  'double their actual cash holding at the end of a stock round to determine '\
                  'player turn order in the next stock round. If held by a company it pays '\
                  'revenue of $20 (green)/$40 (brown)/$60 (gray). Does not close.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P8-CMB (Adv. Tile Lay)',
            sym: 'P8',
            value: 0,
            revenue: 10,
            desc: 'MAJOR/MINOR, Phase 1. Advanced Non-City Tile Lay. The owning company may lay one plain '\
                  'or town track upgrade using the next color of track to be available, before '\
                  'it is actually made available by phase progression. The normal rules for '\
                  'progression of track lay must be followed; it is not possible to skip a color '\
                  'using this private. All other normal track laying restrictions apply. This is '\
                  'in place of its normal track lay action. Once acquired, the private company '\
                  'pays its revenue to the owning company until the power is exercised and '\
                  'the company closes. A minor company may not use this power to upgrade '\
                  'beyond green.',
            abilities: [
              {
                type: 'tile_lay',
                owner_type: 'corporation',
                when: %w[track special_track],
                count: 1,
                reachable: true,
                closed_when_used_up: true,
                hexes: [],
                tiles: %w[80 81 82 83 544 545 546 60 169 141 142 143 144 767 768 769 X17],
                combo_entities: %w[P9 P12 P13],
              },
            ],
            color: nil,
          },
          {
            name: 'P9-M&GNR (Extra Tile Lay)',
            sym: 'P9',
            value: 0,
            revenue: 10,
            desc: 'MAJOR/MINOR, Phase 3. Extra Tile Lay. The owning company may lay an additional yellow tile (or '\
                  'two for major companies beginning in Phase 3), or make one additional '\
                  'tile upgrade in its track laying step. The upgrade can be to a tile laid in its '\
                  'normal tile laying step. All other normal track laying restrictions apply. Once '\
                  'acquired, the private company pays its revenue to the owning company until '\
                  'the power is exercised and the company closes.',
            abilities: [
              {
                type: 'tile_lay',
                owner_type: 'corporation',
                when: %w[track special_track],
                must_lay_together: true,
                lay_count: 2,
                upgrade_count: 1,
                reachable: true,
                closed_when_used_up: true,
                hexes: [],
                tiles: [],
                consume_tile_lay: false,
                combo_entities: %w[P8 P12 P13],
              },
            ],
            color: nil,
          },
          {
            name: 'P10-CCNM (Three Builder Cubes)',
            sym: 'P10',
            value: 0,
            revenue: 10,
            desc: 'MAJOR/MINOR, Phase 1. Three Builder Cubes. When acquired by a company, the private company '\
                  'closes and is exchanged for three of the builder cubes from the cube pool. '\
                  'The company may spend one or more of the cubes to place them on the '\
                  'board during their lay track action. These placements are in addition to the '\
                  'tile placement. These cube placements may occur at any time during the '\
                  'action and can be split among turns.',
            abilities: [
              {
                type: 'tile_lay',
                owner_type: 'corporation',
                when: 'track',
                count: 3,
                reachable: true,
                closed_when_used_up: true,
                hexes: [],
                tiles: [],
              },
            ],
            color: nil,
          },
          {
            name: 'P11-SMB (Three Builder Cubes)',
            sym: 'P11',
            value: 0,
            revenue: 10,
            desc: 'MAJOR/MINOR, Phase 1. Three Builder Cubes. When acquired by a company, the private company '\
                  'closes and is exchanged for three of the builder cubes from the cube pool. '\
                  'The company may spend one or more of the cubes to place them on the '\
                  'board during their lay track action. These placements are in addition to the '\
                  'tile placement. These cube placements may occur at any time during the '\
                  'action and can be split among turns.',
            abilities: [
              {
                type: 'tile_lay',
                owner_type: 'corporation',
                when: 'track',
                count: 3,
                reachable: true,
                closed_when_used_up: true,
                hexes: [],
                tiles: [],
              },
            ],
            color: nil,
          },
          {
            name: 'P12-AIAS (Remove Town)',
            sym: 'P12',
            value: 0,
            revenue: 10,
            desc: 'MAJOR/MINOR, Phase 1. Remove Town. Allows the owning company to place a plain yellow track '\
                  'tile directly on an undeveloped town hex location or upgrade a town tile '\
                  'of one color to a plain track tile of the next color. This closes the company '\
                  'and counts as the company’s normal track laying step. All other normal '\
                  'track laying restrictions apply. Cannot be used in hexes with two small '\
                  'towns. Once acquired, the private company pays its revenue to the owning '\
                  'company until the power is exercised and the company is closed.',
            abilities: [
              {
                type: 'tile_lay',
                owner_type: 'corporation',
                when: %w[track special_track],
                count: 1,
                reachable: true,
                closed_when_used_up: true,
                hexes: [],
                tiles: %w[7 8 9 80 81 82 83 544 545 546 60 169],
                combo_entities: %w[P8 P9],
              },
            ],
            color: nil,
          },
          {
            name: 'P13-AIDS (Remove Town)',
            sym: 'P13',
            value: 0,
            revenue: 10,
            desc: 'MAJOR/MINOR, Phase 1. Remove Town. Allows the owning company to place a plain yellow track '\
                  'tile directly on an undeveloped town hex location or upgrade a town tile '\
                  'of one color to a plain track tile of the next color. This closes the company '\
                  'and counts as the company’s normal track laying step. All other normal '\
                  'track laying restrictions apply. Cannot be used in hexes with two small '\
                  'towns. Once acquired, the private company pays its revenue to the owning '\
                  'company until the power is exercised and the company is closed.',
            abilities: [
              {
                type: 'tile_lay',
                owner_type: 'corporation',
                when: %w[track special_track],
                count: 1,
                reachable: true,
                closed_when_used_up: true,
                hexes: [],
                tiles: %w[7 8 9 80 81 82 83 544 545 546 60 169],
                combo_entities: %w[P8 P9],
              },
            ],
            color: nil,
          },
          {
            name: 'P14-NMS (Mail Contract)',
            sym: 'P14',
            value: 0,
            revenue: 10,
            desc: 'MAJOR, Phase 3. Mail Contract. After running trains, the owning company receives income '\
                  'into its treasury equal to one half of the base value of the start and end '\
                  'stations from one of the trains operated. Modifications to values (for '\
                  'E-trains, a 3/2-train, or destination tokens) do not apply. An L-train may '\
                  'deliver mail within a single city. The company is not required to maximize '\
                  'the dividend from its run if it wishes to maximize its revenue from the mail '\
                  'contract by stopping at a large city and not running beyond it to include '\
                  'towns. A company that owns more than one Mail Contract may not use '\
                  'more than one on any train.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P15-NMS (Mail Contract)',
            sym: 'P15',
            value: 0,
            revenue: 10,
            desc: 'MAJOR, Phase 3. Mail Contract. After running trains, the owning company receives income '\
                  'into its treasury equal to one half of the base value of the start and end '\
                  'stations from one of the trains operated. Modifications to values (for '\
                  'E-trains, a 3/2-train, or destination tokens) do not apply. An L-train may '\
                  'deliver mail within a single city. The company is not required to maximize '\
                  'the dividend from its run if it wishes to maximize its revenue from the mail '\
                  'contract by stopping at a large city and not running beyond it to include '\
                  'towns. A company that owns more than one Mail Contract may not use '\
                  'more than one on any train.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P16-VTPN (Stock Drop)',
            sym: 'P16',
            value: 0,
            revenue: 10,
            desc: 'MAJOR, Phase 2.  Stock Drop. Pays $10 while owned by a player. A company must pay the '\
                  'bank $10 while owned by a company. A major company may close this '\
                  'company during its operating turn, but that makes its stock drop one space. '\
                  'If the company ever cannot pay the $10, this private company closes and the '\
                  'stock drops immediately.',
            abilities: [
              {
                type: 'choose_ability',
                when: 'owning_corp_or_turn',
                choices: { 'close_p16' => 'Close P16' },
              },
            ],
            color: nil,
          },
          {
            name: 'P17-UD (Small Port)',
            sym: 'P17',
            value: 0,
            revenue: 10,
            desc: 'MAJOR/MINOR, Phase 2. Small Port. Replace a spike going to water with this tile. Lay this tile on '\
                  'a spike that does not already have a port. The spike now counts as a 30 '\
                  '(yellow)/40 (green and later) and is treated like a gray off-board area for '\
                  'counting train runs for all companies. This is in addition to the company’s '\
                  'normal tile placement and the company does not need a route to the '\
                  'spike. Once acquired, the private company pays its revenue to the owning '\
                  'company until the power is exercised and the company is closed.',
            abilities: [
              {
                type: 'tile_lay',
                owner_type: 'corporation',
                when: 'track',
                count: 1,
                closed_when_used_up: true,
                hexes: %w[F7 G8 H5 H9 I10 J7 J11 M28 M40 Q28],
                tiles: %w[P1],
                cost: 0,
                consume_tile_lay: false,
              },
            ],
            color: nil,
          },
          {
            name: 'P18-HI (Large Port)',
            sym: 'P18',
            value: 0,
            revenue: 10,
            desc: 'MAJOR, Phase 3. Replace a spike going to water with this tile. Lay this tile on '\
                  'a spike that does not already have a port. The spike now counts as a 40 '\
                  '(green)/50 (brown)/60 (gray) and is treated like a gray off-board area for '\
                  'counting train runs for all companies. This is in addition to the company’s '\
                  'normal tile placement and the company does not need a route to the '\
                  'spike. Once acquired, the private company pays its revenue to the owning '\
                  'company until the power is exercised and the company is closed.',
            abilities: [
              {
                type: 'tile_lay',
                owner_type: 'corporation',
                when: 'track',
                count: 1,
                closed_when_used_up: true,
                hexes: %w[F7 G8 H5 H9 I10 J7 J11 M28 M40 Q28],
                tiles: %w[P2],
                cost: 0,
                consume_tile_lay: false,
              },
            ],
            color: nil,
          },
          {
            name: 'CONCESSION: FCM',
            sym: 'C1',
            value: 100,
            discount: -100,
            revenue: 10,
            desc: 'Has a face value of $100 and contributes $100 to conversion into the FCM director’s certificate.'\
                  ' M18 is purchased along with the FCM concession for a minimum bid of $200.',
            abilities: [
              {
                type: 'exchange',
                corporations: ['FCM'],
                owner_type: 'player',
                from: 'par',
              },
            ],
            color: '#e51c00',
            text_color: 'white',
          },
          {
            name: 'CONCESSION: MC',
            sym: 'C2',
            value: 100,
            revenue: 10,
            desc: 'Has a face value of $100 and contributes $100 to conversion into the MC director’s certificate.',
            abilities: [
              {
                type: 'exchange',
                corporations: ['MC'],
                owner_type: 'player',
                from: 'par',
              },
              { type: 'blocks_hexes_consent', owner_type: 'player', hexes: ['M22'], hidden: true },
            ],
            color: '#000000',
            text_color: 'white',
          },
          {
            name: 'CONCESSION: CHP',
            sym: 'C3',
            value: 100,
            revenue: 10,
            desc: 'Has a face value of $100 and contributes $100 to conversion into the CHP director’s '\
                  'certificate.',
            abilities: [
              {
                type: 'exchange',
                corporations: ['CHP'],
                owner_type: 'player',
                from: 'par',
              },
            ],
            color: '#ff7b93',
            text_color: 'white',
          },
          {
            name: 'CONCESSION: FNM',
            sym: 'C4',
            value: 100,
            revenue: 10,
            desc: 'Has a face value of $100 and contributes $100 to conversion into the FNM director’s '\
                  'certificate.',
            abilities: [
              {
                type: 'exchange',
                corporations: ['FNM'],
                owner_type: 'player',
                from: 'par',
              },
              { type: 'blocks_hexes_consent', owner_type: 'player', hexes: ['M24'], hidden: true },
            ],
            color: '#850040',
            text_color: 'white',
          },
          {
            name: 'CONCESSION: MIR',
            sym: 'C5',
            value: 100,
            revenue: 10,
            desc: 'Has a face value of $100 and contributes $100 to conversion into the MIR director’s certificate.',
            abilities: [
              {
                type: 'exchange',
                corporations: ['MIR'],
                owner_type: 'player',
                from: 'par',
              },
            ],
            color: '#ff3600',
            text_color: 'white',
          },
          {
            name: 'CONCESSION: FCP',
            sym: 'C6',
            value: 100,
            revenue: 10,
            desc: 'Has a face value of $100 and contributes $100 to conversion into the FCP director’s certificate.',
            abilities: [
              {
                type: 'exchange',
                corporations: ['FCP'],
                owner_type: 'player',
                from: 'par',
              },
            ],
            color: '#fab506',
            text_color: 'white',
          },
          {
            name: 'CONCESSION: IRM',
            sym: 'C7',
            value: 100,
            revenue: 10,
            desc: 'Has a face value of $100 and contributes $100 to conversion into the IRM director’s certificate.',
            abilities: [
              {
                type: 'exchange',
                corporations: ['IRM'],
                owner_type: 'player',
                from: 'par',
              },
              { type: 'blocks_hexes_consent', owner_type: 'player', hexes: ['O24'], hidden: true },
            ],
            color: '#004c6c',
            text_color: 'white',
          },
          {
            name: 'MINOR: 1. Ferrocarril Sonora-Baja California',
            sym: 'M1',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is B1 (Tijuana).',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 2. Rio Grande, Sierra Madre & Pacific Railway',
            sym: 'M2',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is D15 (Ciudad Juarez).',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 3. Ferrocarril Nacozari',
            sym: 'M3',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is E8 (Hermosillo).',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 4. Ferrocarril Parral y Durango',
            sym: 'M4',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is F13 (Cuauhtemoc).',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 5. Ferrocarril Coahuila y Zacatecas',
            sym: 'M5',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is G22 (Nuevo Laredo).',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 6. Sinaloa and Durango Railroad',
            sym: 'M6',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is H11 (Los Mochis).',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 7. Monterrey Mineral and Terminal Railway',
            sym: 'M7',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is I22 (Monterrey).',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 8. Ferrocarril Nacional de la Baja California',
            sym: 'M8',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is J9 (La Paz).',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 9. Southern Pacific Railroad of Mexico',
            sym: 'M9',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is J13 (Mazatlan).',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 10. Potosi Central Railroad',
            sym: 'M10',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is K20 (San Luis Potosi).',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 11. Guadalajara to Tepic and Mazatlan',
            sym: 'M11',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is L17 (Guadalajara).',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 12. Ferrocarril Guanajuato a San Luis de la Paz y Pozos',
            sym: 'M12',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is L19 (Guanajuanto Leon).',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 13. Ferrocarril San Marcos a Huajapan de Leon',
            sym: 'M13',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is L19 (Guanajuanto Leon).',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 14. Ferrocarril Cazadero y Solis',
            sym: 'M14',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is N23 (Mexico City).',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 15. Ferrocarril San Gregorio',
            sym: 'M15',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is N23 (Mexico City).',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 16. Ferrocarril Atlamaxac',
            sym: 'M16',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is N25 (Tlaxcala Puebla).',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 17. Campania del ferrocarril de Mexico a Puebla',
            sym: 'M17',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is N25 (Tlaxcala Puebla).',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 18. Ferrocarril Mexicano',
            sym: 'M18',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is N25 (Tlaxcala Puebla).',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 19. Cordoba and Huatusco Railroad',
            sym: 'M19',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is N27 (Veracruz).',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 20. Ferrocarril Interoceanico de Acapulco',
            sym: 'M20',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is P23 (Acapulco).',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 21. Ferrocarril Oaxaca a Ejutla',
            sym: 'M21',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is P27 (Oaxaca).',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 22. Ferrocarriles Unidos de Yucatan',
            sym: 'M22',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is O32 (Villahermosa).',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 23. Ferrocarril Merida a Valladolid',
            sym: 'M23',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is L37 (Merida).',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 24. Northern Railroad of Guatemala',
            sym: 'M24',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is Q34 (Guatemala).',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
        ].freeze

        CORPORATIONS = [
          {
            sym: '1',
            name: 'Ferrocarril Sonora-Baja California',
            logo: '1822/1',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'B1',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '2',
            name: 'Rio Grande, Sierra Madre & Pacific Railway',
            logo: '1822/2',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'D15',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '3',
            name: 'Ferrocarril Nacozari',
            logo: '1822/3',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'E8',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '4',
            name: 'Ferrocarril Parral y Durango',
            logo: '1822/4',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'F13',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '5',
            name: 'Ferrocarril Coahuila y Zacatecas',
            logo: '1822/5',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'G22',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '6',
            name: 'Sinaloa and Durango Railroad',
            logo: '1822/6',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'H11',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '7',
            name: 'Monterrey Mineral and Terminal Railway',
            logo: '1822/7',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'I22',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '8',
            name: 'Ferrocarril Nacional de la Baja California',
            logo: '1822/8',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'J9',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '9',
            name: 'Southern Pacific Railroad of Mexico',
            logo: '1822/9',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'J13',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '10',
            name: 'Potosi Central Railroad',
            logo: '1822/10',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'K20',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '11',
            name: 'Guadalajara to Tepic and Mazatlan',
            logo: '1822/11',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'L17',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '12',
            name: 'Ferrocarril Guanajuato a San Luis de la Paz y Pozos',
            logo: '1822/12',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'L19',
            city: 1,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '13',
            name: 'Ferrocarril San Marcos a Huajapan de Leon',
            logo: '1822/13',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'L19',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '14',
            name: 'Ferrocarril Cazadero y Solis',
            logo: '1822/14',
            tokens: [20],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'N23',
            city: 1,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
            abilities: [{ type: 'blocks_hexes_consent', owner_type: 'player', hexes: ['N21'], hidden: true }],
          },
          {
            sym: '15',
            name: 'Ferrocarril San Gregorio',
            logo: '1822/15',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'N23',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
            abilities: [{ type: 'blocks_hexes_consent', owner_type: 'player', hexes: ['O22'], hidden: true }],
          },
          {
            sym: '16',
            name: 'Ferrocarril Atlamaxac',
            logo: '1822/16',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'N25',
            city: 2,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '17',
            name: 'Campania del ferrocarril de Mexico a Puebla',
            logo: '1822/17',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'N25',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '18',
            name: 'Ferrocarril Mexicano',
            logo: '1822/18',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'N25',
            city: 1,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '19',
            name: 'Cordoba and Huatusco Railroad',
            logo: '1822/19',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'N27',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '20',
            name: 'Ferrocarril Interoceanico de Acapulco',
            logo: '1822/20',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'P23',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '21',
            name: 'Ferrocarril Oaxaca a Ejutla',
            logo: '1822/21',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'P27',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '22',
            name: 'Ferrocarriles Unidos de Yucatan',
            logo: '1822/22',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'O32',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '23',
            name: 'Ferrocarril Merida a Valladolid',
            logo: '1822/23',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'L37',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '24',
            name: 'Northern Railroad of Guatemala',
            logo: '1822/24',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'Q34',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: 'FCM',
            name: 'Ferrocarril Mexicano',
            logo: '1822_mx/FCM',
            tokens: [0, 100],
            type: 'major',
            float_percent: 20,
            always_market_price: true,
            coordinates: 'N23',
            city: 4,
            color: '#e51c00',
            reservation_color: nil,
            destination_coordinates: 'N27',
            destination_icon: '1822_mx/FCM_DEST',
          },
          {
            sym: 'MC',
            name: 'Mexican Central Railway',
            logo: '1822_mx/MC',
            tokens: [0, 100],
            type: 'major',
            float_percent: 20,
            always_market_price: true,
            coordinates: 'N23',
            city: 2,
            color: '#000000',
            reservation_color: nil,
            destination_coordinates: 'F21',
            destination_icon: '1822_mx/MC_DEST',
            abilities: [{ type: 'blocks_hexes_consent', owner_type: 'player', hexes: ['M22'], hidden: true }],
          },
          {
            sym: 'CHP',
            name: 'Chihuahua-Pacfic Railway',
            logo: '1822_mx/CHP',
            tokens: [0, 100],
            type: 'major',
            float_percent: 20,
            always_market_price: true,
            coordinates: 'F15',
            color: '#ff7b93',
            text_color: 'black',
            reservation_color: nil,
            destination_coordinates: 'H11',
            destination_icon: '1822_mx/CHP_DEST',
          },
          {
            sym: 'FNM',
            name: 'Ferrocarriles Nacionales de Mexico',
            logo: '1822_mx/FNM',
            tokens: [0, 100],
            type: 'major',
            float_percent: 20,
            always_market_price: true,
            coordinates: 'N23',
            city: 3,
            color: '#850040',
            reservation_color: nil,
            destination_coordinates: 'G22',
            destination_icon: '1822_mx/FNM_DEST',
            abilities: [{ type: 'blocks_hexes_consent', owner_type: 'player', hexes: ['M24'], hidden: true }],
          },
          {
            sym: 'MIR',
            name: 'Mexican International Railroad',
            logo: '1822_mx/MIR',
            tokens: [0, 100],
            type: 'major',
            float_percent: 20,
            always_market_price: true,
            coordinates: 'F21',
            color: '#ff3600',
            reservation_color: nil,
            destination_coordinates: 'J15',
            destination_icon: '1822_mx/MIR_DEST',
          },
          {
            sym: 'FCP',
            name: 'Ferrocarril del Pacifico',
            logo: '1822_mx/FCP',
            tokens: [0, 100],
            type: 'major',
            float_percent: 20,
            always_market_price: true,
            coordinates: 'D9',
            color: '#fab506',
            reservation_color: nil,
            destination_coordinates: 'L17',
            destination_icon: '1822_mx/FCP_DEST',
          },
          {
            sym: 'IRM',
            name: 'Interoceanic Railway of Mexico',
            logo: '1822_mx/IRM',
            tokens: [0, 100],
            type: 'major',
            float_percent: 20,
            always_market_price: true,
            coordinates: 'N23',
            city: 5,
            color: '#004c6c',
            reservation_color: nil,
            destination_coordinates: 'N27',
            destination_icon: '1822_mx/IRM_DEST',
            abilities: [{ type: 'blocks_hexes_consent', owner_type: 'player', hexes: ['O24'], hidden: true }],
          },
          {
            sym: 'NDEM',
            name: 'Ferrocarriles Nacionales de Mexico',
            logo: '1822_mx/NDEM',
            tokens: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            shares: [10, 10, 10],
            type: 'major',
            always_market_price: true,
            city: 5,
            color: '#525600',
            reservation_color: nil,
          },
        ].freeze
      end
    end
  end
end
