# frozen_string_literal: true

module Engine
  module Game
    module G1822MX
      module Entities
        COMPANIES = [
          {
            name: 'P1-BEC (5-Train)',
            sym: 'P1',
            value: 0,
            revenue: 5,
            desc: 'MAJOR, Phase 5. 5-Train. This is a normal 5-train that is subject to all of the normal rules. '\
                  'Note that a company can acquire this private company at the start of its turn, even if it is '\
                  'already at its train limit as this counts as an acquisition action, not a train buying action. '\
                  'However, once acquired the acquiring company needs to check whether it is at train limit and '\
                  'discard any trains held in excess of limit.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P2-MtonR (Remove Town)',
            sym: 'P2',
            value: 0,
            revenue: 10,
            desc: 'MAJOR/MINOR, Phase 2. Remove Small Station. Allows the owning company to place a plain yellow '\
                  'track tile directly on an undeveloped small station hex location or upgrade a small station tile '\
                  'of one colour to a plain track tile of the next colour. This closes the company and counts as '\
                  'the company’s normal track laying step. All other normal track laying restrictions apply. Once '\
                  'acquired, the private company pays its revenue to the owning company until the power is '\
                  'exercised and the company is closed.',
            abilities: [
              {
                type: 'tile_lay',
                owner_type: 'corporation',
                when: 'track',
                count: 1,
                reachable: true,
                closed_when_used_up: true,
                hexes: [],
                tiles: %w[7 8 9 80 81 82 83 544 545 546 60 169],
              },
            ],
            color: nil,
          },
          {
            name: 'P3-S&HR (Permanent 2T)',
            sym: 'P3',
            value: 0,
            revenue: 0,
            desc: 'MAJOR, Phase 2. Permanent 2-Train. 2P-train is a permanent 2-train. It can’t be sold to another '\
                  'company. It does not count against train limit. It does not count as a train for the purpose of '\
                  'mandatory train ownership and purchase. A company may not own more than one 2P train. '\
                  'A company cannot own both a permanent L-train and a permanent 2-train. Dividends '\
                  'can be separated from other trains and may be split, paid in full, or retained. If a company '\
                  'runs a 2P-train and pays a dividend (split or full), but retains its dividend from other train '\
                  'operations this still counts as a normal dividend for stock price movement purposes. Vice-versa, '\
                  'if a company pays a dividend (split or full) with its other trains, but retains the dividend '\
                  'from the 2P, this also still counts as a normal dividend for stock price movement purposes. Does '\
                  'not close.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P4-SDR (Permanent 2T)',
            sym: 'P4',
            value: 0,
            revenue: 0,
            desc: 'MAJOR, Phase 2. Permanent 2-Train. 2P-train is a permanent 2-train. It can’t be sold to another '\
                  'company. It does not count against train limit. It does not count as a train for the purpose of '\
                  'mandatory train ownership and purchase. A company may not own more than one 2P train. '\
                  'A company cannot own both a permanent L-train and a permanent 2-train. Dividends '\
                  'can be separated from other trains and may be split, paid in full, or retained. If a company '\
                  'runs a 2P-train and pays a dividend (split or full), but retains its dividend from other train '\
                  'operations this still counts as a normal dividend for stock price movement purposes. Vice-versa, '\
                  'if a company pays a dividend (split or full) with its other trains, but retains the dividend '\
                  'from the 2P, this also still counts as a normal dividend for stock price movement purposes. '\
                  'Does not close.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P5-LC&DR (English Channel)',
            sym: 'P5',
            value: 0,
            revenue: 10,
            desc: 'MAJOR, Phase 3. English Channel. The owning company may place an exchange station token on the '\
                  'map, free of charge, in a token space in the English Channel. The company does not need to be '\
                  'able to trace a route to the English Channel to use this property (i.e. any company can use this '\
                  'power to place a token in the English Channel). If no token spaces are available, but a space '\
                  'could be created by upgrading the English Channel track then this power may be used to place a '\
                  'token and upgrade the track simultaneously. This counts as the acquiring company’s tile lay '\
                  'action and incurs the usual costs for doing so. Alternatively, it can move an exchange station '\
                  'token to the available station token section on its company charter.',
            abilities: [
              {
                type: 'teleport',
                owner_type: 'corporation',
                hexes: ['P43'],
                tiles: %w[X9 X15],
              },
              {
                type: 'token',
                owner_type: 'corporation',
                hexes: ['P43'],
                price: 0,
                teleport_price: 0,
                count: 1,
                extra_action: true,
              },
            ],
            color: nil,
          },
          {
            name: 'P6-L&SR (Mail Contract)',
            sym: 'P6',
            value: 0,
            revenue: 10,
            desc: 'MAJOR, Phase 3. Mail Contract. After running trains, the owning company receives income into its '\
                  'treasury equal to one half of the base value of the start and end stations from one of the '\
                  'trains operated. Doubled values (for E trains or destination tokens) do not count. The company '\
                  'is not required to maximise the dividend from its run if it wishes to maximise its revenue from '\
                  'the mail contract by stopping at a large city and not running beyond it to include small '\
                  'stations. Does not close.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P7-S&BR (Mail Contract)',
            sym: 'P7',
            value: 0,
            revenue: 10,
            desc: 'MAJOR, Phase 3. Mail Contract. After running trains, the owning company receives income into its '\
                  'treasury equal to one half of the base value of the start and end stations from one of the '\
                  'trains operated. Doubled values (for E trains or destination tokens) do not count. The company '\
                  'is not required to maximise the dividend from its run if it wishes to maximise its revenue from '\
                  'the mail contract by stopping at a large city and not running beyond it to include small '\
                  'stations. Does not close.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P8-E&GR (Hill Discount)',
            sym: 'P8',
            value: 0,
            revenue: 10,
            desc: 'MAJOR/MINOR, Phase 3. Mountain/Hill Discount. Either: The acquiring company receives a discount '\
                  'token that can be used to pay the full cost of a single track tile lay on a rough terrain, hill '\
                  'or mountain hex. This closes the company. Or: The acquiring company rejects the token and '\
                  'receives a £20 discount off the cost of all hill and mountain terrain (i.e. NOT off the cost of '\
                  'rough terrain). The private company does not close. Closes if free token taken when acquired. '\
                  'Otherwise, flips when acquired and does not close.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P9-M&GNR (Double Cash)',
            sym: 'P9',
            value: 0,
            revenue: 10,
            desc: 'MAJOR/MINOR, Phase 3. Declare 2x Cash Holding. If held by a player, the holding player may '\
                  'declare double their actual cash holding at the end of a stock round to determine player turn '\
                  'order in the next stock round. If held by a company it pays revenue of '\
                  '£20 (green)/£40 (brown)/£60 (grey). Does not close.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P10-G&SWR (River Discount)',
            sym: 'P10',
            value: 0,
            revenue: 10,
            desc: 'MAJOR/MINOR, Phase 3. River/Estuary Discount. The acquiring company receives two discount tokens '\
                  'each of which can be used to pay the cost for one track lay over an estuary crossing. They can '\
                  'be used on the same or different tile lays. Use of the second token closes the company. In '\
                  'addition, until the company closes it provides a discount of £10 against the cost of all river '\
                  'terrain (excluding estuary crossings).',
            abilities: [
              {
                type: 'tile_lay',
                owner_type: 'corporation',
                when: 'track',
                count: 2,
                reachable: true,
                closed_when_used_up: true,
                hexes: [],
                tiles: [],
              },
              {
                type: 'tile_discount',
                owner_type: 'corporation',
                discount: 10,
                terrain: 'swamp',
              },
            ],
            color: nil,
          },
          {
            name: 'P11-B&ER (Adv. Tile Lay)',
            sym: 'P11',
            value: 0,
            revenue: 10,
            desc: 'MAJOR/MINOR, Phase 2. Advanced Tile Lay. The owning company may lay one plain or small station '\
                  'track upgrade using the next colour of track to be available, before it is actually made '\
                  'available by phase progression. The normal rules for progression of track lay must be followed '\
                  '(i.e. grey upgrades brown upgrades green upgrades yellow) it is not possible to skip a colour '\
                  'using this private. All other normal track laying restrictions apply. This is in place of its '\
                  'normal track lay action. Once acquired, the private company pays its revenue to the owning '\
                  'company until the power is exercised and the company closes.',
            abilities: [
              {
                type: 'tile_lay',
                owner_type: 'corporation',
                when: 'track',
                count: 1,
                reachable: true,
                closed_when_used_up: true,
                hexes: [],
                tiles: %w[80 81 82 83 544 545 546 60 169 141 142 143 144 767 768 769 X17],
              },
            ],
            color: nil,
          },
          {
            name: 'P12-L&SR (Extra Tile Lay)',
            sym: 'P12',
            value: 0,
            revenue: 10,
            desc: 'MAJOR/MINOR, Phase 3. Extra Tile Lay. The owning company may lay an additional yellow tile (or '\
                  'two for major companies), or make one additional tile upgrade in its track laying step. The '\
                  'upgrade can be to a tile laid in its normal tile laying step. All other normal track laying '\
                  'restrictions apply. Once acquired, the private company pays its revenue to the owning company '\
                  'until the power is exercised and the company closes.',
            abilities: [
              {
                type: 'tile_lay',
                owner_type: 'corporation',
                when: 'track',
                count: 2,
                reachable: true,
                closed_when_used_up: true,
                hexes: [],
                tiles: [],
              },
            ],
            color: nil,
          },
          {
            name: 'P13-YN&BR (Pullman)',
            sym: 'P13',
            value: 0,
            revenue: 10,
            desc: 'MAJOR/MINOR, Phase 5. Pullman. A “Pullman” carriage train that can be added to another train '\
                  'owned by the company. It converts the train into a + train. Does not count against train limit '\
                  'and does not count as a train for the purposes of train ownership. Can’t be sold to another '\
                  'company. Does not close.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P14-K&TR (Pullman)',
            sym: 'P14',
            value: 0,
            revenue: 10,
            desc: 'MAJOR/MINOR, Phase 5. Pullman. A “Pullman” carriage train that can be added to another train '\
                  'owned by the company. It converts the train into a + train. Does not count against train limit '\
                  'and does not count as a train for the purposes of train ownership. Can’t be sold to another '\
                  'company. Does not close.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P15-HR (£10x Phase)',
            sym: 'P15',
            value: 0,
            revenue: 0,
            desc: 'MAJOR/MINOR, Phase 2. £10x Phase. Pays revenue of £10 x phase number to the player, and pays '\
                  'treasury credits of £10 x phase number to the private company. This credit is retained on the '\
                  'private company charter. When acquired, the acquiring company receives this treasury money and '\
                  'this private company closes. If not acquired beforehand, this company closes at the start of '\
                  'Phase 7 and all treasury credits are returned to the bank.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P16-TH (Tax Haven)',
            sym: 'P16',
            value: 0,
            revenue: 0,
            desc: 'CAN NOT BE ACQUIRED. Tax Haven. As a stock round action, under the direction and funded by the '\
                  'owning player, the off-shore Tax Haven may purchase an available share certificate and place it '\
                  'onto P16’s charter. The certificate is not counted for determining directorship of a company. '\
                  'The share held in the tax haven does NOT count against the 60% share limit for purchasing '\
                  'shares. If at 60% (or more) in hand in a company, a player can still purchase an additional '\
                  'share in that company and place it in the tax haven. Similarly, if a player holds 50% of a '\
                  'company, plus has 10% of the same company in the tax haven, they can buy a further 10% share. '\
                  'A company with a share in the off-shore tax haven CAN be “all sold out” at the end of a stock '\
                  'round. Dividends paid to the share are also placed onto the off-shore tax haven charter. At the '\
                  'end of the game, the player receives the share certificate from the off-shore tax haven charter '\
                  'and includes it in their portfolio for determining final worth. The player also receives the '\
                  'cash from dividend income accumulated on the charter. Can’t be acquired. Does not count against '\
                  'the certificate limit.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P17-LUR (Move Card)',
            sym: 'P17',
            value: 0,
            revenue: 10,
            desc: 'MAJOR, Phase 2. Move Card. Allows the director of the owning company to select one concession, '\
                  'private company, or minor company from the relevant stack of certificates, excluding those items '\
                  'currently in the bidding boxes, and move it to the top or the bottom of the stack. Closes when '\
                  'the power is exercised.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P18-C&HPR (Station Swap)',
            sym: 'P18',
            value: 0,
            revenue: 10,
            desc: 'MAJOR, Phase 5. Station Marker Swap. Allows the owning company to move a token from the exchange '\
                  'token area of its charter to the available token area, or vice versa. This company closes when '\
                  'its power is exercised.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P19-AEC (Perm. L Train)',
            sym: 'P19',
            value: 0,
            revenue: 0,
            desc: 'MAJOR/MINOR, Phase 1. Permanent L-Train. An L-train cannot be sold to another company. It does '\
                  'not count as a train for the purposes of mandatory train ownership. It does not count against '\
                  'train ownership limit. A company cannot own both a permanent L-train and a permanent 2-train. '\
                  'Dividends can be separated from other trains and may be split, paid in full, or retained. If a '\
                  'company runs a permanent L-train and pays a dividend (split or full), but retains its dividend '\
                  'from other train operations this still counts as a normal dividend for stock price movement '\
                  'purposes. Vice-versa, if a company pays a dividend (split or full) with its other trains, but '\
                  'retains the dividend from the permanent L, this also still counts as a normal dividend for stock '\
                  'price movement purposes. Does not close.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P20-C&WR (£5x Phase)',
            sym: 'P20',
            value: 0,
            revenue: 0,
            desc: 'MAJOR/MINOR, Phase 3. £5x Phase. Pays revenue of £5 x phase number to the player, and pays '\
                  'treasury credits of £5 x phase number to the private company. This credit is retained on the '\
                  'private company charter. When acquired, the acquiring company receives this treasury money and '\
                  'this private company closes. If not acquired beforehand, this company closes at the start of '\
                  'Phase 7 and all treasury credits are returned to the bank.',
            abilities: [],
            color: nil,
          },
          {
            name: 'P21-HSBC (Grimsby/Hull Bridge)',
            sym: 'P21',
            value: 0,
            revenue: 10,
            desc: 'MAJOR/MINOR, Phase 2. Grimsby/Hull Bridge. Allows the owning company to lay yellow tiles in '\
                  'Grimsby and / or Hull, forming a direct track connection between the two cities over the '\
                  'Humber estuary. If one of the cities already has a yellow tile in place, then if used in phase 3 '\
                  'or later, one of the tile lays may be a green upgrade. No terrain costs apply for these tile '\
                  'lays. These tile lays count as the normal track laying phase for the operating company. The '\
                  'owning company must have a token in Hull or Grimsby to use this power. Closes when its power is '\
                  'exercised.',
            abilities: [
              {
                type: 'tile_lay',
                owner_type: 'corporation',
                when: 'track',
                count: 2,
                free: true,
                reachable: true,
                closed_when_used_up: true,
                hexes: %w[N21 N23],
                tiles: %w[5 6 57 15],
              },
            ],
            color: nil,
          },
          {
            name: 'CONCESSION: LNWR',
            sym: 'C1',
            value: 100,
            revenue: 10,
            desc: 'Have a face value £100 and converts into the LNWR’s 10% director certificate. LNWR may also put '\
                  'its destination token into Manchester when converted.',
            abilities: [
              {
                type: 'exchange',
                corporations: ['FCM'],
                owner_type: 'player',
                from: 'par',
              },
            ],
            color: '#000',
            text_color: 'white',
          },
          {
            name: 'CONCESSION: GWR',
            sym: 'C2',
            value: 100,
            revenue: 10,
            desc: 'Have a face value £100 and contribute £100 to the conversion into the GWR director’s certificate.',
            abilities: [
              {
                type: 'exchange',
                corporations: ['MC'],
                owner_type: 'player',
                from: 'par',
              },
            ],
            color: '#165016',
            text_color: 'white',
          },
          {
            name: 'CONCESSION: LBSCR',
            sym: 'C3',
            value: 100,
            revenue: 10,
            desc: 'Have a face value £100 and contribute £100 to the conversion into the LBSCR director’s '\
                  'certificate.',
            abilities: [
              {
                type: 'exchange',
                corporations: ['CHP'],
                owner_type: 'player',
                from: 'par',
              },
            ],
            color: '#cccc00',
            text_color: 'white',
          },
          {
            name: 'CONCESSION: SECR',
            sym: 'C4',
            value: 100,
            revenue: 10,
            desc: 'Have a face value £100 and contribute £100 to the conversion into the SECR director’s '\
                  'certificate.',
            abilities: [
              {
                type: 'exchange',
                corporations: ['FNM'],
                owner_type: 'player',
                from: 'par',
              },
            ],
            color: '#ff7f2a',
            text_color: 'white',
          },
          {
            name: 'CONCESSION: CR',
            sym: 'C5',
            value: 100,
            revenue: 10,
            desc: 'Have a face value £100 and contribute £100 to the conversion into the CR director’s certificate.',
            abilities: [
              {
                type: 'exchange',
                corporations: ['MIR'],
                owner_type: 'player',
                from: 'par',
              },
            ],
            color: '#5555ff',
            text_color: 'white',
          },
          {
            name: 'CONCESSION: MR',
            sym: 'C6',
            value: 100,
            revenue: 10,
            desc: 'Have a face value £100 and contribute £100 to the conversion into the MR director’s certificate.',
            abilities: [
              {
                type: 'exchange',
                corporations: ['FCP'],
                owner_type: 'player',
                from: 'par',
              },
            ],
            color: '#ff2a2a',
            text_color: 'white',
          },
          {
            name: 'CONCESSION: LYR',
            sym: 'C7',
            value: 100,
            revenue: 10,
            desc: 'Have a face value £100 and contribute £100 to the conversion into the LYR director’s certificate.',
            abilities: [
              {
                type: 'exchange',
                corporations: ['IRM'],
                owner_type: 'player',
                from: 'par',
              },
            ],
            color: '#5a2ca0',
            text_color: 'white',
          },
          {
            name: 'MINOR: 1. Ferrocarril Sonora-Baja California',
            sym: 'M1',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is B1.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 2. Rio Grande, Sierra Madre & Pacific Railway',
            sym: 'M2',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is D15.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 3. Ferrocarril Nacozari',
            sym: 'M3',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is E8.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 4. Ferrocarril Parral y Durango',
            sym: 'M4',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is F13.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 5. Ferrocarril Coahuila y Zacatecas',
            sym: 'M5',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is G22.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 6. Sinaloa and Durango Railroad',
            sym: 'M6',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is H11.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 7. Monterrey Mineral and Terminal Railway',
            sym: 'M7',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is I22.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 8. Ferrocarril Nacional de la Baja California',
            sym: 'M8',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is J9.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 9. Southern Pacific Railroad of Mexico',
            sym: 'M9',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is J13.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 10. Potosi Central Railroad',
            sym: 'M10',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is K20.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 11. Guadalajara to Tepic and Mazatlan',
            sym: 'M11',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is L17.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 12. Ferrocarril Guanajuato a San Luis de la Paz y Pozos',
            sym: 'M12',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is L19.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 13. Ferrocarril San Marcos a Huajapan de Leon',
            sym: 'M13',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is L19.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 14. Ferrocarril Cazadero y Solis',
            sym: 'M14',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is N23.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 15. Ferrocarril San Gregorio',
            sym: 'M15',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is N23.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 16. Ferrocarril Atlamaxac',
            sym: 'M16',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is N25.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 17. Campania del ferrocarril de Mexico a Puebla',
            sym: 'M17',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is N25.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 18. Ferrocarril Mexicano',
            sym: 'M18',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is N25.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 19. Cordoba and Huatusco Railroad',
            sym: 'M19',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is N27.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 20. Ferrocarril Interoceanico de Acapulco',
            sym: 'M20',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is P23.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 21. Ferrocarril Oaxaca a Ejutla',
            sym: 'M21',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is P27.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 22. Ferrocarriles Unidos de Yucatan',
            sym: 'M22',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is O32.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 23. Ferrocarril Merida a Valladolid',
            sym: 'M23',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is L37.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
          {
            name: 'MINOR: 24. Northern Railroad of Guatemala',
            sym: 'M24',
            value: 100,
            revenue: 0,
            desc: 'A 50% director’s certificate in the associated minor company. Starting location is Q34.',
            abilities: [],
            color: '#ffffff',
            text_color: 'black',
          },
        ].freeze

        CORPORATIONS = [
          {
            sym: '1',
            name: 'Ferrocarril Sonora-Baja California',
            logo: '1822_mx/1',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'B1',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '2',
            name: 'Rio Grande, Sierra Madre & Pacific Railway',
            logo: '1822_mx/2',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'D15',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '3',
            name: 'Ferrocarril Nacozari',
            logo: '1822_mx/3',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'E8',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '4',
            name: 'Ferrocarril Parral y Durango',
            logo: '1822_mx/4',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'F13',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '5',
            name: 'Ferrocarril Coahuila y Zacatecas',
            logo: '1822_mx/5',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'G22',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '6',
            name: 'Sinaloa and Durango Railroad',
            logo: '1822_mx/6',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'H11',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '7',
            name: 'Monterrey Mineral and Terminal Railway',
            logo: '1822_mx/7',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'I22',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '8',
            name: 'Ferrocarril Nacional de la Baja California',
            logo: '1822_mx/8',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'J9',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '9',
            name: 'Southern Pacific Railroad of Mexico',
            logo: '1822_mx/9',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'J13',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '10',
            name: 'Grand Junction Railway',
            logo: '1822_mx/10',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'K20',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '11',
            name: 'Guadalajara to Tepic and Mazatlan',
            logo: '1822_mx/11',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'L17',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '12',
            name: 'Ferrocarril Guanajuato a San Luis de la Paz y Pozos',
            logo: '1822_mx/12',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'L19',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '13',
            name: 'Ferrocarril San Marcos a Huajapan de Leon',
            logo: '1822_mx/13',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'L19',
            city: 1,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '14',
            name: 'Ferrocarril Cazadero y Solis',
            logo: '1822_mx/14',
            tokens: [20],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'N23',
            city: 1,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '15',
            name: 'Ferrocarril San Gregorio',
            logo: '1822_mx/15',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'N23',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '16',
            name: 'Ferrocarril Atlamaxac',
            logo: '1822_mx/16',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'N25',
            city: 2,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '17',
            name: 'Campania del ferrocarril de Mexico a Puebla',
            logo: '1822_mx/17',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'N25',
            city: 0,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '18',
            name: 'Ferrocarril Mexicano',
            logo: '1822_mx/18',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'N25',
            city: 1,
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '19',
            name: 'Cordoba and Huatusco Railroad',
            logo: '1822_mx/19',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'N27',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '20',
            name: 'Ferrocarril Interoceanico de Acapulco',
            logo: '1822_mx/20',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'P23',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '21',
            name: 'Ferrocarril Oaxaca a Ejutla',
            logo: '1822_mx/21',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'P27',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '22',
            name: 'Ferrocarriles Unidos de Yucatan',
            logo: '1822_mx/22',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'O32',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '23',
            name: 'Ferrocarril Merida a Valladolid',
            logo: '1822_mx/23',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'L37',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: '24',
            name: 'Northern Railroad of Guatemala',
            logo: '1822_mx/24',
            tokens: [0],
            type: 'minor',
            always_market_price: true,
            float_percent: 100,
            hide_shares: true,
            shares: [100],
            max_ownership_percent: 100,
            coordinates: 'Q34',
            color: '#ffffff',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: 'FCM',
            name: 'Ferrocarril Mexicano',
            logo: '1822_mx/FCM',
            tokens: [0, 100],
            type: 'major',
            float_percent: 20,
            shares: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
            always_market_price: true,
            coordinates: 'N23',
            city: 4,
            color: '#e51c00',
            reservation_color: nil,
            destination_coordinates: 'N27',
            destination_icon: '1822_xx/FCM_DEST',
          },
          {
            sym: 'MC',
            name: 'Mexican Central Railway',
            logo: '1822_mx/MC',
            tokens: [0, 100],
            type: 'major',
            float_percent: 20,
            always_market_price: true,
            coordinates: 'N23',
            city: 2,
            color: '#000000',
            reservation_color: nil,
            destination_coordinates: 'F21',
            destination_icon: '1822_xx/MC_DEST',
          },
          {
            sym: 'CHP',
            name: 'Chihuahua-Pacfic Railway',
            logo: '1822_mx/CHP',
            tokens: [0, 100],
            type: 'major',
            float_percent: 20,
            always_market_price: true,
            coordinates: 'F15',
            color: '#792e3c',
            text_color: 'black',
            reservation_color: nil,
            destination_coordinates: 'H11',
            destination_icon: '1822_xx/CHP_DEST',
          },
          {
            sym: 'FNM',
            name: 'Ferrocarriles Nacionales de Mexico',
            logo: '1822_mx/FNM',
            tokens: [0, 100],
            type: 'major',
            float_percent: 20,
            always_market_price: true,
            coordinates: 'N23',
            city: 3,
            color: '#850040',
            reservation_color: nil,
            destination_coordinates: 'G22',
            destination_icon: '1822_xx/FNM_DEST',
          },
          {
            sym: 'MIR',
            name: 'Mexican International Railroad',
            logo: '1822_mx/MIR',
            tokens: [0, 100],
            type: 'major',
            float_percent: 20,
            always_market_price: true,
            coordinates: 'F21',
            color: '#ff3600',
            reservation_color: nil,
            destination_coordinates: 'J15',
            destination_icon: '1822_xx/MIR_DEST',
          },
          {
            sym: 'FCP',
            name: 'Ferrocarril del Pacifico',
            logo: '1822_mx/FCP',
            tokens: [0, 100],
            type: 'major',
            float_percent: 20,
            always_market_price: true,
            coordinates: 'D9',
            color: '#fab506',
            reservation_color: nil,
            destination_coordinates: 'L17',
            destination_icon: '1822_xx/FCP_DEST',
          },
          {
            sym: 'IRM',
            name: 'Interoceanic Railway of Mexico',
            logo: '1822_mx/IRM',
            tokens: [0, 100],
            type: 'major',
            float_percent: 20,
            always_market_price: true,
            coordinates: 'N23',
            city: 5,
            color: '#004c6c',
            reservation_color: nil,
            destination_coordinates: 'N27',
            destination_icon: '1822_xx/IRM_DEST',
          },
        ].freeze
      end
    end
  end
end
