# frozen_string_literal: true

module Engine
  module Game
    module G18Norway
      module Corporations
        CORPORATIONS = [
          {
            float_percent: 60,
            sym: 'H',
            name: 'Hovedbanen',
            logo: '18_norway/HB',
            simple_logo: '18_norway/HB.alt',
            tokens: [0, 40, 60, 80],
            shares: [40, 20, 20, 20],
            coordinates: 'G29',
            city: 2,
            color: '#32763f',
            type: :minor,
            always_market_price: true,
          },
          {
            float_percent: 60,
            sym: 'D',
            name: 'Dovrebanen',
            logo: '18_norway/DB',
            simple_logo: '18_norway/DB.alt',
            tokens: [0, 40, 60, 80],
            shares: [40, 20, 20, 20],
            color: '#025aaa',
            coordinates: 'G17',
            type: :minor,
            always_market_price: true,
            abilities: [
              {
                description: '10% discount on trains',
                type: 'train_discount',
                discount: 0.10,
                trains: %w[2 3 4 5 6 D],
                when: 'buying_train',
              },
            ],
          },
          {
            float_percent: 60,
            sym: 'B',
            name: 'Bergensbanen',
            logo: '18_norway/BB',
            simple_logo: '18_norway/BB.alt',
            tokens: [0, 40, 60, 80],
            shares: [40, 20, 20, 20],
            coordinates: 'B26',
            color: '#d1232a',
            type: :minor,
            always_market_price: true,
          },
          {
            float_percent: 60,
            sym: 'R',
            name: 'Raumabanen ',
            logo: '18_norway/RB',
            simple_logo: '18_norway/RB.alt',
            tokens: [0, 40, 60, 80],
            shares: [40, 20, 20, 20],
            color: :'#474548',
            coordinates: 'E19',
            type: :minor,
            always_market_price: true,
          },
          {
            float_percent: 60,
            sym: 'S',
            name: 'Sørlandsbanen',
            logo: '18_norway/SB',
            simple_logo: '18_norway/SB.alt',
            tokens: [0, 40, 60, 80],
            shares: [40, 20, 20, 20],
            color: :'#FFF500',
            text_color: 'black',
            coordinates: 'C35',
            type: :minor,
            always_market_price: true,
          },
          {
            float_percent: 60,
            sym: 'J',
            name: 'Jærbanen',
            logo: '18_norway/JB',
            simple_logo: '18_norway/JB.alt',
            tokens: [0, 40, 60, 80],
            shares: [40, 20, 20, 20],
            color: :'#d88e39',
            coordinates: 'B32',
            type: :minor,
            always_market_price: true,
          },
          {
            float_percent: 60,
            sym: 'V',
            name: 'Vestfoldbanen',
            logo: '18_norway/VB',
            simple_logo: '18_norway/VB.alt',
            tokens: [0, 40, 60, 80],
            shares: [40, 20, 20, 20],
            color: :'#ADD8E6',
            text_color: 'black',
            coordinates: 'F30',
            type: :minor,
            always_market_price: true,
          },
          {
            float_percent: 60,
            sym: 'Ø',
            name: 'Østfoldsbanen',
            logo: '18_norway/OB',
            simple_logo: '18_norway/OB.alt',
            tokens: [0, 40, 60, 80],
            shares: [40, 20, 20, 20],
            coordinates: 'G31',
            color: :'#95c054',
            type: :minor,
            always_market_price: true,
          },
          {
            floatable: false,
            hide_shares: true,
            sym: 'NSB',
            name: 'Norges Statsbaner',
            tokens: [],
            shares: [100],
            logo: '18_norway/NSB',
            simple_logo: '18_norway/NSB',
            coordinates: %w[G15 A25 C17 A31 B36],
            color: :'#d7555f',
          },
        ].freeze
      end
    end
  end
end
