# frozen_string_literal: true

module Engine
  module Game
    module G18Cuba
      module Entities
        COMPANIES = [
          {
            name: 'Juan Tirry y Lacy',
            sym: 'C1',
            type: :commission,
            value: 0,
            revenue: 0,
            desc: 'Marquis de la Cañada. Funding Amount: 30. Yellow plain track tile '\
                  '(standard or narrow gauge including sugar cane field tiles)',
            color: nil,
          },
          {
            name: 'José a. Ferrety',
            sym: 'C2',
            type: :commission,
            value: 0,
            revenue: 0,
            desc: 'Sociedad Económica. Funding Amount: 35. Yellow city tile (without Y city tiles or Havana)',
            color: nil,
          },
          {
            name: 'Carlos Pedroso',
            sym: 'C3',
            type: :commission,
            value: 0,
            revenue: 0,
            desc: 'Real Consulado. Funding Amount: 40. Green plain track tile '\
                  '(standard or narrow gauge including sugar cane field tiles)',
            color: nil,
          },
          {
            name: 'Domingo Herrera',
            sym: 'C4',
            type: :commission,
            value: 0,
            revenue: 0,
            desc: 'Ayuntamiento de la Habana (Havana City Council). Funding Amount: 50. '\
                  'Green city tile (without Y city tiles or Havana)',
            color: nil,
          },
          {
            name: 'Andrés de Zayas',
            sym: 'C5',
            type: :commission,
            value: 0,
            revenue: 0,
            desc: 'Ayuntamiento de la Habana (Havana City Council). Funding Amount: 70. '\
                  'Brown plain track tile (standard or narrow gauge including sugar cane field tiles)',
            color: nil,
          },
          {
            name: 'Francisco Romero',
            sym: 'C6',
            type: :commission,
            value: 0,
            revenue: 0,
            desc: 'Real Consulado. Funding Amount: 80. Brown city tile (without Y city tiles or Havana)',
            color: nil,
          },
          {
            name: 'Claudio Martínez de Pinillos, Count of Villanueva',
            sym: 'M1',
            type: :concession,
            value: 120,
            revenue: 0,
            discount: 210,
            abilities: [
              {
                type: 'exchange',
                corporations: %w[HG JU HY DQ CO SB],
                owner_type: 'player',
                from: 'par',
              },
            ],
            desc: 'None',
            color: nil,
          },
          {
            name: 'Wenceslao de Villaurrutia, secretary',
            sym: 'M2',
            type: :concession,
            value: 140,
            revenue: 0,
            discount: 210,
            abilities: [
              {
                type: 'exchange',
                corporations: %w[HG JU HY DQ CO SB],
                owner_type: 'player',
                from: 'par',
              },
            ],
            desc: '1 Wagon. Must be assigned to a major company.',
            color: nil,
          },
          {
            name: 'Antonio M. de Escovedo, trustee',
            sym: 'M3',
            type: :concession,
            value: 150,
            revenue: 0,
            discount: 210,
            abilities: [
              {
                type: 'exchange',
                corporations: %w[HG JU HY DQ CO SB],
                owner_type: 'player',
                from: 'par',
              },
            ],
            desc: 'May be exchanged anytime during the game in one sugar mill machine (+10/+20/+40) '\
                  'if available to be used for a minor company. The machine is taken from the most expensive space.',
            color: nil,
          },
          {
            name: 'Joaquín de Uriarte, subintendant',
            sym: 'M4',
            type: :concession,
            value: 170,
            revenue: 0,
            discount: 210,
            abilities: [
              {
                type: 'exchange',
                corporations: %w[HG JU HY DQ CO SB],
                owner_type: 'player',
                from: 'par',
              },
            ],
            desc: '10% FC share',
            color: nil,
          },
          {
            name: 'Miguel A. Herrera',
            sym: 'M5',
            type: :concession,
            value: 180,
            revenue: 0,
            discount: 210,
            abilities: [
              {
                type: 'exchange',
                corporations: %w[HG JU HY DQ CO SB],
                owner_type: 'player',
                from: 'par',
              },
            ],
            desc: 'Mail contract. Must be assigned to a major company. Gives the company at the start of '\
                  'their turn during an OR if they own at least one train '\
                  'an income of +10/20/30/40 (depending on the phase).',
            color: nil,
          },
          {
            name: 'Alfred Cruger, first engineer',
            sym: 'M6',
            type: :concession,
            value: 200,
            revenue: 0,
            discount: 210,
            abilities: [
              {
                type: 'exchange',
                corporations: %w[HG JU HY DQ CO SB],
                owner_type: 'player',
                from: 'par',
              },
            ],
            desc: '$80 discount on a n-train.',
            color: nil,
          },
        ].freeze

        CORPORATIONS = [
          {
            float_percent: 60,
            sym: 'Oe',
            name: 'FC del Oeste',
            logo: '18_cuba/Oe',
            tokens: [0, 40, 60, 80],
            coordinates: 'B7',
            city: 0,
            color: :brown,
            type: :major,
            capitalization: :incremental,
          },
          {
            float_percent: 60,
            sym: 'MS',
            name: 'FC de Matanzas a Sabanillas',
            logo: '18_cuba/MS',
            tokens: [0, 40, 60, 80],
            coordinates: 'B9',
            color: :yellow,
            text_color: :black,
            type: :major,
            capitalization: :incremental,
          },
          {
            float_percent: 60,
            sym: 'CVC',
            name: 'FC Cienfuegos y Villa Clara',
            logo: '18_cuba/CVC',
            tokens: [0, 40, 60, 80],
            coordinates: 'C14',
            color: :darkgreen,
            type: :major,
            capitalization: :incremental,
          },
          {
            float_percent: 60,
            sym: 'NPP',
            name: 'FC Nuevitas-Puerto Príncipe',
            logo: '18_cuba/NPP',
            tokens: [0, 40, 60, 80],
            coordinates: 'D19',
            color: :orange,
            type: :major,
            capitalization: :incremental,
          },
          {
            float_percent: 60,
            sym: 'SdC',
            name: 'FC Santiago de Cuba',
            logo: '18_cuba/SdC',
            tokens: [0, 40, 60, 80],
            coordinates: 'G24',
            color: :lightblue,
            type: :major,
            capitalization: :incremental,
          },
          {
            float_percent: 60,
            sym: 'TSS',
            name: 'FC las Tunas – Sancti Spiritus',
            logo: '18_cuba/TSS',
            tokens: [0, 40, 60, 80],
            coordinates: 'E22',
            color: :red,
            type: :major,
            capitalization: :incremental,
          },
          {
            float_percent: 60,
            sym: 'StSp',
            name: 'FC de Sancti Spiritus',
            logo: '18_cuba/StSp',
            tokens: [0, 40, 60, 80],
            coordinates: 'D15',
            color: :black,
            type: :major,
            capitalization: :incremental,
          },
          {
            float_percent: 60,
            sym: 'FEC',
            name: 'Florida East Coast Railroad',
            logo: '18_cuba/FEC',
            tokens: [0, 40, 60, 80],
            color: :purple,
            type: :major,
            capitalization: :incremental,
          },
          {
            float_percent: 60,
            sym: 'FC',
            name: 'FC Central',
            logo: '18_cuba/FC',
            shares: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
            tokens: [0],
            coordinates: 'B7',
            city: 1,
            color: :white,
            text_color: :black,
            type: :state,
          },
          {
            float_percent: 60,
            sym: 'HG',
            name: 'FC de Holguin a Gibara',
            logo: '18_cuba/HG',
            tokens: [0],
            shares: [40, 20, 20, 20],
            color: :purple,
            type: :minor,
            capitalization: :incremental,
          },
          {
            float_percent: 60,
            sym: 'JU',
            name: 'FC de Júcaro',
            logo: '18_cuba/JU',
            tokens: [0],
            shares: [40, 20, 20, 20],
            color: :pink,
            type: :minor,
            capitalization: :incremental,
          },
          {
            float_percent: 60,
            sym: 'HY',
            name: 'FC Cubano de Hershey',
            logo: '18_cuba/HY',
            tokens: [0],
            shares: [40, 20, 20, 20],
            color: :darkblue,
            type: :minor,
            capitalization: :incremental,
          },
          {
            float_percent: 60,
            sym: 'DQ',
            name: 'FC de Dubrocq',
            logo: '18_cuba/DQ',
            tokens: [0],
            shares: [40, 20, 20, 20],
            color: :'#8B8000',
            type: :minor,
            capitalization: :incremental,
          },
          {
            float_percent: 60,
            sym: 'CO',
            name: 'FC del Cobre',
            logo: '18_cuba/CO',
            tokens: [0],
            shares: [40, 20, 20, 20],
            color: :lightgreen,
            type: :minor,
            capitalization: :incremental,
          },
          {
            float_percent: 60,
            sym: 'SB',
            name: 'FC de Cárdenas a Soledad de Bemba',
            logo: '18_cuba/SB',
            tokens: [0],
            shares: [40, 20, 20, 20],
            color: :brown,
            type: :minor,
            capitalization: :incremental,
          },
        ].freeze
      end
    end
  end
end
