# frozen_string_literal: true

module Engine
  module Game
    module G18Africa
      module Entities
        # Special abilities are added in a later stage; values and income are from rules [5].
        COMPANIES = [
          {
            name: 'Cape Wine Co.',
            sym: 'P1',
            value: 25,
            revenue: 5,
            desc: 'No special ability.',
            color: nil,
            type: :private,
          },
          {
            name: 'Allen Rock Aggregates',
            sym: 'P2',
            value: 35,
            revenue: 5,
            desc: 'Once per game, the Company may lay five yellow tiles on its turn instead of four.',
            color: nil,
            type: :private,
          },
          {
            name: 'Thompson Wagon Works',
            sym: 'P3',
            value: 60,
            revenue: 10,
            desc: 'Once per game, the Company may upgrade the same track tile twice in one turn instead of once.',
            color: nil,
            type: :private,
          },
          {
            name: 'Jamieson Tropical Timber',
            sym: 'P4',
            value: 75,
            revenue: 12,
            desc: 'Once per game, the Company does not need to pay the cost for one track lay over a river.',
            color: nil,
            type: :private,
          },
          {
            name: 'George Edmunds Colonial Factors',
            sym: 'P5',
            value: 115,
            revenue: 20,
            desc: 'Once per game, the Company does not need to pay the cost for one token lay '\
                  '(it may lay a £100 token even if a £40 one is still available).',
            color: nil,
            type: :private,
          },
          {
            name: 'Madianos Olive Groves',
            sym: 'P6',
            value: 160,
            revenue: 25,
            desc: 'Once per game, at the start of a Stock Round, the owning player may take the Priority Deal. '\
                  'Can be owned by but cannot be used by a Company.',
            color: nil,
            type: :private,
          },
        ].freeze

        # Director's certificate (20%) + 8 ordinary shares = 9 certificates per company [1.3].
        # The first token is the home token; the market marker is not a token here.
        CORPORATIONS = [
          {
            sym: 'AR',
            logo: '18_africa/AR',
            simple_logo: '18_africa/AR.alt',
            name: 'Alexandria Railway',
            tokens: [0, 40, 100, 100, 100],
            max_ownership_percent: 100,
            coordinates: 'N5',
            color: '#f4a07c',
            text_color: 'black',
          },
          {
            sym: 'CSAR',
            logo: '18_africa/CSAR',
            simple_logo: '18_africa/CSAR.alt',
            name: 'Central South African Railway',
            tokens: [0, 40, 100],
            max_ownership_percent: 100,
            coordinates: 'M32',
            city: 0,
            color: '#d49a1c',
          },
          {
            sym: 'AO',
            logo: '18_africa/AO',
            simple_logo: '18_africa/AO.alt',
            name: 'Algiers-Oran Railway',
            tokens: [0, 40],
            max_ownership_percent: 100,
            coordinates: 'G2',
            color: '#12d212',
          },
          {
            sym: 'EAR',
            logo: '18_africa/EAR',
            simple_logo: '18_africa/EAR.alt',
            name: 'East African Railroad',
            tokens: [0, 40, 100],
            max_ownership_percent: 100,
            coordinates: 'P21',
            color: '#c86414',
          },
          {
            sym: 'COR',
            logo: '18_africa/COR',
            simple_logo: '18_africa/COR.alt',
            name: 'Congo Océan Railway',
            tokens: [0, 40, 100, 100],
            max_ownership_percent: 100,
            coordinates: 'J21',
            city: 0,
            color: '#3cf0f0',
            text_color: 'black',
          },
          {
            sym: 'ENR',
            logo: '18_africa/ENR',
            simple_logo: '18_africa/ENR.alt',
            name: 'Egyptian National Railway',
            tokens: [0, 40, 100, 100],
            max_ownership_percent: 100,
            coordinates: 'N7',
            color: '#f5e600',
            text_color: 'black',
          },
          {
            sym: 'KR',
            logo: '18_africa/KR',
            simple_logo: '18_africa/KR.alt',
            name: 'Kenyan Railway',
            tokens: [0, 40, 100],
            max_ownership_percent: 100,
            coordinates: 'O20',
            color: '#2d6414',
          },
          {
            sym: 'CGH',
            logo: '18_africa/CGH',
            simple_logo: '18_africa/CGH.alt',
            name: 'Cape of Good Hope & Western Railway',
            tokens: [0, 40, 100],
            max_ownership_percent: 100,
            coordinates: 'K36',
            color: '#1e1e1e',
          },
          {
            sym: 'MF',
            logo: '18_africa/MF',
            simple_logo: '18_africa/MF.alt',
            name: 'Marrakech-Fez Railway',
            tokens: [0, 40],
            max_ownership_percent: 100,
            coordinates: 'D5',
            color: '#3291ff',
          },
          {
            sym: 'MNR',
            logo: '18_africa/MNR',
            simple_logo: '18_africa/MNR.alt',
            name: 'Moroccan National Railway',
            tokens: [0, 40],
            max_ownership_percent: 100,
            coordinates: 'D3',
            color: '#7d4614',
          },
          {
            sym: 'NR',
            logo: '18_africa/NR',
            simple_logo: '18_africa/NR.alt',
            name: 'Nigerian Railway',
            tokens: [0, 40],
            max_ownership_percent: 100,
            coordinates: 'G16',
            color: '#b40096',
          },
          {
            sym: 'NZA',
            logo: '18_africa/NZA',
            simple_logo: '18_africa/NZA.alt',
            name: 'Nederlands Zuid Afrikaanse Railway Co',
            tokens: [0, 40, 100],
            max_ownership_percent: 100,
            coordinates: 'M32',
            city: 1,
            color: '#a0401a',
          },
          {
            sym: 'TC',
            logo: '18_africa/TC',
            simple_logo: '18_africa/TC.alt',
            name: 'Tangier Casablanca High Speed Line',
            tokens: [0, 40],
            max_ownership_percent: 100,
            coordinates: 'E2',
            color: '#f5f096',
            text_color: 'black',
          },
          {
            sym: 'TO',
            logo: '18_africa/TO',
            simple_logo: '18_africa/TO.alt',
            name: 'Timbuktu-Oran Railway',
            tokens: [0, 40, 100],
            max_ownership_percent: 100,
            coordinates: 'F11',
            color: '#f9b4f4',
            text_color: 'black',
          },
          {
            sym: 'SR',
            logo: '18_africa/SR',
            simple_logo: '18_africa/SR.alt',
            name: 'Sudan Railway',
            tokens: [0, 40, 100],
            max_ownership_percent: 100,
            coordinates: 'O12',
            color: '#0a0ac8',
          },
          {
            sym: 'UR',
            logo: '18_africa/UR',
            simple_logo: '18_africa/UR.alt',
            name: 'Ugandan Railway',
            tokens: [0, 40, 100],
            max_ownership_percent: 100,
            coordinates: 'P23',
            color: '#b42828',
          },
          {
            sym: 'CNR',
            logo: '18_africa/CNR',
            simple_logo: '18_africa/CNR.alt',
            name: 'Congolese National Railway',
            tokens: [0, 40, 100, 100],
            max_ownership_percent: 100,
            coordinates: 'J21',
            city: 1,
            color: '#5014c0',
          },
        ].freeze

        # Printed share price of each company [6]; also its starting Market Value.
        CORPORATION_PRICES = {
          'AR' => 100,
          'CSAR' => 100,
          'AO' => 90,
          'EAR' => 90,
          'COR' => 82,
          'ENR' => 82,
          'KR' => 82,
          'CGH' => 76,
          'MF' => 76,
          'MNR' => 76,
          'NR' => 71,
          'NZA' => 71,
          'TC' => 71,
          'TO' => 71,
          'SR' => 67,
          'UR' => 64,
          'CNR' => 61,
        }.freeze
      end
    end
  end
end
