# frozen_string_literal: true

module Engine
  module Game
    module G1835
      module Entities
        COMPANIES = [
          {
            name: 'Leipzig-Dresdner Bahn',
            sym: 'LD',
            value: 190,
            revenue: 20,
            desc: 'Leipzig-Dresdner Bahn - Sachsen Direktor Papier',
            abilities: [{ type: 'shares', shares: 'SX_0' },
                        { type: 'no_buy' },
                        { type: 'close', when: 'bought_train', corporation: 'SX' }],
            color: '#D63031',
          },
          {
            name: 'Ostbayrische Bahn',
            sym: 'OBB',
            value: 120,
            revenue: 10,
            desc: 'Ostbayrische Bahn - 2 Tiles on M15, M17 extra (one per OR) and without cost',
            abilities: [
              {
                type: 'teleport',
                description: "Place a free track tile at m15, M17 at any time during the corporation's operations.",
                owner_type: 'player',
                hexes: %w[M15 M17],
                tiles: %w[1 2 3 4 5 6 7 8 9 55 56 57 58],
                free_tile_lay: true,
                when: 'owning_player_or_turn',
                count: 2,
              },
              { type: 'shares', shares: 'BY_1' },
            ],
            color: '#3A9BDC',
            text_color: 'black',
          },
          {
            name: 'Nürnberg-Fürth',
            sym: 'NF',
            value: 100,
            revenue: 5,
            desc: 'Nürnberg-Fürth Bahn, Director of any AG may lay token on L14 north or south',
            abilities: [{ type: 'shares', shares: 'BY_2' }, {
              type: 'token',
              when: 'owning_player_or_turn',
              owner_type: 'player',
              hexes: ['L14'],
              price: 0,
              teleport_price: 0,
              count: 1,
              extra_action: true,
            }],
            color: '#3A9BDC',
            text_color: 'black',
          },
          {
            name: 'Hannoversche Bahn',
            sym: 'HB',
            value: 160,
            revenue: 30,
            desc: '10 Percent Share of Preussische Bahn on Exchange',
            abilities: [
              {
                type: 'exchange',
                corporations: %w[PR_1],
                owner_type: 'player',
                when: ['Phase 2.3', 'Phase 2.4', 'Phase 3.1'],
                # reserved papers perhaps a option
                from: 'ipo',
              },
            ],
            color: 'black',
            text_color: 'white',
          },
          {
            name: 'Pfalzbahnen',
            sym: 'PB',
            value: 150,
            revenue: 15,
            desc: 'Can lay a tile on L6 and Token on L6 if Baden AG is active already',
            abilities: [
              {
                type: 'teleport',
                owner_type: 'player',
                free_tile_lay: true,
                hexes: ['L6'],
                when: 'owning_player_or_turn',
                tiles: %w[210 211 212 213 214 215],
              },
              { type: 'shares', shares: 'BY_3' },
              {
                type: 'token',
                when: 'owning_player_or_turn',
                owner_type: 'player',
                hexes: ['L6'],
                price: 0,
                teleport_price: 0,
                count: 1,
                extra_action: true,
              },
            ],
            color: '#3A9BDC',
            text_color: 'black',
          },
          {
            name: 'Braunschweigische Bahn',
            sym: 'BB',
            value: 130,
            revenue: 25,
            desc: 'Can be exchanged for a 10% share of Preussische Bahn',
            abilities: [
              {
                type: 'exchange',
                corporations: %w[PR_2],
                owner_type: 'player',
                when: ['Phase 2.3', 'Phase 2.4', 'Phase 3.1'],
                from: 'ipo',
              },
            ],
            color: 'black',
            text_color: 'white',
          },
          {
            name: 'Bayerische Eisenbahn Direktor',
            sym: 'BYD',
            value: 184,
            revenue: 0,
            desc: 'Bayerische Eisenbahn Direktor - 20% share of Bayrische Eisenbahn',
            abilities: [{ type: 'shares', shares: 'BY_0' },
                        { type: 'no_buy' }],
            color: '#3A9BDC',
            text_color: 'black',
          },
        ].freeze

        CORPORATIONS = [
          {
            sym: 'BY',
            name: 'Bayrische Eisenbahn',
            logo: '1835/BY',
            simple_logo: '1835/BY.alt',
            tokens: [0, 0, 0, 0, 0],
            type: 'major',
            float_percent: 50,
            max_ownership_percent: 100,
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            coordinates: 'O15',
            color: '#3A9BDC',
            text_color: 'black',
          },
          {
            sym: 'SX',
            name: 'Sächsische Eisenbahn',
            logo: '1835/SX',
            simple_logo: '1835/SX.alt',
            tokens: [0, 0, 0],
            type: 'major',
            float_percent: 50,
            max_ownership_percent: 100,
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            coordinates: 'H16',
            color: '#D63031',
            text_color: 'black',
          },
          {
            sym: 'BA',
            name: 'Badische Eisenbahn',
            logo: '1835/BA',
            simple_logo: '1835/BA.alt',
            tokens: [0, 0],
            type: 'major',
            float_percent: 50,
            max_ownership_percent: 100,
            shares: [20, 10, 10, 10, 10, 10, 10, 20],
            coordinates: 'L6',
            color: '#8E5E41',
          },
          {
            sym: 'HE',
            name: 'Hessische Eisenbahn',
            logo: '1835/HE',
            simple_logo: '1835/HE.alt',
            tokens: [0, 0],
            type: 'major',
            float_percent: 50,
            max_ownership_percent: 100,
            shares: [20, 10, 10, 10, 10, 10, 10, 20],
            last_cert: %w[HE_7],
            coordinates: 'J8',
            color: '#4D9455',
          },
          {
            sym: 'WT',
            name: 'Württembergische Eisenbahn',
            logo: '1835/WT',
            simple_logo: '1835/WT.alt',
            tokens: [0, 0],
            float_percent: 50,
            max_ownership_percent: 100,
            type: 'major',
            shares: [20, 10, 10, 10, 10, 10, 10, 20],
            last_cert: ['WT_7'],
            coordinates: 'M9',
            color: '#F1D849',
            text_color: 'black',
          },
          {
            sym: 'MS',
            name: 'Eisenbahn Mecklenburg Schwerin',
            logo: '1835/MS',
            simple_logo: '1835/MS.alt',
            tokens: [0, 0],
            percent: 10,
            type: 'major',
            float_percent: 60,
            max_ownership_percent: 100,
            shares: [20, 10, 20, 20, 10, 10, 10],
            # the shares order creates a 10 share company, but the first 3 sold papers are 20%
            coordinates: 'C13',
            color: '#8063A3',
            text_color: 'black',
          },
          {
            sym: 'OL',
            name: 'Oldenburgische Eisenbahn',
            logo: '1835/OL',
            simple_logo: '1835/OL.alt',
            tokens: [0, 0],
            float_percent: 60,
            max_ownership_percent: 100,
            type: 'major',
            shares: [20, 10, 20, 20, 10, 10, 10],
            # the shares order creates a 10 share company, but the first 3 sold papers are 20%
            coordinates: 'D6',
            color: '#B2B2B2',
          },

          {
            sym: 'PR',
            name: 'Preussische Eisenbahn',
            logo: '1835/PR',
            simple_logo: '1835/PR.alt',
            tokens: [0, 0, 0, 0, 0],
            type: 'Prussian',
            max_ownership_percent: 100,
            shares: [10, 10, 10, 10, 10, 10, 10, 10, 5, 5, 5, 5],
            # shares for minors and Privates should be reserved
            coordinates: 'E19',
            color: '#37383a',
          },
        ].freeze

        MINORS = [
          {
            sym: 'M1',
            name: 'Bergisch Märkische Bahn',
            logo: '1835/PR',
            simple_logo: '1835/PR.alt',
            value: 80,
            type: 'minor',
            tokens: [0],
            abilities: [
              {
                type: 'exchange',
                corporations: %w[PR_9],
                owner_type: 'player',
                when: ['Phase 2.3', 'Phase 2.4', 'Phase 3.1'],
                # reserved papers perhaps a option
                from: 'ipo',
              },
            ],
            coordinates: 'H2',
            color: '#37383a',
          },
          {
            sym: 'M2',
            name: 'Berlin Potsdamer Bahn',
            logo: '1835/PR',
            simple_logo: '1835/PR.alt',
            value: 170,
            type: 'minor',
            city: 0,
            tokens: [0],
            abilities: [
              {
                type: 'exchange',
                corporations: %w[PR_0],
                owner_type: 'player',
                when: ['Phase 2.3', 'Phase 2.4', 'Phase 3.1'],
                # reserved papers perhaps a option
                from: 'ipo',
              },
            ],
            coordinates: 'E19',
            color: '#37383a',
          },
          {
            sym: 'M3',
            name: 'Magdeburger-Bahn',
            logo: '1835/PR',
            simple_logo: '1835/PR.alt',
            value: 80,
            type: 'minor',
            tokens: [0],
            abilities: [
              {
                type: 'exchange',
                corporations: %w[PR_10],
                owner_type: 'player',
                when: ['Phase 2.3', 'Phase 2.4', 'Phase 3.1'],
                # reserved papers perhaps a option
                from: 'ipo',
              },
            ],
            coordinates: 'F14',
            color: '#37383a',
          },
          {
            sym: 'M4',
            name: 'Köln-Mindener Bahn',
            logo: '1835/PR',
            simple_logo: '1835/PR.alt',
            value: 160,
            type: 'minor',
            tokens: [0],
            abilities: [
              {
                type: 'exchange',
                corporations: %w[PR_3],
                owner_type: 'player',
                when: ['Phase 2.3', 'Phase 2.4', 'Phase 3.1'],
                # reserved papers perhaps a option
                from: 'ipo',
              },
            ],
            coordinates: 'G5',
            color: '#37383a',
          },
          {
            sym: 'M5',
            name: 'Berlin Stettiner Bahn',
            logo: '1835/PR',
            simple_logo: '1835/PR.alt',
            value: 80,
            type: 'minor',
            city: 1,
            tokens: [0],
            abilities: [
              {
                type: 'exchange',
                corporations: %w[PR_11],
                owner_type: 'player',
                when: ['Phase 2.3', 'Phase 2.4', 'Phase 3.1'],
                # reserved papers perhaps a option
                from: 'ipo',
              },
            ],
            coordinates: 'E19',
            color: '#37383a',
          },
          {
            sym: 'M6',
            name: 'Altona Kiel Bahn',
            logo: '1835/PR',
            simple_logo: '1835/PR.alt',
            value: 80,
            type: 'minor',
            city: 1,
            tokens: [0],
            abilities: [
              {
                type: 'exchange',
                corporations: %w[PR_8],
                owner_type: 'player',
                when: ['Phase 2.3', 'Phase 2.4', 'Phase 3.1'],
                # reserved papers perhaps a option
                from: 'ipo',
              },
            ],
            coordinates: 'C11',
            color: '#37383a',
          },
        ].freeze

        # Start packet positions: [entity_symbol, row, column]
        # Grid arrangement for draft system
        START_PACKET = [
          ['NF', 1, 1],
          ['M1', 2, 1],
          ['LD', 2, 2],
          ['M2', 2, 3],
          ['M3', 3, 1],
          ['M4', 3, 2],
          ['BYD', 3, 3],
          ['BB', 3, 4],
          ['HB', 4, 1],
          ['M5', 4, 2],
          ['M6', 4, 3],
          ['OBB', 4, 4],
          ['PB', 4, 5],
        ].freeze
      end
    end
  end
end
