# frozen_string_literal: true

module Engine
  module Game
    module G1871
      module Corporations
        CORPORATIONS = [
          {
            float_percent: 60,
            sym: 'So',
            name: 'Souris - 1',
            logo: '1871/So',
            tokens: [0, 100, 100, 100],
            coordinates: 'T12',
            color: '#0a0a0a',
            reservation_color: nil,
            float_excludes_market: true,
            float_includes_reserved: true,
            always_market_price: true,
          },
          {
            float_percent: 60,
            sym: 'A',
            name: 'Alberton - 2',
            logo: '1871/A',
            tokens: [0, 100, 100, 100],
            coordinates: 'D6',
            color: '#b58168',
            text_color: '#000000',
            reservation_color: nil,
            float_excludes_market: true,
            float_includes_reserved: true,
            always_market_price: true,
          },
          {
            float_percent: 60,
            sym: 'MS',
            name: 'Mount Stewart - 3',
            logo: '1871/MS',
            tokens: [0, 100, 100, 100],
            coordinates: 'M13',
            color: '#fcea18',
            text_color: '#000000',
            reservation_color: nil,
            float_excludes_market: true,
            float_includes_reserved: true,
            always_market_price: true,
          },
          {
            float_percent: 60,
            sym: 'MR',
            name: 'Murray River - 4',
            logo: '1871/MR',
            tokens: [0, 100, 100, 100],
            coordinates: 'Q21',
            color: '#37b2e2',
            text_color: '#000000',
            reservation_color: nil,
            float_excludes_market: true,
            float_includes_reserved: true,
            always_market_price: true,
          },
          {
            float_percent: 60,
            sym: 'S',
            name: 'Summerside - 5',
            logo: '1871/S',
            tokens: [0, 100, 100, 100],
            coordinates: 'F14',
            color: '#7bb137',
            text_color: '#000000',
            reservation_color: nil,
            float_excludes_market: true,
            float_includes_reserved: true,
            always_market_price: true,
          },
          {
            float_percent: 60,
            sym: 'Gt',
            name: 'Georgetown - 6',
            logo: '1871/Gt',
            tokens: [0, 100, 100, 100],
            coordinates: 'R16',
            color: '#9a9a9d',
            text_color: '#000000',
            reservation_color: nil,
            float_excludes_market: true,
            float_includes_reserved: true,
            always_market_price: true,
          },
          {
            float_percent: 60,
            sym: 'C',
            name: 'Charlottetown - 7',
            logo: '1871/C',
            tokens: [0, 100, 100, 100],
            coordinates: 'L16',
            color: '#a60a3d',
            reservation_color: nil,
            float_excludes_market: true,
            float_includes_reserved: true,
            always_market_price: true,
          },
          {
            float_percent: 0,
            sym: 'PEIR',
            name: 'Prince Edward Island Railway',
            logo: '1871/PEIR',
            shares: [20, 20, 20, 20, 20],
            tokens: [0, 0, 0, 0, 0],
            color: '#ec767c',
            text_color: '#000000',
            reservation_color: nil,
            max_ownership_percent: 100,
          },
          {
            float_percent: 60,
            sym: 'CB',
            name: 'Cornwall Branch',
            logo: '1871/CB',
            tokens: [0, 100, 100, 100],
            color: '#baa4cb',
            text_color: '#000000',
            reservation_color: nil,
            float_excludes_market: true,
            float_includes_reserved: true,
            always_market_price: true,
            capitalization: :none,
          },
          {
            float_percent: 60,
            sym: 'SB',
            name: 'Stratford Branch',
            logo: '1871/SB',
            tokens: [0, 100, 100, 100],
            color: '#bf4da5',
            reservation_color: nil,
            float_excludes_market: true,
            float_includes_reserved: true,
            always_market_price: true,
            capitalization: :none,
          },
          {
            float_percent: 60,
            sym: 'MB',
            name: 'Morel Branch',
            logo: '1871/MB',
            tokens: [0, 100, 100, 100],
            color: '#0a70b3',
            reservation_color: nil,
            float_excludes_market: true,
            float_includes_reserved: true,
            always_market_price: true,
            capitalization: :none,
          },
          {
            float_percent: 60,
            sym: 'BB',
            name: 'Belfast Branch',
            logo: '1871/BB',
            tokens: [0, 100, 100, 100],
            color: '#eb6f0e',
            text_color: '#000000',
            reservation_color: nil,
            float_excludes_market: true,
            float_includes_reserved: true,
            always_market_price: true,
            capitalization: :none,
          },
          {
            float_percent: 60,
            sym: 'WB',
            name: 'Wellington Branch',
            logo: '1871/WB',
            tokens: [0, 100, 100, 100],
            color: '#bdbd00',
            text_color: '#000000',
            reservation_color: nil,
            float_excludes_market: true,
            float_includes_reserved: true,
            always_market_price: true,
            capitalization: :none,
          },
          {
            float_percent: 60,
            sym: 'HRB',
            name: 'Hunter River Branch',
            logo: '1871/HRB',
            tokens: [0, 100, 100, 100],
            color: '#008f4f',
            reservation_color: nil,
            float_excludes_market: true,
            float_includes_reserved: true,
            always_market_price: true,
            capitalization: :none,
          },
        ].freeze
      end
    end
  end
end
