# frozen_string_literal: true

module Engine
  module Game
    module G1871
      module Map
        # Map orientation
        LAYOUT = :flat

        LOCATION_NAMES = {
          'A1' => 'Miramichi',
          'M11' => 'Blooming Point',
          'P10' => 'Saint Peters Harbour',
          'U13' => 'Red Point',
          'M13' => 'Mount Stewart',
          'S17' => 'Cardigan Point',
          'H6' => 'England',
          'H14' => 'New London & Kensington',
          'K15' => 'Royalty Jct & York',
          'M17' => 'Stratford',
          'M21' => 'Pinette Harbour',
          'R22' => 'Murray Harbour',
          'K19' => 'Cornwall',
          'K21' => 'North River',
          'P16' => 'Cardigan Head & Lorne Valley',
          'R12' => 'Bear River & Selkirk',
          'R16' => 'Georgetown',
          'R18' => 'Georgetown Harbour',
          'P22' => 'Hopefield & Woods Islands',
          'P26' => 'Pictou Landing',
          'L12' => 'Oyster Bed Bridge',
          'I13' => 'Stanley Bridge',
          'I17' => 'Emerald Jct',
          'I19' => 'Kinkora',
          'H20' => 'Cape Traverse',
          'O19' => 'Iona & Eldon',
          'E7' => 'Northport',
          'E11' => 'Ellerslie & Richmond',
          'C5' => 'Profits Corner & Saint Louis',
          'D8' => 'Freeland & Portage',
          'C13' => 'Cape Egmont',
          'A7' => 'West Cape',
          'T12' => 'Souris',
          'T14' => 'Souris Harbour',
          'R20' => 'Beach Point',
          'N20' => 'Belfast',
          'J14' => 'Hunter River',
          'J20' => 'Eliot River',
          'O15' => 'Peakes',
          'N14' => 'Pisquid & Scotchfort',
          'G17' => 'Borden',
          'D14' => 'Wellington',
          'D2' => 'Tignish',
          'V12' => 'Elmira',
          'V16' => 'Îles de la Madeleine',
          'Q17' => 'Montague',
          'Q15' => 'Cardigan',
          'Q21' => 'Murray River',
          'F14' => 'Summerside',
          'L16' => 'Charlottetown',
          'S21' => 'Port Hawkesbury',
          'D6' => 'Alberton',
          'F20' => 'Cape Tormentine',
          'G11' => 'Malpeque Shipyard',
          'B8' => 'O\'Leary',
        }.freeze

        HEXES = {
          red: {
            ['A1'] => 'offboard=revenue:yellow_20|brown_80;path=a:5,b:_0',
            ['H6'] => 'offboard=revenue:yellow_60|brown_70;path=a:0,b:_0',
            ['P26'] => 'offboard=revenue:yellow_30|brown_60;path=a:2,b:_0',
            ['V16'] => 'offboard=revenue:yellow_40|brown_60;path=a:1,b:_0',
            ['S21'] => 'offboard=revenue:yellow_0|green_10|brown_60;path=a:2,b:_0',
            ['F20'] => 'offboard=revenue:yellow_30|brown_80;path=a:3,b:_0',
          },
          blue: {
            %w[B2 U15] => 'path=a:0,b:2',
            %w[U17] => 'path=a:3,b:4',
            %w[H8 P24] => 'path=a:1,b:3',
            %w[H10] => 'path=a:1,b:2',
            %w[F18] => 'path=a:0,b:4',
            %w[O25 G9] => 'path=a:4,b:5',
          },
          white: {
            %w[B4 C3 B6 D4 E9 H12 H18 I15 J12 J18 K13 K17 L14 N12 O11 O13 O17 O21 P20 Q11 Q13 Q19 R14 S13 N18 D12 C7 P18 G15
               E15] => '',
            %w[U13 L12 J20 Q17 Q15] => 'town=revenue:0',
            %w[M13 Q21 D6] => 'city=revenue:0;label=X',
            %w[H14 K15 P16 P22 O19 E11 C5] => 'town=revenue:0;town=revenue:0',
            %w[N16 J16 H16 P14] => 'upgrade=cost:80,terrain:mountain',
            %w[K19 N20 J14] => 'city=revenue:0',
            %w[R12 N14] => 'town=revenue:0;town=revenue:0;upgrade=cost:60,terrain:water',
            %w[R16] => 'city=revenue:0;label=X;upgrade=cost:60,terrain:water',
            %w[I13] => 'town=revenue:0;upgrade=cost:60,terrain:water',
            %w[C9 D10 E13 F10 S11] => 'upgrade=cost:60,terrain:water',
            %w[D8] => 'town=revenue:0;town=revenue:0;upgrade=cost:80,terrain:water',
            %w[T12] => 'city=revenue:20;path=a:3,b:_0;label=X;upgrade=cost:60,terrain:water',
            %w[G13 F12] => 'upgrade=cost:120,terrain:water',
            %w[G17] => 'city=revenue:0;upgrade=cost:60,terrain:water',
            %w[V12] => 'city=revenue:0;label=T',
          },
          gray: {
            %w[M11 C13 A7] => 'town=revenue:20;path=a:5,b:_0',
            %w[P10] => 'town=revenue:20;path=a:0,b:_0',
            %w[S17 R22 E7] => 'town=revenue:10;path=a:2,b:_0',
            %w[H20] => 'town=revenue:40;path=a:4,b:_0',
            %w[T10] => 'path=a:0,b:1;path=a:0,b:5;path=a:1,b:5',
            %w[U11] => 'path=a:2,b:5',
            %w[M17] => 'town=revenue:10;path=a:2,b:_0;path=a:_0,b:5',
            %w[M21] => 'town=revenue:20;path=a:4,b:_0',
            %w[K21] => 'town=revenue:10;path=a:2,b:_0;path=a:_0,b:3',
            %w[R18] => 'town=revenue:10;path=a:3,b:_0',
            %w[I17] => 'city=revenue:10,slots:2;path=a:0,b:_0;path=a:2,b:_0;path=a:4,b:_0',
            %w[I19] => 'town=revenue:10;path=a:1,b:_0;path=a:_0,b:3',
            %w[O23] => 'path=a:3,b:4',
            %w[T14] => 'town=revenue:20;path=a:3,b:_0;path=a:_0,b:5',
            %w[R20] => 'town=revenue:20;path=a:1,b:_0;path=a:_0,b:5',
            %w[G11] => 'city=revenue:yellow_20|brown_60;path=a:0,b:_0;path=a:4,b:_0;path=a:5,b:_0',
            %w[B8] => 'town=revenue:20;path=a:4,b:_0;path=a:3,b:_0;path=a:2,b:_0;path=a:5,b:_0',
          },
          yellow: {
            %w[O15] => 'city=revenue:20;path=a:0,b:_0;path=a:2,b:_0;path=a:4,b:_0',
            %w[D14] => 'city=revenue:20;path=a:5,b:_0;path=a:3,b:_0',
            %w[D2] => 'city=revenue:20;path=a:0,b:_0;path=a:1,b:_0;label=T',
            %w[F14] => 'city=revenue:20;path=a:5,b:_0;path=a:1,b:_0;label=X',
            %w[L16] => 'city=revenue:20;path=a:1,b:_0;path=a:5,b:_0;label=CX',
          },
          green: {
            %w[M15] => 'path=a:2,b:3;path=a:1,b:5',
            %w[P12] => 'city=revenue:30,slots:2;path=a:0,b:_0;path=a:2,b:_0;path=a:3,b:_0;path=a:4,b:_0',
          },
        }.freeze
      end
    end
  end
end
