# frozen_string_literal: true

module Engine
  module Game
    module G18NewEnglandNorth
      module Entities
        # retain this until draft is implemented to allow game to start
        COMPANIES = [
                  {
                    name: 'Delaware and Raritan Canal',
                    value: 20,
                    revenue: 5,
                    desc: 'No special ability. Blocks hex K3 while owned by a player.',
                    sym: 'D&R',
                    color: nil,
                  },
        ].freeze

        CORPORATIONS = [
          {
            sym: 'AWS',
            name: 'Albany and West Stockbridge Railroad',
            coordinates: 'H11',
            logo: '18_new_england/AWS',
            color: 'red',
            tokens: [0],
            float_percent: 100,
            shares: [100],
            type: 'minor',
            reservation_color: nil,
          },
          {
            sym: 'BL',
            name: 'Boston and Lowell Railroad',
            coordinates: 'A22',
            logo: '18_new_england/BL',
            color: 'orange',
            tokens: [0],
            float_percent: 100,
            shares: [100],
            type: 'minor',
            reservation_color: nil,
          },
          {
            sym: 'BP',
            name: 'Boston & Providence',
            coordinates: 'C8',
            logo: '18_new_england/BP',
            color: 'olive',
            tokens: [0],
            float_percent: 100,
            shares: [100],
            type: 'minor',
            reservation_color: nil,
          },
          {
            sym: 'CR',
            name: 'Connecticut River',
            coordinates: 'C18',
            logo: '18_new_england/CR',
            color: 'brown',
            tokens: [0],
            float_percent: 100,
            shares: [100],
            type: 'minor',
            reservation_color: nil,
          },
          {
            sym: 'CV',
            name: 'Connecticut Valley',
            coordinates: 'D5',
            logo: '18_new_england/CV',
            color: 'yellow',
            text_color: 'black',
            tokens: [0],
            float_percent: 100,
            shares: [100],
            type: 'minor',
            reservation_color: nil,
          },
          {
            sym: 'ER',
            name: 'Eastern Railroad',
            coordinates: 'D17',
            logo: '18_new_england/ER',
            color: 'purple',
            tokens: [0],
            float_percent: 100,
            shares: [100],
            type: 'minor',
            reservation_color: nil,
          },
          {
            sym: 'FRR',
            name: 'Fitchburg Railroad',
            coordinates: 'E16',
            logo: '18_new_england/FRR',
            color: 'green',
            tokens: [0],
            float_percent: 100,
            shares: [100],
            type: 'minor',
            reservation_color: nil,
          },
          {
            sym: 'GR',
            name: 'Granite Railway',
            coordinates: 'F3',
            logo: '18_new_england/GR',
            color: 'green',
            tokens: [0],
            float_percent: 100,
            shares: [100],
            type: 'minor',
            reservation_color: nil,
          },
          {
            sym: 'HNH',
            name: 'Hartford and New Haven',
            coordinates: 'F9',
            logo: '18_new_england/HNH',
            color: 'magenta',
            tokens: [0],
            float_percent: 100,
            shares: [100],
            type: 'minor',
            reservation_color: nil,
          },
          {
            sym: 'HRR',
            name: 'Hudson Railroad',
            coordinates: 'G10',
            logo: '18_new_england/HRR',
            color: 'navy',
            tokens: [0],
            float_percent: 100,
            shares: [100],
            type: 'minor',
            reservation_color: nil,
          },
          {
            sym: 'NLN',
            name: 'New London Northern Railroad',
            coordinates: 'G14',
            logo: '18_new_england/NLN',
            color: 'lightBlue',
            text_color: 'black',
            tokens: [0],
            float_percent: 100,
            shares: [100],
            type: 'minor',
            reservation_color: nil,
          },
          {
            sym: 'NYNH',
            name: 'New York New Haven Railroad',
            coordinates: 'H3',
            logo: '18_new_england/NYNH',
            color: 'darkOrange',
            tokens: [0],
            float_percent: 100,
            shares: [100],
            type: 'minor',
            reservation_color: nil,
          },
          {
            sym: 'NYW',
            name: 'New York Westchester Boston',
            coordinates: 'C2',
            logo: '18_new_england/NYW',
            color: 'red',
            tokens: [0],
            float_percent: 100,
            shares: [100],
            type: 'minor',
            reservation_color: nil,
          },
          {
            sym: 'PE',
            name: 'Poughkeepsie and Eastern Railway',
            coordinates: 'H13',
            logo: '18_new_england/PE',
            color: 'brown',
            tokens: [0],
            float_percent: 100,
            shares: [100],
            type: 'minor',
            reservation_color: nil,
          },
          {
            sym: 'WNR',
            name: 'Worcester, Nashua and Rochester Railroad',
            coordinates: 'I6',
            logo: '18_new_england/WNR',
            color: 'black',
            tokens: [0],
            float_percent: 100,
            shares: [100],
            type: 'minor',
            reservation_color: nil,
          },
        ].freeze
      end
    end
  end
end
