# frozen_string_literal: true

module Engine
  module Game
    module G18MT
      module Corporations
        CORPORATIONS = [
          {
            sym: 'NP',
            name: 'Northern Pacific',
            float_percent: 50,
            always_market_price: true,
            logo: '18_mt/NP',
            simple_logo: '18_mt/NP.alt',
            tokens: [0, 40, 100, 100, 100],
            coordinates: 'F22',
            'text-color': 'white',
            color: :'#20451d',
            reservation_color: nil,
            abilities: [{ type: 'description', description: 'Tile Lay Blocked by GV' }],
          },
          {
            sym: 'MC',
            name: 'Montana Central',
            float_percent: 50,
            always_market_price: true,
            logo: '18_mt/MC',
            simple_logo: '18_mt/MC.alt',
            tokens: [0, 40],
            coordinates: 'C9',
            'text-color': 'white',
            color: :'#754d24',
            reservation_color: nil,
          },
          {
            sym: 'GN',
            name: 'Great Northern',
            float_percent: 50,
            always_market_price: true,
            logo: '18_mt/GN',
            simple_logo: '18_mt/GN.alt',
            tokens: [0, 40, 100, 100, 100],
            city: 0,
            coordinates: 'A21',
            color: '#d81e3e',
            reservation_color: nil,
            abilities: [{ type: 'description', description: 'Tile Lay Blocked by SOO' }],
          },
          {
            sym: 'MILW',
            name: 'Chicago, Milwaukee, St. Paul and Pacific Railroad',
            float_percent: 50,
            always_market_price: true,
            logo: '18_mt/MILW',
            simple_logo: '18_mt/MILW.alt',
            tokens: [0, 40, 60, 80],
            coordinates: 'C19',
            'text-color': 'white',
            color: :'#919191',
            reservation_color: nil,
          },
          {
            sym: 'MR',
            name: 'Montana Railroad',
            float_percent: 50,
            always_market_price: true,
            logo: '18_mt/MR',
            simple_logo: '18_mt/MR.alt',
            tokens: [0, 40, 60],
            coordinates: 'E9',
            'text-color': 'white',
            color: '#000000',
            reservation_color: nil,
          },
          {
            sym: 'CBQ',
            name: 'Chicago, Burlington & Quincy',
            float_percent: 50,
            always_market_price: true,
            logo: '18_mt/CBQ',
            simple_logo: '18_mt/CBQ.alt',
            tokens: [0, 40, 60],
            coordinates: 'G15',
            text_color: 'black',
            color: '#f48221',
            reservation_color: nil,
          },
          {
            sym: 'UP',
            name: 'Union Pacific',
            float_percent: 50,
            always_market_price: true,
            logo: '18_mt/UP',
            simple_logo: '18_mt/UP.alt',
            tokens: [0, 40, 100, 100, 100],
            coordinates: 'H6',
            text_color: 'black',
            color: :'#ffffeb',
            reservation_color: nil,
            abilities: [{ type: 'description', description: 'Tile Lay Blocked by GP' }],
          },
          {
            sym: 'MWS',
            name: 'Montana, Wyoming & Southern',
            float_percent: 50,
            always_market_price: true,
            logo: '18_mt/MWS',
            simple_logo: '18_mt/MWS.alt',
            tokens: [0, 40, 60],
            coordinates: 'F12',
            text_color: 'white',
            color: :'#00bfff',
            reservation_color: nil,
          },
          {
            sym: 'BAP',
            name: 'Butte, Anaconda & Pacific',
            float_percent: 50,
            always_market_price: true,
            logo: '18_mt/BAP',
            simple_logo: '18_mt/BAP.alt',
            tokens: [0, 0],
            coordinates: 'D6',
            text_color: 'black',
            color: '#FFF500',
            reservation_color: nil,
          },
        ].freeze
      end
    end
  end
end
