# frozen_string_literal: true

require_relative 'meta'
require_relative '../base'

module Engine
  module Game
    module GRollingStock
      module Entities
        COMPANIES = [
          {
            name: 'Bergisch-Märkische Eisenbahn-Gesellschaft',
            sym: 'BME',
            value: 1,
            min_price: 1,
            max_price: 2,
            revenue: 1,
            level: 1,
            synergies: %w[KME BD HE PR],
          },
          {
            name: 'Berlin-Stettiner Eisenbahn-Gesellschaft',
            sym: 'BSE',
            value: 2,
            min_price: 1,
            max_price: 3,
            revenue: 1,
            level: 1,
            synergies: %w[BPM SX MS PR],
          },
          {
            name: 'Köln-Mindener Eisenbahn-Gesellschaft',
            sym: 'KME',
            value: 5,
            min_price: 3,
            max_price: 7,
            revenue: 2,
            level: 1,
            synergies: %w[BME MHE OL HE PR],
          },
          {
            name: 'Altona-Kieler Eisenbahn-Gesellschaft',
            sym: 'AKE',
            value: 6,
            min_price: 3,
            max_price: 8,
            revenue: 2,
            level: 1,
            synergies: %w[BPM MHE OL MS PR],
          },
          {
            name: 'Berlin-Potsdam-Magdeburger Eisenbahn',
            sym: 'BPM',
            value: 7,
            min_price: 4,
            max_price: 9,
            revenue: 2,
            level: 1,
            synergies: %w[BSE AKE MHE SX MS PR],
          },
          {
            name: 'Magdeburg-Halberstädter Eisenbahngesellschaft',
            sym: 'MHE',
            value: 8,
            min_price: 4,
            max_price: 10,
            revenue: 2,
            level: 1,
            synergies: %w[KME AKE BPM OL SX MS PR],
          },
          {
            name: 'Königlich Württembergische Staats-Eisenbahnen',
            sym: 'WT',
            value: 11,
            min_price: 6,
            max_price: 14,
            revenue: 3,
            level: 2,
            synergies: %w[BD BY SBB DR],
          },
          {
            name: 'Großherzoglich Badische Staatseisenbahnen',
            sym: 'BD',
            value: 12,
            min_price: 6,
            max_price: 15,
            revenue: 3,
            level: 2,
            synergies: %w[BME WT HE SNCF SBB DR],
          },
          {
            name: 'Königlich Bayerische Staatseisenbahnen',
            sym: 'BY',
            value: 13,
            min_price: 7,
            max_price: 16,
            revenue: 3,
            level: 2,
            synergies: %w[WT HE SX KK DR],
          },
          {
            name: 'Großherzoglich Oldenburgische Staatseisenbahnen',
            sym: 'OL',
            value: 14,
            min_price: 7,
            max_price: 18,
            revenue: 3,
            level: 2,
            synergies: %w[KME AKE MHE MS PR DSB NS DR],
          },
          {
            name: 'Großherzoglich Hessische Staatseisenbahnen',
            sym: 'HE',
            value: 15,
            min_price: 8,
            max_price: 19,
            revenue: 3,
            level: 2,
            synergies: %w[BME KME BD BY PR DR],
          },
          {
            name: 'Königlich Sächsische Staatseisenbahnen',
            sym: 'SX',
            value: 16,
            min_price: 8,
            max_price: 20,
            revenue: 3,
            level: 2,
            synergies: %w[BSE BPM MHE BY MS PR PKP KK DR],
          },
          {
            name: 'Großherzoglich Mecklenburgische Friedrich-Franz-Eisenbahn',
            sym: 'MS',
            value: 17,
            min_price: 9,
            max_price: 21,
            revenue: 3,
            level: 2,
            synergies: %w[BSE AKE BPM MHE OL SX PR DSB PKP DR],
          },
          {
            name: 'Preußische Staatseisenbahnen',
            sym: 'PR',
            value: 19,
            min_price: 10,
            max_price: 24,
            revenue: 3,
            level: 2,
            synergies: %w[BME BSE KME AKE BPM MHE OL HE SX MS DSB NS B PKP DR],
          },
          {
            name: 'Danske Statsbaner',
            sym: 'DSB',
            value: 20,
            min_price: 10,
            max_price: 26,
            revenue: 6,
            level: 3,
            synergies: %w[OL MS PR DR BSR HH],
          },
          {
            name: 'Nederlandse Spoorwegen',
            sym: 'NS',
            value: 21,
            min_price: 11,
            max_price: 27,
            revenue: 6,
            level: 3,
            synergies: %w[OL PR B DR E HA HR],
          },
          {
            name: 'Nationale Maatschappij der Belgische Spoorwegen – Société Nationale des Chemins de fer Belges',
            sym: 'B',
            value: 22,
            min_price: 11,
            max_price: 28,
            revenue: 6,
            level: 3,
            synergies: %w[PR NS SNCF DR E HA HR],
          },
          {
            name: 'Polskie Koleje Państwowe',
            sym: 'PKP',
            value: 23,
            min_price: 12,
            max_price: 29,
            revenue: 6,
            level: 3,
            synergies: %w[SX MS PR KK DR SZD BSR HH FRA],
          },
          {
            name: 'Société nationale des chemins de fer français',
            sym: 'SNCF',
            value: 24,
            min_price: 12,
            max_price: 30,
            revenue: 6,
            level: 3,
            synergies: %w[BD B SBB DR RENFE FS E HA CDG],
          },
          {
            name: 'k.k. Österreichische Staatsbahnen',
            sym: 'KK',
            value: 25,
            min_price: 13,
            max_price: 32,
            revenue: 6,
            level: 3,
            synergies: %w[BY SX PKP SBB DR FS FRA],
          },
          {
            name: 'Schweizerische Bundesbahnen – Chemins de fer fédéraux suisses – Ferrovie federali svizzere',
            sym: 'SBB',
            value: 26,
            min_price: 13,
            max_price: 33,
            revenue: 6,
            level: 3,
            synergies: %w[WT BD SNCF KK DR FS CDG FRA],
          },
          {
            name: 'Deutsche Reichsbahn',
            sym: 'DR',
            value: 29,
            min_price: 15,
            max_price: 36,
            revenue: 6,
            level: 3,
            synergies: %w[WT BD BY OL HE SX MS PR DSB NS B PKP SNCF KK SBB BSR
                          HH HR FRA],
          },
          {
            name: 'Statens Järnvägar',
            sym: 'SJ',
            value: 30,
            min_price: 15,
            max_price: 42,
            revenue: 12,
            level: 4,
            synergies: ['BSR'],
          },
          {
            name: 'Советские железные дороги (Sovetskie železnye dorogi)',
            sym: 'SZD',
            value: 31,
            min_price: 16,
            max_price: 43,
            revenue: 12,
            level: 4,
            synergies: ['PKP'],
          },
          {
            name: 'Red Nacional de los Ferrocarriles Españoles',
            sym: 'RENFE',
            value: 32,
            min_price: 16,
            max_price: 45,
            revenue: 12,
            level: 4,
            synergies: %w[SNCF MAD],
          },
          {
            name: 'British Rail',
            sym: 'BR',
            value: 33,
            min_price: 17,
            max_price: 46,
            revenue: 12,
            level: 4,
            synergies: %w[E LHR],
          },
          {
            name: 'Ferrovie dello Stato',
            sym: 'FS',
            value: 37,
            min_price: 19,
            max_price: 51,
            revenue: 10,
            level: 4,
            synergies: %w[SNCF KK SBB],
          },
          {
            name: 'Baltic Sea Rail',
            sym: 'BSR',
            value: 40,
            min_price: 20,
            max_price: 54,
            revenue: 10,
            level: 4,
            synergies: %w[DSB PKP DR SJ HH],
          },
          {
            name: 'Eurotunnel',
            sym: 'E',
            value: 43,
            min_price: 22,
            max_price: 58,
            revenue: 10,
            level: 4,
            synergies: %w[NS B SNCF BR HA HR LHR CDG],
          },
          {
            name: 'Madrid-Barajas Airport',
            sym: 'MAD',
            value: 45,
            min_price: 23,
            max_price: 67,
            revenue: 15,
            level: 5,
            synergies: %w[RENFE FR VP LE],
          },
          {
            name: 'Haven van Antwerpen',
            sym: 'HA',
            value: 47,
            min_price: 24,
            max_price: 69,
            revenue: 15,
            level: 5,
            synergies: %w[NS B SNCF E RU AL],
          },
          {
            name: 'Hamburger Hafen',
            sym: 'HH',
            value: 48,
            min_price: 24,
            max_price: 70,
            revenue: 15,
            level: 5,
            synergies: %w[DSB PKP DR BSR RU AL],
          },
          {
            name: 'Haven van Rotterdam',
            sym: 'HR',
            value: 49,
            min_price: 25,
            max_price: 71,
            revenue: 15,
            level: 5,
            synergies: %w[NS B DR E RU AL],
          },
          {
            name: 'London Heathrow Airport',
            sym: 'LHR',
            value: 54,
            min_price: 27,
            max_price: 77,
            revenue: 15,
            level: 5,
            synergies: %w[BR E FR MM VP LE],
          },
          {
            name: 'Aéroport Paris-Charles-de-Gaulle',
            sym: 'CDG',
            value: 56,
            min_price: 28,
            max_price: 79,
            revenue: 15,
            level: 5,
            synergies: %w[SNCF SBB E FR VP LE],
          },
          {
            name: 'Flughafen Frankfurt',
            sym: 'FRA',
            value: 58,
            min_price: 29,
            max_price: 82,
            revenue: 15,
            level: 5,
            synergies: %w[PKP KK SBB DR FR MM LE],
          },
          {
            name: 'Ryanair',
            sym: 'FR',
            value: 60,
            min_price: 30,
            max_price: 84,
            revenue: 15,
            level: 5,
            synergies: %w[MAD LHR CDG FRA],
          },
          {
            name: 'Outer Planet Consortium',
            sym: 'OPC',
            value: 70,
            min_price: 35,
            max_price: 107,
            revenue: 25,
            level: 6,
            synergies: %w[RU AL TSI],
          },
          {
            name: 'Ring Construction Corporation',
            sym: 'RCC',
            value: 71,
            min_price: 36,
            max_price: 108,
            revenue: 25,
            level: 6,
            synergies: %w[RU AL TSI],
          },
          {
            name: 'Mars Mining Associates',
            sym: 'MM',
            value: 75,
            min_price: 38,
            max_price: 112,
            revenue: 25,
            level: 6,
            synergies: %w[LHR FRA LE TSI],
          },
          {
            name: 'Venus Prospectors',
            sym: 'VP',
            value: 80,
            min_price: 40,
            max_price: 118,
            revenue: 25,
            level: 6,
            synergies: %w[MAD LHR CDG LE TSI],
          },
          {
            name: 'Resources Unlimited',
            sym: 'RU',
            value: 85,
            min_price: 43,
            max_price: 123,
            revenue: 25,
            level: 6,
            synergies: %w[HA HH HR OPC RCC TSI],
          },
          {
            name: 'Asteroid League',
            sym: 'AL',
            value: 86,
            min_price: 43,
            max_price: 124,
            revenue: 25,
            level: 6,
            synergies: %w[HA HH HR OPC RCC TSI],
          },
          {
            name: 'Lunar Enterprises',
            sym: 'LE',
            value: 90,
            min_price: 45,
            max_price: 129,
            revenue: 25,
            level: 6,
            synergies: %w[MAD LHR CDG FRA MM VP TSI],
          },
          {
            name: 'Trans-Space Inc.',
            sym: 'TSI',
            value: 100,
            min_price: 50,
            max_price: 140,
            revenue: 25,
            level: 6,
            synergies: %w[OPC RCC MM VP RU AL LE],
          },
        ].freeze

        CORPORATIONS = [
          {
            sym: 'Wheel',
            name: 'Wheel',
            logo: 'rolling_stock/WHEEL',
            color: 'black',
            text_color: 'white',
            tokens: [],
            shares: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
            float_percent: 10,
            max_ownership_percent: 100,
            always_market_price: true,
          },
          {
            sym: 'Android',
            name: 'Android',
            logo: 'rolling_stock/ANDROID',
            color: 'yellowgreen',
            text_color: 'black',
            tokens: [],
            shares: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
            float_percent: 10,
            max_ownership_percent: 100,
            always_market_price: true,
          },
          {
            sym: 'Orion',
            name: 'Orion',
            logo: 'rolling_stock/ORION',
            color: 'mediumpurple',
            text_color: 'white',
            tokens: [],
            shares: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
            float_percent: 10,
            max_ownership_percent: 100,
            always_market_price: true,
          },
          {
            sym: 'Jupiter',
            name: 'Jupiter',
            logo: 'rolling_stock/JUPITER',
            color: 'chocolate',
            text_color: 'white',
            tokens: [],
            shares: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
            float_percent: 10,
            max_ownership_percent: 100,
            always_market_price: true,
          },
          {
            sym: 'Bear',
            name: 'Bear',
            logo: 'rolling_stock/BEAR',
            color: 'red',
            text_color: 'white',
            tokens: [],
            shares: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
            float_percent: 10,
            max_ownership_percent: 100,
            always_market_price: true,
          },
          {
            sym: 'Eagle',
            name: 'Eagle',
            logo: 'rolling_stock/EAGLE',
            color: 'gold',
            text_color: 'black',
            tokens: [],
            shares: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
            float_percent: 10,
            max_ownership_percent: 100,
            always_market_price: true,
          },
          {
            sym: 'Saturn',
            name: 'Saturn',
            logo: 'rolling_stock/SATURN',
            color: 'deeppink',
            text_color: 'white',
            tokens: [],
            shares: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
            float_percent: 10,
            max_ownership_percent: 100,
            always_market_price: true,
          },
          {
            sym: 'Ship',
            name: 'Ship',
            logo: 'rolling_stock/SHIP',
            color: 'slateblue',
            text_color: 'white',
            tokens: [],
            shares: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
            float_percent: 10,
            max_ownership_percent: 100,
            always_market_price: true,
          },
          {
            sym: 'Star',
            name: 'Star',
            logo: 'rolling_stock/STAR',
            color: 'green',
            text_color: 'white',
            tokens: [],
            shares: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
            float_percent: 10,
            max_ownership_percent: 100,
            always_market_price: true,
          },
          {
            sym: 'Horse',
            name: 'Horse',
            logo: 'rolling_stock/HORSE',
            color: 'lightgray',
            text_color: 'black',
            tokens: [],
            shares: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
            float_percent: 10,
            max_ownership_percent: 100,
            always_market_price: true,
          },
        ].freeze
      end
    end
  end
end
