# frozen_string_literal: true

require_relative 'meta'
require_relative '../base'

module Engine
  module Game
    module GRollingStock
      module Entities
        COMPANIES = [
          {
            name: 'Bergisch-Märkische Eisenbahn-Gesellschaft',
            sym: 'BME',
            value: 1,
            min_price: 1,
            max_price: 2,
            revenue: 1,
            stars: 1,
            synergies: %w[KME BD HE PR],
          },
          {
            name: 'Berlin-Stettiner Eisenbahn-Gesellschaft',
            sym: 'BSE',
            value: 2,
            min_price: 1,
            max_price: 3,
            revenue: 1,
            stars: 1,
            synergies: %w[BPM SX MS PR],
          },
          {
            name: 'Köln-Mindener Eisenbahn-Gesellschaft',
            sym: 'KME',
            value: 5,
            min_price: 3,
            max_price: 7,
            revenue: 2,
            stars: 1,
            synergies: %w[BME MHE HE OL PR],
          },
          {
            name: 'Altona-Kieler Eisenbahn-Gesellschaft',
            sym: 'AKE',
            value: 6,
            min_price: 3,
            max_price: 8,
            revenue: 2,
            stars: 1,
            synergies: %w[BPM MHE OL MS PR],
          },
          {
            name: 'Berlin-Potsdam-Magdeburger Eisenbahn',
            sym: 'BPM',
            value: 7,
            min_price: 4,
            max_price: 9,
            revenue: 2,
            stars: 1,
            synergies: %w[BSE AKE MHE SX MS PR],
          },
          {
            name: 'Magdeburg-Halberstädter Eisenbahngesellschaft',
            sym: 'MHE',
            value: 8,
            min_price: 4,
            max_price: 10,
            revenue: 2,
            stars: 1,
            synergies: %w[KME AKE BPM OL SX MS PR],
          },
          {
            name: 'Königlich Württembergische Staats-Eisenbahnen',
            sym: 'WT',
            value: 11,
            min_price: 6,
            max_price: 14,
            revenue: 3,
            stars: 2,
            synergies: %w[BY BD SBB DR],
          },
          {
            name: 'Königlich Bayerische Staatseisenbahnen',
            sym: 'BY',
            value: 12,
            min_price: 6,
            max_price: 16,
            revenue: 3,
            stars: 2,
            synergies: %w[WT HE SX KK DR],
          },
          {
            name: 'Großherzoglich Badische Staatseisenbahnen',
            sym: 'BD',
            value: 13,
            min_price: 7,
            max_price: 17,
            revenue: 3,
            stars: 2,
            synergies: %w[BME WT HE SBB SNCF DR],
          },
          {
            name: 'Großherzoglich Oldenburgische Staatseisenbahnen',
            sym: 'OL',
            value: 15,
            min_price: 8,
            max_price: 20,
            revenue: 3,
            stars: 2,
            synergies: %w[KME AKE MHE MS PR DSB NS DR],
          },
          {
            name: 'Großherzoglich Hessische Staatseisenbahnen',
            sym: 'HE',
            value: 14,
            min_price: 7,
            max_price: 18,
            revenue: 3,
            stars: 2,
            synergies: %w[BME KME BY BD PR DR],
          },
          {
            name: 'Königlich Sächsische Staatseisenbahnen',
            sym: 'SX',
            value: 16,
            min_price: 8,
            max_price: 21,
            revenue: 3,
            stars: 2,
            synergies: %w[BSE BPM MHE BY MS PR KK PKP DR],
          },
          {
            name: 'Großherzoglich Mecklenburgische Friedrich-Franz-Eisenbahn',
            sym: 'MS',
            value: 17,
            min_price: 9,
            max_price: 22,
            revenue: 3,
            stars: 2,
            synergies: %w[BSE AKE BPM MHE OL SX PR DSB PKP DR],
          },
          {
            name: 'Preußische Staatseisenbahnen',
            sym: 'PR',
            value: 19,
            min_price: 10,
            max_price: 25,
            revenue: 3,
            stars: 2,
            synergies: %w[BME BSE KME AKE BPM MHE HE OL SX MS DSB NS B PKP DR],
          },
          {
            name: 'Danske Statsbaner',
            sym: 'DSB',
            value: 20,
            min_price: 10,
            max_price: 26,
            revenue: 5,
            stars: 3,
            synergies: %w[OL MS PR DR BSR HH],
          },
          {
            name: 'k.k. Österreichische Staatsbahnen',
            sym: 'KK',
            value: 21,
            min_price: 11,
            max_price: 28,
            revenue: 5,
            stars: 3,
            synergies: %w[BY SX SBB PKP DR FS FRA],
          },
          {
            name: 'Nederlandse Spoorwegen',
            sym: 'NS',
            value: 22,
            min_price: 11,
            max_price: 29,
            revenue: 5,
            stars: 3,
            synergies: %w[OL PR B DR E HA HR],
          },
          {
            name: 'Schweizerische Bundesbahnen – Chemins de fer fédéraux suisses – Ferrovie federali svizzere',
            sym: 'SBB',
            value: 23,
            min_price: 12,
            max_price: 30,
            revenue: 5,
            stars: 3,
            synergies: %w[WT BD KK SNCF DR FS FRA CDG],
          },
          {
            name: 'Nationale Maatschappij der Belgische Spoorwegen – Société Nationale des Chemins de fer Belges',
            sym: 'B',
            value: 24,
            min_price: 12,
            max_price: 32,
            revenue: 5,
            stars: 3,
            synergies: %w[PR NS SNCF DR E HA HR],
          },
          {
            name: 'Polskie Koleje Państwowe',
            sym: 'PKP',
            value: 25,
            min_price: 13,
            max_price: 33,
            revenue: 5,
            stars: 3,
            synergies: %w[SX MS PR KK DR SZD BSR HH FRA],
          },
          {
            name: 'Société nationale des chemins de fer français',
            sym: 'SNCF',
            value: 26,
            min_price: 13,
            max_price: 34,
            revenue: 5,
            stars: 3,
            synergies: %w[BD SBB B DR FS RENFE E HA CDG],
          },
          {
            name: 'Deutsche Reichsbahn',
            sym: 'DR',
            value: 29,
            min_price: 15,
            max_price: 38,
            revenue: 5,
            stars: 3,
            synergies: %w[WT BY BD HE OL SX MS PR DSB KK NS SBB
                          B PKP SNCF BSR HH HR FRA],
          },
          {
            name: 'Советские железные дороги (Sovetskie železnye dorogi)',
            sym: 'SZD',
            value: 30,
            min_price: 15,
            max_price: 40,
            revenue: 7,
            stars: 4,
            synergies: ['PKP'],
          },
          {
            name: 'Statens Järnvägar',
            sym: 'SJ',
            value: 31,
            min_price: 16,
            max_price: 41,
            revenue: 7,
            stars: 4,
            synergies: ['BSR'],
          },
          {
            name: 'Ferrovie dello Stato',
            sym: 'FS',
            value: 32,
            min_price: 16,
            max_price: 42,
            revenue: 7,
            stars: 4,
            synergies: %w[KK SBB SNCF],
          },
          {
            name: 'Red Nacional de los Ferrocarriles Españoles',
            sym: 'RENFE',
            value: 33,
            min_price: 17,
            max_price: 44,
            revenue: 7,
            stars: 4,
            synergies: %w[SNCF MAD],
          },
          {
            name: 'British Rail',
            sym: 'BR',
            value: 34,
            min_price: 17,
            max_price: 45,
            revenue: 7,
            stars: 4,
            synergies: %w[E LHR],
          },
          {
            name: 'Baltic Sea Rail',
            sym: 'BSR',
            value: 36,
            min_price: 18,
            max_price: 48,
            revenue: 7,
            stars: 4,
            synergies: %w[DSB PKP DR SJ HH],
          },
          {
            name: 'Eurotunnel',
            sym: 'E',
            value: 43,
            min_price: 22,
            max_price: 57,
            revenue: 7,
            stars: 4,
            synergies: %w[NS B SNCF BR HA HR LHR CDG],
          },
          {
            name: 'Hamburger Hafen',
            sym: 'HH',
            value: 45,
            min_price: 23,
            max_price: 60,
            revenue: 10,
            stars: 5,
            synergies: %w[DSB PKP DR BSR],
          },
          {
            name: 'Haven van Antwerpen',
            sym: 'HA',
            value: 46,
            min_price: 23,
            max_price: 61,
            revenue: 10,
            stars: 5,
            synergies: %w[NS B SNCF E],
          },
          {
            name: 'Haven van Rotterdam',
            sym: 'HR',
            value: 47,
            min_price: 24,
            max_price: 62,
            revenue: 10,
            stars: 5,
            synergies: %w[NS B DR E],
          },
          {
            name: 'Madrid-Barajas Airport',
            sym: 'MAD',
            value: 50,
            min_price: 25,
            max_price: 66,
            revenue: 10,
            stars: 5,
            synergies: %w[RENFE CDG],
          },
          {
            name: 'Flughafen Frankfurt',
            sym: 'FRA',
            value: 56,
            min_price: 28,
            max_price: 74,
            revenue: 10,
            stars: 5,
            synergies: %w[KK SBB PKP DR LHR CDG],
          },
          {
            name: 'London Heathrow Airport',
            sym: 'LHR',
            value: 58,
            min_price: 29,
            max_price: 77,
            revenue: 10,
            stars: 5,
            synergies: %w[BR E FRA CDG],
          },
          {
            name: 'Aéroport Paris-Charles-de-Gaulle',
            sym: 'CDG',
            value: 60,
            min_price: 30,
            max_price: 80,
            revenue: 10,
            stars: 5,
            synergies: %w[SBB SNCF E MAD FRA LHR],
          },
        ].freeze

        CORPORATIONS = [
          {
            sym: 'PR',
            name: 'Prussian Ralway',
            logo: 'rolling_stock/PR',
            color: 'black',
            text_color: 'white',
            tokens: [],
            shares: [10, 10, 10, 10, 10],
            float_percent: 60,
            max_ownership_percent: 100,
            always_market_price: true,
          },
          {
            sym: 'OS',
            name: 'Overseas Trading',
            logo: 'rolling_stock/OS',
            color: 'yellow',
            text_color: 'black',
            tokens: [],
            shares: [10, 10, 10, 10, 10, 10],
            float_percent: 50,
            max_ownership_percent: 100,
            always_market_price: true,
          },
          {
            sym: 'SI',
            name: 'Stars, Inc.',
            logo: 'rolling_stock/SI',
            color: 'purple',
            text_color: 'white',
            tokens: [],
            shares: [10, 10, 10, 10],
            float_percent: 70,
            max_ownership_percent: 100,
            always_market_price: true,
          },
          {
            sym: 'DA',
            name: 'Doppler AG',
            logo: 'rolling_stock/DA',
            color: 'red',
            text_color: 'white',
            tokens: [],
            shares: [10, 10, 10, 10, 10],
            float_percent: 60,
            max_ownership_percent: 100,
            always_market_price: true,
          },
          {
            sym: 'VM',
            name: 'Vintage Machinery',
            logo: 'rolling_stock/VM',
            color: 'orange',
            text_color: 'black',
            tokens: [],
            shares: [10, 10, 10, 10],
            float_percent: 70,
            max_ownership_percent: 100,
            always_market_price: true,
          },
          {
            sym: 'SM',
            name: 'Stock Masters',
            logo: 'rolling_stock/SM',
            color: 'green',
            text_color: 'white',
            tokens: [],
            shares: [10, 10, 10, 10, 10, 10],
            float_percent: 50,
            max_ownership_percent: 100,
            always_market_price: true,
          },
          {
            sym: 'JS',
            name: 'Junkyard Scrappers',
            logo: 'rolling_stock/JS',
            color: 'brown',
            text_color: 'white',
            tokens: [],
            shares: [10, 10, 10, 10, 10, 10, 10],
            float_percent: 40,
            max_ownership_percent: 100,
            always_market_price: true,
          },
          {
            sym: 'S',
            name: 'Synergistic',
            logo: 'rolling_stock/S',
            color: 'LightBlue',
            text_color: 'black',
            tokens: [],
            shares: [10, 10, 10, 10, 10, 10, 10],
            float_percent: 40,
            max_ownership_percent: 100,
            always_market_price: true,
          },
        ].freeze
      end
    end
  end
end
