# frozen_string_literal: true

module Engine
  module Game
    module G1828
      module Entities
        COMPANIES = [
          {
            name: 'Schuylkill Valley Navigation',
            value: 20,
            revenue: 5,
            desc: 'Blocks G19 while owned by a player.',
            sym: 'SVN',
            abilities: [{ type: 'blocks_hexes', owner_type: 'player', hexes: ['G19'] }],
            color: nil,
          },
          {
            name: 'Saint Clair Tunnel',
            value: 20,
            revenue: 5,
            desc: 'Blocks Sarnia (D10) while owned by a player. When this company is sold to a corporation, ' \
                  'revenue increases to $10.',
            sym: 'StCT',
            abilities: [{ type: 'blocks_hexes', owner_type: 'player', hexes: ['D10'] },
                        { type: 'revenue_change', revenue: 10, when: 'sold' }],
            color: nil,
          },
          {
            name: 'Champlain & St. Lawrence Railroad',
            value: 40,
            revenue: 10,
            desc: 'Blocks Burlington (B24) while owned by a player. ' \
                  'Owning corporation may place a free track tile at B24 at any time in its operations.',
            sym: 'C&StL',
            abilities: [{ type: 'blocks_hexes', owner_type: 'player', hexes: ['B24'] },
                        {
                          type: 'tile_lay',
                          description: "Place a free track tile at B24 any time during the corporation's operations.",
                          owner_type: 'corporation',
                          when: 'owning_corp_or_turn',
                          hexes: ['B24'],
                          tiles: %w[3 4 58],
                          free: true,
                          count: 1,
                        }],
            color: nil,
          },
          {
            name: 'Delaware & Hudson Railroad',
            value: 80,
            revenue: 15,
            desc: 'Blocks Scranton (F20) while owned by a player. Owning corporation may place a track tile ' \
                  '(or upgrade) in Scranton (F20) along with an (optional) station marker for $120.',
            sym: 'D&H',
            abilities: [{ type: 'blocks_hexes', owner_type: 'player', hexes: ['F20'] },
                        {
                          type: 'teleport',
                          owner_type: 'corporation',
                          cost: 120,
                          free_tile_lay: true,
                          hexes: ['F20'],
                          tiles: %w[14 15 57 205 206],
                        }],
            color: nil,
          },
          {
            name: 'Cobourg & Peterborough Railway',
            value: 80,
            revenue: 15,
            desc: 'Blocks/reserves Peterborough (C15) while owned by a player. ' \
                  'Owning player may place or upgrade track tiles on a route connected to Peterborough (C15). ' \
                  'Half-pays the revenue of a 2-train route from that track tile instead of normal revenue.',
            sym: 'C&P',
            abilities: [{ type: 'blocks_hexes', owner_type: 'player', hexes: ['C15'] },
                        { type: 'revenue_change', revenue: 0, when: 'auction_end' }],
            color: nil,
          },
          {
            name: 'Mohawk & Hudson Railroad',
            value: 120,
            revenue: 20,
            desc: 'Blocks D22 while owned by a player. ' \
                  'Owning player may exchange for a share of any company from the market or IPO.',
            sym: 'M&H',
            abilities: [{ type: 'blocks_hexes', owner_type: 'player', hexes: ['D22'] },
                        {
                          type: 'exchange',
                          corporations: 'any',
                          owner_type: 'player',
                          from: %w[ipo market],
                        }],
            color: nil,
          },
          {
            name: 'Erie & Kalamazoo Railroad',
            value: 120,
            revenue: 20,
            desc: 'Blocks Adrian & Ann Arbor (E7) while owned by a player. ' \
                  'A yellow track tile is placed at E7 when purchased by a company. ' \
                  'Owning company may (once) place one additional yellow track tile ' \
                  'at $20 as part of its normal track build.',
            sym: 'E&K',
            abilities: [{ type: 'blocks_hexes', owner_type: 'player', hexes: ['E7'] },
                        {
                          type: 'tile_lay',
                          owner_type: 'corporation',
                          when: 'sold',
                          blocks: true,
                          count: 1,
                          hexes: ['E7'],
                          tiles: %w[1 2 55 56 69],
                        },
                        {
                          type: 'tile_lay',
                          owner_type: 'corporation',
                          when: 'track',
                          cost: 20,
                          count: 1,
                          special: false,
                          reachable: true,
                          hexes: [],
                          tiles: %w[1 2 3 4 6 7 8 9 55 56 57 58 69],
                        }],
            color: nil,
          },
          {
            name: 'Camden & Amboy Railroad',
            value: 160,
            revenue: 25,
            desc: 'Blocks Philadelphia & Trenton (H22) while owned by a player. ' \
                  'Purchaser receives 10% of Pennsylvania Railroad (PRR).',
            sym: 'C&A',
            abilities: [{ type: 'blocks_hexes', owner_type: 'player', hexes: ['H22'] },
                        { type: 'shares', shares: 'PRR_1' }],
            color: nil,
          },
          {
            name: 'Canadian Pacific Railroad',
            value: 250,
            revenue: 40,
            desc: 'Purchaser receives 30% of Canadian Pacific Railroad (CPR) and sets par price. ' \
                  'May not be sold to a corporation. Closes when CPR acquires a train.',
            sym: 'CPR',
            abilities: [{ type: 'shares', shares: %w[CPR_0 CPR_1] },
                        { type: 'no_buy' },
                        { type: 'close', when: 'bought_train', corporation: 'CPR' }],
            color: nil,
          },
          {
            name: 'Grand Trunk',
            value: 250,
            revenue: 40,
            desc: 'Purchaser receives 30% of Grand Trunk (GT) and sets par price. ' \
                  'May not be sold to a corporation. Closes when GT acquires a train.',
            sym: 'GT',
            abilities: [{ type: 'shares', shares: %w[GT_0 GT_1] },
                        { type: 'no_buy' },
                        { type: 'close', when: 'bought_train', corporation: 'GT' }],
            color: nil,
          },
          {
            name: 'Illinois Central',
            value: 250,
            revenue: 40,
            desc: 'Purchaser receives 30% of Illinois Central (IC) and sets par price. ' \
                  'May not be sold to a corporation. Closes when IC acquires a train.',
            sym: 'IC',
            abilities: [{ type: 'shares', shares: %w[IC_0 IC_1] },
                        { type: 'no_buy' },
                        { type: 'close', when: 'bought_train', corporation: 'IC' }],
            color: nil,
          },
          {
            name: 'Michigan Central Railroad',
            value: 250,
            revenue: 40,
            desc: 'Purchaser receives 30% of Michigan Central Railroad (MC) and sets par price. ' \
                  'May not be sold to a corporation. Closes when MC acquires a train.',
            sym: 'MC',
            abilities: [{ type: 'shares', shares: %w[MC_0 MC_1] },
                        { type: 'no_buy' },
                        { type: 'close', when: 'bought_train', corporation: 'MC' }],
            color: nil,
          },
          {
            name: 'Missouri Pacific Railroad',
            value: 250,
            revenue: 40,
            desc: 'Purchaser receives 30% of Missouri Pacific Railroad (MP) and sets par price. ' \
                  'May not be sold to a corporation. Closes when MP acquires a train.',
            sym: 'MP',
            abilities: [{ type: 'shares', shares: %w[MP_0 MP_1] },
                        { type: 'no_buy' },
                        { type: 'close', when: 'bought_train', corporation: 'MP' }],
            color: nil,
          },
          {
            name: 'New York, Chicago & St. Louis Railroad',
            value: 250,
            revenue: 40,
            desc: 'Purchaser receives 30% of New York, Chicago & St. Louis Railroad (NKP) and sets par price. ' \
                  'May not be sold to a corporation. Closes when NKP acquires a train.',
            sym: 'NKP',
            abilities: [{ type: 'shares', shares: %w[NKP_0 NKP_1] },
                        { type: 'no_buy' },
                        { type: 'close', when: 'bought_train', corporation: 'NKP' }],
            color: nil,
          },
          {
            name: 'Norfolk & Western Railway',
            value: 250,
            revenue: 40,
            desc: 'Purchaser receives 30% of Norfolk & Western Railway (NW) and sets par price. ' \
                  'May not be sold to a corporation. Closes when NW acquires a train.',
            sym: 'NW',
            abilities: [{ type: 'shares', shares: %w[NW_0 NW_1] },
                        { type: 'no_buy' },
                        { type: 'close', when: 'bought_train', corporation: 'NW' }],
            color: nil,
          },
          {
            name: 'Ontario, Simcoe & Huron',
            value: 250,
            revenue: 40,
            desc: 'Purchaser receives 30% of Ontario, Simcoe & Huron (OSH) and sets par price. ' \
                  'May not be sold to a corporation. Closes when OSH acquires a train.',
            sym: 'OSH',
            abilities: [{ type: 'shares', shares: %w[OSH_0 OSH_1] },
                        { type: 'no_buy' },
                        { type: 'close', when: 'bought_train', corporation: 'OSH' }],
            color: nil,
          },
        ].freeze

        CORPORATIONS = [
          {
            sym: 'B&M',
            name: 'Boston & Maine',
            logo: '1828/BM',
            simple_logo: '1828/BM.alt',
            tokens: [0, 100, 100, 100],
            coordinates: 'E27',
            color: '#446CCF',
            abilities: [
            {
              type: 'description',
              description: 'Place one additional yellow tile for $40',
            },
          ],
            reservation_color: nil,
          },
          {
            sym: 'B&O',
            name: 'Baltimore & Ohio',
            logo: '1828/BO',
            simple_logo: '1828/BO.alt',
            tokens: [0, 100, 100],
            coordinates: 'I19',
            color: '#4682B4',
            reservation_color: nil,
          },
          {
            sym: 'C&O',
            name: 'Chesapeake & Ohio Railroad',
            logo: '1828/CO',
            simple_logo: '1828/CO.alt',
            tokens: [0, 100, 100],
            coordinates: 'K15',
            color: '#B0E0E6',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: 'CPR',
            name: 'Canadian Pacific Railroad',
            logo: '1828/CPR',
            simple_logo: '1828/CPR.alt',
            tokens: [0, 100, 100, 100],
            coordinates: 'A23',
            color: '#9C661F',
            reservation_color: nil,
          },
          {
            sym: 'GT',
            name: 'Grand Trunk',
            logo: '1828/GT',
            simple_logo: '1828/GT.alt',
            tokens: [0, 100, 100],
            coordinates: 'D4',
            color: '#F0E68C',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: 'ERIE',
            name: 'Erie Railroad',
            logo: '1828/ERIE',
            simple_logo: '1828/ERIE.alt',
            tokens: [0, 100, 100],
            coordinates: 'E15',
            color: '#B8860B',
            reservation_color: nil,
          },
          {
            sym: 'IC',
            name: 'Illinois Central',
            logo: '1828/IC',
            simple_logo: '1828/IC.alt',
            tokens: [0, 100, 100, 100],
            coordinates: 'J6',
            color: '#9ACD32',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: 'MC',
            name: 'Michigan Central',
            logo: '1828/MC',
            simple_logo: '1828/MC.alt',
            tokens: [0, 100, 100, 100],
            coordinates: 'A7',
            color: '#B3B3B3',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: 'MP',
            name: 'Missouri Pacific Railroad',
            logo: '1828/MP',
            simple_logo: '1828/MP.alt',
            tokens: [0, 100, 100, 100],
            coordinates: 'I3',
            color: '#BDB76B',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: 'NYC',
            name: 'New York Central Railroad',
            logo: '1828/NYC',
            simple_logo: '1828/NYC.alt',
            tokens: [0, 100, 100],
            coordinates: 'E23',
            color: '#7F7F7F',
            reservation_color: nil,
          },
          {
            sym: 'NKP',
            name: 'New York, Chicago & St. Louis Railroad',
            logo: '1828/NKP',
            simple_logo: '1828/NKP.alt',
            tokens: [0, 100, 100],
            coordinates: 'F10',
            color: '#D8BFD8',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: 'NYH',
            name: 'New York, New Haven & Hartford Railway',
            logo: '1828/NYH',
            simple_logo: '1828/NYH.alt',
            tokens: [0, 100, 100],
            coordinates: 'G23',
            city: 1,
            color: '#D2B48C',
            text_color: 'black',
            abilities: [
              {
                type: 'description',
                description: 'Place one additional yellow tile for $40',
              },
            ],
            reservation_color: nil,
          },
          {
            sym: 'NW',
            name: 'Norfolk & Western Railway',
            logo: '1828/NW',
            simple_logo: '1828/NW.alt',
            tokens: [0, 100, 100, 100],
            coordinates: 'K19',
            color: '#F08080',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            sym: 'OSH',
            name: 'Ontario, Simcoe & Huron',
            logo: '1828/OSH',
            simple_logo: '1828/OSH.alt',
            tokens: [0, 100, 100, 100],
            coordinates: 'A15',
            color: '#61B329',
            reservation_color: nil,
          },
          {
            sym: 'PRR',
            name: 'Pennsylvania Railroad',
            logo: '1828/PRR',
            simple_logo: '1828/PRR.alt',
            tokens: [0, 100, 100, 100],
            coordinates: 'H16',
            color: '#FF6347',
            reservation_color: nil,
          },
          {
            sym: 'WAB',
            name: 'Wabash Railroad',
            logo: '1828/WAB',
            simple_logo: '1828/WAB.alt',
            tokens: [0, 100, 100],
            coordinates: 'H6',
            color: '#DDA0DD',
            text_color: 'black',
            reservation_color: nil,
          },
        ].freeze

        MINORS = [
          {
            sym: 'C&P',
            name: 'Cobourg & Peterborough Railway',
            logo: '1828/CP',
            simple_logo: '1828/CP.alt',
            tokens: [0],
            coordinates: 'C15',
            color: '#7F7F7F',
          },
        ].freeze
      end
    end
  end
end
