# frozen_string_literal: true

module Engine
  module Game
    module G1877StockholmTramways
      module Entities
        COMPANIES = [].freeze

        CORPORATIONS = [
          {
            float_percent: 50,
            sym: 'SS',
            name: 'AB Stockholms Spårvägar',
            logo: '1877_stockholm_tramways/SS',
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            tokens: [0, 60, 60, 60, 60, 60],
            coordinates: 'F6',
            city: 0,
            color: '#9A9A9D',
            text_color: :black,
            reservation_color: nil,
          },
          {
            float_percent: 50,
            sym: 'SF',
            name: 'AB Södra Förstadsbanan',
            logo: '1877_stockholm_tramways/SF',
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            tokens: [0, 60, 60, 60, 60, 60],
            coordinates: 'H4',
            color: '#7BB137',
            text_color: :black,
            reservation_color: nil,
          },
          {
            float_percent: 50,
            sym: 'D',
            name: 'Djursholms AB',
            logo: '1877_stockholm_tramways/D',
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            tokens: [0, 60, 60, 60, 60, 60],
            coordinates: 'C7',
            color: '#06038D',
            reservation_color: nil,
          },
          {
            float_percent: 50,
            sym: 'JSS',
            name: 'Järnvägs AB Stockholm-Saltsjön',
            logo: '1877_stockholm_tramways/JSS',
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            tokens: [0, 60, 60, 60, 60, 60],
            coordinates: 'I13',
            color: '#881A1E',
            reservation_color: nil,
          },
          {
            float_percent: 50,
            sym: 'LT',
            name: 'Lidingö Trafik AB',
            logo: '1877_stockholm_tramways/LT',
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            tokens: [0, 60, 60, 60, 60, 60],
            coordinates: 'D10',
            city: 0,
            color: '#235758',
            reservation_color: nil,
          },
          {
            float_percent: 50,
            sym: 'RF',
            name: 'Råsunda Förstads AB',
            logo: '1877_stockholm_tramways/RF',
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            tokens: [0, 60, 60, 60, 60, 60],
            coordinates: 'D4',
            color: '#008F4F',
            text_color: :black,
            reservation_color: nil,
          },
          {
            float_percent: 50,
            sym: 'SRJ',
            name: 'Stockholm-Rimbo Järnvägs AB',
            logo: '1877_stockholm_tramways/SRJ',
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            tokens: [0, 60, 60, 60, 60, 60],
            coordinates: 'A9',
            color: '#FCEA18',
            text_color: :black,
            reservation_color: nil,
          },
          {
            float_percent: 50,
            sym: 'SNS',
            name: 'Stockholms Nya Spårvägs AB',
            logo: '1877_stockholm_tramways/SNS',
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            tokens: [0, 60, 60, 60, 60, 60],
            coordinates: 'F6',
            city: 1,
            color: '#EC767C',
            text_color: :black,
            reservation_color: nil,
          },
          {
            float_percent: 50,
            sym: 'SSS',
            name: 'Stockholms Stads Spårväg',
            logo: '1877_stockholm_tramways/SSS',
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            tokens: [0, 60, 60, 60, 60, 60],
            coordinates: 'G1',
            color: '#4D2674',
            reservation_color: nil,
          },
          {
            float_percent: 50,
            sym: 'SSB',
            name: 'Stockholms Södra Spårvägs AB',
            logo: '1877_stockholm_tramways/SSB',
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            tokens: [0, 60, 60, 60, 60, 60],
            coordinates: 'G7',
            color: '#DD0030',
            reservation_color: nil,
          },
          {
            float_percent: 50,
            sym: 'SST',
            name: 'Södra Spårvägarnes Trafik AB',
            logo: '1877_stockholm_tramways/SST',
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            tokens: [0, 60, 60, 60, 60, 60],
            coordinates: 'H8',
            color: '#0A70B3',
            reservation_color: nil,
          },
          {
            float_percent: 50,
            sym: 'TSSL',
            name: 'Trafik AB Stockholm-Södra Lidingön',
            logo: '1877_stockholm_tramways/TSSL',
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            tokens: [0, 60, 60, 60, 60, 60],
            coordinates: 'D10',
            city: 1,
            color: '#EB6f0E',
            text_color: :black,
            reservation_color: nil,
          },
        ].freeze
      end
    end
  end
end
