# frozen_string_literal: true

require_relative 'meta'
require_relative '../base'

module Engine
  module Game
    module G18NewEngland
      module Entities
        CORPORATIONS = [
          # Share Corporations
          {
            sym: 'B&A',
            name: 'Boston and Albany Railroad',
            logo: '18_new_england/BA',
            color: '#ec1c24',
            tokens: [0, 40, 80],
            float_percent: 20,
            max_ownership_percent: 60,
          },
          {
            sym: 'B&M',
            name: 'Boston and Maine Railroad',
            logo: '18_new_england/BM',
            color: '#84c77a',
            text_color: 'black',
            tokens: [0, 40, 80],
            float_percent: 20,
            max_ownership_percent: 60,
          },
          {
            sym: 'CN',
            name: 'Canadian National Railroad',
            logo: '18_new_england/CN',
            color: '#ffd900',
            text_color: 'black',
            tokens: [0, 40, 80],
            float_percent: 20,
            max_ownership_percent: 60,
          },
          {
            sym: 'CVT',
            name: 'Central Vermont Railroad',
            logo: '18_new_england/CVT',
            color: '#b43e95',
            tokens: [0, 40, 80],
            float_percent: 20,
            max_ownership_percent: 60,
          },
          {
            sym: 'D&H',
            name: 'Delaware and Hudson Railroad',
            logo: '18_new_england/DH',
            color: '#0d7bb5',
            tokens: [0, 40, 80],
            float_percent: 20,
            max_ownership_percent: 60,
          },
          {
            sym: 'NYC',
            name: 'New York Central Railroad',
            logo: '18_new_england/NYC',
            color: '#231f20',
            tokens: [0, 40, 80],
            float_percent: 20,
            max_ownership_percent: 60,
          },
          {
            sym: 'NYNHH',
            name: 'New York, New Haven and Hardford Railroad',
            logo: '18_new_england/NYNHH',
            color: '#f68e1e',
            tokens: [0, 40, 80],
            float_percent: 20,
            max_ownership_percent: 60,
          },
          {
            sym: 'P&W',
            name: 'Providence and Worcester Railroad',
            logo: '18_new_england/PW',
            color: '#833000',
            tokens: [0, 40, 80],
            float_percent: 20,
            max_ownership_percent: 60,
          },
          # Minor Corporations
          {
            sym: 'AWS',
            name: 'Albany and West Stockbridge Railroad',
            coordinates: 'B3',
            city: 1,
            logo: '18_new_england/AWS',
            color: '#f05f72',
            tokens: [0],
            float_percent: 100,
            max_ownership_percent: 100,
            shares: [100],
            type: 'minor',
          },
          {
            sym: 'BL',
            name: 'Boston and Lowell Railroad',
            coordinates: 'L5',
            city: 0,
            logo: '18_new_england/BL',
            color: '#fbb116',
            tokens: [0],
            float_percent: 100,
            max_ownership_percent: 100,
            shares: [100],
            type: 'minor',
          },
          {
            sym: 'BP',
            name: 'Boston & Providence',
            coordinates: 'K10',
            logo: '18_new_england/BP',
            color: '#bdaf32',
            text_color: 'black',
            tokens: [0],
            float_percent: 100,
            max_ownership_percent: 100,
            shares: [100],
            type: 'minor',
          },
          {
            sym: 'CR',
            name: 'Connecticut River',
            coordinates: 'G8',
            city: 1,
            logo: '18_new_england/CR',
            color: '#584232',
            tokens: [0],
            float_percent: 100,
            max_ownership_percent: 100,
            shares: [100],
            type: 'minor',
          },
          {
            sym: 'CV',
            name: 'Connecticut Valley',
            coordinates: 'E2',
            logo: '18_new_england/CV',
            color: '#e5df17',
            text_color: 'black',
            tokens: [0],
            float_percent: 100,
            max_ownership_percent: 100,
            shares: [100],
            type: 'minor',
          },
          {
            sym: 'ER',
            name: 'Eastern Railroad',
            coordinates: 'L5',
            city: 1,
            logo: '18_new_england/ER',
            color: '#b43e95',
            tokens: [0],
            float_percent: 100,
            max_ownership_percent: 100,
            shares: [100],
            type: 'minor',
          },
          {
            sym: 'FRR',
            name: 'Fitchburg Railroad',
            coordinates: 'J3',
            logo: '18_new_england/FRR',
            color: '#2ab24b',
            tokens: [0],
            float_percent: 100,
            max_ownership_percent: 100,
            shares: [100],
            type: 'minor',
          },
          {
            sym: 'GR',
            name: 'Granite Railway',
            coordinates: 'L7',
            logo: '18_new_england/GR',
            color: '#09743b',
            tokens: [0],
            float_percent: 100,
            max_ownership_percent: 100,
            shares: [100],
            type: 'minor',
          },
          {
            sym: 'HNH',
            name: 'Hartford and New Haven',
            coordinates: 'F13',
            city: 1,
            logo: '18_new_england/HNH',
            color: '#ec2785',
            tokens: [0],
            float_percent: 100,
            max_ownership_percent: 100,
            shares: [100],
            type: 'minor',
          },
          {
            sym: 'HRR',
            name: 'Hudson Railroad',
            coordinates: 'B3',
            city: 0,
            logo: '18_new_england/HRR',
            color: '#3b60ab',
            tokens: [0],
            float_percent: 100,
            max_ownership_percent: 100,
            shares: [100],
            type: 'minor',
          },
          {
            sym: 'NLN',
            name: 'New London Northern Railroad',
            coordinates: 'F13',
            city: 2,
            logo: '18_new_england/NLN',
            color: '#6dcef5',
            text_color: 'black',
            tokens: [0],
            float_percent: 100,
            max_ownership_percent: 100,
            shares: [100],
            type: 'minor',
          },
          {
            sym: 'NYNH',
            name: 'New York New Haven Railroad',
            coordinates: 'F13',
            city: 0,
            logo: '18_new_england/NYNH',
            color: '#cf6d28',
            tokens: [0],
            float_percent: 100,
            max_ownership_percent: 100,
            shares: [100],
            type: 'minor',
          },
          {
            sym: 'NYW',
            name: 'New York Westchester Boston',
            coordinates: 'B19',
            logo: '18_new_england/NYW',
            color: '#ec1e29',
            tokens: [0],
            float_percent: 100,
            max_ownership_percent: 100,
            shares: [100],
            type: 'minor',
          },
          {
            sym: 'PE',
            name: 'Poughkeepsie and Eastern Railway',
            coordinates: 'B11',
            logo: '18_new_england/PE',
            color: '#b94e27',
            tokens: [0],
            float_percent: 100,
            max_ownership_percent: 100,
            shares: [100],
            type: 'minor',
          },
          {
            sym: 'WNR',
            name: 'Worcester, Nashua and Rochester Railroad',
            coordinates: 'I6',
            logo: '18_new_england/WNR',
            color: '#231f20',
            tokens: [0],
            float_percent: 100,
            max_ownership_percent: 100,
            shares: [100],
            type: 'minor',
          },
        ].freeze

        MINORS = [
          {
            sym: 'Y',
            name: 'Yellow Dummy',
            logo: '18_new_england/YELLOW',
            color: 'yellow',
            tokens: [0],
          },
          {
            sym: 'G',
            name: 'Green Dummy',
            logo: '18_new_england/GREEN',
            color: 'green',
            tokens: [0],
          },
        ].freeze
      end
    end
  end
end
