# frozen_string_literal: true

module Engine
  module Game
    module G1880Romania
      module Entities
        COMPANIES = [
          {
            name: 'P1. Banater Montanbahn',
            sym: 'P1',
            value: 20,
            revenue: 5,
            desc: 'May be closed any time during the game to give the owner 20 (if player) or 40 (if company) out of the bank.',
          },
          {
            name: 'P2. Consorţiu Bethel Henry Strousberg',
            sym: 'P2',
            value: 30,
            revenue: 10,
            desc: 'During yellow phase all companies of the owner of this private may build track towards and across the '\
                  'yellow doted border. Each time (until the communist phase) a connection is built across the yellow doted '\
                  'border, the owner receives 20.',
          },
          {
            name: 'P3. Valea Jiului',
            sym: 'P3',
            value: 40,
            revenue: 10,
            desc: 'Gives a discount of two mountain symbols for each hex with mountain terrain costs.',
            abilities: [{
              type: 'tile_discount',
              discount: 20,
              terrain: 'mountain',
              exact_match: false,
              owner_type: 'player',
              when: 'owning_player_track',
              description: 'Discount of two mountain symbols for each hex with mountain terrain costs',
            }],
          },
          {
            name: 'P4. The Danube and Black Sea Railway and Free Port of Küstendjie',
            sym: 'P4',
            value: 60,
            revenue: 20,
            desc: 'Comes with a +10 token. This token may be laid any time to any Danube harbor (blue anchor symbol). It '\
                  'remains there until the end of the game. This doesn’t close the private company. The token increases the '\
                  'value of the relevant city by 10 for all companies of the owning player.',
            abilities: [
              {
                type: 'assign_hexes',
                hexes: %w[G23 G25 H4 J20 K9 K17],
                count: 1,
                owner_type: 'player',
                when: 'owning_player_or_turn',
                closed_when_used_up: false,
              },
            ],
          },
          {
            name: 'P5. REMAR – Reparatii Material Ruland',
            sym: 'P5',
            value: 70,
            revenue: 10,
            desc: 'Comes with a +1 tender. This tender must be assigned to a share company (not a foreign investor) and remain '\
                  'in this company until the end of the game (it never rusts). The tender may be assigned each round to a '\
                  'train. This can be the same or a different train. It may be assigned to a restored 2-train. '\
                  'Company closes with 3+3.',
          },
          {
            name: 'P6. Malaxa Manufacturing Company',
            sym: 'P6',
            value: 30,
            revenue: 10,
            desc: 'May be exchanged any time into a building permit of two consecutive phases which must be assigned '\
                  'immediately to a company. This private company is then discarded.',
          },
          {
            name: 'P7. Electroputere S.A.',
            sym: 'P7',
            value: 100,
            revenue: 5,
            desc: 'As soon as the first 3+3 train is bought or exported, this private is exchanged for a 3+3 train '\
                  'which must be assigned immediately to a company. If the company is then above the train limit it must '\
                  'remove trains until it is within the limit. It may choose which trains to remove.',
            # this company's ability is implemented in 1880's game class
            # with the same logic as the Rocket of China forced exchange.
          },
          {
            name: 'P8. Orient Express',
            sym: 'P8',
            value: 160,
            revenue: 0,
            desc: 'Comes with the 20% director share of the TR with building permits for phases ABC. The TR gets a L10 discount '\
                  'on all mountain terrain hex costs.',
            abilities: [{ type: 'shares', shares: 'TR_0' },
                        { type: 'close', when: 'par', corporation: 'TR' }],
          },
        ].freeze

        CORPORATIONS = [
          {
            float_percent: 20,
            sym: 'BR',
            name: 'Banat Railways',
            logo: '1880_romania/BR',
            simple_logo: '1880_romania/BR.alt',
            tokens: [0, 40, 100],
            coordinates: 'F4',
            color: '#f58121',
            max_ownership_percent: 100,
            always_market_price: true,
          },
          {
            float_percent: 20,
            sym: 'Bess',
            name: 'Bessarabian Railways',
            logo: '1880_romania/Bess',
            simple_logo: '1880_romania/Bess.alt',
            tokens: [0, 40, 100],
            coordinates: 'D24',
            color: :gray,
            max_ownership_percent: 100,
            always_market_price: true,
          },
          {
            float_percent: 20,
            sym: 'CFR',
            name: 'Căile Ferate Române',
            logo: '1880_romania/CFR',
            simple_logo: '1880_romania/CFR.alt',
            tokens: [0, 40, 100],
            coordinates: 'I17',
            city: 0,
            color: :pink,
            text_color: 'black',
            max_ownership_percent: 100,
            always_market_price: true,
          },
          {
            float_percent: 20,
            sym: 'CR',
            name: 'Crișana Railways',
            logo: '1880_romania/CR',
            simple_logo: '1880_romania/CR.alt',
            tokens: [0, 40, 100],
            coordinates: 'C5',
            color: '#FBDA03',
            text_color: 'black',
            max_ownership_percent: 100,
            always_market_price: true,
          },
          {
            float_percent: 20,
            sym: 'DR',
            name: 'Dobrudja Railways',
            logo: '1880_romania/DR',
            simple_logo: '1880_romania/DR.alt',
            tokens: [0, 40, 100],
            coordinates: 'J24',
            color: '#069847',
            max_ownership_percent: 100,
            always_market_price: true,
          },
          {
            float_percent: 20,
            sym: 'GWR',
            name: 'Greater Wallachian Railways',
            logo: '1880_romania/GWR',
            simple_logo: '1880_romania/GWR.alt',
            tokens: [0, 40, 100],
            coordinates: 'I17',
            city: 1,
            color: '#088DD0',
            max_ownership_percent: 100,
            always_market_price: true,
          },
          {
            float_percent: 20,
            sym: 'LCR',
            name: 'Lemberg-Czernowitz Railways',
            logo: '1880_romania/LCR',
            simple_logo: '1880_romania/LCR.alt',
            tokens: [0, 40, 100],
            coordinates: 'A17',
            color: '#ADD8E6',
            text_color: 'black',
            max_ownership_percent: 100,
            always_market_price: true,
          },
          {
            float_percent: 20,
            sym: 'LWR',
            name: 'Lesser Wallachian Railways',
            logo: '1880_romania/LWR',
            simple_logo: '1880_romania/LWR.alt',
            tokens: [0, 40, 100],
            coordinates: 'J10',
            color: '#D5B36C',
            max_ownership_percent: 100,
            always_market_price: true,
          },
          {
            float_percent: 20,
            sym: 'MR',
            name: 'Moldavia Railways',
            logo: '1880_romania/MR',
            simple_logo: '1880_romania/MR.alt',
            tokens: [0, 40, 100],
            coordinates: 'C21',
            color: '#AE4B84',
            max_ownership_percent: 100,
            always_market_price: true,
          },
          {
            float_percent: 20,
            sym: 'SZ',
            name: 'Szatmár Railways',
            logo: '1880_romania/SZ',
            simple_logo: '1880_romania/SZ.alt',
            tokens: [0, 40, 100],
            coordinates: 'A7',
            color: '#B0CC19',
            max_ownership_percent: 100,
            always_market_price: true,
          },
          {
            float_percent: 20,
            sym: 'TR',
            name: 'Transylvanian Railways',
            logo: '1880_romania/TR',
            simple_logo: '1880_romania/TR.alt',
            tokens: [0, 40, 100],
            coordinates: 'F12',
            color: :black,
            max_ownership_percent: 100,
            always_market_price: true,
            abilities: [{
              type: 'tile_discount',
              discount: 10,
              terrain: 'mountain',
              description: 'L10 discount on mountain terrain costs',
            }],
          },
          {
            float_percent: 20,
            sym: 'VRL',
            name: 'Vârciorova-Roman line',
            logo: '1880_romania/VRL',
            simple_logo: '1880_romania/VRL.alt',
            tokens: [0, 40, 100],
            coordinates: 'H16',
            city: 1,
            color: '#E32327',
            max_ownership_percent: 100,
            always_market_price: true,
          },
        ].freeze

        MINORS = [
          {
            sym: '1',
            name: 'Austro-Hungarian Investors',
            logo: '1880_romania/1',
            simple_logo: '1880/1',
            tokens: [0],
            coordinates: 'B4',
            color: :gray,
            text_color: 'black',
          },
          {
            sym: '2',
            name: 'Russian Investors',
            logo: '1880_romania/2',
            simple_logo: '1880/2',
            tokens: [0],
            coordinates: 'B22',
            color: :gray,
            text_color: 'black',
          },
          {
            sym: '3',
            name: 'British Investors',
            logo: '1880_romania/3',
            simple_logo: '1880/3',
            tokens: [0],
            coordinates: 'J26',
            color: :gray,
            text_color: 'black',
          },
          {
            sym: '4',
            name: 'Serbian Investors',
            logo: '1880_romania/4',
            simple_logo: '1880/4',
            tokens: [0],
            coordinates: 'H2',
            color: :gray,
            text_color: 'black',
          },
          {
            sym: '5',
            name: 'French Investors',
            logo: '1880_romania/5',
            simple_logo: '1880/5',
            tokens: [0],
            coordinates: 'D10',
            color: :gray,
            text_color: 'black',
          },
          {
            sym: '6',
            name: 'German Investors',
            logo: '1880_romania/6',
            simple_logo: '1880/6',
            tokens: [0],
            coordinates: 'H14',
            color: :gray,
            text_color: 'black',
          },
        ].freeze
      end
    end
  end
end
