# frozen_string_literal: true

module Engine
  module Game
    module G18OE
      module Entities
        COMPANIES = [
          {
            name: 'Ponts et Chaussees',
            sym: 'PeC',
            value: 20,
            revenue: 5,
            auction_row: 1,
          },
          {
            name: 'Star Harbor Trading Co.',
            sym: 'SHTC',
            value: 60,
            revenue: 15,
            auction_row: 2,
          },
          {
            name: 'Central Circle Transport Co.',
            sym: 'CCTC',
            value: 60,
            revenue: 15,
            auction_row: 3,
          },
          {
            name: 'White Cliffs Ferry',
            sym: 'WCF',
            value: 60,
            revenue: 15,
            auction_row: 4,
          },
          {
            name: 'Golden Bell Marketplace',
            sym: 'C',
            value: 120,
            revenue: 0,
            auction_row: 5,
            abilities: [
              {
                type: 'exchange',
                corporations: %w[C],
                owner_type: 'player',
                from: %w[ipo],
              },
            ],
          },
          {
            name: 'Great Western Steamship Company',
            sym: 'H',
            value: 120,
            revenue: 0,
            auction_row: 5,
            abilities: [
              {
                type: 'exchange',
                corporations: %w[H],
                owner_type: 'player',
                from: %w[ipo],
              },
            ],
          },
          {
            name: 'Vermilion Seal Couriers',
            sym: 'K',
            value: 120,
            revenue: 0,
            auction_row: 6,
            abilities: [
              {
                type: 'exchange',
                corporations: %w[K],
                owner_type: 'player',
                from: %w[ipo],
              },
            ],
          },
          {
            name: 'Compagnie Internationale des Wagons-Lits',
            sym: 'M',
            value: 120,
            revenue: 0,
            auction_row: 6,
            abilities: [
              {
                type: 'exchange',
                corporations: %w[M],
                owner_type: 'player',
                from: %w[ipo],
              },
            ],
          },
        ].freeze

        CORPORATIONS = [
          # -----------------------------------------------------------------------
          # Minors (placeholder set from UK-FR variant)
          # -----------------------------------------------------------------------
          {
            name: 'Golden Bell Marketplace',
            logo: '18_oe/C',
            sym: 'C',
            tokens: [0, 20],
            type: 'minor',
            shares: [100],
            float_percent: 100,
            max_ownership_percent: 100,
          },
          {
            name: 'Great Western Steamship Company',
            logo: '18_oe/H',
            sym: 'H',
            tokens: [0, 20],
            type: 'minor',
            shares: [100],
            float_percent: 100,
            max_ownership_percent: 100,
          },
          {
            name: 'Vermilion Seal Couriers',
            logo: '18_oe/K',
            sym: 'K',
            tokens: [0, 20],
            type: 'minor',
            shares: [100],
            float_percent: 100,
            max_ownership_percent: 100,
          },
          {
            name: 'Compagnie Internationale des Wagons-Lits',
            logo: '18_oe/M',
            sym: 'M',
            tokens: [0, 20],
            type: 'minor',
            shares: [100],
            float_percent: 100,
            max_ownership_percent: 100,
          },
          # -----------------------------------------------------------------------
          # Regionals — United Kingdom (UK)
          # -----------------------------------------------------------------------
          {
            name: 'London and North Western Railway',
            logo: '18_oe/LNWR',
            sym: 'LNWR',
            tokens: [40, 20],
            type: 'regional',
            shares: [50, 25, 25],
            float_percent: 50,
            max_ownership_percent: 100,
            coordinates: 'J27',
            color: :black,
            always_market_price: true,
          },
          {
            name: 'Great Western Railway',
            logo: '18_oe/GWR',
            sym: 'GWR',
            tokens: [40, 20],
            type: 'regional',
            shares: [50, 25, 25],
            float_percent: 50,
            max_ownership_percent: 100,
            coordinates: 'L25',
            color: :red,
            always_market_price: true,
          },
          {
            name: 'Great Southern and Western Railway',
            logo: '18_oe/GSWR',
            sym: 'GSWR',
            tokens: [40, 20],
            type: 'regional',
            shares: [50, 25, 25],
            float_percent: 50,
            max_ownership_percent: 100,
            coordinates: 'I20',
            color: :blue,
            always_market_price: true,
          },
          # -----------------------------------------------------------------------
          # Regionals — France / Belgium (FR)
          # -----------------------------------------------------------------------
          {
            name: 'CF Paris a Lyon et a la Mediterranee',
            logo: '18_oe/PLM',
            sym: 'PLM',
            tokens: [20, 20],
            type: 'regional',
            shares: [50, 25, 25],
            float_percent: 50,
            max_ownership_percent: 100,
            coordinates: 'U34',
            color: :purple,
            always_market_price: true,
          },
          {
            name: 'CF du Midi',
            logo: '18_oe/MIDI',
            sym: 'MIDI',
            tokens: [20, 20],
            type: 'regional',
            shares: [50, 25, 25],
            float_percent: 50,
            max_ownership_percent: 100,
            coordinates: 'U24',
            color: :blue,
            always_market_price: true,
          },
          {
            name: "CF de l'Ouest",
            logo: '18_oe/OU',
            sym: 'OU',
            tokens: [20, 20],
            type: 'regional',
            shares: [50, 25, 25],
            float_percent: 50,
            max_ownership_percent: 100,
            coordinates: 'Q26',
            color: :orange,
            always_market_price: true,
          },
          {
            name: 'SNCF Belges',
            logo: '18_oe/BEL',
            sym: 'BEL',
            tokens: [20, 20],
            type: 'regional',
            shares: [50, 25, 25],
            float_percent: 50,
            max_ownership_percent: 100,
            coordinates: 'N35',
            color: :green,
            always_market_price: true,
          },
          # -----------------------------------------------------------------------
          # Regionals — Prussia / Holland / Switzerland (PHS)
          # -----------------------------------------------------------------------
          {
            name: 'Berlin Hamburger Bahn',
            logo: '18_oe/BHB',
            sym: 'BHB',
            tokens: [40, 20],
            type: 'regional',
            shares: [50, 25, 25],
            float_percent: 50,
            max_ownership_percent: 100,
            coordinates: 'K46',
            color: :blue,
            always_market_price: true,
          },
          {
            name: 'Preußische Ostbahn',
            logo: '18_oe/POB',
            sym: 'POB',
            tokens: [40, 20],
            type: 'regional',
            shares: [50, 25, 25],
            float_percent: 50,
            max_ownership_percent: 100,
            coordinates: 'L53',
            color: :green,
            always_market_price: true,
          },
          {
            name: 'Königlich Sächsische Staatseisenbahnen',
            logo: '18_oe/KSS',
            sym: 'KSS',
            tokens: [40, 20],
            type: 'regional',
            shares: [50, 25, 25],
            float_percent: 50,
            max_ownership_percent: 100,
            coordinates: 'N49',
            color: :green,
            always_market_price: true,
          },
          {
            name: 'Königlich Bayerische Staatseisenbahnen',
            logo: '18_oe/KBS',
            sym: 'KBS',
            tokens: [40, 20],
            type: 'regional',
            shares: [50, 25, 25],
            float_percent: 50,
            max_ownership_percent: 100,
            coordinates: 'R47',
            color: :lightblue,
            always_market_price: true,
          },
          # -----------------------------------------------------------------------
          # Regionals — Austria-Hungary (AH)
          # -----------------------------------------------------------------------
          {
            name: 'Österreichische Südbahn',
            logo: '18_oe/SB',
            sym: 'SB',
            tokens: [20, 20],
            type: 'regional',
            shares: [50, 25, 25],
            float_percent: 50,
            max_ownership_percent: 100,
            coordinates: 'R55',
            color: :orange,
            always_market_price: true,
          },
          {
            name: 'Magyar Allamvasutak',
            logo: '18_oe/MAV',
            sym: 'MAV',
            tokens: [20, 20],
            type: 'regional',
            shares: [50, 25, 25],
            float_percent: 50,
            max_ownership_percent: 100,
            coordinates: 'S60',
            color: :black,
            always_market_price: true,
          },
          # -----------------------------------------------------------------------
          # Regionals — Italy (IT)
          # -----------------------------------------------------------------------
          {
            name: "Societa per le Ferrovie dell'Alta Italia",
            logo: '18_oe/SFAI',
            sym: 'SFAI',
            tokens: [10, 20],
            type: 'regional',
            shares: [50, 25, 25],
            float_percent: 50,
            max_ownership_percent: 100,
            coordinates: 'V41',
            color: :tan,
            always_market_price: true,
          },
          {
            name: 'Societa per le strade ferrate romane',
            logo: '18_oe/SFR',
            sym: 'SFR',
            tokens: [10, 20],
            type: 'regional',
            shares: [50, 25, 25],
            float_percent: 50,
            max_ownership_percent: 100,
            coordinates: 'Z47',
            color: :green,
            always_market_price: true,
          },
          # -----------------------------------------------------------------------
          # Regionals — Spain / Portugal (SP)
          # -----------------------------------------------------------------------
          {
            name: 'Caminos de Hierro del Norte de Espana',
            logo: '18_oe/CHN',
            sym: 'CHN',
            tokens: [10, 20],
            type: 'regional',
            shares: [50, 25, 25],
            float_percent: 50,
            max_ownership_percent: 100,
            coordinates: 'Z27',
            color: :green,
            always_market_price: true,
          },
          {
            name: 'Cia de los Ferrocarriles de Madrid a Zaragoza y Alicante',
            logo: '18_oe/MZA',
            sym: 'MZA',
            tokens: [10, 20],
            type: 'regional',
            shares: [50, 25, 25],
            float_percent: 50,
            max_ownership_percent: 100,
            coordinates: 'AD17',
            color: :yellow,
            always_market_price: true,
          },
          {
            name: 'Companhia Real dos Caminhos de Ferro Portugueses',
            logo: '18_oe/RCP',
            sym: 'RCP',
            tokens: [10, 20],
            type: 'regional',
            shares: [50, 25, 25],
            float_percent: 50,
            max_ownership_percent: 100,
            coordinates: 'Z1',
            color: :green,
            always_market_price: true,
          },
          # -----------------------------------------------------------------------
          # Regionals — Russia (RU)
          # -----------------------------------------------------------------------
          {
            name: 'Petersburgo-Moskovskaya Zheleznaya Doroga',
            logo: '18_oe/MSP',
            sym: 'MSP',
            tokens: [10, 20],
            type: 'regional',
            shares: [50, 25, 25],
            float_percent: 50,
            max_ownership_percent: 100,
            coordinates: 'C74',
            color: :red,
            always_market_price: true,
          },
          {
            name: 'Moskovsko-Kiyevo-Voronezhskaya Zheleznaya Doroga',
            logo: '18_oe/MKV',
            sym: 'MKV',
            tokens: [10, 20],
            type: 'regional',
            shares: [50, 25, 25],
            float_percent: 50,
            max_ownership_percent: 100,
            coordinates: 'O80',
            color: :red,
            always_market_price: true,
          },
          {
            name: 'Libavo-Romenskaya Zheleznaya Doroga',
            logo: '18_oe/LRZD',
            sym: 'LRZD',
            tokens: [10, 20],
            type: 'regional',
            shares: [50, 25, 25],
            float_percent: 50,
            max_ownership_percent: 100,
            coordinates: 'J73',
            color: :purple,
            always_market_price: true,
          },
          {
            name: 'Droga Zelazna Warszawsko-Wiedenska',
            logo: '18_oe/WW',
            sym: 'WW',
            tokens: [10, 20],
            type: 'regional',
            shares: [50, 25, 25],
            float_percent: 50,
            max_ownership_percent: 100,
            coordinates: 'M62',
            color: :lightblue,
            always_market_price: true,
          },
          # -----------------------------------------------------------------------
          # Regionals — Scandinavia / Denmark / Norway (SC)
          # -----------------------------------------------------------------------
          {
            name: 'Det Sjaellandske Jernbaneselskab',
            logo: '18_oe/DSJ',
            sym: 'DSJ',
            tokens: [10, 20],
            type: 'regional',
            shares: [50, 25, 25],
            float_percent: 50,
            max_ownership_percent: 100,
            coordinates: 'I50',
            color: :gray,
            always_market_price: true,
          },
          {
            name: 'Bergslagernas Järnvägar',
            logo: '18_oe/BJV',
            sym: 'BJV',
            tokens: [10, 20],
            type: 'regional',
            shares: [50, 25, 25],
            float_percent: 50,
            max_ownership_percent: 100,
            coordinates: 'F49',
            color: :brown,
            always_market_price: true,
          },
        ].freeze
      end
    end
  end
end
