# frozen_string_literal: true

module Engine
  module Game
    module G1877
      module Entities
        CORPORATIONS = [
          {
            float_percent: 20,
            sym: 'BPC',
            name: 'Ferroviario de Barquisimento y Puerto Caballo',
            logo: '1877/BPC',
            shares: [40, 20, 20, 20],
            max_ownership_percent: 60,
            tokens: [0],
            always_market_price: true,
            color: :dodgerblue,
            reservation_color: nil,
          },
          {
            float_percent: 20,
            sym: 'BSC',
            name: 'Ferroviario de Barinas y San Cristobál',
            logo: '1877/BSC',
            shares: [40, 20, 20, 20],
            max_ownership_percent: 60,
            tokens: [0],
            always_market_price: true,
            text_color: 'black',
            color: :lightgreen,
            reservation_color: nil,
          },
          {
            float_percent: 20,
            sym: 'Cap',
            name: 'Capital Line',
            logo: '1877/CAP',
            shares: [40, 20, 20, 20],
            max_ownership_percent: 60,
            tokens: [0],
            always_market_price: true,
            text_color: 'black',
            color: :'#FFD700',
            reservation_color: nil,
          },
          {
            float_percent: 20,
            sym: 'CLG',
            name: 'Ferroviario de Caracas y La Guaira',
            logo: '1877/CLG',
            shares: [40, 20, 20, 20],
            max_ownership_percent: 60,
            tokens: [0],
            always_market_price: true,
            color: :deeppink,
            reservation_color: nil,
          },
          {
            float_percent: 20,
            sym: 'E&M',
            name: 'Ferroviario de Encontrados y Machiques',
            logo: '1877/EM',
            shares: [40, 20, 20, 20],
            max_ownership_percent: 60,
            tokens: [0],
            always_market_price: true,
            color: :darkmagenta,
            reservation_color: nil,
          },
          {
            float_percent: 20,
            sym: 'FCC',
            name: 'Ferroviario de Caracas y Cúa',
            logo: '1877/FCC',
            shares: [40, 20, 20, 20],
            max_ownership_percent: 60,
            tokens: [0],
            always_market_price: true,
            color: '#ef4223',
            reservation_color: nil,
          },
          {
            float_percent: 20,
            sym: 'LESJ',
            name: 'Ferroviario de La Encrucijada y San Juan de Los Morros',
            logo: '1877/LESJ',
            shares: [40, 20, 20, 20],
            max_ownership_percent: 60,
            tokens: [0],
            always_market_price: true,
            text_color: 'black',
            color: '#f2a847',
            reservation_color: nil,
          },
          {
            float_percent: 20,
            sym: 'M&M',
            name: 'Ferroviario de Machiques y Maracaibo',
            logo: '1877/MM',
            shares: [40, 20, 20, 20],
            max_ownership_percent: 60,
            tokens: [0],
            always_market_price: true,
            color: :saddlebrown,
            reservation_color: nil,
          },
          {
            float_percent: 20,
            sym: 'PCB',
            name: 'Ferroviario de Puerto Cabello y Barquisimeto',
            logo: '1877/PCB',
            shares: [40, 20, 20, 20],
            max_ownership_percent: 60,
            tokens: [0],
            always_market_price: true,
            color: :darkgreen,
            reservation_color: nil,
          },
          {
            float_percent: 20,
            sym: 'Sans',
            name: 'Ferroviario de San Juan de Los Morros y San Fernando de Apure',
            logo: '1877/SANS',
            shares: [40, 20, 20, 20],
            max_ownership_percent: 60,
            tokens: [0],
            always_market_price: true,
            text_color: 'black',
            color: :aqua,
            reservation_color: nil,
          },
          {
            float_percent: 20,
            sym: 'SMB',
            name: 'Ferroviario de Sabana de Mendoza y Barquisimeto',
            logo: '1877/SMB',
            shares: [40, 20, 20, 20],
            max_ownership_percent: 60,
            tokens: [0],
            always_market_price: true,
            color: :silver,
            text_color: 'black',
            reservation_color: nil,
          },
          {
            float_percent: 20,
            sym: 'TCM',
            name: 'Tucucas Copper Mining Railway',
            logo: '1877/TCM',
            shares: [40, 20, 20, 20],
            max_ownership_percent: 60,
            tokens: [0],
            always_market_price: true,
            color: '#16190e',
            reservation_color: nil,
          },
        ].freeze
      end
    end
  end
end
